import test from'node:test';
import assert from'node:assert/strict';
import{buildGardenBackup,integrityHash,migrateGardenDataset,migrateToMockCloud,rehearseMigration,restoreGardenBackupToIsolated,validateGardenBackup,validateMockMigration}from'../src/dataReadiness.js';
const garden=()=>migrateGardenDataset({profile:{gardenerName:'Brooke',gardenName:'The Runyan Garden'},spaces:[{id:'bed',name:'Bed'}],plants:[{id:'plant',name:'Lettuce',spaceId:'bed',photo:'data:image/jpeg;base64,abc',stageHistory:[{id:'stage',stage:'Seed Started',enteredAt:'2026-03-01'}]}],seedPackets:[{id:'packet',name:'Lettuce',quantity:10}],seedTransactions:[{id:'tx',operationId:'tx',packetId:'packet',quantity:-1,status:'completed'}],reminders:[{id:'task',title:'Check soil'}],taskHistory:[{id:'done',operationId:'done',taskId:'task',status:'completed'}],wateringEvents:[{id:'water',operationId:'water',plantId:'plant',spaceId:'bed'}],vacationPlans:[{id:'trip',status:'completed',tasks:[{id:'vt',status:'completed'}]}],shoppingItems:[{id:'shop',name:'Soil',quantity:1}],harvests:[{id:'harvest',plantId:'plant',spaceId:'bed'}],problems:[],calculatorResults:[]},{now:'2026-07-18T12:00:00Z'});

test('45 complete export contains manifest, photos and counts',()=>{const backup=buildGardenBackup(garden());assert.equal(backup.manifest.photoHandling.mode,'embedded-and-manifested');assert.equal(backup.manifest.recordCounts.plants,1);assert.ok(backup.checksum)});
test('46 corrupted export is rejected',()=>{const backup=buildGardenBackup(garden());backup.garden.plants[0].name='Changed';assert.equal(validateGardenBackup(backup).ok,false)});
test('47 restore occurs in isolated dataset',()=>{const source=garden(),backup=buildGardenBackup(source),restored=restoreGardenBackupToIsolated(backup);assert.equal(restored.ok,true);assert.notEqual(restored.garden,source);assert.equal(restored.sourceUntouched,true)});
test('48 mock migration maps all major entities',()=>{const source=garden(),cloud=migrateToMockCloud(source),validation=validateMockMigration(source,cloud);assert.equal(validation.ok,true);assert.equal(cloud.plants.length,1);assert.equal(cloud.lifecycle_events.length,1);assert.equal(cloud.vacation_actions.length,1)});
test('49 migration run twice does not duplicate records',()=>{const source=garden(),first=migrateToMockCloud(source),second=migrateToMockCloud(source,first);assert.equal(integrityHash(first),integrityHash(second))});
test('50 rollback rehearsal preserves source and discards target safely',()=>{const result=rehearseMigration(garden());assert.equal(result.ok,true);assert.equal(result.rollback.ok,true);assert.equal(result.rollback.sourcePreserved,true);assert.equal(result.interrupted.detected,true);assert.equal(result.interrupted.retryOk,true)});
