import test from'node:test';
import assert from'node:assert/strict';
import{DATASET_SCHEMA_VERSION,COLLECTION_DEFINITIONS,migrateGardenDataset,validateGardenData,integrityHash}from'../src/dataReadiness.js';

const legacy=()=>({profile:{gardenerName:'Brooke'},spaces:[{id:'bed',name:'Raised Bed'},{id:'bed',name:'Duplicate Bed'}],plants:[{name:'Tomato',spaceId:'bed',photo:'data:image/jpeg;base64,abc',stageHistory:[{stage:'Seed Started',enteredAt:'2026-03-01'}]}],seeds:[{id:'seed-1',name:'Lettuce',variety:'Iceberg A',quantity:20}],seedPackets:[],harvests:[],problems:[],reminders:[],taskHistory:[],vacationPlans:[]});

test('1 existing record without stable ID receives deterministic stable ID',()=>{const a=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'}),b=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'});assert.equal(a.plants[0].id,b.plants[0].id);assert.match(a.plants[0].id,/^plant-/)});
test('2 duplicate IDs are repaired without dropping records',()=>{const result=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'});assert.equal(result.spaces.length,2);assert.equal(new Set(result.spaces.map(row=>row.id)).size,2)});
test('3 plant rename does not change stable ID',()=>{const garden=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'}),id=garden.plants[0].id;garden.plants[0].name='Patio Tomato';assert.equal(migrateGardenDataset(garden).plants[0].id,id)});
test('4 Growing Space rename preserves plant relationship',()=>{const garden=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'}),id=garden.spaces[0].id;garden.plants[0].spaceId=id;garden.spaces[0].name='Kitchen Bed';const next=migrateGardenDataset(garden);assert.equal(next.plants[0].spaceId,id)});
test('5 orphaned task is reported without crashing',()=>{const garden=migrateGardenDataset({...legacy(),reminders:[{id:'r',title:'Water',plantId:'missing'}]});const health=validateGardenData(garden);assert.ok(health.issues.some(row=>row.collection==='reminders'&&row.type==='orphan-link'))});
test('6 orphaned photo is reported',()=>{const garden=migrateGardenDataset({...legacy(),photos:[{id:'p',parentType:'plants',parentId:'missing',storageReference:'embedded:plants:missing:photo'}]});assert.ok(validateGardenData(garden).issues.some(row=>row.type==='orphan-photo'))});
test('7 deleted parent is not treated as active relationship target',()=>{const garden=migrateGardenDataset({...legacy(),spaces:[{id:'bed',name:'Bed',deletedAt:'2026-07-18T00:00:00Z'}],plants:[{id:'plant',name:'Tomato',spaceId:'bed'}]});assert.ok(validateGardenData(garden).issues.some(row=>row.collection==='plants'&&row.field==='spaceId'))});
test('8 old schema record migrates to current schema',()=>{const result=migrateGardenDataset({...legacy(),schemaVersion:10},{now:'2026-07-18T12:00:00Z'});assert.equal(result.schemaVersion,DATASET_SCHEMA_VERSION);assert.ok(result.migrationHistory.length)});
test('9 interrupted migration marker is preserved for diagnosis',()=>{const result=migrateGardenDataset({...legacy(),migrationHistory:[{id:'x',operationId:'schema-migration:9:10',status:'failed'}]});assert.ok(result.migrationHistory.some(row=>row.status==='failed'))});
test('10 repeated migration is idempotent',()=>{const once=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'}),twice=migrateGardenDataset(once);assert.equal(integrityHash(once),integrityHash(twice))});
test('11 legacy seed collection consolidates into one authority',()=>{const result=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'});assert.equal(result.seeds.length,0);assert.equal(result.seedPackets.length,1);assert.equal(result.seedPackets[0].name,'Lettuce')});
test('12 lifecycle events receive stable IDs',()=>{const result=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'});assert.ok(result.plants[0].stageHistory[0].id);assert.equal(result.plants[0].stageHistory[0].plantId,result.plants[0].id)});
test('13 embedded photos receive stable parent metadata',()=>{const result=migrateGardenDataset(legacy(),{now:'2026-07-18T12:00:00Z'}),photo=result.photos.find(row=>row.parentType==='plants');assert.ok(photo);assert.equal(photo.parentId,result.plants[0].id);assert.equal(photo.migrationStatus,'pending-cloud-upload')});
test('14 collection map declares one authoritative source for seed packets',()=>{assert.match(COLLECTION_DEFINITIONS.seedPackets.authority,/Seed inventory/);assert.equal(COLLECTION_DEFINITIONS.dailyViewCache.ownership,'device-local')});
