import test from'node:test';
import assert from'node:assert/strict';
import{buildEnvironmentalSnapshot,classifySpaceExposure,createManualCorrection,dedupeRainRecords,effectiveRainfall,FRESHNESS,freshnessFor,normalizeEnvironmentalRecord,rainCreditForSpace,SOURCE_TYPES}from'../src/environmentalIntelligence.js';
import{formatGardenDate,formatGardenDateRange,formatGardenDateTime}from'../src/dateFormat.js';

test('normalization preserves unknown values as null and source metadata',()=>{const row=normalizeEnvironmentalRecord({record_id:'x',source_type:SOURCE_TYPES.OBSERVED,source_name:'NWS',source_provider:'National Weather Service',source_station_id:'KGRB',observed_at:'2026-07-17T15:00:00-05:00',temperature:72,humidity:undefined});assert.equal(row.record_id,'x');assert.equal(row.temperature,72);assert.equal(row.humidity,null);assert.equal(row.source_station_id,'KGRB');assert.equal(row.forecast_for,null)});

test('freshness distinguishes current recent stale and unavailable',()=>{const now=Date.parse('2026-07-17T20:00:00Z');const make=minutes=>normalizeEnvironmentalRecord({source_type:SOURCE_TYPES.OBSERVED,observed_at:new Date(now-minutes*60000),received_at:new Date(now-minutes*60000)});assert.equal(freshnessFor(make(5),now),FRESHNESS.CURRENT);assert.equal(freshnessFor(make(45),now),FRESHNESS.RECENT);assert.equal(freshnessFor(make(180),now),FRESHNESS.STALE);assert.equal(freshnessFor(null,now),FRESHNESS.UNAVAILABLE)});

test('manual correction stores decimal rain, source, timestamp, and null identity',()=>{const row=createManualCorrection({rainfall_amount:0.56,observed_at:'2026-07-17T15:15:00-05:00',note:'Backyard gauge'});assert.equal(row.precipitation_amount,0.56);assert.equal(row.source_name,'Home weather monitor');assert.equal(row.is_manual_correction,true);assert.equal(row.entered_by,null);assert.equal(row.entry_note,'Backyard gauge')});

test('rain records from one event are deduplicated',()=>{const base={source_type:SOURCE_TYPES.OBSERVED,source_provider:'NWS',source_station_id:'KGRB',observed_at:'2026-07-17T15:15:00Z',precipitation_period:'1-hour'};const rows=dedupeRainRecords([{...base,precipitation_amount:0.1},{...base,observed_at:'2026-07-17T15:40:00Z',precipitation_amount:0.2}]);assert.equal(rows.length,1);assert.equal(rows[0].precipitation_amount,0.2)});

test('manual replacement preserves provider record while changing effective amount',()=>{const provider=normalizeEnvironmentalRecord({record_id:'provider-rain',source_type:SOURCE_TYPES.OBSERVED,source_name:'NWS',observed_at:'2026-07-17T18:00:00Z',received_at:'2026-07-17T18:01:00Z',precipitation_amount:0.2,precipitation_period:'event'});const correction=createManualCorrection({rainfall_amount:0.56,observed_at:'2026-07-17T18:00:00Z',supersedes_observation_id:'provider-rain'});const result=effectiveRainfall({records:[provider],corrections:[correction],sinceHours:24,now:Date.parse('2026-07-17T20:00:00Z')});assert.equal(result.amount,0.56);assert.equal(result.provider_records.length,0);assert.equal(result.manual_records.length,1)});

test('forecast rain is never counted as observed rainfall',()=>{const forecast=normalizeEnvironmentalRecord({source_type:SOURCE_TYPES.FORECAST,forecast_for:'2026-07-17T22:00:00Z',precipitation_amount:1});const result=effectiveRainfall({records:[forecast],corrections:[],sinceHours:24,now:Date.parse('2026-07-17T20:00:00Z')});assert.equal(result.amount,0)});

test('growing space exposure changes rain credit',()=>{assert.equal(classifySpaceExposure({type:'indoor'}),'indoor');assert.equal(rainCreditForSpace({type:'indoor'},0.56).amount,0);assert.equal(rainCreditForSpace({type:'greenhouse'},0.56).amount,0);assert.equal(rainCreditForSpace({type:'container'},0.56).amount,0.45);assert.equal(rainCreditForSpace({type:'black-square-bed'},0.56).amount,0.5)});

test('snapshot separates observations from forecasts and creates explained signals',()=>{const observation=normalizeEnvironmentalRecord({source_type:SOURCE_TYPES.OBSERVED,source_name:'NWS KGRB',observed_at:new Date(),received_at:new Date(),temperature:92,humidity:85,wind_speed:20,precipitation_amount:0.3,precipitation_period:'event'});const forecast=normalizeEnvironmentalRecord({source_type:SOURCE_TYPES.FORECAST,source_name:'NWS forecast',forecast_for:new Date(Date.now()+3600000),expires_at:new Date(Date.now()+7200000),minimum_temperature:34,maximum_temperature:94,precipitation_probability:70});const result=buildEnvironmentalSnapshot({records:[observation,forecast],spaces:[{id:'bed',type:'black-square-bed'},{id:'inside',type:'indoor'}]});assert.equal(result.observations.length,1);assert.equal(result.forecasts.length,1);assert.equal(result.rainCreditBySpace.inside.amount,0);assert.equal(result.signals.heatStressRisk.status,true);assert.match(result.signals.heatStressRisk.reason,/stress/i);assert.equal(result.signals.rainExpectedSoon.status,true)});

test('shared date formatting uses MM-DD-YYYY and never raw ISO',()=>{assert.equal(formatGardenDate('2026-08-01'),'08-01-2026');assert.equal(formatGardenDateRange('2026-08-01','2026-09-15'),'08-01-2026–09-15-2026');assert.match(formatGardenDateTime('2026-07-17T15:15:00-05:00'),/^07-17-2026 at /);assert.notEqual(formatGardenDate('bad date'),'Invalid Date')});
