import test from'node:test';
import assert from'node:assert/strict';
import{readFileSync}from'node:fs';

const src=file=>readFileSync(new URL(`../src/${file}`,import.meta.url),'utf8');

test('Chore Board presents one active queue plus later work and history',()=>{const source=src('ChoreBoard.jsx');assert.match(source,/id="attention"/);assert.match(source,/NEEDS ATTENTION/);assert.match(source,/title="Do these first"/);assert.match(source,/title="Later work"/);assert.match(source,/title="Completed, skipped, or not needed"/);assert.equal(source.includes('WEATHER ALERTS'),false);assert.equal(source.includes('Past the due date'),false);assert.equal(source.includes('Due today" tasks='),false)});
test('More consolidates household settings into one collapsed destination with no closed body',()=>{const source=src('MoreHub.jsx'),css=src('styles/phase-4-8-1-mobile-continuity.css');assert.match(source,/<details className="more-settings-hub">/);assert.doesNotMatch(source,/<details className="more-settings-hub" open/);assert.match(source,/Garden and gardeners/);assert.match(source,/Location and frost dates/);assert.match(source,/Notifications/);assert.match(css,/more-settings-hub:not\(\[open\]\)>div\{display:none!important\}/);assert.match(source,/title="Backup & Data"/);assert.match(source,/title="How Garden Compass Works"/)});
test('Today stays useful without repeating primary navigation and weather copy is human-readable',()=>{const workspace=src('WorkspaceScreens.jsx'),home=src('UrgentHome.jsx');assert.equal(workspace.includes('today-quick-links'),false);assert.match(home,/Your garden is caught up/);assert.match(home,/No urgent garden actions right now/);assert.match(home,/Let’s set up your garden/);assert.match(workspace,/impactDisplayTitle/);assert.match(workspace,/Rain changed the watering plan/);assert.match(workspace,/WHAT TO DO/);assert.equal(workspace.includes('WEATHER-ACTION-SUMMARY'),false)});
test('Phase 4.8.3 navigation styles retain More, weather, Indoor, Tool Shed, and setup protections',()=>{const lock=src('styles/phase-4-7-5-navigation-lock.css'),smoothing=src('styles/phase-4-7-3-smoothing.css'),continuity=src('styles/phase-4-8-1-mobile-continuity.css'),clarity=src('styles/phase-4-8-3-first-time-clarity.css'),toolShed=src('ToolShed.jsx'),main=src('main.jsx');assert.match(main,/phase-4-7-5-navigation-lock\.css/);assert.match(main,/phase-4-8-1-mobile-continuity\.css/);assert.match(main,/phase-4-8-3-first-time-clarity\.css/);assert.match(main,/phase-4-8-3b-garden-history\.css/);assert.match(lock,/compact-secondary-header/);assert.match(smoothing,/more-settings-hub>summary/);assert.match(smoothing,/weather-tool-tabs/);assert.match(smoothing,/indoor-center-content \.control-center-title/);assert.equal((toolShed.match(/<ToolCategory /g)||[]).length,3);assert.equal((toolShed.match(/<ToolCard /g)||[]).length,6);assert.match(continuity,/tool-shed-category-summary/);assert.match(clarity,/garden-setup-steps/)});
test('release metadata identifies Phase 4.8.3c checklist layout correction',()=>{const source=src('version.js');assert.match(source,/APP_VERSION='0\.21\.1'/);assert.match(source,/phase-4-8-3c-checklist-layout-hotfix/);assert.match(source,/Fixed the first-time setup checklist layout on mobile\./);assert.match(source,/Garden History is now available directly from Garden/);assert.match(source,/Center is now Plan & Care/);assert.match(source,/Tool Shed now contains only utilities, weather, and Print & Labels/);assert.match(source,/New gardens are guided through setup in the correct order/)});