import test from'node:test';
import assert from'node:assert/strict';
import{applyPacketExtraction,emptyPacketDraft,extractionReview,findLikelyDuplicatePacket,markManualField,packetPayload,parsePacketText,validatePacketImage}from'../src/seedPacketIntelligence.js';

const front=`BURPEE\nBELL PEPPER\nCalifornia Wonder\nHEIRLOOM\nPacked for 2026\nApproximately 300 seeds\nNet Wt. 1.5 g\nLOT CW-26`;
const back=`Start indoors 8-10 weeks before last frost. Transplant after danger of frost. Sow seed 1/4 inch deep. Plant spacing: 18 inches. Row spacing: 24 inches. Germination 7-14 days. Germination temperature 70-85 F. 75 days to maturity from transplant. Full sun. Keep soil evenly moist. Stake plants if needed. Harvest when fruits are full size.`;

const lowMeta=(sourcePhoto='front')=>({source:'packet-vision',sourceLabel:'Read from packet photos',confidence:'Low',sourcePhoto,originalText:'faded packet text'});

test('manual packet entry starts as a backward-compatible draft',()=>{const draft=emptyPacketDraft({name:'Basil'});assert.equal(draft.name,'Basil');assert.equal(draft.fieldMeta.name.source,'manual');assert.equal(draft.packetIntelligence.front,null)});
test('front photo text identifies crop, variety, brand, year and count',()=>{const result=parsePacketText(front,{side:'front'});assert.equal(result.fields.name.value,'Bell Pepper');assert.equal(result.fields.brand.value,'Burpee');assert.equal(result.fields.packetYear.value,2026);assert.equal(result.fields.quantity.value,300);assert.equal(result.fields.packetWeight.value,'1.5 g')});
test('back photo text identifies planting details',()=>{const result=parsePacketText(back,{side:'back'});assert.equal(result.fields.depth.value,'1/4 inch');assert.equal(result.fields.spacing.value,'18 inches');assert.equal(result.fields.daysToMaturity.value,75);assert.equal(result.fields.maturityBasis.value,'transplant');assert.match(result.fields.sunlight.value,/Full sun/)});
test('front and back extraction combine without flattening packet details',()=>{let draft=applyPacketExtraction(emptyPacketDraft(),parsePacketText(front,{side:'front'}));draft=applyPacketExtraction(draft,parsePacketText(back,{side:'back'}));assert.equal(draft.name,'Bell Pepper');assert.equal(draft.daysToMaturity,75);assert.ok(draft.packetIntelligence.front.rawText);assert.ok(draft.packetIntelligence.back.rawText)});
test('clear modern packet produces multiple high confidence fields',()=>{const result=parsePacketText(front,{side:'front'}),high=Object.values(result.fields).filter(row=>row.confidence==='High');assert.ok(high.length>=5)});
test('older faded packet text remains partial rather than invented',()=>{const result=parsePacketText('bUrPeE\nTomato\nold faded label',{side:'front'});assert.equal(result.fields.name.value,'Tomato');assert.equal(result.fields.brand.value,'Burpee');assert.equal(result.fields.packetYear,undefined)});
test('glare-like missing text leaves fields blank',()=>{const result=parsePacketText('BURPEE\nBELL PEP',{side:'front'});assert.equal(result.fields.packetYear,undefined);assert.equal(result.fields.quantity,undefined)});
test('rotation does not alter the text parser contract',()=>{const result=parsePacketText(front,{side:'front'});assert.equal(result.side,'front');assert.ok(result.fieldCount>0)});
test('slightly blurry partial text is flagged through low or medium confidence',()=>{const result=parsePacketText('Burpee\nPepper\nCalif Wonder',{side:'front'});assert.ok(Object.values(result.fields).some(row=>row.confidence!=='High'))});
test('packet with no visible year does not receive an invented year',()=>{assert.equal(parsePacketText('Ferry-Morse\nBasil\nGenovese',{side:'front'}).fields.packetYear,undefined)});
test('weight without seed count stays weight-only',()=>{const result=parsePacketText('Botanical Interests\nDill\nNet Wt 2 g',{side:'front'});assert.equal(result.fields.packetWeight.value,'2 g');assert.equal(result.fields.quantity,undefined)});
test('approximate seed count is preserved as estimated',()=>{const result=parsePacketText('About 125 seeds',{side:'front'});assert.equal(result.fields.quantity.value,125);assert.equal(result.fields.countType.value,'estimated')});
test('maturity from transplant is recorded separately',()=>{const result=parsePacketText('72 days to maturity from transplant',{side:'back'});assert.equal(result.fields.daysToMaturity.value,72);assert.equal(result.fields.maturityBasis.value,'transplant')});
test('maturity from sowing is recorded separately',()=>{const result=parsePacketText('55 days to harvest from seed',{side:'back'});assert.equal(result.fields.daysToMaturity.value,55);assert.equal(result.fields.maturityBasis.value,'sowing')});
test('incomplete spacing does not create a false value',()=>{const result=parsePacketText('Thin seedlings when crowded.',{side:'back'});assert.equal(result.fields.spacing,undefined);assert.equal(result.fields.thinningSpacing,undefined)});
test('regional planting guidance is preserved as packet text',()=>{const result=parsePacketText('Zone 3-8. Northern climates sow in May.',{side:'back'});assert.match(result.fields.regionalGuidance.value,/Zone 3-8/i)});
test('English content is still extracted from a bilingual packet',()=>{const result=parsePacketText('Tomato / Tomate\nFull sun / Pleno sol\nPlant spacing: 18 inches',{side:'back'});assert.equal(result.fields.name.value,'Tomato');assert.equal(result.fields.spacing.value,'18 inches')});
test('large but allowed image receives validation approval before compression',()=>{assert.equal(validatePacketImage({type:'image/jpeg',size:8*1024*1024}).ok,true)});
test('unsupported image format is rejected with a recovery message',()=>{const result=validatePacketImage({type:'image/heic',size:1000});assert.equal(result.ok,false);assert.match(result.message,/JPEG, PNG, or WebP/)});
test('oversized image is rejected before browser storage is threatened',()=>{const result=validatePacketImage({type:'image/jpeg',size:30*1024*1024});assert.equal(result.ok,false);assert.match(result.message,/too large/i)});
test('likely duplicate uses packet-specific identity',()=>{const packet={id:'p1',name:'Bell Pepper',variety:'California Wonder',brand:'Burpee',packetYear:2026,lotNumber:'CW-26'};const duplicate=findLikelyDuplicatePacket(packet,[packet]);assert.equal(duplicate.packet.id,'p1');assert.ok(duplicate.score>=6)});
test('similar crop alone is not automatically treated as a duplicate',()=>{const duplicate=findLikelyDuplicatePacket({name:'Tomato',variety:'Roma'},[{id:'p1',name:'Tomato',variety:'Cherokee Purple'}]);assert.equal(duplicate,null)});
test('manual correction wins over later OCR extraction',()=>{let draft=applyPacketExtraction(emptyPacketDraft(),parsePacketText(front,{side:'front'}));draft=markManualField(draft,'variety','California Wonder Improved');draft=applyPacketExtraction(draft,parsePacketText('Bell Pepper\nCalifornia Wonder',{side:'front'}));assert.equal(draft.variety,'California Wonder Improved');assert.equal(draft.fieldMeta.variety.source,'manual');assert.equal(draft.fieldMeta.variety.manuallyCorrected,true)});
test('low confidence fields appear in the review group',()=>{const draft=emptyPacketDraft({name:'Tomato',variety:'Mystery Red',brand:'Unknown Seeds',fieldMeta:{name:lowMeta(),variety:lowMeta(),brand:lowMeta()}}),review=extractionReview(draft);assert.ok(review.check.some(row=>row.key==='variety'));assert.ok(review.check.every(row=>row.confidence==='Low'))});
test('only missing packet identity remains blocking while manufacturer-optional fields stay optional',()=>{const review=extractionReview(emptyPacketDraft({name:'Basil'}));assert.ok(review.missing.some(row=>row.key==='brand'));assert.ok(review.missing.some(row=>row.key==='variety'));assert.ok(!review.missing.some(row=>row.key==='packetYear'));assert.ok(review.optionalMissing.some(row=>row.key==='packetYear'));assert.ok(review.optionalMissing.some(row=>row.key==='daysToMaturity'))});
test('saved payload preserves front and back images plus legacy preview',()=>{const payload=packetPayload(emptyPacketDraft({name:'Basil'}),{frontPhoto:'front-data',backPhoto:'back-data'});assert.equal(payload.photo,'front-data');assert.equal(payload.frontPhoto,'front-data');assert.equal(payload.backPhoto,'back-data')});
test('saved payload does not invent seed count from weight',()=>{const payload=packetPayload(emptyPacketDraft({name:'Dill',packetWeight:'2 g',countType:'weight-only'}),{});assert.equal(payload.quantity,0);assert.equal(payload.packetWeight,'2 g');assert.equal(payload.countType,'weight-only')});
test('reserved quantity remains packet-specific',()=>{const payload=packetPayload(emptyPacketDraft({name:'Pea',quantity:50,reservedQuantity:12}),{});assert.equal(payload.quantity,50);assert.equal(payload.reservedQuantity,12)});
test('extraction provenance records source photo and date',()=>{const result=parsePacketText(front,{side:'front'});assert.equal(result.fields.name.sourcePhoto,'front');assert.ok(result.fields.name.extractedAt)});
test('packet parser preserves original OCR wording',()=>{const result=parsePacketText(back,{side:'back'});assert.match(result.fields.seedStartingGuidance.originalText,/Start indoors/i)});

test('recovered draft defaults are not counted as confirmed packet details',()=>{const original=emptyPacketDraft({name:'Radish'}),recovered=emptyPacketDraft(original),review=extractionReview(recovered);assert.deepEqual(review.ready.map(row=>row.key),['name'])});
