import test from'node:test';
import assert from'node:assert/strict';
import{icebergAVisionResponse}from'./fixtures/icebergAVisionResponse.js';
import{validateVisionAnalysis}from'../server/seedPacketSchema.js';
import{buildVisionRequest,analyzeSeedPacket}from'../server/seedPacketVision.js';

const clone=value=>JSON.parse(JSON.stringify(value));
test('strict Iceberg A multimodal response passes with field evidence',()=>{const result=validateVisionAnalysis(icebergAVisionResponse);assert.equal(result.ok,true);assert.equal(result.value.packetIdentity.variety,'Iceberg A');assert.equal(result.value.inventory.inventoryBasis,'weight')});
test('malformed product identity and guidance are rejected before merge',()=>{const input=clone(icebergAVisionResponse);input.packetIdentity.variety='Iceberg A FULL SUN';input.fieldEvidence['packetIdentity.variety'].value=input.packetIdentity.variety;input.instructions.moistureGuidance='$5, keep evenly moist';input.fieldEvidence['instructions.moistureGuidance'].value=input.instructions.moistureGuidance;const result=validateVisionAnalysis(input);assert.equal(result.ok,false);assert.match(result.errors.join(' '),/variety/i);assert.match(result.errors.join(' '),/moistureGuidance/i)});
test('weight-only packet cannot claim a printed exact count',()=>{const input=clone(icebergAVisionResponse);input.inventory.printedSeedCount=100;input.fieldEvidence['inventory.printedSeedCount']={value:100,sourceImage:'inferred',visibleEvidence:'estimated from weight',confidence:'low',printed:false,normalized:true};const result=validateVisionAnalysis(input);assert.equal(result.ok,false);assert.match(result.errors.join(' '),/Weight-only/i)});
test('populated fields require evidence',()=>{const input=clone(icebergAVisionResponse);delete input.fieldEvidence['packetIdentity.variety'];const result=validateVisionAnalysis(input);assert.equal(result.ok,false);assert.match(result.errors.join(' '),/packetIdentity.variety is populated without field evidence/)});
test('OpenAI request sends front and back together, uses high detail and disables storage',()=>{const request=buildVisionRequest({front:{dataUrl:'data:image/jpeg;base64,front'},back:{dataUrl:'data:image/jpeg;base64,back'},model:'gpt-5'});assert.equal(request.store,false);const content=request.input[1].content;assert.equal(content.filter(row=>row.type==='input_image').length,2);assert.deepEqual(content.filter(row=>row.type==='input_image').map(row=>row.detail),['high','high']);assert.equal(request.model,'gpt-5')});
test('invalid first model response receives one repair pass and never reaches active fields',async()=>{let calls=0;const malformed=clone(icebergAVisionResponse);malformed.packetIdentity.variety='Iceberg A FULL SUN';malformed.fieldEvidence['packetIdentity.variety'].value=malformed.packetIdentity.variety;const result=await analyzeSeedPacket({front:{dataUrl:'front',hash:'f',buffer:Buffer.from('front')},back:{dataUrl:'back',hash:'b',buffer:Buffer.from('back')},currentDraft:{draftId:'fixture'},requestId:'req-test'},{modelCaller:async({repairErrors})=>{calls++;if(calls===1){assert.equal(repairErrors.length,0);return{output_parsed:malformed,usage:{}}}assert.ok(repairErrors.some(row=>/variety/i.test(row)));return{output_parsed:clone(icebergAVisionResponse),usage:{input_tokens:10,output_tokens:5,total_tokens:15}}},barcodeDecoder:async()=>({value:null,format:null,confidence:'low',method:'test',checkDigitValid:null}),productResearcher:async()=>({primary:null,candidates:[],cacheHit:false})});assert.equal(calls,2);assert.equal(result.packetDraft.variety,'Iceberg A');assert.equal(result.analysis.analysisPassCount,2)});
