import test from'node:test';
import assert from'node:assert/strict';
import{bestWeatherTimestamp,formatRainAmount,groupWeatherImpacts,hasUsableWeather,normalizeForecastDays,roundWeatherValue}from'../src/weatherPresentation.js';

const row=(overrides={})=>({recommendationId:Math.random().toString(36),category:'watering',actionKey:'check-soil',priority:70,title:'Check soil',plainLanguageExplanation:'Recent rain changed watering.',recommendedAction:'Check the root zone before watering.',affectedPlants:['p1'],affectedGrowingSpaces:['s1'],confidence:'Medium',source:'NWS',dataFreshness:'Current',destination:'chores',...overrides});

test('mild day stays one compact calm group',()=>{const groups=groupWeatherImpacts([row({category:'calm',actionKey:'calm-weather',priority:20,recommendedAction:'Continue normal care.',affectedPlants:[],affectedGrowingSpaces:[]})]);assert.equal(groups.length,1);assert.equal(groups[0].key,'calm')});
test('recent observed rain and delayed watering merge into one watering group',()=>{const groups=groupWeatherImpacts([row({actionKey:'check-soil'}),row({actionKey:'delay-watering',recommendedAction:'Wait for the rain window, then reassess.'})]);assert.equal(groups.length,1);assert.equal(groups[0].key,'watering');assert.match(groups[0].summary,/root zone|rain window/i)});
test('forecast rain remains wording distinct from observed rain',()=>{const groups=groupWeatherImpacts([row({plainLanguageExplanation:'Forecast rain has not happened yet.',recommendedAction:'Reassess after the forecast period.'})]);assert.match(groups[0].explanation,/has not happened/i)});
test('heat and overlapping wind merge into heat and drying',()=>{const groups=groupWeatherImpacts([row({category:'heat',actionKey:'check-heat-stress',affectedPlants:['p1']}),row({category:'wind',actionKey:'secure-wind',affectedPlants:['p1']})]);assert.equal(groups.length,1);assert.equal(groups[0].key,'heat-drying')});
test('unrelated wind remains storms and wind',()=>{const groups=groupWeatherImpacts([row({category:'heat',affectedPlants:['p1']}),row({category:'wind',affectedPlants:['p2'],affectedGrowingSpaces:['s2']})]);assert.ok(groups.some(group=>group.key==='storms-wind'))});
test('greenhouse ventilation gets its own group',()=>{const groups=groupWeatherImpacts([row({category:'heat',actionKey:'ventilate-greenhouse',title:'Check greenhouse ventilation'})]);assert.equal(groups[0].key,'greenhouse')});
test('frost recommendations group together',()=>{const groups=groupWeatherImpacts([row({category:'frost',actionKey:'protect-frost'}),row({category:'frost',actionKey:'recheck-frost'})]);assert.equal(groups.length,1);assert.equal(groups[0].key,'frost-cold')});
test('storm and heavy rain group together',()=>{const groups=groupWeatherImpacts([row({category:'storm'}),row({category:'heavy-rain'})]);assert.equal(groups.length,1);assert.equal(groups[0].key,'storms-wind')});
test('damp disease signal stays separate',()=>{const groups=groupWeatherImpacts([row({category:'disease-risk'})]);assert.equal(groups[0].key,'damp-disease')});
test('top impacts are limited to three',()=>{const groups=groupWeatherImpacts([row({category:'watering'}),row({category:'frost'}),row({category:'heat'}),row({category:'storm'}),row({category:'disease-risk'})],3);assert.equal(groups.length,3)});
test('groups remain priority sorted',()=>{const groups=groupWeatherImpacts([row({category:'watering',priority:50}),row({category:'frost',priority:95})]);assert.equal(groups[0].key,'frost-cold')});
test('duplicate action sentences are removed',()=>{const groups=groupWeatherImpacts([row(),row()]);assert.equal((groups[0].summary.match(/Check the root zone/g)||[]).length,1)});
test('forecast day and night periods combine into one date',()=>{const days=normalizeForecastDays([{record_id:'d',forecast_for:'2026-07-17T15:00:00Z',maximum_temperature:88,minimum_temperature:null,precipitation_probability:20},{record_id:'n',forecast_for:'2026-07-17T23:00:00Z',maximum_temperature:null,minimum_temperature:62,precipitation_probability:35}]);assert.equal(days.length,1);assert.equal(days[0].high,88);assert.equal(days[0].low,62);assert.equal(days[0].rainProbability,35)});
test('duplicate forecast dates do not render duplicate days',()=>{const days=normalizeForecastDays([{forecast_for:'2026-07-18T10:00:00Z',temperature:80},{forecast_for:'2026-07-18T16:00:00Z',temperature:85},{forecast_for:'2026-07-18T22:00:00Z',temperature:67}]);assert.equal(days.length,1)});
test('missing high is labeled clearly',()=>{const days=normalizeForecastDays([{forecast_for:'2026-07-18T23:00:00Z',minimum_temperature:61}]);assert.equal(days[0].temperatureLabel,'Low 61° available')});
test('missing low is labeled clearly',()=>{const days=normalizeForecastDays([{forecast_for:'2026-07-18T12:00:00Z',maximum_temperature:85}]);assert.equal(days[0].temperatureLabel,'High 85° available')});
test('missing both temperatures is not shown as a broken dash',()=>{const days=normalizeForecastDays([{forecast_for:'2026-07-18T12:00:00Z',precipitation_probability:20}]);assert.equal(days[0].temperatureLabel,'Temperature details unavailable');assert.equal(days[0].temperatureLabel.includes('—'),false)});
test('forecast rain probability uses sensible whole-number rounding',()=>{const days=normalizeForecastDays([{forecast_for:'2026-07-18T12:00:00Z',precipitation_probability:62.497648839725}]);assert.equal(days[0].rainProbability,62)});
test('rain totals combine for the day',()=>{const days=normalizeForecastDays([{forecast_for:'2026-07-18T10:00:00Z',precipitation_amount:.1},{forecast_for:'2026-07-18T15:00:00Z',precipitation_amount:.25}]);assert.equal(days[0].rainAmount,.35)});
test('forecast output is limited',()=>{const rows=Array.from({length:8},(_,index)=>({forecast_for:`2026-07-${String(18+index).padStart(2,'0')}T12:00:00Z`,maximum_temperature:80+index}));assert.equal(normalizeForecastDays(rows,4).length,4)});
test('temperature rounding removes raw decimals',()=>{assert.equal(roundWeatherValue(87.84567,{suffix:'°'}),'88°')});
test('humidity rounding removes raw decimals',()=>{assert.equal(roundWeatherValue(62.497648839725,{suffix:'%'}),'62%')});
test('small rainfall keeps useful hundredths',()=>{assert.equal(formatRainAmount(.56),'0.56 in')});
test('larger rainfall avoids excessive precision',()=>{assert.equal(formatRainAmount(1.567),'1.6 in')});
test('best timestamp prefers observation time',()=>{const result=bestWeatherTimestamp({weather:{currentObservation:{observed_at:'2026-07-17T22:50:00Z'},fetchedAt:'2026-07-17T23:00:00Z'}});assert.equal(result.label,'Last observation');assert.equal(result.value,'2026-07-17T22:50:00Z')});
test('best timestamp falls back to forecast update',()=>{const result=bestWeatherTimestamp({weather:{forecasts:[{received_at:'2026-07-17T22:00:00Z'}]}});assert.equal(result.label,'Forecast updated')});
test('best timestamp uses app refresh only when better timestamps are absent',()=>{const result=bestWeatherTimestamp({weather:{},savedAt:'2026-07-17T22:30:00Z'});assert.equal(result.label,'App refreshed')});
test('provider failure can still produce an unavailable group',()=>{const groups=groupWeatherImpacts([row({category:'unavailable',actionKey:'manual-weather-check',priority:55,affectedPlants:[],affectedGrowingSpaces:[]})]);assert.equal(groups[0].key,'unavailable')});
test('more than ten raw recommendations collapse into few categories',()=>{const rows=Array.from({length:12},(_,index)=>row({recommendationId:String(index),category:index%2?'watering':'heat',actionKey:index%2?'check-soil':'check-heat-stress'}));assert.ok(groupWeatherImpacts(rows,3).length<=2)});
test('weather grouping preserves source and freshness',()=>{const groups=groupWeatherImpacts([row({source:'National Weather Service',dataFreshness:'Current'})]);assert.match(groups[0].source,/National Weather Service/);assert.match(groups[0].freshness,/Current/)});

test('weather impacts wait for a usable reading or forecast summary',()=>{assert.equal(hasUsableWeather(null),false);assert.equal(hasUsableWeather({condition:'Current conditions unavailable'}),false);assert.equal(hasUsableWeather({high:82}),true);assert.equal(hasUsableWeather({temperature:71,condition:'Clear'}),true)});

test('explicit null weather values remain unavailable instead of becoming zero',()=>{assert.equal(roundWeatherValue(null,{suffix:'°'}),'');assert.equal(hasUsableWeather({temperature:null,high:null,low:null,condition:'Current conditions unavailable'}),false);const day=normalizeForecastDays([{forecast_for:'2026-07-18T12:00:00Z',maximum_temperature:null,minimum_temperature:null,temperature:null}])[0];assert.equal(day.temperatureLabel,'Temperature details unavailable')});
