import test from'node:test';
import assert from'node:assert/strict';
import{buildYearRoundTasks,migrateGarden}from'../src/yearRoundEngine.js';

const plant={id:'plant-1',name:'Tomato',cropId:'tomato',spaceId:'bed',stage:'Established',quantity:1,lastWatered:'2026-07-01T12:00:00Z',lastSoilCheck:'2026-07-01T12:00:00Z',moisture:'unknown'};
const garden={profile:{gardenerName:'Brooke'},spaces:[{id:'bed',name:'Raised Bed',type:'black-square-bed',capacity:12},{id:'greenhouse',name:'Greenhouse',type:'greenhouse',capacity:8},{id:'inside',name:'Indoor Shelf',type:'indoor',capacity:8}],plants:[plant],reminders:[],hardeningPlans:[],taskHistory:[],seeds:[]};

function weather(overrides={}){return{recentRain24h:0,rainCreditBySpace:{bed:{amount:0,factor:1,exposure:'raised-bed'},greenhouse:{amount:0,factor:0,exposure:'fully-rain-protected'},inside:{amount:0,factor:0,exposure:'indoor'}},signals:{rainExpectedSoon:{status:false},dryingConditions:{status:false},heatStressRisk:{status:false},frostRisk:{status:false},freezeRisk:{status:false},windDamageRisk:{status:false},fungalDiseaseRisk:{status:false},greenhouseOverheatRisk:{status:false},delayFertilizing:{status:false},delaySpraying:{status:false},transplantStressRisk:{status:false}},activeAlerts:[],isStale:false,...overrides}}

test('meaningful observed rain changes routine watering to Check Soil',()=>{const w=weather({recentRain24h:.56,rainCreditBySpace:{bed:{amount:.5,factor:.9,exposure:'raised-bed'},greenhouse:{amount:0,factor:0,exposure:'fully-rain-protected'},inside:{amount:0,factor:0,exposure:'indoor'}},signals:{...weather().signals,heavyRain:{status:false},recentMeaningfulRain:{status:true}}});const tasks=buildYearRoundTasks({garden,weather:w,date:new Date('2026-07-17T12:00:00-05:00')});const task=tasks.find(row=>row.id==='soil-plant-1');assert.ok(task);assert.equal(task.taskType,'Check Moisture');assert.match(task.reason,/effective observed rain|Check Soil/i);assert.equal(tasks.some(row=>row.id==='water-plant-1'),false)});

test('forecast rain never completes or records watering',()=>{const w=weather({signals:{...weather().signals,rainExpectedSoon:{status:true,reason:'Forecast rain may arrive.'}}});const dryGarden={...garden,plants:[{...plant,moisture:'dry'}]};const tasks=buildYearRoundTasks({garden:dryGarden,weather:w,date:new Date('2026-07-17T12:00:00-05:00')});assert.equal(tasks.some(row=>row.id==='water-plant-1'),false);assert.ok(tasks.some(row=>row.id==='soil-plant-1'));assert.equal(dryGarden.plants[0].lastWatered,plant.lastWatered)});

test('protected greenhouse receives no outdoor rain watering credit',()=>{const greenhousePlant={...plant,id:'green-plant',spaceId:'greenhouse',name:'Greenhouse Tomato'};const w=weather({recentRain24h:1,rainCreditBySpace:{bed:{amount:.9,factor:.9,exposure:'raised-bed'},greenhouse:{amount:0,factor:0,exposure:'fully-rain-protected'},inside:{amount:0,factor:0,exposure:'indoor'}},signals:{...weather().signals,recentMeaningfulRain:{status:true},greenhouseOverheatRisk:{status:false}}});const tasks=buildYearRoundTasks({garden:{...garden,plants:[greenhousePlant]},weather:w,date:new Date('2026-07-17T12:00:00-05:00')});const soil=tasks.find(row=>row.id==='soil-green-plant');assert.ok(soil);assert.match(soil.reason,/protected|no outdoor rain credit/i)});

test('weather task ids remain stable and duplicate-free',()=>{const w=weather({high:95,signals:{...weather().signals,heatStressRisk:{status:true,reason:'High heat may stress plants.'},greenhouseOverheatRisk:{status:true,reason:'Greenhouse may overheat.'}}});const tasks=buildYearRoundTasks({garden,weather:w,date:new Date('2026-07-17T12:00:00-05:00')});const ids=tasks.map(row=>row.id);assert.equal(new Set(ids).size,ids.length);assert.ok(tasks.some(row=>row.taskType==='Heat Protection'));assert.ok(tasks.some(row=>row.taskType==='Greenhouse Ventilation'))});

test('migration is idempotent and preserves environmental sync fields',()=>{const once=migrateGarden(garden,{profile:{},spaces:[],plants:[],activity:[]}),twice=migrateGarden(once,{profile:{},spaces:[],plants:[],activity:[]});assert.deepEqual(twice.environmentalRecords,once.environmentalRecords);assert.deepEqual(twice.environmentalCorrections,once.environmentalCorrections);assert.equal(twice.environmentSchemaVersion,1);assert.equal(twice.plants.length,1)});
