from pathlib import Path

path=Path('src/WorkspaceScreens.jsx')
text=path.read_text()
old="""function WeatherLine({weather,loading,error,refresh,source,stale,savedAt,guidance}){
 const groups=groupWeatherImpacts(guidance?.recommendations||[],3),primary=groups[0],sourceLabel=weather?.provider||'Weather source unavailable',freshness=source==='live'&&!stale?`${sourceLabel} · updated ${weatherTime(savedAt||weather?.fetchedAt)}`:source==='fallback'?`${sourceLabel} · fallback · updated ${weatherTime(savedAt||weather?.fetchedAt)}`:`Saved weather · updated ${weatherTime(savedAt||weather?.fetchedAt)}`,temperature=roundWeatherValue(weather?.temperature,{suffix:'°'}),high=roundWeatherValue(weather?.high,{suffix:'°'}),low=roundWeatherValue(weather?.low,{suffix:'°'}),recentRain=Number(weather?.recentRain24h||0),calm=!primary||primary.key==='calm';
 return <section className={`compact-weather-line phase-45-current-weather ${stale?'weather-is-stale':''}`}><div className="compact-weather-reading"><WeatherIcon weather={weather}/><span><strong>{weather?`${temperature||'Temperature unavailable'} · ${weather.condition||'Condition unavailable'}`:'Green Bay 54302 weather'}</strong><small>{loading?'Updating official weather…':error||[high&&`High ${high}`,low&&`Low ${low}`].filter(Boolean).join(' · ')||'High and low unavailable'}</small><em className="weather-freshness">{freshness}</em></span></div><button className="weather-refresh-button" onClick={refresh} aria-label="Refresh official weather"><RefreshCw/></button>{recentRain>0&&<div className="weather-rain-hold"><Droplets/><span><strong>{formatRainAmount(recentRain)} recorded recently</strong><small>Exposed spaces receive rain credit; protected spaces stay separate.</small></span></div>}{stale&&<div className="weather-stale-warning" role="status"><AlertTriangle/><span><strong>Weather may be outdated</strong><small>Use a soil check before making a definite watering decision.</small></span></div>}<div className={`compact-weather-message ${calm?'is-calm':''}`}><Check/><span><strong>{calm?'Conditions look steady':primary.title}</strong><small>{calm?'Routine garden care can continue.':primary.explanation||'See the prioritized garden impacts below.'}</small></span></div><button className="weather-rain-record" onClick={openWeatherDetails}><Droplets/>Record rain or view weather details</button></section>;
}"""
new="""function WeatherLine({weather,loading,error,refresh,source,stale,savedAt,guidance}){
 const groups=groupWeatherImpacts(guidance?.recommendations||[],3),primary=groups[0],sourceLabel=weather?.provider||'Weather source unavailable',freshness=source==='live'&&!stale?`${sourceLabel} · updated ${weatherTime(savedAt||weather?.fetchedAt)}`:source==='fallback'?`${sourceLabel} · fallback · updated ${weatherTime(savedAt||weather?.fetchedAt)}`:`Saved weather · updated ${weatherTime(savedAt||weather?.fetchedAt)}`,temperature=roundWeatherValue(weather?.temperature,{suffix:'°'}),high=roundWeatherValue(weather?.high,{suffix:'°'}),low=roundWeatherValue(weather?.low,{suffix:'°'}),recentRain=Number(weather?.recentRain24h||0),usableWeather=Boolean(temperature||(weather?.condition&&!/unavailable/i.test(weather.condition))),calm=!primary||primary.key==='calm',headline=usableWeather?`${temperature||'Temperature unavailable'} · ${weather.condition||'Condition unavailable'}`:loading?'Updating Green Bay weather':'Garden weather temporarily unavailable',subline=usableWeather?error||[high&&`High ${high}`,low&&`Low ${low}`].filter(Boolean).join(' · ')||'High and low unavailable':error||'Garden records and normal tools remain available.';
 return <section className={`compact-weather-line phase-45-current-weather ${stale&&usableWeather?'weather-is-stale':''}`}><div className="compact-weather-reading"><WeatherIcon weather={weather}/><span><strong>{headline}</strong><small>{subline}</small><em className="weather-freshness">{freshness}</em></span></div><button className="weather-refresh-button" onClick={refresh} aria-label="Refresh official weather"><RefreshCw/></button>{recentRain>0&&<div className="weather-rain-hold"><Droplets/><span><strong>{formatRainAmount(recentRain)} recorded recently</strong><small>Exposed spaces receive rain credit; protected spaces stay separate.</small></span></div>}{stale&&usableWeather&&!loading&&<div className="weather-stale-warning" role="status"><AlertTriangle/><span><strong>Weather may be outdated</strong><small>Use a soil check before making a definite watering decision.</small></span></div>}{usableWeather&&!loading&&<div className={`compact-weather-message ${calm?'is-calm':''}`}><Check/><span><strong>{calm?'Conditions look steady':primary.title}</strong><small>{calm?'Routine garden care can continue.':primary.explanation||'See the prioritized garden impacts below.'}</small></span></div>}<button className="weather-rain-record" onClick={openWeatherDetails}><Droplets/>Record rain or view weather details</button></section>;
}"""
if old not in text: raise SystemExit('weather line block not found')
path.write_text(text.replace(old,new,1))
print('compacted unavailable weather state')
