import crypto from'node:crypto';
import{load}from'cheerio';
const DAY=86400000,CACHE_TTL=7*DAY,cache=new Map();
const normalize=value=>String(value??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const same=(a,b)=>normalize(a)===normalize(b);
const TRUSTED_DOMAINS=new Set(['www.burpee.com','burpee.com','support.burpee.com','www.ferry-morse.com','ferry-morse.com','www.botanicalinterests.com','botanicalinterests.com']);
export const VERIFIED_PRODUCT_CACHE=[{provider:'curated-verified-cache',manufacturer:'Burpee',brand:'Burpee',crop:'Lettuce',variety:'Iceberg A',productName:'Iceberg A Lettuce Seeds',productId:'prod000747',sourceUrl:'https://www.burpee.com/lettuce-iceberg-a-prod000747.html',sourceTitle:'Burpee Iceberg A Lettuce Seeds',barcode:null,fields:{category:'Vegetable',designations:['Heirloom'],sunlight:'Full sun',daysToHarvest:65,plantingDepthValue:.25,plantingDepthUnit:'inch',emergenceMinimumDays:7,emergenceMaximumDays:10,containerFriendly:true,directSowGuidance:'Sow in average soil in full sun in early spring and again in late summer for a fall crop.',moistureGuidance:'Keep evenly moist throughout growth.',soilGuidance:'Average, well-drained soil enriched with organic matter.',successionGuidance:'Sow every two weeks to extend the harvest.',harvestGuidance:'Harvest when the head is firm and full-sized.'}}];
function score(identity,candidate){let points=0,reasons=[];if(identity.barcode&&candidate.barcode&&same(identity.barcode,candidate.barcode)){points+=120;reasons.push('exact barcode')}if(identity.sku&&candidate.productId&&same(identity.sku,candidate.productId)){points+=100;reasons.push('exact product ID')}if(identity.brand&&same(identity.brand,candidate.brand)){points+=25;reasons.push('brand')}if(identity.crop&&same(identity.crop,candidate.crop)){points+=25;reasons.push('crop')}if(identity.variety&&same(identity.variety,candidate.variety)){points+=55;reasons.push('variety')}if(identity.productName&&same(identity.productName,candidate.productName)){points+=35;reasons.push('product name')}return{score:points,reasons,exact:points>=90&&(reasons.includes('exact barcode')||reasons.includes('exact product ID')||(reasons.includes('brand')&&reasons.includes('crop')&&reasons.includes('variety')))}}
async function fetchTextSafe(url,{timeoutMs=5500,maxBytes=350000}={}){const target=new URL(url);if(!TRUSTED_DOMAINS.has(target.hostname))throw new Error('Untrusted product source.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(target,{signal:controller.signal,headers:{'user-agent':'RunyanGardenProductResearch/1.0'}});if(!response.ok)throw new Error(`Source returned ${response.status}.`);const length=Number(response.headers.get('content-length')||0);if(length>maxBytes)throw new Error('Product source response was too large.');const reader=response.body.getReader();let total=0,chunks=[];while(true){const{done,value}=await reader.read();if(done)break;total+=value.length;if(total>maxBytes)throw new Error('Product source response was too large.');chunks.push(value)}return Buffer.concat(chunks).toString('utf8')}finally{clearTimeout(timer)}}
async function officialManufacturerSearch(identity){if(normalize(identity.brand)!=='burpee'||!identity.variety||!identity.crop)return[];const query=encodeURIComponent(`${identity.crop} ${identity.variety}`),searchUrl=`https://www.burpee.com/search?q=${query}`;try{const html=await fetchTextSafe(searchUrl),$=load(html),links=[];$('a[href]').each((_,node)=>{const href=$(node).attr('href'),text=normalize($(node).text());if(!href||!text.includes(normalize(identity.variety)))return;const url=new URL(href,searchUrl);if(TRUSTED_DOMAINS.has(url.hostname)&&/lettuce|seed|product/i.test(url.pathname))links.push(url.href)});return[...new Set(links)].slice(0,3).map((url,index)=>({provider:'official-manufacturer-search',manufacturer:identity.brand,brand:identity.brand,crop:identity.crop,variety:identity.variety,productName:identity.productName||`${identity.variety} ${identity.crop} Seeds`,productId:null,sourceUrl:url,sourceTitle:`${identity.brand} official product result ${index+1}`,fields:{}}))}catch{return[]}}
async function externalProvider(identity){const endpoint=process.env.SEED_PACKET_PRODUCT_PROVIDER_URL;if(!endpoint)return[];const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000);try{const response=await fetch(endpoint,{method:'POST',signal:controller.signal,headers:{'content-type':'application/json'},body:JSON.stringify(identity)});if(!response.ok)return[];const json=await response.json();return Array.isArray(json?.candidates)?json.candidates:[]}catch{return[]}finally{clearTimeout(timer)}}
export async function researchExactProduct(identity){const key=crypto.createHash('sha256').update(JSON.stringify(identity)).digest('hex'),cached=cache.get(key);if(cached&&Date.now()-cached.at<CACHE_TTL)return{...cached.result,cacheHit:true};const providers=[VERIFIED_PRODUCT_CACHE,await officialManufacturerSearch(identity),await externalProvider(identity)],candidates=providers.flat().map(candidate=>({...candidate,match:score(identity,candidate),fetchedAt:new Date().toISOString()})).filter(row=>row.match.score>=50).sort((a,b)=>b.match.score-a.match.score),primary=candidates[0]?.match.exact?candidates[0]:null,result={primary,candidates:candidates.slice(0,3),providerCount:providers.length,cacheHit:false};cache.set(key,{at:Date.now(),result});return result}
