import { z } from 'zod';

const nullableText = z.string().trim().max(500).nullable();
const nullableNumber = z.number().finite().nullable();
const confidence = z.enum(['high','medium','low']);
const evidenceSource = z.enum(['front','back','both','barcode','official-source','inferred']);
const evidence = z.object({value:z.union([z.string(),z.number(),z.boolean(),z.array(z.string())]).nullable(),sourceImage:evidenceSource,visibleEvidence:z.string().trim().max(500),confidence,printed:z.boolean(),normalized:z.boolean()});
const packetIdentity = z.object({brand:nullableText,crop:nullableText,variety:nullableText,productName:nullableText,category:nullableText,designations:z.array(z.string().trim().max(80)).max(12),notableClaims:z.array(z.string().trim().max(160)).max(20),colorDescription:nullableText});
const inventory = z.object({packetWeightValue:nullableNumber,packetWeightUnit:z.enum(['g','mg','oz','lb','count']).nullable(),printedSeedCount:nullableNumber,inventoryBasis:z.enum(['exact-count','approximate-count','weight','unknown']),estimatedSeedCount:nullableNumber,estimatedSeedCountSource:nullableText,estimatedSeedCountConfidence:confidence.nullable(),packetYear:z.number().int().min(1900).max(2100).nullable(),packedForYear:z.number().int().min(1900).max(2100).nullable(),sellByDate:nullableText,purchasePrice:nullableNumber});
const machineIdentifiers = z.object({barcode:nullableText,barcodeFormat:z.enum(['UPC-A','UPC-E','EAN-8','EAN-13','CODE-128','unknown']).nullable(),sku:nullableText,catalogNumber:nullableText,lotNumber:nullableText,productCode:nullableText,barcodeConfidence:confidence.nullable(),barcodeMethod:z.enum(['machine-decoder','vision-read','both','unavailable']).nullable(),checkDigitValid:z.boolean().nullable(),visibleDigits:nullableText});
const growing = z.object({sunlight:nullableText,daysToHarvest:nullableNumber,daysToMaturity:nullableNumber,maturityBasis:z.enum(['sowing','transplant','unknown']).nullable(),emergenceMinimumDays:nullableNumber,emergenceMaximumDays:nullableNumber,germinationTemperatureMinimum:nullableNumber,germinationTemperatureMaximum:nullableNumber,plantingDepthValue:nullableNumber,plantingDepthUnit:z.enum(['inch','cm']).nullable(),thinningSpacingValue:nullableNumber,thinningSpacingUnit:z.enum(['inch','cm']).nullable(),finalSpacingValue:nullableNumber,finalSpacingUnit:z.enum(['inch','cm']).nullable(),rowSpacingValue:nullableNumber,rowSpacingUnit:z.enum(['inch','cm']).nullable(),containerMinimumDiameterValue:nullableNumber,containerMinimumDiameterUnit:z.enum(['inch','cm']).nullable(),plantsPerContainer:nullableNumber,plantHeight:nullableText,plantSpread:nullableText,growthHabit:nullableText,containerFriendly:z.boolean().nullable()});
const instructions = z.object({sowingMethod:nullableText,directSowGuidance:nullableText,indoorStartGuidance:nullableText,transplantGuidance:nullableText,seasonalWindow:nullableText,frostTiming:nullableText,moistureGuidance:nullableText,soilGuidance:nullableText,fertilizingGuidance:nullableText,successionGuidance:nullableText,harvestGuidance:nullableText,regionalGuidance:nullableText,warnings:z.array(z.string().trim().max(240)).max(20),treatmentInformation:nullableText,seedSavingRestrictions:nullableText,specialCare:nullableText});
const automation = z.object({successionRecommended:z.boolean(),successionIntervalDays:nullableNumber,successionReminderText:nullableText,successionReason:nullableText,otherSuggestedReminders:z.array(z.object({text:z.string().trim().max(240),reason:z.string().trim().max(240),daysAfterPlanting:nullableNumber})).max(10)});
const quality = z.object({frontUsable:z.boolean(),backUsable:z.boolean(),packetIdentityConfidence:confidence,overallConfidence:confidence,exactIdentitySupportedByImages:z.boolean(),manualReviewFields:z.array(z.string()).max(50),unreadableFields:z.array(z.string()).max(100),contradictoryFields:z.array(z.string()).max(50),analysisNotes:z.array(z.string().trim().max(300)).max(30)});
export const seedPacketVisionSchema = z.object({analysisVersion:z.literal('seed-packet-vision-v1'),packetIdentity,inventory,growing,instructions,automation,machineIdentifiers,quality,fieldEvidence:z.record(z.string(),evidence),rawVisibleText:z.object({front:z.string().max(10000),back:z.string().max(10000)}),warnings:z.array(z.string().trim().max(300)).max(40)}).strict();

const bannedIdentity=/\b(full sun|vegetable|heirloom|organic|container|days? to|harvest|depth|spacing)\b/i;
const fragment=/^(?:\d+\s*)?(?:outdoor sown|to harvest|full sun)$/i;
export function validateSeedPacketAnalysis(input){
 const parsed=seedPacketVisionSchema.parse(input),errors=[];
 const {packetIdentity:i,instructions:s,inventory:q,machineIdentifiers:m,fieldEvidence:e}=parsed;
 if(i.variety&&bannedIdentity.test(i.variety))errors.push('variety contains a non-variety label');
 if(i.productName&&/\b(full sun|vegetable|heirloom)\b/i.test(i.productName))errors.push('productName contains an unrelated label');
 for(const [key,value] of Object.entries({directSowGuidance:s.directSowGuidance,moistureGuidance:s.moistureGuidance,soilGuidance:s.soilGuidance,harvestGuidance:s.harvestGuidance}))if(value&&(value.length<12||fragment.test(value)||/^\$/.test(value)))errors.push(`${key} is incomplete or malformed`);
 if(q.inventoryBasis==='weight'&&q.printedSeedCount!==null)errors.push('weight-only inventory cannot claim a printed seed count');
 if(m.checkDigitValid===false&&m.barcodeMethod==='machine-decoder')errors.push('machine-decoded barcode failed check digit');
 const evidenceRequired=['brand','crop','variety','productName','packetWeightValue','sunlight','daysToHarvest','plantingDepthValue','emergenceMinimumDays','directSowGuidance','moistureGuidance','successionGuidance'];
 for(const key of evidenceRequired){const value=key in i?i[key]:key in q?q[key]:key in parsed.growing?parsed.growing[key]:s[key];if(value!==null&&value!==''&&value!==undefined&&!e[key])errors.push(`${key} is missing field evidence`)}
 if(errors.length){const error=new Error('Seed packet analysis failed validation');error.code='MODEL_RESPONSE_INVALID';error.validationErrors=errors;throw error}
 return parsed;
}

export const seedPacketJsonSchema={name:'seed_packet_vision',strict:true,schema:{type:'object',additionalProperties:false,required:['analysisVersion','packetIdentity','inventory','growing','instructions','automation','machineIdentifiers','quality','fieldEvidence','rawVisibleText','warnings'],properties:{analysisVersion:{const:'seed-packet-vision-v1'},packetIdentity:{type:'object'},inventory:{type:'object'},growing:{type:'object'},instructions:{type:'object'},automation:{type:'object'},machineIdentifiers:{type:'object'},quality:{type:'object'},fieldEvidence:{type:'object'},rawVisibleText:{type:'object'},warnings:{type:'array',items:{type:'string'}}}}};
