import{readFile,writeFile}from'node:fs/promises';

async function patch(path,changes){let source=await readFile(path,'utf8'),changed=false;for(const{old,next,label}of changes){if(source.includes(next))continue;if(!source.includes(old))throw new Error(`${path}: expected source not found for ${label}`);source=source.replace(old,next);changed=true}if(changed)await writeFile(path,source);return changed}

const appChanged=await patch('src/App.jsx',[
 {label:'page routing import',old:"import{applySeedTransaction,integrityHash}from'./dataReadiness.js';",next:"import{applySeedTransaction,integrityHash}from'./dataReadiness.js';\nimport{pageFromPopState,readInitialPage,syncPageUrl}from'./pageRouting.js';"},
 {label:'direct initial page',old:"const[page,setPage]=useState('today'),history=useRef([{page:'today',scroll:0}]),",next:"const initialPageRef=useRef(readInitialPage()),[page,setPage]=useState(initialPageRef.current),history=useRef([{page:initialPageRef.current,scroll:0}]),"},
 {label:'initial URL and popstate handling',old:"useEffect(()=>{try{localStorage.setItem(PAGE_KEY,page)}catch(error){console.error('[Runyan Garden] page-state persistence failure',error)}},[page]);useEffect(()=>{const result=persistJson(GARDEN_KEY,garden);",next:"useEffect(()=>{try{localStorage.setItem(PAGE_KEY,page)}catch(error){console.error('[Runyan Garden] page-state persistence failure',error)}},[page]);useEffect(()=>{syncPageUrl(page,{replace:true});const onPopState=event=>{const params=new URLSearchParams(window.location.search);if(params.has('bed')||params.has('gardenLabel')){window.location.reload();return}const target=pageFromPopState(event);history.current=[{page:target,scroll:0}];setPage(target);setNoticeOpen(false);setModal(null);requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}))};window.addEventListener('popstate',onPopState);return()=>window.removeEventListener('popstate',onPopState)},[]);useEffect(()=>{const result=persistJson(GARDEN_KEY,garden);"},
 {label:'contextual back URL',old:"setPage(previous.page);setNoticeOpen(false);",next:"setPage(previous.page);syncPageUrl(previous.page,{replace:true});setNoticeOpen(false);"},
 {label:'fallback back URL',old:"}else{setPage('today');requestAnimationFrame(()=>window.scrollTo(0,0))}return}",next:"}else{setPage('today');syncPageUrl('today',{replace:true});requestAnimationFrame(()=>window.scrollTo(0,0))}return}"},
 {label:'forward page URL',old:"if(target!==page)history.current.push({page:target,scroll:0});setPage(target);setNoticeOpen(false);",next:"if(target!==page)history.current.push({page:target,scroll:0});setPage(target);syncPageUrl(target);setNoticeOpen(false);"}
]);

const bedChanged=await patch('src/BedWorkspace.jsx',[
 {label:'Growing Space imports',old:"import{publicBedLink}from'./qrExport.js';",next:"import{publicBedLink}from'./qrExport.js';\nimport{GROWING_SPACE_TYPES,normalizeSpaceIntelligence}from'./gardenIntelligence.js';\nimport{cleanGrowingSpaceForType,SOIL_SPACE_TYPES}from'./spaceRecord.js';"},
 {label:'type labels',old:"container:'Container',greenhouse:'Greenhouse'",next:"container:'Container Planter','potato-grow-bag':'Potato Grow Bag',greenhouse:'Greenhouse'"},
 {label:'complete edit draft',old:"const[d,setD]=useState({name:space.name,type:space.type,capacity:space.capacity||12,notes:space.notes||'',photo:space.photo||''}),[tab,setTab]=useState('bed'),[copyStatus,setCopyStatus]=useState('');",next:"const[d,setD]=useState(()=>normalizeSpaceIntelligence({...space,capacity:space.capacity||12,notes:space.notes||'',photo:space.photo||''})),[tab,setTab]=useState('bed'),[copyStatus,setCopyStatus]=useState(''),container=d.type==='container',growBag=d.type==='potato-grow-bag',soilSpace=SOIL_SPACE_TYPES.has(d.type);"},
 {label:'shared type options',old:"<select value={d.type} onChange={e=>setD({...d,type:e.target.value})}><option value=\"black-square-bed\">Black square raised bed</option><option value=\"white-oval-bed\">White rounded raised bed</option><option value=\"bed\">Other raised bed</option><option value=\"in-ground\">In-ground garden bed</option><option value=\"container\">Container or pot</option><option value=\"greenhouse\">Greenhouse</option><option value=\"indoor\">Indoor growing area</option><option value=\"basement\">Basement growing area</option><option value=\"hydro\">Hydroponics</option></select>",next:"<select value={d.type} onChange={e=>setD({...d,type:e.target.value})}>{GROWING_SPACE_TYPES.map(type=><option key={type.value} value={type.value}>{type.label}</option>)}</select>"},
 {label:'conditional edit fields',old:"</label><label>Private garden notes<textarea value={d.notes}",next:"</label>{soilSpace&&<><label>Soil type<input value={d.soilType||''} onChange={e=>setD({...d,soilType:e.target.value})}/></label><label>Drainage quality<select value={d.drainageQuality||''} onChange={e=>setD({...d,drainageQuality:e.target.value})}><option value=\"\">Not recorded</option><option>Fast</option><option>Moderate</option><option>Slow</option><option>Poor</option></select></label><label>Mulch status<select value={d.mulchStatus||''} onChange={e=>setD({...d,mulchStatus:e.target.value})}><option value=\"\">Not recorded</option><option>None</option><option>Straw</option><option>Wood chips</option><option>Leaves</option><option>Other</option></select></label><label>Irrigation method<input value={d.irrigationMethod||''} onChange={e=>setD({...d,irrigationMethod:e.target.value})}/></label><label>Sun exposure<input value={d.sunExposure||''} onChange={e=>setD({...d,sunExposure:e.target.value})}/></label></>}{container&&<><label>Container size<input value={d.size||''} onChange={e=>setD({...d,size:e.target.value})} placeholder=\"Example: 5 gallon\"/></label><label>Container material<input value={d.material||''} onChange={e=>setD({...d,material:e.target.value})}/></label><label className=\"checkbox-line\"><input type=\"checkbox\" checked={Boolean(d.drainageHoles)} onChange={e=>setD({...d,drainageHoles:e.target.checked})}/> Drainage holes</label><label className=\"checkbox-line\"><input type=\"checkbox\" checked={Boolean(d.selfWateringReservoir)} onChange={e=>setD({...d,selfWateringReservoir:e.target.checked})}/> Self-watering reservoir</label></>}{growBag&&<><label>Grow bag size<input value={d.bagSize||''} onChange={e=>setD({...d,bagSize:e.target.value})} placeholder=\"Example: 10 gallon\"/></label><label>Seed potatoes planted<input type=\"number\" min=\"0\" value={d.seedPotatoesPlanted||''} onChange={e=>setD({...d,seedPotatoesPlanted:e.target.value})}/></label><label>Hilling stage<input value={d.hillingStage||''} onChange={e=>setD({...d,hillingStage:e.target.value})}/></label><label>Last hilled<input type=\"date\" value={d.lastHilledDate||''} onChange={e=>setD({...d,lastHilledDate:e.target.value})}/></label></>}<label>Private garden notes<textarea value={d.notes}"},
 {label:'typed edit cleanup',old:"saveSpace(space.id,d);close()",next:"saveSpace(space.id,cleanGrowingSpaceForType(d));close()"}
]);

const modalChanged=await patch('src/ClearDetailModal.jsx',[
 {label:'space cleanup import',old:"import{activeSeedPacketInventory,packetSeedUseDefaults}from'./gardenIntelligenceEngine.js';",next:"import{activeSeedPacketInventory,packetSeedUseDefaults}from'./gardenIntelligenceEngine.js';\nimport{cleanGrowingSpaceForType}from'./spaceRecord.js';"},
 {label:'typed create cleanup',old:"addSpace(d);close()",next:"addSpace(cleanGrowingSpaceForType(d));close()"}
]);

const workspaceChanged=await patch('src/WorkspaceScreens.jsx',[
 {label:'dynamic Today identity',old:"<h1>{profile.gardenerName||'Brooke'}'s Garden</h1><p>The Runyan Garden - Green Bay</p>",next:"<h1>{profile.gardenerName||'Brooke'}’s Garden</h1><p>{profile.gardenName||'The Runyan Garden'} — {String(profile.location||'Green Bay').replace(/\\s+54302$/,'').replace(/,\\s*Wisconsin$/,'')}</p>"}
]);

const seedChanged=await patch('src/SeedTools.jsx',[
 {label:'germination range encoding',old:'placeholder="7â€“14 days"',next:'placeholder="7–14 days"'}
]);

console.log(JSON.stringify({ok:true,changed:{appChanged,bedChanged,modalChanged,workspaceChanged,seedChanged}},null,2));
