import{readFile,writeFile}from'node:fs/promises';
async function patch(path,changes){let source=await readFile(path,'utf8'),changed=false;for(const{old,next,label}of changes){if(source.includes(next))continue;if(!source.includes(old))throw new Error(`${path}: expected source not found for ${label}`);source=source.replace(old,next);changed=true}if(changed)await writeFile(path,source);return changed}

const bedChanged=await patch('src/BedWorkspace.jsx',[
 {label:'public back accessible name',old:'<button className="public-bed-back" onClick={onExit}><ArrowLeft/></button>',next:'<button className="public-bed-back" onClick={onExit} aria-label="Back to all Growing Spaces"><ArrowLeft/></button>'},
 {label:'move up accessible name',old:'<button disabled={index===0} onClick={()=>manage(\'up\',space.id)}><ArrowUp/></button>',next:'<button disabled={index===0} onClick={()=>manage(\'up\',space.id)} aria-label={`Move ${space.name} up`}><ArrowUp/></button>'},
 {label:'move down accessible name',old:'<button disabled={index===total-1} onClick={()=>manage(\'down\',space.id)}><ArrowDown/></button>',next:'<button disabled={index===total-1} onClick={()=>manage(\'down\',space.id)} aria-label={`Move ${space.name} down`}><ArrowDown/></button>'},
 {label:'space detail close accessible name',old:'<button className="modal-close" onClick={close}><X/></button><Cover',next:'<button className="modal-close" onClick={close} aria-label="Close Growing Space details"><X/></button><Cover'}
]);

const auditChanged=await patch('scripts/verifyPhase474WholeApp.mjs',[
 {label:'Garden Memory expected title',old:"route('memory','Garden History',page=>centerCard(page,'Garden History'))",next:"route('memory','Garden Memory',page=>centerCard(page,'Garden History'))"},
 {label:'Whats New flexible expected title',old:'route(\'admin-whatsnew\',"What\'s New",page=>moreCard(page,"What\'s New"))',next:'route(\'admin-whatsnew\',"Meaningful user-facing changes",page=>moreCard(page,"What\'s New"))'},
 {label:'associated form label audit',old:"const rows=await page.locator('button:visible,a:visible,summary:visible,input:visible,select:visible,textarea:visible').evaluateAll(nodes=>nodes.map((node,index)=>{const box=node.getBoundingClientRect(),label=(node.getAttribute('aria-label')||node.getAttribute('title')||node.innerText||node.getAttribute('placeholder')||node.getAttribute('name')||'').trim().replace(/\\s+/g,' ');return{index,tag:node.tagName.toLowerCase(),label,width:box.width,height:box.height,disabled:Boolean(node.disabled),href:node.getAttribute('href')||''}}))",next:"const rows=await page.locator('button:visible,a:visible,summary:visible,input:visible,select:visible,textarea:visible').evaluateAll(nodes=>nodes.map((node,index)=>{const box=node.getBoundingClientRect(),associated=node.closest('label')?.innerText||'',label=(node.getAttribute('aria-label')||node.getAttribute('title')||node.innerText||associated||node.getAttribute('placeholder')||node.getAttribute('name')||'').trim().replace(/\\s+/g,' ');return{index,tag:node.tagName.toLowerCase(),label,width:box.width,height:box.height,disabled:Boolean(node.disabled),href:node.getAttribute('href')||''}}))"},
 {label:'modal route content audit',old:"const text=(await page.locator('main').first().innerText()).trim();assert.ok(text.length>20,`${routeId} appears blank at ${width}px`);assert.match(text,new RegExp(escape(expected),'i'),`${routeId} did not show ${expected} at ${width}px`);",next:"const text=(await page.locator('main').first().innerText()).trim(),visibleText=(await page.locator('body').innerText()).trim();assert.ok(text.length>20,`${routeId} appears blank at ${width}px`);assert.match(visibleText,new RegExp(escape(expected),'i'),`${routeId} did not show ${expected} at ${width}px`);"}
]);
console.log(JSON.stringify({ok:true,changed:{bedChanged,auditChanged}},null,2));
