import{readFile,writeFile}from'node:fs/promises';
async function patch(path,changes){let source=await readFile(path,'utf8'),changed=false;for(const{old,next,label}of changes){if(source.includes(next))continue;if(!source.includes(old))throw new Error(`${path}: expected source not found for ${label}`);source=source.replace(old,next);changed=true}if(changed)await writeFile(path,source);return changed}

const choreChanged=await patch('src/ChoreBoard.jsx',[
 {label:'chore edit delete icons',old:"import{CalendarPlus,Check,ChevronDown,ClipboardList,CloudRain,Leaf,Plus,Sprout,Undo2,Warehouse,XCircle}from'lucide-react';",next:"import{CalendarPlus,Check,ChevronDown,ClipboardList,CloudRain,Leaf,Pencil,Plus,Sprout,Trash2,Undo2,Warehouse,XCircle}from'lucide-react';"},
 {label:'row edit delete props',old:'function Row({task,completion,onOpen,onOpenPlant,onOpenSpace,onStatus,onUndo})',next:'function Row({task,completion,onOpen,onOpenPlant,onOpenSpace,onStatus,onUndo,onEdit,onDelete})'},
 {label:'manual task actions',old:'<div className="task-secondary-outcomes"><button onClick={()=>onStatus(task,\'not-needed\')}',next:'{task.manual&&<div className="task-navigation-actions manual-task-management"><button onClick={()=>onEdit(task)}><Pencil/>Edit task</button><button className="danger-space-action" onClick={()=>onDelete(task)}><Trash2/>Delete task</button></div>}<div className="task-secondary-outcomes"><button onClick={()=>onStatus(task,\'not-needed\')}'},
 {label:'editable reminder form',old:"function ReminderForm({garden,onAdd,onClose}){const[d,setD]=useState({title:'',taskType:'Check Moisture',plantId:'',spaceId:'',priority:60,dueDate:todayKey(),reason:'',note:''}),selectedPlant=garden.plants.find(plant=>plant.id===d.plantId),submit=event=>{event.preventDefault();if(!d.title.trim())return;onAdd({...d,spaceId:d.spaceId||selectedPlant?.spaceId||''});onClose()};",next:"function ReminderForm({garden,onAdd,onSave,onClose,initial=null}){const base={title:'',taskType:'Check Moisture',plantId:'',spaceId:'',priority:60,dueDate:todayKey(),reason:'',note:''},[d,setD]=useState(()=>({...base,...initial,plantId:initial?.plantId||initial?.plant?.id||'',spaceId:initial?.spaceId||initial?.space?.id||''})),selectedPlant=garden.plants.find(plant=>plant.id===d.plantId),submit=event=>{event.preventDefault();if(!d.title.trim())return;const data={...d,spaceId:d.spaceId||selectedPlant?.spaceId||''};if(initial)onSave(initial.id,data);else onAdd(data);onClose()};"},
 {label:'editable reminder heading',old:'<span className="section-kicker">MANUAL REMINDER</span><h2>Add a garden task</h2>',next:'<span className="section-kicker">{initial?\'EDIT MANUAL REMINDER\':\'MANUAL REMINDER\'}</span><h2>{initial?\'Edit garden task\':\'Add a garden task\'}</h2>'},
 {label:'editable reminder submit copy',old:'<button className="primary-button"><CalendarPlus/>Add to Chore Board</button>',next:'<button className="primary-button"><CalendarPlus/>{initial?\'Save task changes\':\'Add to Chore Board\'}</button>'},
 {label:'Chore Board lifecycle props and state',old:"export default function ChoreBoard({todayTasks,dailyDone,onOpen,onOpenPlant,onOpenSpace,onStatus,onUndo,navigate,garden,onAddReminder}){const[filter,setFilter]=useState('All'),[adding,setAdding]=useState(false),",next:"export default function ChoreBoard({todayTasks,dailyDone,onOpen,onOpenPlant,onOpenSpace,onStatus,onUndo,navigate,garden,onAddReminder,onUpdateReminder,onDeleteReminder}){const[filter,setFilter]=useState('All'),[adding,setAdding]=useState(false),[editing,setEditing]=useState(null),"},
 {label:'row lifecycle callbacks',old:'rowProps={completion,onOpen,onOpenPlant,onOpenSpace,onStatus,onUndo},attention=',next:"rowProps={completion,onOpen,onOpenPlant,onOpenSpace,onStatus,onUndo,onEdit:task=>{setEditing(task);setAdding(false)},onDelete:task=>{if(window.confirm(`Delete “${task.title}”? This removes only this manual reminder.`))onDeleteReminder(task.id)}},attention="},
 {label:'Add task resets edit state',old:'<button onClick={()=>setAdding(true)}><Plus/>Add task</button>',next:'<button onClick={()=>{setEditing(null);setAdding(true)}}><Plus/>Add task</button>'},
 {label:'add and edit forms',old:'{adding&&<ReminderForm garden={garden} onAdd={onAddReminder} onClose={()=>setAdding(false)}/>}<section className="chore-filter-block">',next:'{adding&&<ReminderForm garden={garden} onAdd={onAddReminder} onClose={()=>setAdding(false)}/>} {editing&&<ReminderForm garden={garden} initial={editing} onSave={onUpdateReminder} onClose={()=>setEditing(null)}/>}<section className="chore-filter-block">'}
]);

const appChanged=await patch('src/App.jsx',[
 {label:'plant confirmation close label',old:'<button className="plant-confirmation-close" onClick={onClose}><X/></button>',next:'<button className="plant-confirmation-close" onClick={onClose} aria-label="Close planting confirmation"><X/></button>'},
 {label:'manual reminder update delete handlers',old:"showToast('Reminder added to the Chore Board.');return{status:'added',task:candidate}},savePlantingDecision=",next:"showToast('Reminder added to the Chore Board.');return{status:'added',task:candidate}},updateReminder=(id,data)=>{setGarden(current=>({...current,reminders:(current.reminders||[]).map(reminder=>reminder.taskId===id||reminder.id===id?touchRecord({...reminder,...data,title:String(data.title||reminder.title).trim(),plantId:data.plantId||'',spaceId:data.spaceId||'',priority:Number(data.priority)||60},actor):reminder)}));showToast('Garden task updated.')},deleteReminder=id=>{setGarden(current=>({...current,reminders:(current.reminders||[]).map(reminder=>reminder.taskId===id||reminder.id===id?softDelete(reminder,actor):reminder)}));setDaily(current=>({...current,done:(current.done||[]).filter(item=>item.id!==id)}));showToast('Garden task deleted.')},savePlantingDecision="},
 {label:'manual reminder resolution timestamp',old:"reminders:task.manual?(current.reminders||[]).map(reminder=>reminder.taskId===task.id?touchRecord({...reminder,enabled:false,status:status==='done'?'completed':normalizedStatus,completedAt:status==='done'?at:null},actor):reminder):current.reminders||[]",next:"reminders:task.manual?(current.reminders||[]).map(reminder=>reminder.taskId===task.id?touchRecord({...reminder,enabled:false,status:status==='done'?'completed':normalizedStatus,completedAt:at},actor):reminder):current.reminders||[]"},
 {label:'undo task status and manual reminder resolution',old:"const undoDaily=id=>{setDaily(current=>({...current,done:(current.done||[]).filter(item=>item.id!==id)}));showToast('Task status undone for today.')}",next:"const undoDaily=id=>{setDaily(current=>({...current,done:(current.done||[]).filter(item=>item.id!==id)}));setGarden(current=>({...current,reminders:(current.reminders||[]).map(reminder=>reminder.taskId===id?touchRecord({...reminder,enabled:true,status:'scheduled',completedAt:null},actor):reminder),taskHistory:(current.taskHistory||[]).map(entry=>entry.taskId===id&&entry.dueDate===dayKey()&&!entry.deletedAt?softDelete(entry,actor):entry)}));showToast('Task status undone for today.')}"},
 {label:'Chore Board lifecycle props',old:'onAddReminder={addReminder}/>} {page===\'garden\'',next:'onAddReminder={addReminder} onUpdateReminder={updateReminder} onDeleteReminder={deleteReminder}/>} {page===\'garden\''}
]);

const yearRoundChanged=await patch('src/yearRoundEngine.js',[
 {label:'resolved manual chores remain in same-day history',old:"function manualTasks(garden,date){return(garden.reminders||[]).filter(item=>!item.deletedAt&&item.enabled!==false).map(item=>task({id:item.taskId||`manual-${item.id}`,kind:'manual'",next:"function manualTasks(garden,date){const today=dateKey(date);return(garden.reminders||[]).filter(item=>!item.deletedAt&&(item.enabled!==false||Boolean(item.completedAt&&dateKey(item.completedAt)===today))).map(item=>task({id:item.taskId||`manual-${item.id}`,kind:'manual'"}
]);

const modalChanged=await patch('src/ClearDetailModal.jsx',[
 {label:'generic modal close label',old:'<button className="modal-close" onClick={close}><X/></button>{modal.type===\'addPlant\'',next:'<button className="modal-close" onClick={close} aria-label="Close dialog"><X/></button>{modal.type===\'addPlant\''}
]);
console.log(JSON.stringify({ok:true,changed:{choreChanged,appChanged,yearRoundChanged,modalChanged}},null,2));