import assert from'node:assert/strict';
import{mkdir,readFile,writeFile}from'node:fs/promises';
import{chromium}from'playwright';

const base=(process.env.APP_URL||'http://127.0.0.1:4173').replace(/\/$/,'');
const now=new Date().toISOString(),today=now.slice(0,10);
const emptyGarden={schemaVersion:10,profile:{gardenerName:'Archie',activeProfileId:'archie',gardenName:'The Runyan Garden',location:'Green Bay, Wisconsin 54302',zip:'54302',zone:'5b',lastFrost:'May 15',firstFrost:'October 10',notifications:{weather:true,tasks:true,shopping:true}},spaces:[],plants:[],seedPackets:[],reminders:[],taskHistory:[],seedTransactions:[],seedUsage:[],activity:[],harvests:[],problems:[],succession:[],trays:[],growLights:[],hardeningPlans:[],hydroPods:[],greenhouseReadings:[],plantingDecisions:[],shoppingItems:[],weatherRecommendationHistory:[],vacationPlans:[],calculatorResults:[],environmentalRecords:[],environmentalCorrections:[],wateringEvents:[],soilCheckEvents:[],photos:[],attachments:[],qrLabels:[],offlineOperations:[],yearPlan:{crops:[]}};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nWQAAAAASUVORK5CYII=','base64');
await mkdir('phase474-audit/journeys',{recursive:true});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({serviceWorkers:'block',viewport:{width:390,height:900},deviceScaleFactor:1}),findings=[],steps=[];
const record=(name,status='pass',detail='')=>steps.push({name,status,detail});
const garden=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('brookes-garden-state-v2')||'{}'));
const waitGarden=async(page,predicate,label)=>{const deadline=Date.now()+10000;let snapshot={};while(Date.now()<deadline){snapshot=await garden(page).catch(()=>({}));if(predicate(snapshot))return snapshot;await page.waitForTimeout(75)}throw new Error(`${label}. Current stored state: ${JSON.stringify(snapshot).slice(0,2000)}`)};
async function go(page,id){await page.goto(`${base}/?page=${encodeURIComponent(id)}`,{waitUntil:'networkidle'});await page.locator('main').first().waitFor({state:'visible'})}
async function doubleActivate(locator){await locator.evaluate(node=>{node.click();node.click()})}
async function verifyPlantingDeskReadability(page){
 const widths=[320,375,390,430];
 await page.evaluate(()=>{const garden=JSON.parse(localStorage.getItem('brookes-garden-state-v2')||'{}'),packet=(garden.seedPackets||[]).find(row=>!row.deletedAt&&/lettuce/i.test(row.name||row.crop||''));if(!packet)return;Object.assign(packet,{cropId:'lettuce',crop:'Lettuce',name:'Lettuce',brand:packet.brand||'Burpee',variety:packet.variety||'QA Iceberg A Corrected',packetYear:packet.packetYear||'2026',sowingMethod:'Direct Sow',sunlight:'Full sun',daysToMaturity:Number(packet.daysToMaturity)||70,maturityBasis:packet.maturityBasis||'sowing',depth:packet.depth||'0.25 inches',spacing:packet.spacing||'12 inches',germinationEstimate:packet.germinationEstimate||'7–14 days',successionGuidance:packet.successionGuidance||'Sow every 14 days',packetIntelligence:{...(packet.packetIntelligence||{}),vision:{...(packet.packetIntelligence?.vision||{}),exactIdentitySupportedByImages:true,overallAnalysisConfidence:'high'}}});localStorage.setItem('brookes-garden-state-v2',JSON.stringify(garden))});
 for(const width of widths){
  await page.setViewportSize({width,height:900});await go(page,'plan-plant');
  const group=page.locator('.saved-seed-queue-groups details.opportunity-group').filter({hasText:/[1-9]\d* recommendation/i}).first();
  await group.waitFor({state:'visible',timeout:10000});if(!(await group.getAttribute('open')))await group.locator(':scope > summary').click();
  const card=group.locator('.intelligence-queue-card.collapsed-recommendation').first(),summary=card.locator(':scope > summary');await card.waitFor({state:'visible',timeout:10000});
  const layout=await summary.evaluate(node=>{const visible=element=>{if(!element)return false;const style=getComputedStyle(element),rect=element.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&rect.width>0&&rect.height>0},box=(name,element)=>{const rect=element.getBoundingClientRect();return{name,left:rect.left,top:rect.top,right:rect.right,bottom:rect.bottom,width:rect.width,height:rect.height}},elements=[['copy',node.querySelector('.recommendation-summary-copy')],['badge',node.querySelector('.recommendation-confidence,.seed-status-badge')],['action',node.querySelector('.recommendation-summary-action')],['arrow',node.querySelector(':scope > svg')]].filter(([,element])=>visible(element)).map(([name,element])=>box(name,element)),overlap=(a,b)=>Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1,pairs=[];for(let i=0;i<elements.length;i+=1)for(let j=i+1;j<elements.length;j+=1)if(overlap(elements[i],elements[j]))pairs.push(`${elements[i].name}/${elements[j].name}`);const card=node.closest('.collapsed-recommendation'),text=node.querySelector('.recommendation-summary-copy');return{elements,pairs,summaryOverflow:node.scrollWidth>node.clientWidth+1,cardOverflow:card.scrollWidth>card.clientWidth+1,textOverflow:text.scrollWidth>text.clientWidth+1}});
  assert.deepEqual(layout.pairs,[],`Planting Desk recommendation elements overlap at ${width}px: ${layout.pairs.join(', ')}`);assert.equal(layout.summaryOverflow,false,`Planting Desk recommendation summary overflows at ${width}px`);assert.equal(layout.cardOverflow,false,`Planting Desk recommendation card overflows at ${width}px`);assert.equal(layout.textOverflow,false,`Planting Desk recommendation text overflows at ${width}px`);
  await page.screenshot({path:`phase474-audit/journeys/planting-desk-iceberg-${width}.png`,fullPage:true});
 }
 await page.setViewportSize({width:390,height:900});record('Planting Desk Iceberg recommendation remains readable at 320, 375, 390, and 430px');
}
async function createSpace(page,{name,type,container=false,growBag=false,double=false}){
 await go(page,'garden');await page.getByRole('button',{name:'Add Growing Space'}).click();
 const dialog=page.locator('.detail-modal');await dialog.getByLabel('Garden space name').fill(name);await dialog.getByLabel('Growing area or container type').selectOption(type);
 if(container){assert.equal(await dialog.getByLabel('Container size').isVisible(),true);assert.equal(await dialog.getByLabel('Grow bag size').count(),0);await dialog.getByLabel('Container size').fill('5 gallon');await dialog.getByLabel('Material').fill('plastic');await dialog.getByLabel('Drainage holes').check()}
 if(growBag){assert.equal(await dialog.getByLabel('Grow bag size').isVisible(),true);assert.equal(await dialog.getByLabel('Container size').count(),0);await dialog.getByLabel('Grow bag size').fill('10 gallon');await dialog.getByLabel('Seed potatoes planted').fill('4');await dialog.getByLabel('Hilling stage').selectOption('First hill');await dialog.getByLabel('Last hilled date').fill(today)}
 const submit=dialog.getByRole('button',{name:'Add garden space'});if(double)await doubleActivate(submit);else await submit.click();
 await waitGarden(page,g=>g.spaces?.some(row=>row.name===name),`space ${name} did not save`);
 const data=await garden(page);assert.equal(data.spaces.filter(row=>row.name===name&&!row.deletedAt).length,1,`${name} duplicated`);record(`Create ${name}`);
 return data.spaces.find(row=>row.name===name&&!row.deletedAt);
}

const page=await context.newPage();
const pageErrors=[],failed=[];page.on('pageerror',error=>pageErrors.push(String(error?.stack||error)));page.on('response',response=>{if(response.status()>=400&&!/api\/seed-packets\/analyze/.test(response.url()))failed.push({status:response.status(),url:response.url()})});page.on('dialog',dialog=>dialog.accept());
await page.addInitScript(data=>{localStorage.clear();sessionStorage.clear();localStorage.setItem('runyan-garden-active-profile','archie');localStorage.setItem('brookes-garden-state-v2',JSON.stringify(data))},emptyGarden);
await context.route('**/api/health',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,version:'0.20.3',packetVisionConfigured:true})}));
await context.route('**/api/seed-packets/analyze',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code:'CERTIFICATION_FAILURE',message:'Certification analysis failure. Photos and draft remain saved.'})}));
try{
 const container=await createSpace(page,{name:'QA Container Planter',type:'container',container:true,double:true});
 assert.equal(container.type,'container');assert.equal(container.size,'5 gallon');assert.equal(container.drainageHoles,true);
 const bag=await createSpace(page,{name:'QA Potato Grow Bag',type:'potato-grow-bag',growBag:true});assert.equal(bag.type,'potato-grow-bag');assert.equal(bag.bagSize,'10 gallon');assert.equal(bag.size,'');
 await go(page,'garden');await page.getByRole('button',{name:/QA Container Planter/}).first().click();const spaceDialog=page.locator('.bed-detail-modal');await spaceDialog.getByLabel('Garden space name').fill('QA Container Renamed');await spaceDialog.getByRole('button',{name:/Save garden-space details/i}).click();await waitGarden(page,g=>g.spaces?.some(row=>row.id===container.id&&row.name==='QA Container Renamed'),'space rename did not persist');await page.reload({waitUntil:'networkidle'});assert.match(await page.locator('main').innerText(),/QA Container Renamed/);record('Rename and refresh Growing Space');
 await page.getByRole('button',{name:'Add plant'}).click();const plantDialog=page.locator('.detail-modal');await plantDialog.getByRole('button',{name:/Enter manually/i}).click();await plantDialog.getByLabel('Crop').fill('Tomato');await plantDialog.getByLabel('Planting or batch name').fill('QA Tomato Batch');await plantDialog.getByLabel('Growing Space').selectOption({label:'QA Container Renamed'});await doubleActivate(plantDialog.getByRole('button',{name:/Add QA Tomato Batch to QA Container Renamed/i}));await page.getByRole('button',{name:'Close planting confirmation'}).click();await waitGarden(page,g=>g.plants?.filter(row=>row.name==='QA Tomato Batch'&&!row.deletedAt).length===1,'plant did not save once');let data=await garden(page),plant=data.plants.find(row=>row.name==='QA Tomato Batch'&&!row.deletedAt);assert.equal(plant.spaceId,container.id);record('Create linked plant once after repeated activation');
 await go(page,'garden');await page.getByRole('button',{name:/QA Container Renamed/}).first().click();await page.getByRole('button',{name:/Plants \(1\)/}).click();await page.getByRole('button',{name:/QA Tomato Batch/}).click();const plantControl=page.locator('.plant-journey-modal');await plantControl.getByLabel('Planting or batch name').fill('QA Tomato Renamed');await plantControl.getByRole('button',{name:'Save plant changes'}).click();await waitGarden(page,g=>g.plants?.some(row=>row.id===plant.id&&row.name==='QA Tomato Renamed'),'plant edit did not persist');record('Edit linked plant');
 await go(page,'garden');await page.getByRole('button',{name:/QA Container Renamed/}).first().click();await page.locator('.bed-detail-modal').getByLabel('Garden space name').fill('QA Container Final');await page.locator('.bed-detail-modal').getByRole('button',{name:/Save garden-space details/i}).click();data=await garden(page);assert.equal(data.plants.find(row=>row.id===plant.id).spaceId,container.id);await page.reload({waitUntil:'networkidle'});data=await garden(page);assert.equal(data.plants.find(row=>row.id===plant.id).spaceId,container.id);record('Relationship survives space rename and refresh');
 await go(page,'chores');await page.getByRole('button',{name:'Add task'}).click();let form=page.locator('.manual-reminder-form');await form.getByLabel('Task name').fill('QA Fertilize Task');await form.getByLabel('Task type').selectOption('Fertilize');await form.getByLabel('Priority').selectOption('95');await form.getByLabel('Plant').selectOption({label:'QA Tomato Renamed'});await doubleActivate(form.getByRole('button',{name:'Add to Chore Board'}));await waitGarden(page,g=>g.reminders?.filter(row=>row.title==='QA Fertilize Task'&&!row.deletedAt).length===1,'manual task duplicated or missing');record('Create manual chore once after repeated activation');
 await go(page,'today');assert.match(await page.locator('main').innerText(),/QA Fertilize Task/);record('Manual chore appears on Today');
 await go(page,'chores');await page.getByRole('button',{name:/QA Fertilize Task/}).click();await page.getByRole('button',{name:'Edit task'}).click();form=page.locator('.manual-reminder-form');await form.getByLabel('Task name').fill('QA Fertilize Task Edited');await form.getByRole('button',{name:'Save task changes'}).click();await waitGarden(page,g=>g.reminders?.some(row=>row.title==='QA Fertilize Task Edited'&&!row.deletedAt),'manual task edit missing');record('Edit manual chore');
 await page.getByRole('button',{name:/QA Fertilize Task Edited/}).click();await page.getByRole('button',{name:'Fertilizing Complete'}).click();await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:/QA Fertilize Task Edited/}).click();assert.equal(await page.getByRole('button',{name:'Undo'}).isVisible(),true);await page.getByRole('button',{name:'Undo'}).click();await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:/QA Fertilize Task Edited/}).click();await page.getByRole('button',{name:'Delete task'}).click();await waitGarden(page,g=>g.reminders?.some(row=>row.title==='QA Fertilize Task Edited'&&row.deletedAt),'manual task delete missing');record('Complete, refresh, undo, and delete manual chore');
 await go(page,'seed-tools');const files=page.locator('input[type=file]');await files.nth(0).setInputFiles({name:'front.png',mimeType:'image/png',buffer:png});await files.nth(1).setInputFiles({name:'back.png',mimeType:'image/png',buffer:png});await page.locator('.packet-photo-panel.has-photo').nth(1).waitFor();await page.getByRole('button',{name:/Analyze packet/i}).click();await page.getByText(/Certification analysis failure/).waitFor();assert.equal(await page.locator('.packet-photo-panel.has-photo').count(),2);await page.getByLabel(/^Crop/).first().fill('Lettuce');await page.getByLabel(/^Variety/).first().fill('QA Iceberg A');await page.getByLabel(/^Brand/).first().fill('Burpee');const allPacketDetails=page.locator('details.packet-all-details');if(!(await allPacketDetails.getAttribute('open')))await allPacketDetails.locator(':scope > summary').click();await page.getByLabel(/^Seed count/).first().fill('100');await doubleActivate(page.getByRole('button',{name:'Save packet'}));await waitGarden(page,g=>g.seedPackets?.filter(row=>row.name==='Lettuce'&&!row.deletedAt).length===1,'packet duplicated or missing');data=await garden(page);let packet=data.seedPackets.find(row=>row.name==='Lettuce'&&!row.deletedAt);assert.ok(packet.frontPhoto&&packet.backPhoto);record('Packet failure fallback preserves photos and saves once');
 await page.getByRole('button',{name:'Edit'}).click();await page.getByLabel(/^Variety/).first().fill('QA Iceberg A Corrected');await page.getByRole('button',{name:'Save packet'}).click();await waitGarden(page,g=>g.seedPackets?.some(row=>row.variety==='QA Iceberg A Corrected'&&!row.deletedAt),'packet edit missing');await page.reload({waitUntil:'networkidle'});data=await garden(page);packet=data.seedPackets.find(row=>row.variety==='QA Iceberg A Corrected'&&!row.deletedAt);assert.ok(packet.frontPhoto&&packet.backPhoto);assert.equal(data.seedPackets.filter(row=>!row.deletedAt).length,1);record('Edit, reopen, and preserve packet photos');
 await verifyPlantingDeskReadability(page);
 await go(page,'admin-backup');const before=JSON.stringify(await garden(page));await page.getByRole('button',{name:/Run Safe Restore Rehearsal/i}).click();await page.getByText(/migration retry:/i).waitFor();assert.equal(JSON.stringify(await garden(page))===before||JSON.stringify(await garden(page)).includes('lastBackupAt'),true);record('Safe Restore Rehearsal leaves active records intact');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:/Export Garden Backup/i}).click();const download=await downloadPromise,path=await download.path();assert.ok(path);const backup=JSON.parse(await readFile(path,'utf8'));assert.ok(backup.checksum);assert.ok(backup.garden.spaces.some(row=>row.id===container.id));assert.ok(backup.garden.plants.some(row=>row.id===plant.id&&row.spaceId===container.id));assert.ok(backup.garden.seedPackets.some(row=>row.id===packet.id&&row.frontPhoto&&row.backPhoto));record('Export validated linked backup with photos');
 await go(page,'garden');await page.getByRole('button',{name:/QA Container Final/}).first().click();await page.getByRole('button',{name:/Plants \(1\)/}).click();await page.getByRole('button',{name:/QA Tomato Renamed/}).click();await page.getByRole('button',{name:'Remove from active records'}).click();await waitGarden(page,g=>g.plants?.some(row=>row.id===plant.id&&row.deletedAt),'plant soft delete missing');record('Confirmed plant removal soft-deletes record');
 await go(page,'seed-tools');await page.getByRole('button',{name:/Remove Lettuce packet/i}).click();await waitGarden(page,g=>g.seedPackets?.some(row=>row.id===packet.id&&row.deletedAt),'packet soft delete missing');record('Confirmed packet removal soft-deletes record');
 await go(page,'garden');const linkedButton=page.locator('.individual-bed-card').filter({hasText:'QA Container Final'}).getByRole('button',{name:/Remove|Plants linked/});assert.equal(await linkedButton.isDisabled(),false);await linkedButton.click();await waitGarden(page,g=>g.spaces?.some(row=>row.id===container.id&&row.deletedAt),'space soft delete missing');data=await garden(page);assert.ok(data.spaces.some(row=>row.id===bag.id&&!row.deletedAt));record('Confirmed empty-space removal preserves unrelated records');
 await page.screenshot({path:'phase474-audit/journeys/final-state-390.png',fullPage:true});
 assert.deepEqual(pageErrors,[],`Page errors: ${pageErrors.join('\n')}`);assert.deepEqual(failed,[],`Unexpected failed requests: ${JSON.stringify(failed)}`);
}catch(error){findings.push({severity:'P1',error:String(error?.stack||error)});record('Journey execution','fail',String(error?.message||error));try{await page.screenshot({path:'phase474-audit/journeys/FAILED.png',fullPage:true})}catch{}}
await writeFile('phase474-audit/journeys/results.json',JSON.stringify({steps,findings,pageErrors,failed},null,2));
await browser.close();
assert.equal(findings.length,0,findings.map(row=>row.error).join('\n'));
console.log(JSON.stringify({ok:true,steps:steps.length,pageErrors:pageErrors.length,failedRequests:failed.length},null,2));
