import assert from'node:assert/strict';
import{mkdir,writeFile}from'node:fs/promises';
import{chromium}from'playwright';

const base=(process.env.APP_URL||'http://127.0.0.1:4173').replace(/\/$/,'');
const garden={profile:{gardenerName:'Archie',activeProfileId:'archie',gardenName:'The Runyan Garden',location:'Green Bay, Wisconsin 54302',zone:'5b'},spaces:[{id:'print-space',name:'QA <North> & South Bed',type:'bed',size:'4 × 8 ft',hidden:false,deletedAt:null}],plants:[{id:'print-plant',name:'QA Tomato & Basil',variety:'Test <Variety>',spaceId:'print-space',archived:false,deletedAt:null}],shoppingItems:[],yearPlan:{crops:[]},seedPackets:[],reminders:[],taskHistory:[],activity:[],harvests:[],problems:[],succession:[],trays:[],growLights:[],hardeningPlans:[],hydroPods:[],greenhouseReadings:[],plantingDecisions:[],weatherRecommendationHistory:[],vacationPlans:[],calculatorResults:[],seedTransactions:[],seedUsage:[],environmentalRecords:[],environmentalCorrections:[],wateringEvents:[],soilCheckEvents:[],photos:[],attachments:[],qrLabels:[],offlineOperations:[]};
await mkdir('phase474-audit/pwa-print',{recursive:true});
const browser=await chromium.launch({headless:true}),results=[];
try{
 const manifestResponse=await fetch(`${base}/manifest.webmanifest`);assert.equal(manifestResponse.status,200);const manifest=await manifestResponse.json();assert.equal(manifest.start_url,'/');assert.equal(manifest.display,'standalone');assert.ok(manifest.icons?.length);for(const icon of manifest.icons){const response=await fetch(new URL(icon.src,`${base}/`).toString());assert.equal(response.status,200,`Manifest icon ${icon.src} failed`)}
 const swResponse=await fetch(`${base}/sw.js`);assert.equal(swResponse.status,200);const sw=await swResponse.text();assert.match(sw,/event\.request\.mode === 'navigate'/);assert.match(sw,/caches\.match\('\/'\)/);results.push({check:'manifest-icons-service-worker-assets',status:'pass'});
 for(const width of [390,1200]){
  const page=await browser.newPage({viewport:{width,height:width===390?900:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',error=>errors.push(String(error?.stack||error)));
  await page.addInitScript(data=>{localStorage.setItem('runyan-garden-active-profile','archie');localStorage.setItem('brookes-garden-state-v2',JSON.stringify(data))},garden);
  const direct=await page.goto(`${base}/?page=admin-about`,{waitUntil:'networkidle'});assert.equal(direct.status(),200);await page.getByText('About Garden Compass',{exact:false}).first().waitFor();await page.reload({waitUntil:'networkidle'});assert.match(await page.locator('main').innerText(),/About Garden Compass/i);assert.match(page.url(),/[?&]page=admin-about/);results.push({check:'direct-route-refresh',width,status:'pass'});
  await page.goto(`${base}/?page=printable-pack`,{waitUntil:'networkidle'});await page.evaluate(()=>{window.__phase474Print='';window.open=()=>({document:{write:value=>{window.__phase474Print+=String(value)},close:()=>{}},focus:()=>{}})});
  await page.getByLabel('Printable').selectOption('map');await page.getByLabel('Growing Spaces').selectOption('print-space');await page.getByRole('button',{name:'Print or Save as PDF'}).click();const html=await page.evaluate(()=>window.__phase474Print);assert.ok(html.length>500,'Printable HTML was blank');assert.match(html,/Growing Space Map/);assert.match(html,/QA &lt;North&gt; &amp; South Bed/);assert.match(html,/QA Tomato &amp; Basil/);assert.doesNotMatch(html,/bottom-nav|Tool Shed|Garden Center/);assert.match(html,/window\.print/);results.push({check:'nonblank-escaped-printable',width,status:'pass',bytes:html.length});
  await page.getByLabel('Printable').selectOption('labels');await page.getByRole('button',{name:'Open Plant Labels'}).click();await page.getByText('Plant Labels',{exact:true}).first().waitFor();assert.match(page.url(),/[?&]page=labels/);results.push({check:'plant-label-handoff',width,status:'pass'});
  const registration=await page.evaluate(async()=>{if(!('serviceWorker'in navigator))return{supported:false};await navigator.serviceWorker.ready.catch(()=>null);const row=await navigator.serviceWorker.getRegistration();return{supported:true,registered:Boolean(row),scope:row?.scope||''}});assert.equal(registration.supported,true);assert.equal(registration.registered,true);results.push({check:'service-worker-registration',width,status:'pass'});
  const obstruction=await page.evaluate(()=>{const nav=document.querySelector('.bottom-nav');const main=document.querySelector('main');if(!nav||!main)return null;const navBox=nav.getBoundingClientRect(),last=main.lastElementChild?.getBoundingClientRect();return{navTop:navBox.top,lastBottom:last?.bottom||0,scrollHeight:document.documentElement.scrollHeight,clientHeight:document.documentElement.clientHeight,paddingBottom:getComputedStyle(main).paddingBottom}});assert.ok(obstruction);assert.deepEqual(errors,[],`PWA/print page errors at ${width}px: ${errors.join('\n')}`);
  await page.screenshot({path:`phase474-audit/pwa-print/${width}-plant-labels.png`,fullPage:true});await page.close();
 }
 await writeFile('phase474-audit/pwa-print/results.json',JSON.stringify(results,null,2));console.log(JSON.stringify({ok:true,checks:results.length},null,2));
}finally{await browser.close()}
