import assert from'node:assert/strict';
import{chromium}from'playwright';

const base=(process.env.APP_URL||'https://brookes-garden-compass.onrender.com').replace(/\/$/,'');
const expectedBuild='phase-4-7-8-urgent-only-home';
const attempts=Number(process.env.VERIFY_ATTEMPTS||80),delay=Number(process.env.VERIFY_DELAY_MS||15000);
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const fetchText=async url=>{const response=await fetch(url,{cache:'no-store',headers:{'cache-control':'no-cache'}});assert.equal(response.status,200,`${url} returned ${response.status}`);return response.text()};
const currentGreenBaySeason=()=>{const month=Number(new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',month:'numeric'}).format(new Date()));if(month>=3&&month<=5)return'spring';if(month>=6&&month<=8)return'summer';if(month>=9&&month<=11)return'fall';return'winter'};
let result=null,lastError=null;
for(let attempt=1;attempt<=attempts;attempt+=1){
 let browser;
 try{
  const healthResponse=await fetch(`${base}/api/health`,{headers:{accept:'application/json','cache-control':'no-cache'},cache:'no-store'});
  assert.equal(healthResponse.status,200,`Health endpoint returned ${healthResponse.status}`);
  const health=await healthResponse.json();
  assert.equal(health.ok,true);
  const html=await fetchText(`${base}/?phase478=${Date.now()}`);
  const scriptPaths=[...html.matchAll(/<script[^>]+src="([^"]+\.js)"/g)].map(match=>match[1]);
  const stylePaths=[...html.matchAll(/<link[^>]+href="([^"]+\.css)"/g)].map(match=>match[1]);
  assert.ok(scriptPaths.length,'Live JavaScript asset was not found.');
  assert.ok(stylePaths.length,'Live CSS asset was not found.');
  const js=(await Promise.all(scriptPaths.map(path=>fetchText(new URL(path,`${base}/`).toString())))).join('\n');
  const css=(await Promise.all(stylePaths.map(path=>fetchText(new URL(path,`${base}/`).toString())))).join('\n');
  assert.match(js,new RegExp(expectedBuild));
  assert.match(js,/Urgent Garden Alerts/);
  assert.match(js,/Nothing urgent right now/);
  assert.match(js,/watering-can-icon/);
  assert.match(js,/America\/Chicago/);
  assert.match(js,/CALCULATORS & UTILITIES/);
  assert.match(js,/WEATHER & TIMING/);
  assert.match(js,/RECORDS & EXTRAS/);
  assert.match(css,/garden-header-summer\.webp\?v=0477/);
  assert.match(css,/aspect-ratio:2\/1/);
  assert.match(css,/background-size:contain/);
  assert.match(css,/urgent-alert-overlay/);
  assert.match(css,/z-index:5000/);
  assert.match(css,/100dvh/);
  assert.match(css,/compact-secondary-header/);
  assert.match(css,/tool-shed-directory-card/);
  assert.match(css,/garden-center-tile/);
  const liveSeason=currentGreenBaySeason(),seasonalAsset=`/images/garden-headers/garden-header-${liveSeason}.webp?v=0477`;
  const assetResponse=await fetch(`${base}${seasonalAsset}`,{cache:'no-store'});
  assert.equal(assetResponse.status,200,`${seasonalAsset} returned ${assetResponse.status}`);
  assert.match(assetResponse.headers.get('content-type')||'',/image\/webp/);
  assert.ok((await assetResponse.arrayBuffer()).byteLength>10000,`${seasonalAsset} is unexpectedly small`);

  browser=await chromium.launch({headless:true});
  const widths=[320,375,390,430];
  for(const width of widths){
   const context=await browser.newContext({serviceWorkers:'block',viewport:{width,height:900},deviceScaleFactor:1});
   const page=await context.newPage();
   await page.addInitScript(()=>localStorage.setItem('runyan-garden-active-profile','archie'));
   const goto=async route=>{const response=await page.goto(`${base}/?page=${route}&phase478=${width}-${Date.now()}`,{waitUntil:'domcontentloaded',timeout:60000});assert.equal(response?.status(),200);await page.locator('main').waitFor()};
   await goto('today');
   const hero=page.locator('.compact-home-hero'),todayCard=page.locator('.what-matters-today'),title=page.locator('.compact-hero-title');
   await hero.waitFor();await todayCard.waitFor();
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true,`${width}px has horizontal overflow`);
   const heroBox=await hero.boundingBox(),cardBox=await todayCard.boundingBox(),titleBox=await title.boundingBox();
   assert.ok(Math.abs(heroBox.width/heroBox.height-2)<.04,`${width}px seasonal header ratio was ${heroBox.width/heroBox.height}`);
   assert.ok(cardBox.y<heroBox.y+heroBox.height,`${width}px Today card does not overlap the seasonal header`);
   const heroStyle=await hero.evaluate(element=>({backgroundImage:getComputedStyle(element).backgroundImage,backgroundSize:getComputedStyle(element).backgroundSize,borderRadius:getComputedStyle(element).borderRadius,afterDisplay:getComputedStyle(element,'::after').display}));
   assert.ok(heroStyle.backgroundImage.includes(`garden-header-${liveSeason}.webp`),`Expected ${liveSeason} header, received ${heroStyle.backgroundImage}`);
   assert.equal(heroStyle.backgroundSize,'contain');
   assert.notEqual(heroStyle.borderRadius,'0px');
   assert.equal(heroStyle.afterDisplay,'none');
   assert.ok(titleBox.width<=1&&titleBox.height<=1,'A duplicate live title panel is visible over the approved artwork');
   assert.equal(await page.locator('.watering-can-icon').count(),1,'Watering can trigger is missing or duplicated');
   assert.equal(await page.getByText('GARDEN STATUS',{exact:true}).count(),0,'The removed Garden Status dashboard returned');
   assert.equal(await page.locator('.today-quick-links').count(),0,'Removed Today shortcut boxes returned');
   const trigger=page.getByRole('button',{name:/Urgent garden alerts/i});
   await trigger.click();
   const dialog=page.getByRole('dialog',{name:'Urgent Garden Alerts',exact:true});
   await dialog.waitFor();
   assert.equal(await page.locator('.urgent-alert-overlay').evaluate(element=>element.parentElement===document.body),true,'Urgent alert overlay is not attached to document.body');
   const dialogBox=await dialog.boundingBox();
   assert.ok(dialogBox.x>=0&&dialogBox.x+dialogBox.width<=width+1,`${width}px alert dialog exceeds viewport`);
   const dialogStyle=await dialog.evaluate(element=>({position:getComputedStyle(element).position,z:Number(getComputedStyle(element).zIndex),overflowY:getComputedStyle(element).overflowY}));
   const nav=page.locator('.bottom-nav');
   if(await nav.count())assert.ok(dialogStyle.z>(await nav.evaluate(element=>Number(getComputedStyle(element).zIndex)||0)),'Urgent alert dialog is behind bottom navigation');
   assert.equal(dialogStyle.overflowY,'auto');
   assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden');
   await page.keyboard.press('Escape');
   await dialog.waitFor({state:'hidden'});
   assert.equal(await page.evaluate(()=>document.body.style.overflow),'');
   assert.equal(await trigger.evaluate(element=>document.activeElement===element),true,'Focus did not return to watering can');
   await context.close();
  }
  await browser.close();browser=null;
  result={ok:true,base,attempt,health,expectedBuild,liveSeason,seasonalAsset,widths,gardenCenterDestinations:5,toolShedDestinations:11};
  break;
 }catch(error){
  if(browser)await browser.close().catch(()=>{});
  lastError=error;
  console.error(`[Phase 4.7.8 live check ${attempt}/${attempts}] ${error.message}`);
  if(attempt<attempts)await sleep(delay);
 }
}
assert.ok(result,`Live Phase 4.7.8 verification failed after ${attempts} attempts: ${lastError?.stack||lastError}`);
console.log(JSON.stringify(result,null,2));
