import assert from'node:assert/strict';

const base=(process.env.GARDEN_URL||'https://brookes-garden-compass.onrender.com').replace(/\/$/,'');
const noStore={cache:'no-store',headers:{'cache-control':'no-cache','pragma':'no-cache'}};
const get=async path=>{const separator=path.includes('?')?'&':'?';const response=await fetch(`${base}${path}${separator}verify=${Date.now()}`,noStore);assert.equal(response.ok,true,`${path} returned ${response.status}`);return response};
const health=await(await get('/api/health')).json();
assert.equal(health.version,'0.21.1');
assert.equal(health.buildId,'phase-4-8-3c-checklist-layout-hotfix');
assert.equal(health.phase,'4.8.3c');
const html=await(await get('/')).text();
assert.match(html,/id=["']root["']/);
const assetMatch=html.match(/<script[^>]+src=["']([^"']+\.js)["']/);
assert.ok(assetMatch,'Production JavaScript asset was not found in the app shell.');
const bundle=await(await get(assetMatch[1])).text();
assert.match(bundle,/phase-4-8-3c-checklist-layout-hotfix/);
assert.match(bundle,/Fixed the first-time setup checklist layout on mobile\./);
const sw=await(await get('/sw.js')).text();
assert.match(sw,/brookes-garden-v0483c-checklist-layout-hotfix-20260723/);
const cssMatches=[...html.matchAll(/<link[^>]+href=["']([^"']+\.css)["']/g)];
assert.ok(cssMatches.length,'Production CSS asset was not found in the app shell.');
const css=(await Promise.all(cssMatches.map(async match=>await(await get(match[1])).text()))).join('\n');
assert.match(css,/\.garden-setup-steps li\{display:block;width:100%;min-width:0;padding:0;border-top:0\}/);
assert.match(css,/grid-template-columns:28px minmax\(0,1fr\) 18px/);
const station=await(await get('/api/weather/current')).json();
assert.equal('apiKey'in station,false);assert.equal('PWS_API_KEY'in station,false);
console.log(JSON.stringify({ok:true,base,health,cache:'brookes-garden-v0483c-checklist-layout-hotfix-20260723',layoutCss:true},null,2));