import React,{useRef,useState}from'react';
import{Bell,ChevronRight,CircleHelp,DatabaseBackup,Download,Info,LifeBuoy,MapPin,Sprout,Upload,Users}from'lucide-react';
import{SecondaryHero}from'./SecondaryUI.jsx';
import{APP_VERSION,BUILD_ID,UPDATED_AT,WHATS_NEW}from'./version.js';
import{DEFAULT_PROFILES,ProfileAvatar,ProfileSwitcher}from'./RunyanProfiles.jsx';
import{exportGardenBackup}from'./syncModel.js';

const ACTIVE_PROFILE_KEY='runyan-garden-active-profile',GARDEN_KEY='brookes-garden-state-v2';
export const QUICK_HELP=[
 ['Where do I find things?','Today shows immediate weather and work. Garden shows active plants and Growing Spaces. Center contains care, planting, shopping, seeds, indoor growing, records, and next-season planning. Tool Shed contains optional calculators, measurements, printables, and Plant Labels. More contains focused settings, data, support, and app information.'],
 ['Plant Labels','Create bed signs, plant tags, and custom QR labels while preserving the exact saved garden-record destinations.'],
 ['Spacing Calculator','Estimate how many plants fit in a Growing Space. Exact packet spacing is used when recorded; otherwise the result identifies general crop guidance.'],
 ['Soil & Container Calculator','Estimate cubic feet, gallons, and common bag quantities for pots, planters, raised beds, grow bags, and custom dimensions.'],
 ['Frost & Planting Dates','Check indoor-starting, transplant, direct-sow, and fall-planting dates using the saved Green Bay frost timing.'],
 ['Seed Quantity Calculator','Estimate how many seeds to start from a final plant target, germination rate, survival rate, and desired extras. It never reduces Seed Inventory.'],
 ['Garden Measurements','Use common garden conversions for inches, feet, bed area, soil volume, gallons, containers, and row length.'],
 ['Printable Garden Pack','Create garden notes, Growing Space maps, seed-starting logs, harvest logs, watering sheets, seasonal plans, and shopping checklists. Labels continue through Plant Labels.'],
 ['What is in More?','More contains focused Garden Profile, location and frost dates, notification settings, backup and restore, Quick Help, What’s New, support, and About screens.'],
 ['How does Planting Desk work?','Grow Now is the first and default view. It checks exact owned packets and suitable owned seeds first, then may show honest Seeds Needed options. Today and This Week show scheduled planting work. Plan Ahead shows future windows and purchase needs.'],
 ['How does Smart Watering work?','It considers crop, lifecycle stage, Growing Space, recent rain, heat, and saved soil or watering observations. Check the soil before recording watering.'],
 ['What is Plant Journey?','Plant Journey is the history and current status for one planting or batch, including packet, variety, stage, estimates, milestones, notes, photos, watering, harvests, and problems.']
];

const screenInfo={
 profile:{icon:Users,eyebrow:'GARDEN PROFILE',title:'Garden Profile',description:'Garden identity, household gardeners, and the active gardener on this device.'},
 location:{icon:MapPin,eyebrow:'GARDEN PROFILE',title:'Location and Frost Dates',description:'The saved Green Bay location used for planting and weather guidance.'},
 notifications:{icon:Bell,eyebrow:'PREFERENCES',title:'Notification Settings',description:'Browser permission and the garden alerts this device should surface.'},
 backup:{icon:DatabaseBackup,eyebrow:'DATA',title:'Backup and Restore',description:'Create a recovery copy or restore saved garden records.'},
 help:{icon:CircleHelp,eyebrow:'HELP AND ABOUT',title:'Quick Help',description:'Plain-language guidance for navigation, tools, recommendations, and garden records.'},
 whatsnew:{icon:Sprout,eyebrow:'HELP AND ABOUT',title:'What’s New',description:'Meaningful user-facing changes in the current release.'},
 support:{icon:LifeBuoy,eyebrow:'HELP AND ABOUT',title:'Help and Support',description:'Prepare an email with the app version and the information needed to investigate a problem.'},
 about:{icon:Info,eyebrow:'HELP AND ABOUT',title:'About',description:'Version, build, storage, and app identity.'}
};

function ProfileScreen({garden,onUpdateProfile}){const activeId=localStorage.getItem(ACTIVE_PROFILE_KEY)||garden.profile?.activeProfileId||'brooke',active=DEFAULT_PROFILES.find(profile=>profile.id===activeId)||DEFAULT_PROFILES[0],[name,setName]=useState(garden.profile?.gardenName||'The Runyan Garden');const switchProfile=id=>{const selected=DEFAULT_PROFILES.find(profile=>profile.id===id)||DEFAULT_PROFILES[0];localStorage.setItem(ACTIVE_PROFILE_KEY,selected.id);onUpdateProfile({gardenerName:selected.name,activeProfileId:selected.id})};return <><section className="admin-focus-card"><span className="section-kicker">HOUSEHOLD GARDENERS</span><div className="profile-switch-grid director-display">{DEFAULT_PROFILES.map(profile=><div key={profile.id}><ProfileAvatar profile={profile} small/><span><strong>{profile.name}</strong><small>{profile.role}</small></span></div>)}</div></section><section className="admin-focus-card"><label>Garden name<input value={name} onChange={event=>setName(event.target.value)}/></label><button className="primary-button" onClick={()=>onUpdateProfile({gardenName:name.trim()||'The Runyan Garden'})}>Save garden name</button></section><section className="admin-focus-card"><span className="section-kicker">ACTIVE GARDENER</span><p>Currently gardening as <strong>{active.name}</strong> on this device.</p><ProfileSwitcher profiles={DEFAULT_PROFILES} activeId={active.id} onSwitch={switchProfile}/></section></>}
function LocationScreen({garden,onUpdateProfile}){const profile=garden.profile||{},[draft,setDraft]=useState({location:profile.location||'Green Bay, Wisconsin',zip:profile.zip||'54302',zone:profile.zone||'5b',lastFrost:profile.lastFrost||'May 15',firstFrost:profile.firstFrost||'October 10'});return <><section className="admin-focus-card location-summary"><MapPin/><span><strong>{draft.location.replace(/\s+54302$/,'')} {draft.zip}</strong><small>USDA Zone {draft.zone}</small><p>Weather and planting guidance use this saved location and working frost dates.</p></span></section><form className="admin-focus-card admin-form" onSubmit={event=>{event.preventDefault();onUpdateProfile(draft)}}><label>Saved city<input value={draft.location} onChange={event=>setDraft({...draft,location:event.target.value})}/></label><div className="admin-two-fields"><label>ZIP code<input inputMode="numeric" value={draft.zip} onChange={event=>setDraft({...draft,zip:event.target.value})}/></label><label>USDA zone<input value={draft.zone} onChange={event=>setDraft({...draft,zone:event.target.value})}/></label></div><div className="admin-two-fields"><label>Working last frost<input value={draft.lastFrost} onChange={event=>setDraft({...draft,lastFrost:event.target.value})}/></label><label>Working first frost<input value={draft.firstFrost} onChange={event=>setDraft({...draft,firstFrost:event.target.value})}/></label></div><button className="primary-button">Save location settings</button></form></>}
function NotificationScreen({garden,onUpdateProfile}){const prefs=garden.profile?.notifications||{},[permission,setPermission]=useState(()=>typeof Notification==='undefined'?'unsupported':Notification.permission),[draft,setDraft]=useState({weather:prefs.weather!==false,tasks:prefs.tasks!==false,shopping:prefs.shopping!==false});const request=async()=>{if(typeof Notification==='undefined')return setPermission('unsupported');setPermission(await Notification.requestPermission())};return <><section className="admin-focus-card notification-permission"><Bell/><span><strong>{permission==='granted'?'Browser notifications allowed':permission==='denied'?'Browser notifications blocked':permission==='unsupported'?'Browser notifications unavailable':'Browser permission not requested'}</strong><small>In-app alerts and counts remain available regardless of browser permission.</small></span>{permission!=='granted'&&permission!=='unsupported'&&<button onClick={request}>Request permission</button>}</section><section className="admin-focus-card preference-toggle-list"><label><span><strong>Weather alerts</strong><small>Storm, heat, frost, and rain changes that affect garden work</small></span><input type="checkbox" checked={draft.weather} onChange={event=>setDraft({...draft,weather:event.target.checked})}/></label><label><span><strong>Task alerts</strong><small>Overdue and due-today Chore Board work</small></span><input type="checkbox" checked={draft.tasks} onChange={event=>setDraft({...draft,tasks:event.target.checked})}/></label><label><span><strong>Shopping reminders</strong><small>Items needed before a planting window</small></span><input type="checkbox" checked={draft.shopping} onChange={event=>setDraft({...draft,shopping:event.target.checked})}/></label><button className="primary-button" onClick={()=>onUpdateProfile({notifications:draft})}>Save notification preferences</button></section></>}
function BackupScreen({garden,onUpdateProfile}){const[fileMessage,setFileMessage]=useState(''),inputRef=useRef(null),last=garden.profile?.lastBackupAt||'';const backup=()=>{exportGardenBackup(garden);const at=new Date().toISOString();onUpdateProfile({lastBackupAt:at});setFileMessage('Backup download created.')};const restore=async file=>{if(!file)return;try{const payload=JSON.parse(await file.text()),restored=payload.garden||payload;if(!restored||!Array.isArray(restored.plants)||!Array.isArray(restored.spaces))throw new Error('This file does not contain a valid Runyan Garden backup.');if(!window.confirm(`Restore ${restored.plants.length} plant record${restored.plants.length===1?'':'s'} and ${restored.spaces.length} Growing Space${restored.spaces.length===1?'':'s'}? Current records on this device will be replaced.`))return;localStorage.setItem(GARDEN_KEY,JSON.stringify(restored));setFileMessage('Backup restored. Reloading…');window.setTimeout(()=>window.location.reload(),500)}catch(error){setFileMessage(error?.message||'That backup could not be restored.')}};return <><section className="admin-focus-card backup-status"><DatabaseBackup/><span><strong>{last?'Last backup created':'No backup date recorded'}</strong><small>{last?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(last)):'Create a recovery copy before major garden changes.'}</small></span></section><section className="admin-focus-card backup-actions"><button className="primary-button" onClick={backup}><Download/>Create Backup</button><button onClick={()=>inputRef.current?.click()}><Upload/>Restore Backup</button><input ref={inputRef} className="visually-hidden-input" type="file" accept="application/json,.json" onChange={event=>restore(event.target.files?.[0])}/><p><strong>Restore replaces records on this device.</strong> Review the confirmation count before continuing.</p>{fileMessage&&<small role="status">{fileMessage}</small>}</section></>}
function HelpScreen(){return <div className="focused-help-list">{QUICK_HELP.map(([title,text])=><details key={title}><summary><strong>{title}</strong><ChevronRight/></summary><p>{text}</p></details>)}</div>}
function WhatsNewScreen(){return <section className="admin-focus-card whats-new-focused"><span className="section-kicker">WHAT’S NEW IN {APP_VERSION}</span>{WHATS_NEW.map(item=><div key={item}><Sprout/><span>{item}</span></div>)}</section>}
function SupportScreen(){const body=`Runyan Garden support request%0A%0AApp version: ${encodeURIComponent(APP_VERSION)}%0ABuild: ${encodeURIComponent(BUILD_ID)}%0A%0APlease describe what happened and attach screenshots.`;return <section className="admin-focus-card support-card"><LifeBuoy/><h2>Include the screen and what happened</h2><p>Attach screenshots when possible and describe what you expected, what happened, and the last action you took.</p><a className="primary-button" href={`mailto:?subject=Runyan%20Garden%20Support&body=${body}`}>Open support email</a></section>}
function AboutScreen(){return <section className="admin-focus-card about-card"><Sprout/><h2>The Runyan Garden</h2><p>A mobile garden workspace for Archie and Brooke in Green Bay, Wisconsin.</p><dl><div><dt>Version</dt><dd>{APP_VERSION}</dd></div><div><dt>Build</dt><dd>{BUILD_ID}</dd></div><div><dt>Updated</dt><dd>{UPDATED_AT}</dd></div><div><dt>Storage</dt><dd>On this device</dd></div></dl></section>}

export default function AdminScreen({mode='profile',garden,navigate,onUpdateProfile}){const info=screenInfo[mode]||screenInfo.profile,Icon=info.icon;return <main className="screen secondary-screen admin-screen"><SecondaryHero icon={Icon} eyebrow={info.eyebrow} title={info.title} description={info.description} onBack={()=>navigate('more')} backLabel="Back to More" className="admin-hero"/><section className="screen-pad secondary-screen-content admin-screen-content">{mode==='profile'&&<ProfileScreen garden={garden} onUpdateProfile={onUpdateProfile}/>} {mode==='location'&&<LocationScreen garden={garden} onUpdateProfile={onUpdateProfile}/>} {mode==='notifications'&&<NotificationScreen garden={garden} onUpdateProfile={onUpdateProfile}/>} {mode==='backup'&&<BackupScreen garden={garden} onUpdateProfile={onUpdateProfile}/>} {mode==='help'&&<HelpScreen/>} {mode==='whatsnew'&&<WhatsNewScreen/>} {mode==='support'&&<SupportScreen/>} {mode==='about'&&<AboutScreen/>}</section></main>}
