import React, { useEffect, useMemo, useState } from 'react';
import { BottomNav, DetailModal, MenuDrawer, PlantScreen } from './screens.jsx';
import { GardenWorkspace, TodayWorkspace } from './WorkspaceScreens.jsx';
import PlannerScreen from './PlannerScreen.jsx';
import GardenControls from './GardenControls.jsx';
import IndoorCenter from './IndoorCenter.jsx';
import SettingsCenter from './SettingsCenter.jsx';
import { getCropRecommendations, newId, starterGarden } from './data.js';
import { gardenWeatherAlert, useGreenBayWeather } from './weather.js';
import { buildYearRoundTasks, getSeasonMode, migrateGarden } from './yearRoundEngine.js';
import { buildTimeline, createSuccession, nextStage, normalizePlanning } from './planning.js';

const GARDEN_KEY='brookes-garden-state-v2', PAGE_KEY='brookes-garden-page-v2', DAILY_KEY='brookes-garden-daily-v4';
const safeLoad=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}};
const dayKey=()=>{const n=new Date();return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`;};
const plusDays=(days)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);};
const normalizeIndoor=(garden)=>({...garden,trays:garden.trays||[],growLights:garden.growLights||[],hardeningPlans:garden.hardeningPlans||[],hydroPods:garden.hydroPods||[],greenhouseReadings:garden.greenhouseReadings||[]});

export default function App(){
 const [page,setPage]=useState(()=>localStorage.getItem(PAGE_KEY)||'today');
 const [garden,setGarden]=useState(()=>normalizeIndoor(normalizePlanning(migrateGarden(safeLoad(GARDEN_KEY,starterGarden),starterGarden))));
 const [daily,setDaily]=useState(()=>{const s=safeLoad(DAILY_KEY,{date:dayKey(),done:[],snoozed:{}});return s.date===dayKey()?{...s,snoozed:s.snoozed||{}}:{date:dayKey(),done:[],snoozed:{}};});
 const [filter,setFilter]=useState('all'),[drawerOpen,setDrawerOpen]=useState(false),[noticeOpen,setNoticeOpen]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState('');
 const weatherState=useGreenBayWeather();
 useEffect(()=>localStorage.setItem(PAGE_KEY,page),[page]);useEffect(()=>localStorage.setItem(GARDEN_KEY,JSON.stringify(garden)),[garden]);useEffect(()=>localStorage.setItem(DAILY_KEY,JSON.stringify(daily)),[daily]);
 const showToast=(m)=>{setToast(m);clearTimeout(window.__gardenToast);window.__gardenToast=setTimeout(()=>setToast(''),2600);};
 const navigate=(next)=>{setPage(next);setDrawerOpen(false);setNoticeOpen(false);scrollTo({top:0,behavior:'smooth'});};
 const activityEntry=(entry)=>({id:newId('activity'),at:new Date().toISOString(),...entry});
 const addActivity=(entry)=>setGarden(c=>({...c,activity:[activityEntry(entry),...(c.activity||[])].slice(0,200)}));
 const markDaily=(id)=>setDaily(c=>({...c,done:Array.from(new Set([...(c.done||[]),id]))}));
 const snoozeTask=(id,days=1)=>{setDaily(c=>({...c,snoozed:{...(c.snoozed||{}),[id]:plusDays(days)}}));setNoticeOpen(false);showToast(days===1?'Moved to tomorrow.':`Snoozed for ${days} days.`);};

 const addPlant=(plant)=>{const p={id:newId('plant'),name:plant.name.trim(),variety:plant.variety?.trim()||'',cropId:plant.cropId||'',spaceId:plant.spaceId,stage:plant.stage||'Growing',plantedAt:plant.plantedAt||dayKey(),batchName:plant.batchName||'Batch 1',quantity:Number(plant.quantity)||1,successionEnabled:Boolean(plant.successionEnabled),successionDays:Number(plant.successionDays)||14,lastWatered:null,lastSoilCheck:null,lastFertilized:null,moisture:'unknown',notes:'',archived:false};setGarden(c=>({...c,profile:{...c.profile,setupComplete:true},plants:[...c.plants,p],succession:p.successionEnabled?[...(c.succession||[]),createSuccession(p,p.successionDays,p.quantity)]:c.succession||[],activity:[activityEntry({type:'planted',title:`Added ${p.name}`,detail:`${p.batchName} is now tracked.`,plantId:p.id}),...(c.activity||[])].slice(0,200)}));showToast(`${p.name} is now in the garden.`);};
 const addSpace=(space)=>{const s={id:newId('space'),name:space.name.trim(),type:space.type||'bed',capacity:Number(space.capacity)||12,hidden:false};setGarden(c=>({...c,spaces:[...c.spaces,s],activity:[activityEntry({type:'space',title:`Added ${s.name}`,detail:'New growing space created.'}),...(c.activity||[])].slice(0,200)}));showToast(`${s.name} was added.`);};
 const manageSpace=(action,id)=>{const s=garden.spaces.find(x=>x.id===id);if(!s)return;const count=garden.plants.filter(p=>p.spaceId===id&&!p.archived).length;if(action==='remove'){if(count){showToast(`Move or archive the ${count} tracked plant${count===1?'':'s'} first.`);return;}if(!confirm(`Remove ${s.name}?`))return;setGarden(c=>({...c,spaces:c.spaces.filter(x=>x.id!==id)}));showToast(`${s.name} removed.`);return;}if(action==='hide'||action==='show'){const hidden=action==='hide';setGarden(c=>({...c,spaces:c.spaces.map(x=>x.id===id?{...x,hidden}:x)}));showToast(hidden?`${s.name} hidden for now.`:`${s.name} restored.`);return;}setGarden(c=>{const visible=c.spaces.filter(x=>!x.hidden),hidden=c.spaces.filter(x=>x.hidden),i=visible.findIndex(x=>x.id===id),t=action==='up'?i-1:i+1;if(i<0||t<0||t>=visible.length)return c;[visible[i],visible[t]]=[visible[t],visible[i]];return{...c,spaces:[...visible,...hidden]};});};
 const updateProfile=(profile)=>{setGarden(c=>({...c,profile:{...c.profile,...profile}}));showToast('Garden settings saved.');};
 const recordSoilCheck=(id,moisture)=>{const p=garden.plants.find(x=>x.id===id),now=new Date().toISOString();setGarden(c=>({...c,plants:c.plants.map(x=>x.id===id?{...x,moisture,lastSoilCheck:now}:x),activity:[activityEntry({type:'soil',title:`Checked ${p?.name||'plant'} soil`,detail:`Soil felt ${moisture}.`,plantId:id}),...(c.activity||[])].slice(0,200)}));if(moisture!=='dry')markDaily(`soil-${id}`);};
 const recordWatered=(id)=>{const p=garden.plants.find(x=>x.id===id),now=new Date().toISOString();setGarden(c=>({...c,plants:c.plants.map(x=>x.id===id?{...x,moisture:'damp',lastSoilCheck:now,lastWatered:now}:x),activity:[activityEntry({type:'watered',title:`Watered ${p?.name||'plant'}`,detail:'Watering recorded.',plantId:id}),...(c.activity||[])].slice(0,200)}));markDaily(`soil-${id}`);showToast('Watering recorded.');};
 const logGreenhouseCheck=({temperature,humidity,note})=>{const r={id:newId('reading'),at:new Date().toISOString(),temperature:Number(temperature)||null,humidity:Number(humidity)||null,note:note||''};setGarden(c=>({...c,greenhouseReadings:[r,...(c.greenhouseReadings||[])].slice(0,100),activity:[activityEntry({type:'greenhouse',title:'Greenhouse check',detail:[temperature?`${temperature}°F`:'',humidity?`${humidity}% humidity`:'',note].filter(Boolean).join(' • ')||'Conditions checked.'}),...(c.activity||[])].slice(0,200)}));markDaily('greenhouse-check');showToast('Greenhouse conditions saved.');};
 const addSeed=(seed)=>{const s={id:newId('seed'),cropId:seed.cropId,name:seed.name,variety:seed.variety?.trim()||'',packetYear:Number(seed.packetYear)||new Date().getFullYear(),quantity:Number(seed.quantity)||0,addedAt:new Date().toISOString()};setGarden(c=>({...c,seeds:[...(c.seeds||[]),s]}));showToast(`${s.name} added to the seed box.`);};
 const updatePlantStage=(id)=>{const p=garden.plants.find(x=>x.id===id);if(!p)return;const stage=nextStage(p.stage);setGarden(c=>({...c,plants:c.plants.map(x=>x.id===id?{...x,stage,stageUpdatedAt:new Date().toISOString()}:x)}));showToast(`${p.name} is now ${stage}.`);};
 const savePlant=(id,draft)=>{const old=garden.plants.find(x=>x.id===id);setGarden(c=>({...c,plants:c.plants.map(x=>x.id===id?{...x,...draft,quantity:Number(draft.quantity)||1,stageUpdatedAt:x.stage!==draft.stage?new Date().toISOString():x.stageUpdatedAt}:x),activity:[activityEntry({type:'plant',title:`Updated ${draft.name}`,detail:`Stage: ${draft.stage} • ${c.spaces.find(s=>s.id===draft.spaceId)?.name||'Unassigned'}`,plantId:id}),...(c.activity||[])].slice(0,200)}));showToast(`${old?.name||'Plant'} updated.`);};
 const archivePlant=(id)=>{const p=garden.plants.find(x=>x.id===id);if(!p)return;setGarden(c=>({...c,plants:c.plants.map(x=>x.id===id?{...x,archived:true,stage:x.stage==='Failed'?'Failed':'Finished',archivedAt:new Date().toISOString()}:x)}));setModal(null);showToast(`${p.name} archived.`);};
 const deletePlant=(id)=>{const p=garden.plants.find(x=>x.id===id);if(!p||!confirm(`Delete ${p.name}?`))return;setGarden(c=>({...c,plants:c.plants.filter(x=>x.id!==id),succession:(c.succession||[]).filter(x=>x.plantId!==id)}));setModal(null);showToast(`${p.name} deleted.`);};
 const saveHarvest=(id,data)=>{const p=garden.plants.find(x=>x.id===id);if(!p)return;const h={id:newId('harvest'),plantId:id,name:p.name,amount:Number(data.amount)||0,unit:data.unit,quality:data.quality,note:data.note,growAgain:data.growAgain,at:new Date().toISOString()};setGarden(c=>({...c,harvests:[h,...(c.harvests||[])],plants:c.plants.map(x=>x.id===id?{...x,stage:'Producing',lastHarvested:h.at,growAgain:data.growAgain}:x),activity:[activityEntry({type:'harvest',title:`Harvested ${p.name}`,detail:`${h.amount} ${h.unit} • ${h.quality}`,plantId:id}),...(c.activity||[])].slice(0,200)}));showToast(`${p.name} harvest saved.`);};
 const saveProblem=(id,data)=>{const p=garden.plants.find(x=>x.id===id),problem={id:newId('problem'),plantId:id,type:data.type,severity:data.severity,note:data.note,status:'open',at:new Date().toISOString()};setGarden(c=>({...c,problems:[problem,...(c.problems||[])],activity:[activityEntry({type:'problem',title:`${data.type}: ${p?.name||'Plant'}`,detail:`${data.severity} • ${data.note}`,plantId:id}),...(c.activity||[])].slice(0,200)}));showToast('Problem record saved.');};
 const recordHarvest=(id)=>setModal({type:'managePlant',plant:garden.plants.find(x=>x.id===id),view:'harvest'});
 const scheduleSuccession=(id,completed=false)=>{const p=garden.plants.find(x=>x.id===id);if(!p)return;const next=createSuccession(p,p.successionDays||14,p.quantity||6);setGarden(c=>({...c,succession:[...(c.succession||[]).map(x=>completed&&x.plantId===id&&x.status!=='done'?{...x,status:'done'}:x),next]}));showToast(`Next ${p.name} batch scheduled.`);};
 const completePlanItem=(item)=>{if(item.type==='succession')setGarden(c=>({...c,succession:(c.succession||[]).map(x=>x.id===item.id?{...x,status:'done'}:x)}));addActivity({type:'plan',title:`Completed: ${item.title}`,detail:item.detail||'Plan item completed.'});showToast('Plan item completed.');};

 const addTray=(draft)=>{const tray={id:newId('tray'),...draft,cells:Number(draft.cells)||1,createdAt:new Date().toISOString()};setGarden(c=>({...c,trays:[...(c.trays||[]),tray],activity:[activityEntry({type:'tray',title:`Added ${tray.name}`,detail:`${tray.crop} • ${tray.cells} cells`}),...(c.activity||[])]}));showToast(`${tray.name} saved.`);};
 const addLight=(draft)=>{const light={id:newId('light'),...draft,checkedToday:false,lastChecked:null};setGarden(c=>({...c,growLights:[...(c.growLights||[]),light]}));showToast(`${light.name} schedule saved.`);};
 const toggleLight=(id)=>setGarden(c=>({...c,growLights:(c.growLights||[]).map(x=>x.id===id?{...x,checkedToday:!x.checkedToday,lastChecked:new Date().toISOString()}:x)}));
 const startHardening=(plantId)=>{const p=garden.plants.find(x=>x.id===plantId);if(!p)return;const plan={id:newId('hardening'),plantId,plantName:p.name,day:1,complete:false,startedAt:new Date().toISOString()};setGarden(c=>({...c,hardeningPlans:[plan,...(c.hardeningPlans||[])]}));showToast(`${p.name} hardening plan started.`);};
 const advanceHardening=(id)=>setGarden(c=>({...c,hardeningPlans:(c.hardeningPlans||[]).map(x=>x.id===id?(x.day>=7?{...x,complete:true,completedAt:new Date().toISOString()}:{...x,day:x.day+1,lastCompletedAt:new Date().toISOString()}):x)}));
 const saveHydroPod=(draft)=>{const existing=garden.hydroPods?.find(x=>String(x.position)===String(draft.position));setGarden(c=>({...c,hydroPods:existing?(c.hydroPods||[]).map(x=>x.id===existing.id?{...x,...draft,updatedAt:new Date().toISOString()}:x):[...(c.hydroPods||[]),{id:newId('pod'),...draft,updatedAt:new Date().toISOString()}]}));showToast(`Hydroponic pod ${draft.position} saved.`);};

 const cropRecommendations=useMemo(()=>getCropRecommendations(new Date()),[]),weatherAlert=useMemo(()=>gardenWeatherAlert(weatherState.weather),[weatherState.weather]),seasonMode=useMemo(()=>getSeasonMode(new Date()),[]);
 const activeGarden=useMemo(()=>({...garden,spaces:garden.spaces.filter(s=>!s.hidden),plants:garden.plants.filter(p=>!p.archived)}),[garden]);
 const allTasks=useMemo(()=>buildYearRoundTasks({garden:activeGarden,weather:weatherState.weather,date:new Date()}),[activeGarden,weatherState.weather]);
 const todayTasks=allTasks.filter(task=>{const until=daily.snoozed?.[task.id];return !until||until<=dayKey();}),timeline=useMemo(()=>buildTimeline(activeGarden),[activeGarden]);
 const openTask=(task)=>{if(task.kind==='setup')setModal({type:'addMenu'});if(task.kind==='setupPlant')setModal({type:'addPlant'});if(task.kind==='soil')setModal({type:'soilCheck',plant:task.plant});if(task.kind==='navigate')navigate(task.target);if(task.kind==='greenhouse')setModal({type:'greenhouseCheck'});if(task.kind==='plantDetail')setModal({type:'managePlant',plant:task.plant});};
 const controlModal=modal?.type==='managePlant';

 return <div className="site-stage"><div className={`app-shell page-${page}`}>
  {page==='today'&&<TodayWorkspace profile={garden.profile} tasks={todayTasks} dailyDone={daily.done||[]} onTask={openTask} onSnooze={id=>snoozeTask(id,1)} onMenu={()=>setDrawerOpen(true)} noticeOpen={noticeOpen} setNoticeOpen={setNoticeOpen} weatherState={weatherState} weatherAlert={weatherAlert} activity={garden.activity||[]} setModal={setModal} seasonMode={seasonMode}/>} 
  {page==='plant'&&<PlantScreen filter={filter} setFilter={setFilter} recommendations={cropRecommendations} setModal={setModal} navigate={navigate}/>} 
  {page==='garden'&&<GardenWorkspace garden={garden} setModal={setModal} manageSpace={manageSpace}/>} 
  {page==='learn'&&<PlannerScreen garden={garden} timeline={timeline} addSeed={addSeed} completePlanItem={completePlanItem} updatePlantStage={updatePlantStage} recordHarvest={recordHarvest} scheduleSuccession={scheduleSuccession}/>} 
  {page==='profile'&&<SettingsCenter profile={garden.profile} updateProfile={updateProfile} navigate={navigate}/>} 
  {page==='indoor'&&<IndoorCenter garden={garden} navigate={navigate} addTray={addTray} addLight={addLight} toggleLight={toggleLight} startHardening={startHardening} advanceHardening={advanceHardening} saveHydroPod={saveHydroPod} setModal={setModal}/>} 
  <BottomNav page={page==='indoor'?'profile':page} navigate={navigate}/>{drawerOpen&&<MenuDrawer close={()=>setDrawerOpen(false)} navigate={navigate}/>} 
  {controlModal&&<GardenControls modal={modal} garden={garden} close={()=>setModal(null)} savePlant={savePlant} archivePlant={archivePlant} deletePlant={deletePlant} saveHarvest={saveHarvest} saveProblem={saveProblem}/>} 
  {modal&&!controlModal&&<DetailModal key={`${modal.type}-${modal.plant?.id||modal.space?.id||modal.crop?.id||''}`} modal={modal} close={()=>setModal(null)} garden={garden} addPlant={addPlant} addSpace={addSpace} recordSoilCheck={recordSoilCheck} recordWatered={recordWatered} logGreenhouseCheck={logGreenhouseCheck} setModal={setModal}/>} 
  {toast&&<div className="toast" role="status">{toast}</div>}
 </div></div>;
}
