import React,{useMemo,useState}from'react';
import{ArrowDown,ArrowUp,Camera,ChevronRight,Download,Eye,EyeOff,ImageOff,Leaf,Pencil,Plus,Printer,QrCode,Sprout,Trash2,X}from'lucide-react';
import{QRCodeSVG}from'qrcode.react';
import{cropArt,gardenArt}from'./art.jsx';
import{formatDateTime}from'./data.js';

const isBed=type=>['bed','black-square-bed','white-oval-bed','oval-bed','in-ground','container'].includes(type);
const bedTypeLabel=type=>({
 'black-square-bed':'Black square raised bed','white-oval-bed':'White rounded raised bed','oval-bed':'White rounded raised bed',bed:'Raised bed','in-ground':'In-ground bed',container:'Container',greenhouse:'Greenhouse',indoor:'Indoor seed-starting area',basement:'Basement growing area',hydro:'Hydroponics'
}[type]||'Growing space');

function BedImage({space}){return <div className="bed-cover">{space.photo?<img src={space.photo} alt={`${space.name} garden bed`}/>:gardenArt(space.type)}</div>}

function BedCard({space,plants,index,total,onOpen,manageSpace}){return <article className="individual-bed-card">
 <button className="bed-card-main" onClick={()=>onOpen(space.id)}><BedImage space={space}/><div className="bed-card-copy"><span className="bed-type-label">{bedTypeLabel(space.type)}</span><h3>{space.name}</h3><p>{plants.length?`${plants.length} plant record${plants.length===1?'':'s'} connected`:'No plants connected yet'}</p><div className="bed-card-footer"><span>{space.photo?'Photo saved on this device':'Default bed artwork'}</span><ChevronRight/></div></div></button>
 <div className="space-management-row"><button disabled={index===0} onClick={()=>manageSpace('up',space.id)} aria-label={`Move ${space.name} up`}><ArrowUp/></button><button disabled={index===total-1} onClick={()=>manageSpace('down',space.id)} aria-label={`Move ${space.name} down`}><ArrowDown/></button><button onClick={()=>manageSpace('hide',space.id)}><EyeOff/> Hide</button><button className="danger-space-action" onClick={()=>manageSpace('remove',space.id)}><Trash2/> Remove</button></div>
 </article>}

function BedDetail({space,plants,activity,onClose,saveSpace,setModal}){const[draft,setDraft]=useState({name:space.name,type:space.type,capacity:space.capacity||12,notes:space.notes||'',photo:space.photo||''});const[tab,setTab]=useState('overview');const link=`${window.location.origin}${window.location.pathname}?bed=${encodeURIComponent(space.id)}`;const bedActivity=activity.filter(e=>e.spaceId===space.id||plants.some(p=>p.id===e.plantId)).slice(0,20);
 const readPhoto=file=>{if(!file)return;if(file.size>1800000){window.alert('Choose a photo smaller than about 1.8 MB for this local-device version.');return}const reader=new FileReader();reader.onload=()=>setDraft(v=>({...v,photo:String(reader.result)}));reader.readAsDataURL(file)};
 const save=()=>{saveSpace(space.id,draft);onClose()};
 const print=()=>{const old=document.title;document.title=`${draft.name} - Runyan Garden`;window.print();document.title=old};
 return <div className="overlay modal-overlay bed-detail-overlay" onMouseDown={onClose}><section className="detail-modal bed-detail-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><X/></button>
  <BedImage space={{...space,...draft}}/><span className="modal-kicker">{bedTypeLabel(draft.type)}</span><h2>{draft.name}</h2>
  <div className="bed-detail-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Bed</button><button className={tab==='plants'?'active':''} onClick={()=>setTab('plants')}>Plants ({plants.length})</button><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Activity</button><button className={tab==='qr'?'active':''} onClick={()=>setTab('qr')}>QR label</button></div>
  {tab==='overview'&&<div className="bed-edit-form"><label>Bed name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Bed or space type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option value="black-square-bed">Black square raised bed</option><option value="white-oval-bed">White rounded raised bed</option><option value="bed">Other raised bed</option><option value="in-ground">In-ground bed</option><option value="container">Container</option><option value="greenhouse">Greenhouse</option><option value="indoor">Indoor seed-starting area</option><option value="basement">Basement growing area</option><option value="hydro">Hydroponics</option></select></label><label>Approximate plant capacity<input type="number" min="1" max="200" value={draft.capacity} onChange={e=>setDraft({...draft,capacity:e.target.value})}/></label><label>Bed notes<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} placeholder="Sun, shade, soil, fencing, or anything the other gardener should know"/></label><div className="bed-photo-actions"><label className="photo-upload-button"><Camera/> {draft.photo?'Replace bed photo':'Add bed photo'}<input type="file" accept="image/*" capture="environment" onChange={e=>readPhoto(e.target.files?.[0])}/></label>{draft.photo&&<button onClick={()=>setDraft({...draft,photo:''})}><ImageOff/> Remove photo</button>}</div><p className="local-photo-note">Photo is saved on this device for now. v1.0.0 will upload it so both phones see the same image.</p><button className="primary-button" onClick={save}><Pencil/> Save bed details</button></div>}
  {tab==='plants'&&<div className="bed-plant-list">{plants.length?plants.map(p=><button key={p.id} onClick={()=>setModal({type:'managePlant',plant:p})}><span className="bed-plant-art">{p.cropId?cropArt(p.cropId):<Sprout/>}</span><span><strong>{p.name}</strong><small>{p.variety||p.stage} • {p.stage}</small></span><ChevronRight/></button>):<button className="empty-bed-action" onClick={()=>setModal({type:'addPlant',spaceId:space.id})}><Plus/><span><strong>Add the first plant to {space.name}</strong><small>The app will connect its care, harvests, and history to this bed.</small></span></button>}<button className="secondary-button full-width" onClick={()=>setModal({type:'addPlant',spaceId:space.id})}>Add plant to this bed</button></div>}
  {tab==='activity'&&<div className="bed-activity-list">{bedActivity.length?bedActivity.map(e=><article key={e.id}><strong>{e.actor?`${e.actor}: `:''}{e.title}</strong><span>{e.detail}</span><small>{formatDateTime(e.at)}</small></article>):<p>No activity has been recorded for this bed yet. Normal garden actions will fill this automatically.</p>}</div>}
  {tab==='qr'&&<div className="bed-qr-panel"><div className="printable-bed-label"><span className="label-brand">THE RUNYAN GARDEN</span><QRCodeSVG value={link} size={190} includeMargin/><h3>{draft.name}</h3><p>{bedTypeLabel(draft.type)}</p><small>Scan to open this exact garden-space record</small></div><p className="local-photo-note">This code links to bed ID <strong>{space.id}</strong>. It opens locally now; shared cross-phone access activates with v1.0.0.</p><div className="modal-action-row"><button className="primary-button" onClick={print}><Printer/> Print bed label</button><button className="secondary-button" onClick={()=>navigator.clipboard?.writeText(link)}><QrCode/> Copy link</button></div></div>}
 </section></div>}

export default function BedWorkspace({garden,setModal,manageSpace,saveSpace}){const[selected,setSelected]=useState(null);const visible=garden.spaces.filter(s=>!s.hidden&&!s.deletedAt),hidden=garden.spaces.filter(s=>s.hidden&&!s.deletedAt),plants=garden.plants.filter(p=>!p.archived&&!p.deletedAt);const selectedSpace=visible.concat(hidden).find(s=>s.id===selected);const selectedPlants=selectedSpace?plants.filter(p=>p.spaceId===selectedSpace.id):[];return <main className="screen garden-screen"><section className="dark-header garden-header"><Leaf/><h1>The Runyan Garden</h1><p>Each card is one real bed or growing space—with its own name, photo, plants, care history, and QR label.</p><button className="add-garden" onClick={()=>setModal({type:'addMenu'})}><Plus/></button></section><section className="garden-list screen-pad"><div className="garden-actions"><button onClick={()=>setModal({type:'addPlant'})}><Sprout/> Add plant</button><button onClick={()=>setModal({type:'addSpace'})}><Plus/> Add bed or space</button></div><div className="bed-link-note"><QrCode/><span><strong>Everything links through the bed.</strong><small>Name it, add a photo, connect its plants, then print its exact QR label.</small></span></div>{visible.map((space,index)=><BedCard key={space.id} space={space} plants={plants.filter(p=>p.spaceId===space.id)} index={index} total={visible.length} onOpen={setSelected} manageSpace={manageSpace}/>)}{!visible.length&&<button className="empty-garden" onClick={()=>setModal({type:'addSpace'})}><Plus/><span><strong>Add the first Runyan garden bed.</strong><small>Create one record for each physical bed so tasks and QR labels stay clear.</small></span></button>}{hidden.length>0&&<section className="hidden-spaces"><div><Eye/><span><strong>Hidden seasonal spaces</strong><small>Still saved and ready to restore.</small></span></div>{hidden.map(s=><button key={s.id} onClick={()=>manageSpace('show',s.id)}><Eye/> Restore {s.name}</button>)}</section>}</section>{selectedSpace&&<BedDetail space={selectedSpace} plants={selectedPlants} activity={garden.activity||[]} onClose={()=>setSelected(null)} saveSpace={saveSpace} setModal={setModal}/>}</main>}
