export const colors={green:'#063c27',gold:'#efb52b',cream:'#fbf7ec',red:'#c64231',blue:'#4c8fb7'};
export const GREEN_BAY={name:'Green Bay, Wisconsin',shortName:'Green Bay',zone:'5b',latitude:44.5133,longitude:-88.0133,timezone:'America/Chicago'};
export const starterGarden={profile:{gardenerName:'Brooke',location:GREEN_BAY.name,zone:GREEN_BAY.zone},spaces:[{id:'raised-bed-1',name:'Raised Bed 1',type:'black-square-bed',capacity:12},{id:'greenhouse',name:'Greenhouse',type:'greenhouse',capacity:8},{id:'hydroponics',name:'Hydroponics',type:'hydro',capacity:10}],plants:[],activity:[]};
const C=(id,name,family,care={})=>({id,name,family,variety:care.variety||'',depth:care.depth||'',spacing:care.spacing||'',sun:care.sun||'6+ hours',harvest:care.harvest||'',succession:care.succession||'Usually one planting',moisture:care.moisture||'even',checkDepth:care.checkDepth||'1 inch',watering:care.watering||'Water when the soil check shows the root zone is becoming dry.',criticalStage:care.criticalStage||'',indoorSuitable:Boolean(care.indoorSuitable),summary:care.summary||''});
export const cropCatalog=[
 C('bell-pepper','Bell Pepper','vegetables',{variety:'Sweet peppers',depth:'¼ inch indoors',spacing:'18–24 inches',sun:'8+ hours',harvest:'60–90 days from transplant',moisture:'moderately even',checkDepth:'1–2 inches',watering:'Water deeply when the upper 1–2 inches are dry; avoid constantly soggy soil.',criticalStage:'flowering and fruit development',indoorSuitable:true,summary:'Warm-season fruiting plant that needs steady warmth and strong light.'}),
 C('hot-pepper','Hot Pepper','vegetables',{variety:'Jalapeño, serrano & others',depth:'¼ inch indoors',spacing:'18–24 inches',sun:'8+ hours',harvest:'65–100 days from transplant',moisture:'moderately even',checkDepth:'1–2 inches',watering:'Water deeply after the upper 1–2 inches begin drying.',criticalStage:'flowering and fruit set',indoorSuitable:true,summary:'Long-season pepper suited to outdoor beds or large indoor containers under strong lights.'}),
 C('tomato','Tomato','vegetables',{depth:'¼ inch indoors',spacing:'24–36 inches',sun:'8+ hours',harvest:'55–90 days from transplant',moisture:'consistently even',checkDepth:'2 inches',watering:'Water deeply at the base when soil is drying two inches down; avoid large wet-dry swings.',criticalStage:'flowering and fruit fill',indoorSuitable:true,summary:'Fruiting crop that benefits from consistent moisture, support, and strong light.'}),
 C('lettuce','Lettuce','vegetables',{variety:'Leaf & head',depth:'¼ inch',spacing:'6–12 inches',sun:'4–6 hours',harvest:'35–60 days',succession:'Every 10–14 days',moisture:'consistently moist',checkDepth:'top 1 inch',watering:'Keep the shallow root zone evenly moist; water before the top inch fully dries.',criticalStage:'heading and hot weather',indoorSuitable:true,summary:'Cool-season shallow-rooted crop that dislikes drying out or prolonged heat.'}),
 C('cabbage','Cabbage','vegetables',{depth:'¼–½ inch',spacing:'18–24 inches',sun:'6+ hours',harvest:'70–110 days',moisture:'steady moisture',checkDepth:'1–2 inches',watering:'Water the root zone evenly when the upper soil begins drying; avoid large swings while heads form.',criticalStage:'head formation',summary:'Cool-season brassica that needs consistent moisture while developing a head.'}),
 C('broccoli','Broccoli','vegetables',{depth:'¼–½ inch',spacing:'18–24 inches',sun:'6+ hours',harvest:'55–85 days',moisture:'steady moisture',checkDepth:'1–2 inches',watering:'Keep the root zone evenly moist, especially while the main head forms.',criticalStage:'head formation',summary:'Cool-season brassica grown for central and side shoots.'}),
 C('cauliflower','Cauliflower','vegetables',{depth:'¼–½ inch',spacing:'18–24 inches',sun:'6+ hours',harvest:'60–100 days',moisture:'very steady',checkDepth:'1–2 inches',watering:'Prevent drying during curd formation; water deeply whenever the upper root zone begins drying.',criticalStage:'curd formation',summary:'Temperature-sensitive brassica that performs best with steady growth.'}),
 C('corn','Sweet Corn','vegetables',{depth:'1–2 inches',spacing:'8–12 inches in blocks',sun:'8+ hours',harvest:'60–100 days',succession:'Small blocks every 10–14 days',moisture:'deep and steady',checkDepth:'3–4 inches',watering:'Check several inches deep and water thoroughly when the root zone is drying.',criticalStage:'tasseling, silking, and ear fill',summary:'Deep-rooted crop that needs blocks for pollination and reliable moisture during ear development.'}),
 C('green-bean','Green Beans','vegetables',{depth:'1 inch',spacing:'3–6 inches',sun:'6+ hours',harvest:'50–65 days',succession:'Every 2–3 weeks',moisture:'moderately even',checkDepth:'1–2 inches',watering:'Water when soil is dry 1–2 inches down, especially during flowering and pod fill.',criticalStage:'flowering and pod fill',summary:'Fast warm-season crop available in bush and pole types.'}),
 C('peas','Peas','vegetables',{depth:'1 inch',spacing:'2–3 inches',sun:'6+ hours',harvest:'55–75 days',moisture:'even in cool soil',checkDepth:'1 inch',watering:'Keep soil evenly moist without waterlogging, especially while flowering and filling pods.',criticalStage:'flowering and pod fill',summary:'Cool-season climber that prefers mild temperatures.'}),
 C('carrot','Carrots','vegetables',{depth:'¼ inch',spacing:'2–3 inches',sun:'6+ hours',harvest:'60–80 days',succession:'Every 2–3 weeks',moisture:'even near the surface during germination',checkDepth:'1–2 inches',watering:'Keep the seed zone moist until established, then water deeply enough to support straight roots.',criticalStage:'germination and root expansion',summary:'Direct-sown root crop that needs loose soil and consistent germination moisture.'}),
 C('radish','Radishes','vegetables',{depth:'½ inch',spacing:'2 inches',sun:'4–6 hours',harvest:'22–40 days',succession:'Every 7–14 days',moisture:'even',checkDepth:'1 inch',watering:'Keep the top inch evenly moist so roots grow quickly and stay tender.',criticalStage:'root expansion',indoorSuitable:true,summary:'Very fast cool-season root crop.'}),
 C('cucumber','Cucumbers','vegetables',{depth:'1 inch',spacing:'12–24 inches',sun:'8+ hours',harvest:'50–70 days',moisture:'consistently moist',checkDepth:'1–2 inches',watering:'Water deeply whenever the upper root zone begins drying; fruit can turn bitter after moisture stress.',criticalStage:'flowering and fruit production',summary:'Warm-season vine that produces best with steady moisture and frequent picking.'}),
 C('zucchini','Zucchini & Summer Squash','vegetables',{depth:'1 inch',spacing:'30–48 inches',sun:'8+ hours',harvest:'45–60 days',moisture:'deep and even',checkDepth:'2 inches',watering:'Water deeply at the base when soil is drying two inches down.',criticalStage:'flowering and fruit growth',summary:'Large warm-season plant that grows quickly and needs room.'}),
 C('winter-squash','Winter Squash','vegetables',{depth:'1 inch',spacing:'36–60 inches',sun:'8+ hours',harvest:'80–120 days',moisture:'deep and even',checkDepth:'2–3 inches',watering:'Water deeply when the root zone is drying; reduce overhead watering around leaves.',criticalStage:'fruit set and sizing',summary:'Long-vining crop grown for mature storage fruit.'}),
 C('pumpkin','Pumpkins','vegetables',{depth:'1 inch',spacing:'48–72 inches',sun:'8+ hours',harvest:'90–120 days',moisture:'deep and even',checkDepth:'2–3 inches',watering:'Water deeply near the root zone as soil dries, particularly while fruit sizes up.',criticalStage:'fruit set and sizing',summary:'Space-hungry warm-season vine.'}),
 C('green-onion','Green Onions','vegetables',{depth:'¼ inch',spacing:'1–2 inches',sun:'6+ hours',harvest:'45–70 days',succession:'Every 2–3 weeks',moisture:'even',checkDepth:'1 inch',watering:'Keep the shallow root zone evenly moist.',indoorSuitable:true,summary:'Compact crop that works outdoors or in bright indoor containers.'}),
 C('onion','Bulb Onions','vegetables',{depth:'¼ inch indoors',spacing:'4–6 inches',sun:'8+ hours',harvest:'90–120 days',moisture:'even until bulbs mature',checkDepth:'1–2 inches',watering:'Maintain even moisture while bulbs enlarge, then reduce near maturity.',criticalStage:'bulb enlargement',summary:'Long-season crop commonly started indoors in Wisconsin.'}),
 C('garlic','Garlic','vegetables',{variety:'Hardneck',depth:'2–3 inches',spacing:'6 inches',sun:'6+ hours',harvest:'Following July',moisture:'moderate',checkDepth:'2 inches',watering:'Water when spring soil dries around the root zone; reduce as leaves yellow near harvest.',criticalStage:'spring growth and bulb formation',summary:'Fall-planted Wisconsin staple that overwinters outdoors.'}),
 C('potato','Potatoes','vegetables',{depth:'3–5 inches',spacing:'12 inches',sun:'6+ hours',harvest:'70–120 days',moisture:'even',checkDepth:'2–3 inches',watering:'Keep soil evenly moist during tuber formation but never waterlogged.',criticalStage:'flowering and tuber formation',summary:'Cool-season tuber crop that benefits from hilling.'}),
 C('spinach','Spinach','vegetables',{depth:'½ inch',spacing:'3–6 inches',sun:'4–6 hours',harvest:'35–50 days',succession:'Every 10–14 days',moisture:'consistently moist',checkDepth:'top 1 inch',watering:'Keep the shallow root zone evenly moist, especially as weather warms.',indoorSuitable:true,summary:'Cool-season leafy crop that can also produce indoors.'}),
 C('kale','Kale','vegetables',{depth:'¼–½ inch',spacing:'12–18 inches',sun:'6+ hours',harvest:'50–75 days',moisture:'even',checkDepth:'1–2 inches',watering:'Water when the upper root zone begins drying; consistent growth produces tender leaves.',indoorSuitable:true,summary:'Cold-tolerant leafy green with a long harvest window.'}),
 C('chard','Swiss Chard','vegetables',{depth:'½ inch',spacing:'8–12 inches',sun:'5–6 hours',harvest:'50–65 days',moisture:'even',checkDepth:'1–2 inches',watering:'Maintain even moisture for steady leaf production.',indoorSuitable:true,summary:'Productive leafy crop tolerant of summer warmth.'}),
 C('basil','Basil','herbs',{variety:'Genovese',depth:'¼ inch',spacing:'8–12 inches',sun:'6+ hours',harvest:'30–60 days',succession:'Every 3–4 weeks',moisture:'even but not soggy',checkDepth:'1 inch',watering:'Water when the top inch begins drying; avoid prolonged sogginess.',criticalStage:'active leaf production',indoorSuitable:true,summary:'Warm herb that responds well to frequent pinching.'}),
 C('cilantro','Cilantro','herbs',{depth:'¼–½ inch',spacing:'4–6 inches',sun:'4–6 hours',harvest:'30–50 days',succession:'Every 2–3 weeks',moisture:'even and cool',checkDepth:'1 inch',watering:'Keep evenly moist and cool to delay bolting.',indoorSuitable:true,summary:'Fast cool-season herb.'}),
 C('dill','Dill','herbs',{depth:'¼ inch',spacing:'8–12 inches',sun:'6+ hours',harvest:'40–70 days',succession:'Every 3–4 weeks',moisture:'moderate',checkDepth:'1 inch',watering:'Water when the top inch dries; established dill tolerates slight drying.',summary:'Tall annual herb useful for leaves, flowers, and seed.'}),
 C('parsley','Parsley','herbs',{depth:'¼ inch',spacing:'8–10 inches',sun:'4–6 hours',harvest:'70–90 days',moisture:'even',checkDepth:'1 inch',watering:'Keep the root zone evenly moist for continuous leaf production.',indoorSuitable:true,summary:'Slow-germinating biennial herb.'}),
 C('strawberry','Strawberries','fruits',{spacing:'12–18 inches',sun:'6+ hours',harvest:'Early to midsummer',moisture:'even',checkDepth:'1–2 inches',watering:'Keep moisture consistent during bloom and berry development; water at the base.',criticalStage:'flowering and berry fill',summary:'Perennial fruit suited to beds and containers.'}),
 C('marigold','Marigolds','flowers',{variety:'French',depth:'¼ inch',spacing:'8–12 inches',sun:'6+ hours',harvest:'Blooms in 50–60 days',moisture:'moderate',checkDepth:'1 inch',watering:'Water when the top inch dries; established plants tolerate short dry periods.',summary:'Warm-season flower often started indoors.'})
];
const outdoorNow=(id,m)=>{if(['lettuce','spinach','kale','radish','peas','carrot','cabbage','broccoli','cauliflower','potato'].includes(id))return m>=3&&m<=5||m>=8&&m<=9;if(['bell-pepper','hot-pepper','tomato','corn','green-bean','cucumber','zucchini','winter-squash','pumpkin','basil','marigold'].includes(id))return m>=5&&m<=7;return m>=4&&m<=8};
function recommendationFor(c,date=new Date()){const m=date.getMonth()+1;if(c.indoorSuitable&&[10,11,12,1,2].includes(m))return{status:'Grow indoors',timing:'Under strong lights',tone:'green',action:'Add from catalog',note:`${c.name} can be tracked as an indoor crop when the setup is suitable.`};if(outdoorNow(c.id,m))return{status:'Plant or care for outdoors',timing:'Current seasonal window',tone:'green',action:'Add from catalog',note:c.summary};if(['bell-pepper','hot-pepper','tomato','cabbage','broccoli','cauliflower','onion','marigold'].includes(c.id)&&m<=4)return{status:'Start seeds indoors',timing:'Before outdoor planting',tone:'gold',action:'Add from catalog',note:c.summary};return{status:'Plan for later',timing:'Upcoming seasonal window',tone:'gold',action:'View crop',note:c.summary};}
export function getCropRecommendations(date=new Date()){return cropCatalog.map(c=>({...c,...recommendationFor(c,date)}));}
export function getCropProfile(id){return cropCatalog.find(c=>c.id===id)||null;}
export function newId(prefix){return`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;}
export function formatDateTime(value){if(!value)return'Not recorded';return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value));}