export const colors = { green:'#063c27', gold:'#efb52b', cream:'#fbf7ec', red:'#c64231', blue:'#4c8fb7' };
export const GREEN_BAY = { name:'Green Bay, Wisconsin', shortName:'Green Bay', zone:'5b', latitude:44.5133, longitude:-88.0133, timezone:'America/Chicago' };
export const starterGarden = {
 profile:{gardenerName:'Brooke',location:GREEN_BAY.name,zone:GREEN_BAY.zone},
 spaces:[{id:'raised-bed-1',name:'Raised Bed 1',type:'black-square-bed',capacity:12},{id:'greenhouse',name:'Greenhouse',type:'greenhouse',capacity:8},{id:'hydroponics',name:'Hydroponics',type:'hydro',capacity:10}],
 plants:[],activity:[]
};
export const cropCatalog=[
 {id:'lettuce',name:'Lettuce',variety:'Leaf & Head',family:'vegetables',depth:'¼ inch',sun:'4–6 hours',harvest:'35–60 days',succession:'Every 10–14 days',indoorSeason:'winter',summary:'A cool-season crop that can grow outdoors in cool weather or indoors under lights.'},
 {id:'onions',name:'Green Onions',variety:'Bunching',family:'vegetables',depth:'¼ inch',sun:'6+ hours',harvest:'45–70 days',succession:'Every 2–3 weeks',indoorSeason:'winter',summary:'A forgiving crop for short outdoor rows or indoor containers under strong lights.'},
 {id:'garlic',name:'Garlic',variety:'Hardneck',family:'vegetables',depth:'2–3 inches',sun:'6+ hours',harvest:'The following July',succession:'One fall planting',summary:'Hardneck garlic is planted outdoors in fall so it can overwinter and form bulbs next summer.'},
 {id:'spinach',name:'Spinach',variety:'Bloomsdale',family:'vegetables',depth:'½ inch',sun:'4–6 hours',harvest:'35–50 days',succession:'Every 10–14 days',indoorSeason:'winter',summary:'Spinach prefers cool conditions and can also be grown indoors for leaves.'},
 {id:'peppers',name:'Peppers',variety:'Bell & Sweet',family:'vegetables',depth:'¼ inch indoors',sun:'8+ hours',harvest:'60–90 days from transplant',succession:'One indoor start',summary:'Peppers need a long warm season. They can be seedlings for spring or mature container plants grown indoors under strong lights.'},
 {id:'basil',name:'Basil',variety:'Genovese',family:'herbs',depth:'¼ inch',sun:'6+ hours',harvest:'30–60 days',succession:'Every 3–4 weeks',indoorSeason:'winter',summary:'Basil loves warmth and can be harvested indoors under lights or outside in summer.'},
 {id:'marigold',name:'Marigolds',variety:'French',family:'flowers',depth:'¼ inch',sun:'6+ hours',harvest:'Blooms in 50–60 days',succession:'Usually one planting',summary:'A warm-season flower often started from seed indoors, then moved outside as a young plant.'}
];
function recommendationFor(id,date=new Date()){
 const month=date.getMonth()+1,day=date.getDate();
 switch(id){
  case'lettuce':if(month<=4)return{status:'Plant outside from seed',timing:'Now',tone:'green',action:'Plant now',note:'Cool weather is ideal.'};if(month===5)return{status:'Plant outside carefully',timing:'Cool spot',tone:'gold',action:'See heat tips',note:'Choose shade and heat-tolerant varieties.'};if(month===7&&day>=20)return{status:'Start a fall crop',timing:'Now',tone:'green',action:'Plan a batch',note:'Start a small fall planting.'};if(month===8||month===9)return{status:'Plant outside from seed',timing:'Now',tone:'green',action:'Plant now',note:'A good window for fall lettuce.'};return{status:'Plan for later',timing:'Spring or indoors',tone:'gold',action:'View options',note:'Outdoor timing is closed, but indoor leaf production is possible.'};
  case'onions':if(month>=4&&month<=8)return{status:'Plant outside from seed',timing:'Now',tone:'green',action:'Plant now',note:'Sow a short row for a steady supply.'};if(month<=3)return{status:'Start seeds indoors',timing:'Now',tone:'gold',action:'See steps',note:'Grow young plants under lights before spring planting.'};return{status:'Grow indoors or plan spring',timing:'Now or later',tone:'gold',action:'View options',note:'Green onions can grow indoors under strong lights.'};
  case'garlic':if(month>=9&&month<=11)return{status:'Plant outside',timing:'Now',tone:'green',action:'See steps',note:'Plant before the ground freezes.'};return{status:'Plan for later',timing:'October',tone:'gold',action:'Plan ahead',note:'Hardneck garlic belongs in the fall calendar.'};
  case'spinach':if(month===3||month===4||month===8||month===9)return{status:'Plant outside from seed',timing:'Now',tone:'green',action:'Plant now',note:'Cool soil is ideal.'};return{status:'Grow indoors or wait for cool weather',timing:'Indoor option',tone:'gold',action:'View options',note:'Heat can make outdoor spinach bolt.'};
  case'peppers':if(month<=3)return{status:'Start seeds indoors',timing:'Now',tone:'green',action:'See steps',note:'These are young plants for spring unless you choose indoor fruit production.'};if(month===4||month===5)return{status:'Move young plants outside carefully',timing:'After warm nights',tone:'gold',action:'Check conditions',note:'Harden seedlings off before transplanting.'};if(month>=6&&month<=9)return{status:'Care for existing plants',timing:'Already growing',tone:'green',action:'Track a plant',note:'Existing plants need warmth, water checks, and harvest tracking.'};return{status:'Grow indoors or plan spring',timing:'Choose a goal',tone:'gold',action:'View options',note:'A mature container pepper can be grown indoors with strong light and enough space.'};
  case'basil':if(month>=5&&month<=7)return{status:'Plant outside or move young plants outside',timing:'Now',tone:'green',action:'Plant now',note:'Warm weather supports fast growth.'};if(month===8)return{status:'Care for existing plants',timing:'Already growing',tone:'green',action:'Track a plant',note:'Keep pinching flowers to extend harvest.'};return{status:'Grow indoors',timing:'Under lights',tone:'green',action:'See indoor setup',note:'Basil can produce leaves indoors with warmth and strong light.'};
  case'marigold':if(month>=5&&month<=7)return{status:'Move young marigold plants outside',timing:'Now',tone:'green',action:'Add to garden',note:'These are seedlings already started indoors or purchased as small plants.'};if(month<=4)return{status:'Start seeds indoors',timing:'Now',tone:'gold',action:'See steps',note:'Grow seedlings under lights before moving them outside.'};return{status:'Plan for later',timing:'Late spring',tone:'red',action:'View timing',note:'The outdoor season is winding down.'};
  default:return{status:'Review options',timing:'Today',tone:'gold',action:'Learn more',note:''};
 }
}
export function getCropRecommendations(date=new Date()){return cropCatalog.map(c=>({...c,...recommendationFor(c.id,date)}));}
export function newId(prefix){return`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;}
export function formatDateTime(value){if(!value)return'Not recorded';return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value));}
