export const DATASET_SCHEMA_VERSION=16;
export const DATA_READINESS_VERSION=1;
export const BACKUP_EXPORT_VERSION=2;
export const GARDEN_TIMEZONE='America/Chicago';

const nowIso=()=>new Date().toISOString();
const text=value=>String(value??'').trim();
const number=value=>Number.isFinite(Number(value))?Number(value):0;
const array=value=>Array.isArray(value)?value:[];
const clone=value=>JSON.parse(JSON.stringify(value));
const dataUrlFields=['photo','frontPhoto','backPhoto','image','imageData','thumbnail','attachment'];
const mojibakePairs=[
 ['\u00c2\u00b7','·'],['\u00c2\u00b0','°'],['\u00c2\u00bc','¼'],['\u00c2\u00bd','½'],['\u00c2\u00be','¾'],
 ['\u00c3\u0097','×'],['\u00c3\u00b7','÷'],['\u00c3\u00a9','é'],['\u00c3\u00b1','ñ'],['\u00c3\u00bc','ü'],
 ['\u00e2\u20ac\u2122','’'],['\u00e2\u20ac\u0153','“'],['\u00e2\u20ac\u009d','”'],['\u00e2\u20ac\u201c','”'],['\u00e2\u20ac\u201d','”'],
 ['\u00e2\u20ac\u2013','–'],['\u00e2\u20ac\u201d','—'],['\u00e2\u20ac\u00a2','•'],['\u00e2\u20ac\u00a6','…']
];
export function repairKnownMojibakeText(value){
 if(typeof value==='string'){let next=value;for(const[bad,good]of mojibakePairs)next=next.split(bad).join(good);return next}
 if(Array.isArray(value))return value.map(repairKnownMojibakeText);
 if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,row])=>[key,repairKnownMojibakeText(row)]));
 return value;
}

function stableStringify(value){
 if(value===null||typeof value!=='object')return JSON.stringify(value);
 if(Array.isArray(value))return`[${value.map(stableStringify).join(',')}]`;
 return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stableStringify(value[key])}`).join(',')}}`;
}
export function integrityHash(value){
 const input=typeof value==='string'?value:stableStringify(value);let hash=2166136261;
 for(let i=0;i<input.length;i++){hash^=input.charCodeAt(i);hash=Math.imul(hash,16777619)}
 return(hash>>>0).toString(16).padStart(8,'0');
}
const compactRecord=record=>Object.fromEntries(Object.entries(record||{}).filter(([key,value])=>!dataUrlFields.includes(key)&&typeof value!=='function'&&!(typeof value==='string'&&value.length>1000)));
const legacySignature=(key,record,index)=>stableStringify({key,index,oldId:record?.id||'',name:record?.name||record?.title||record?.label||'',parent:record?.plantId||record?.spaceId||record?.packetId||record?.vacationPlanId||'',date:record?.createdAt||record?.at||record?.date||record?.dueDate||'',record:compactRecord(record)});
const prefixFor=key=>({spaces:'space',plants:'plant',activity:'activity',seedPackets:'packet',seedUsage:'seed-use',seedTransactions:'seed-tx',harvests:'harvest',problems:'issue',succession:'succession',trays:'tray',growLights:'light',hardeningPlans:'hardening',hydroPods:'pod',greenhouseReadings:'reading',reminders:'reminder',taskHistory:'task-completion',plantingDecisions:'planting-decision',shoppingItems:'shopping',weatherRecommendationHistory:'weather-decision',vacationPlans:'vacation',calculatorResults:'calculator',environmentalRecords:'environment',environmentalCorrections:'rain-correction',wateringEvents:'watering',soilCheckEvents:'soil-check',photos:'photo',attachments:'attachment',qrLabels:'qr-label',offlineOperations:'operation'}[key]||key.replace(/s$/,''));

export const STATUS_MODELS={
 spaces:['active','archived','deleted'],plants:['active','archived','deleted'],seedPackets:['active','empty','archived','deleted'],trays:['active','completed','archived','deleted'],hydroPods:['active','completed','archived','deleted'],reminders:['active','completed','canceled','archived','deleted'],taskHistory:['completed','not-needed','skipped','canceled','deleted'],shoppingItems:['active','owned','purchased','archived','deleted'],vacationPlans:['draft','active','completed','canceled','archived','deleted'],vacationActions:['active','completed','canceled','archived','deleted'],problems:['open','resolved','archived','deleted'],photos:['active','archived','deleted'],attachments:['active','archived','deleted'],offlineOperations:['pending','processing','completed','failed','conflict','canceled']
};

export const COLLECTION_DEFINITIONS={
 profile:{source:'brookes-garden-state-v2.profile',authority:'Shared garden settings',ownership:'shared',relationships:[]},
 spaces:{source:'brookes-garden-state-v2.spaces',authority:'Growing Space record',ownership:'shared',relationships:[]},
 plants:{source:'brookes-garden-state-v2.plants',authority:'Plant record with nested Plant Journey stage history',ownership:'shared',relationships:['spaceId -> spaces.id','sourcePacketId -> seedPackets.id']},
 seedPackets:{source:'brookes-garden-state-v2.seedPackets',authority:'Seed inventory packet and current quantity projection',ownership:'shared',relationships:[]},
 seedTransactions:{source:'brookes-garden-state-v2.seedTransactions',authority:'Seed quantity changes and reservations',ownership:'attributed',relationships:['packetId -> seedPackets.id','plantId -> plants.id']},
 seedUsage:{source:'brookes-garden-state-v2.seedUsage',authority:'Legacy seed-use history retained as events',ownership:'attributed',relationships:['packetId -> seedPackets.id','plantId -> plants.id']},
 trays:{source:'brookes-garden-state-v2.trays',authority:'Indoor Growing project/tray record',ownership:'shared',relationships:['packetId/sourcePacketId -> seedPackets.id','plantId -> plants.id']},
 growLights:{source:'brookes-garden-state-v2.growLights',authority:'Grow-light equipment record',ownership:'shared',relationships:[]},
 hardeningPlans:{source:'brookes-garden-state-v2.hardeningPlans',authority:'Hardening plan',ownership:'shared',relationships:['plantId -> plants.id']},
 hydroPods:{source:'brookes-garden-state-v2.hydroPods',authority:'Hydroponic pod record',ownership:'shared',relationships:['plantId -> plants.id','packetId -> seedPackets.id']},
 greenhouseReadings:{source:'brookes-garden-state-v2.greenhouseReadings',authority:'Observed greenhouse reading event',ownership:'attributed',relationships:['spaceId -> spaces.id']},
 reminders:{source:'brookes-garden-state-v2.reminders',authority:'Manual Chore Board task',ownership:'shared',relationships:['plantId -> plants.id','spaceId -> spaces.id']},
 taskHistory:{source:'brookes-garden-state-v2.taskHistory',authority:'Task completion event stream',ownership:'attributed',relationships:['taskId -> generated/manual/vacation task','plantId -> plants.id','spaceId -> spaces.id']},
 weatherRecommendationHistory:{source:'brookes-garden-state-v2.weatherRecommendationHistory',authority:'Weather recommendation decisions',ownership:'attributed',relationships:[]},
 wateringEvents:{source:'brookes-garden-state-v2.wateringEvents',authority:'Watering completion event stream',ownership:'attributed',relationships:['plantId -> plants.id','spaceId -> spaces.id']},
 soilCheckEvents:{source:'brookes-garden-state-v2.soilCheckEvents',authority:'Soil-check event stream',ownership:'attributed',relationships:['plantId -> plants.id','spaceId -> spaces.id']},
 environmentalRecords:{source:'brookes-garden-state-v2.environmentalRecords',authority:'Saved normalized observations and forecasts',ownership:'system',relationships:[]},
 environmentalCorrections:{source:'brookes-garden-state-v2.environmentalCorrections',authority:'Manual rainfall correction events',ownership:'attributed',relationships:['supersedes_observation_id -> environmentalRecords.record_id']},
 plantingDecisions:{source:'brookes-garden-state-v2.plantingDecisions',authority:'Planting Desk decision',ownership:'shared',relationships:['packetId -> seedPackets.id','spaceId -> spaces.id']},
 shoppingItems:{source:'brookes-garden-state-v2.shoppingItems',authority:'Garden Shopping List item',ownership:'shared',relationships:['linkedPlantId -> plants.id','linkedSeedInventoryId -> seedPackets.id','intendedSpaceId -> spaces.id']},
 vacationPlans:{source:'brookes-garden-state-v2.vacationPlans',authority:'Vacation plan with nested authoritative actions',ownership:'shared',relationships:['tasks.targetId -> plant/space stable ID','tasks.linkedTaskId -> reminders/taskHistory']},
 harvests:{source:'brookes-garden-state-v2.harvests',authority:'Harvest event',ownership:'attributed',relationships:['plantId -> plants.id','spaceId -> spaces.id']},
 problems:{source:'brookes-garden-state-v2.problems',authority:'Issue/observation record',ownership:'shared',relationships:['plantId -> plants.id','spaceId -> spaces.id']},
 succession:{source:'brookes-garden-state-v2.succession',authority:'Succession planting schedule',ownership:'shared',relationships:['plantId -> plants.id']},
 photos:{source:'brookes-garden-state-v2.photos',authority:'Photo metadata and parent relationship; embedded field remains original local storage',ownership:'shared',relationships:['parentId -> parent collection']},
 attachments:{source:'brookes-garden-state-v2.attachments',authority:'Non-photo attachment metadata',ownership:'shared',relationships:['parentId -> parent collection']},
 qrLabels:{source:'brookes-garden-state-v2.qrLabels',authority:'QR label state and stable destination',ownership:'shared',relationships:['targetId -> target collection']},
 calculatorResults:{source:'brookes-garden-state-v2.calculatorResults',authority:'Saved calculator result',ownership:'shared',relationships:['appliedToSpaceId -> spaces.id','reservedPacketId -> seedPackets.id']},
 activity:{source:'brookes-garden-state-v2.activity',authority:'Append-only attributed garden activity log',ownership:'attributed',relationships:['plantId -> plants.id','spaceId -> spaces.id']},
 offlineOperations:{source:'brookes-garden-state-v2.offlineOperations',authority:'Future-sync operation queue placeholder; device-local until Phase 5',ownership:'device-local',relationships:['recordId -> collection record']},
 drafts:{source:'sessionStorage',authority:'Device-local unsaved work only',ownership:'device-local',relationships:[]},
 dailyViewCache:{source:'brookes-garden-daily-v5',authority:'Device-local task-view cache; taskHistory is authoritative',ownership:'device-local',relationships:[]},
 weatherCache:{source:'weather-specific localStorage keys',authority:'External-data cache only; not shared garden truth',ownership:'device-local',relationships:[]},
 schemaMetadata:{source:'brookes-garden-state-v2 migrationMetadata',authority:'Dataset migration state',ownership:'system',relationships:[]}
};

function statusFor(key,record){
 if(record.deletedAt)return'deleted';if(record.archivedAt||record.archived)return'archived';
 if(key==='taskHistory')return record.status==='done'?'completed':record.status||'completed';
 const explicit=text(record.status),aliases={vacationActions:{open:'active',closed:'archived',done:'completed'},reminders:{open:'active',done:'completed',hidden:'archived'},shoppingItems:{removed:'deleted',done:'purchased'},problems:{closed:'resolved'}};if(aliases[key]?.[explicit])return aliases[key][explicit];if(explicit&&STATUS_MODELS[key]?.includes(explicit))return explicit;
 if(key==='seedPackets')return number(record.quantity)<=0?'empty':'active';
 if(key==='reminders')return record.enabled===false?'completed':'active';
 if(key==='shoppingItems')return record.purchased?'purchased':record.alreadyOwned?'owned':'active';
 if(key==='problems')return'open';
 if(key==='vacationPlans')return'draft';
 if(key==='offlineOperations')return'pending';
 return explicit||'active';
}
function createdAtFor(record,fallback){return record.createdAt||record.addedAt||record.at||record.plantedAt||record.observedAt||record.harvestedAt||record.savedAt||fallback}
function normalizeRecord(key,record,index,actor,usedIds,migratedAt){
 const source={...(record||{})},prefix=prefixFor(key),candidate=text(source.id),signature=legacySignature(key,source,index);let id=candidate;
 if(!id||usedIds.has(id)){let suffix=0;do{id=`${prefix}-legacy-${integrityHash(`${signature}|${suffix}`)}`;suffix++}while(usedIds.has(id))}
 usedIds.add(id);const createdAt=createdAtFor(source,migratedAt),updatedAt=source.updatedAt||source.completedAt||source.resolvedAt||createdAt;
 return{...source,id,schemaVersion:Number(source.schemaVersion)||1,createdAt,updatedAt,createdBy:source.createdBy||source.actor||actor,updatedBy:source.updatedBy||source.actor||actor,revision:Math.max(1,Number(source.revision)||1),status:statusFor(key,source),archivedAt:source.archivedAt||(source.archived?updatedAt:null),deletedAt:source.deletedAt||null,lastValidatedAt:migratedAt};
}
function normalizeCollection(key,rows,actor,migratedAt){const used=new Set();return array(rows).map((row,index)=>normalizeRecord(key,row,index,actor,used,migratedAt))}
function seedIdentity(record){return[text(record.brand).toLowerCase(),text(record.name||record.cropName).toLowerCase(),text(record.variety).toLowerCase(),text(record.packetYear)].join('|')}
function consolidateSeedInventory(garden,actor,migratedAt){
 const packets=normalizeCollection('seedPackets',garden.seedPackets,actor,migratedAt),legacy=normalizeCollection('seedPackets',garden.seeds,actor,migratedAt),byId=new Map(packets.map(row=>[row.id,row])),byIdentity=new Map(packets.map(row=>[seedIdentity(row),row]));
 for(const row of legacy){const exact=byId.get(row.id)||byIdentity.get(seedIdentity(row));if(exact){exact.legacySourceIds=[...new Set([...(exact.legacySourceIds||[]),row.id])];for(const[key,value]of Object.entries(row))if((exact[key]===undefined||exact[key]===null||exact[key]==='')&&value!==undefined&&value!==null&&value!=='')exact[key]=value;continue}const migrated={...row,source:row.source||'Legacy Seed Catalog',legacyMigrated:true};packets.push(migrated);byId.set(migrated.id,migrated);byIdentity.set(seedIdentity(migrated),migrated)}
 return packets;
}
function normalizeStageHistory(plant,actor,migratedAt){const used=new Set();return array(plant.stageHistory).map((event,index)=>normalizeRecord('lifecycleEvents',{...event,plantId:plant.id,status:event.status||'completed'},index,actor,used,migratedAt))}
function normalizeVacationTasks(plan,actor,migratedAt){const used=new Set();return array(plan.tasks).map((task,index)=>normalizeRecord('vacationActions',{...task,vacationPlanId:plan.id,status:task.status||'active'},index,actor,used,migratedAt))}
function mimeFromDataUrl(value){const match=String(value||'').match(/^data:([^;,]+)/);return match?.[1]||'image/jpeg'}
function dataSize(value){return typeof value==='string'?Math.ceil(value.length*0.75):0}
const photoParents={spaces:['photo'],plants:['photo'],seedPackets:['photo','frontPhoto','backPhoto'],trays:['photo'],hydroPods:['photo'],harvests:['photo'],problems:['photo'],activity:['photo']};
function buildPhotoManifest(garden,actor,migratedAt){
 const existing=normalizeCollection('photos',garden.photos,actor,migratedAt),byRef=new Map(existing.map(row=>[row.storageReference,row])),add=(parentType,parentId,role,value,createdAt=migratedAt)=>{if(!value||typeof value!=='string')return;const storageReference=`embedded:${parentType}:${parentId}:${role}`;if(byRef.has(storageReference))return;const used=new Set(existing.map(item=>item.id)),row=normalizeRecord('photos',{id:`photo-${integrityHash(storageReference)}`,parentType,parentId,role,storageReference,contentHash:integrityHash(value),fileType:mimeFromDataUrl(value),sizeBytes:dataSize(value),embedded:true,thumbnailStrategy:'use embedded image at display size',migrationStatus:'pending-cloud-upload',source:'Local embedded image',status:'active',createdAt},existing.length,actor,used,migratedAt);existing.push(row);byRef.set(storageReference,row)};
 for(const[collection,fields]of Object.entries(photoParents))for(const parent of array(garden[collection]))for(const field of fields)add(collection,parent.id,field,parent?.[field],parent?.createdAt||migratedAt);
 for(const plant of array(garden.plants))for(const event of array(plant.stageHistory))array(event.photos).forEach((value,index)=>add('plants',plant.id,`lifecycle:${event.id}:${index}`,value,event.enteredAt||event.createdAt||migratedAt));
 return existing;
}
function seedTransactionsFromUsage(garden,actor,migratedAt){
 const transactions=normalizeCollection('seedTransactions',garden.seedTransactions,actor,migratedAt),seen=new Set(transactions.map(row=>row.operationId||row.id));
 for(const usage of array(garden.seedUsage)){const operationId=usage.operationId||`seed-use:${usage.id}`;if(seen.has(operationId))continue;transactions.push(normalizeRecord('seedTransactions',{id:`seed-tx-${integrityHash(operationId)}`,operationId,type:'planted',packetId:usage.packetId||'',plantId:usage.plantId||'',quantity:-Math.abs(number(usage.quantity)),countType:usage.countType||'estimated',occurredAt:usage.at||usage.createdAt||migratedAt,note:usage.note||'',source:'Seed usage migration',actor:usage.actor||actor,status:'completed'},transactions.length,actor,new Set(transactions.map(row=>row.id)),migratedAt));seen.add(operationId)}
 return transactions;
}

function eventStreamsFromPlantProjections(garden,actor,migratedAt){
 const watering=normalizeCollection('wateringEvents',garden.wateringEvents,actor,migratedAt),soil=normalizeCollection('soilCheckEvents',garden.soilCheckEvents,actor,migratedAt),wateringOps=new Set(watering.map(row=>row.operationId)),soilOps=new Set(soil.map(row=>row.operationId));
 for(const plant of array(garden.plants)){
  if(plant.lastWatered){const operationId=`legacy-watering:${plant.id}:${plant.lastWatered}`;if(!wateringOps.has(operationId)){watering.push(normalizeRecord('wateringEvents',{id:`watering-${integrityHash(operationId)}`,operationId,plantId:plant.id,spaceId:plant.spaceId||'',completedAt:plant.lastWatered,method:'Legacy plant record',status:'completed',source:'Projection migration'},watering.length,actor,new Set(watering.map(row=>row.id)),migratedAt));wateringOps.add(operationId)}}
  if(plant.lastSoilCheck){const operationId=`legacy-soil:${plant.id}:${plant.lastSoilCheck}:${plant.moisture||'unknown'}`;if(!soilOps.has(operationId)){soil.push(normalizeRecord('soilCheckEvents',{id:`soil-check-${integrityHash(operationId)}`,operationId,plantId:plant.id,spaceId:plant.spaceId||'',checkedAt:plant.lastSoilCheck,result:plant.moisture||'unknown',status:'completed',source:'Projection migration'},soil.length,actor,new Set(soil.map(row=>row.id)),migratedAt));soilOps.add(operationId)}}
 }
 return{watering,soil};
}

function migrationEntry(from,to,at,status='completed',details=''){return{id:`migration-${from}-${to}`,fromVersion:from,toVersion:to,startedAt:at,completedAt:status==='completed'?at:null,status,details,operationId:`schema-migration:${from}:${to}`}}

export function migrateGardenDataset(input={},options={}){
 const migratedAt=options.now||input.migrationMetadata?.lastMigrationAt||input.updatedAt||nowIso(),actor=input.profile?.gardenerName||options.actor||'System',fromVersion=Number(input.schemaVersion)||Number(input.version)||10,garden=repairKnownMojibakeText(clone(input||{}));
 const packets=consolidateSeedInventory(garden,actor,migratedAt),prepared={...garden,seedPackets:packets,seeds:[],seedUsage:normalizeCollection('seedUsage',garden.seedUsage,actor,migratedAt)};
 const collectionKeys=['spaces','plants','activity','harvests','problems','succession','trays','growLights','hardeningPlans','hydroPods','greenhouseReadings','reminders','taskHistory','plantingDecisions','shoppingItems','weatherRecommendationHistory','vacationPlans','calculatorResults','environmentalRecords','environmentalCorrections','wateringEvents','soilCheckEvents','attachments','qrLabels','offlineOperations'];
 for(const key of collectionKeys)prepared[key]=normalizeCollection(key,garden[key],actor,migratedAt);
 prepared.plants=prepared.plants.map(plant=>({...plant,stageHistory:normalizeStageHistory(plant,actor,migratedAt)}));
 prepared.vacationPlans=prepared.vacationPlans.map(plan=>({...plan,tasks:normalizeVacationTasks(plan,actor,migratedAt)}));
 const projectedEvents=eventStreamsFromPlantProjections({...garden,plants:prepared.plants},actor,migratedAt);prepared.wateringEvents=projectedEvents.watering;prepared.soilCheckEvents=projectedEvents.soil;
 prepared.seedTransactions=seedTransactionsFromUsage({...garden,seedUsage:prepared.seedUsage},actor,migratedAt);
 prepared.seedPackets=prepared.seedPackets.map(packet=>{const used=prepared.seedTransactions.filter(row=>row.packetId===packet.id&&['planted','used'].includes(row.type)&&!row.deletedAt).reduce((sum,row)=>sum+Math.abs(number(row.quantity)),0);return{...packet,originalQuantity:packet.originalQuantity??(number(packet.quantity)+used),reservedQuantity:Math.max(0,number(packet.reservedQuantity))}});
 prepared.photos=buildPhotoManifest({...prepared,seedPackets:prepared.seedPackets},actor,migratedAt);
 const prior=array(garden.migrationHistory),already=prior.some(row=>row.operationId===`schema-migration:${fromVersion}:${DATASET_SCHEMA_VERSION}`&&row.status==='completed'),history=fromVersion<DATASET_SCHEMA_VERSION&&!already?[...prior,migrationEntry(fromVersion,DATASET_SCHEMA_VERSION,migratedAt,'completed','Stable IDs, authoritative seed inventory, photo manifest, event streams, and sync metadata prepared.')]:prior;
 return{...prepared,schemaVersion:DATASET_SCHEMA_VERSION,dataReadinessVersion:DATA_READINESS_VERSION,updatedAt:garden.updatedAt||migratedAt,migrationHistory:history,migrationMetadata:{currentVersion:DATASET_SCHEMA_VERSION,lastMigrationAt:history.at(-1)?.completedAt||garden.migrationMetadata?.lastMigrationAt||null,lastMigrationStatus:history.at(-1)?.status||'not-required',rollbackProtected:true,sourcePreserved:true,legacySeedCollectionMigrated:true},storageMetadata:{gardenKey:'brookes-garden-state-v2',dailyCacheKey:'brookes-garden-daily-v5',activeProfileKey:'runyan-garden-active-profile',packetDraftKey:'runyan-seed-packet-draft-v1',timezone:GARDEN_TIMEZONE}};
}

const idSet=(garden,key)=>new Set(array(garden[key]).filter(row=>!row.deletedAt).map(row=>row.id));
function relationshipIssues(garden){
 const issues=[],spaces=idSet(garden,'spaces'),plants=idSet(garden,'plants'),packets=idSet(garden,'seedPackets'),reminders=idSet(garden,'reminders'),taskHistory=idSet(garden,'taskHistory');
 const check=(collection,row,field,targetSet,targetType,{optional=true}={})=>{const value=row?.[field];if(!value){if(!optional)issues.push({severity:'high',type:'missing-link',collection,id:row.id,field,targetType});return}if(!targetSet.has(value))issues.push({severity:'medium',type:'orphan-link',collection,id:row.id,field,value,targetType})};
 for(const row of array(garden.plants)){check('plants',row,'spaceId',spaces,'spaces');check('plants',row,'sourcePacketId',packets,'seedPackets')}
 for(const row of array(garden.harvests)){check('harvests',row,'plantId',plants,'plants',{optional:false});check('harvests',row,'spaceId',spaces,'spaces')}
 for(const row of array(garden.problems)){check('problems',row,'plantId',plants,'plants');check('problems',row,'spaceId',spaces,'spaces')}
 for(const row of array(garden.seedUsage)){check('seedUsage',row,'packetId',packets,'seedPackets',{optional:false});check('seedUsage',row,'plantId',plants,'plants')}
 for(const row of array(garden.seedTransactions)){check('seedTransactions',row,'packetId',packets,'seedPackets',{optional:false});check('seedTransactions',row,'plantId',plants,'plants')}
 for(const row of array(garden.trays)){check('trays',row,'packetId',packets,'seedPackets');check('trays',row,'sourcePacketId',packets,'seedPackets');check('trays',row,'plantId',plants,'plants')}
 for(const row of array(garden.hardeningPlans))check('hardeningPlans',row,'plantId',plants,'plants',{optional:false});
 for(const row of array(garden.reminders)){check('reminders',row,'plantId',plants,'plants');check('reminders',row,'spaceId',spaces,'spaces')}
 for(const row of array(garden.taskHistory)){check('taskHistory',row,'plantId',plants,'plants');check('taskHistory',row,'spaceId',spaces,'spaces')}
 for(const row of array(garden.shoppingItems)){check('shoppingItems',row,'linkedPlantId',plants,'plants');check('shoppingItems',row,'linkedSeedInventoryId',packets,'seedPackets');check('shoppingItems',row,'intendedSpaceId',spaces,'spaces')}
 for(const plan of array(garden.vacationPlans))for(const task of array(plan.tasks)){if(task.targetType==='plant')check('vacationActions',task,'targetId',plants,'plants',{optional:false});if(task.targetType==='space')check('vacationActions',task,'targetId',spaces,'spaces',{optional:false});if(task.linkedTaskId&&!reminders.has(task.linkedTaskId)&&!taskHistory.has(task.linkedTaskId))issues.push({severity:'low',type:'unresolved-task-link',collection:'vacationActions',id:task.id,field:'linkedTaskId',value:task.linkedTaskId})}
 const parentSets={spaces,plants,seedPackets:packets,trays:idSet(garden,'trays'),hydroPods:idSet(garden,'hydroPods'),harvests:idSet(garden,'harvests'),problems:idSet(garden,'problems'),activity:idSet(garden,'activity')};
 for(const photo of array(garden.photos)){const set=parentSets[photo.parentType];if(!set||!set.has(photo.parentId))issues.push({severity:'medium',type:'orphan-photo',collection:'photos',id:photo.id,parentType:photo.parentType,parentId:photo.parentId})}
 for(const label of array(garden.qrLabels)){const set=parentSets[label.targetType==='space'?'spaces':label.targetType==='plant'?'plants':label.targetType==='tray'?'trays':label.targetType==='pod'?'hydroPods':label.targetType];if(label.targetId&&(!set||!set.has(label.targetId)))issues.push({severity:'medium',type:'dangling-qr',collection:'qrLabels',id:label.id,targetType:label.targetType,targetId:label.targetId})}
 return issues;
}
function duplicateIdIssues(garden){const issues=[];for(const key of Object.keys(COLLECTION_DEFINITIONS)){if(!Array.isArray(garden[key]))continue;const seen=new Set();for(const row of garden[key]){if(!row.id){issues.push({severity:'high',type:'missing-id',collection:key});continue}if(seen.has(row.id))issues.push({severity:'high',type:'duplicate-id',collection:key,id:row.id});seen.add(row.id)}}return issues}
function metadataIssues(garden){const issues=[];for(const key of Object.keys(COLLECTION_DEFINITIONS)){if(!Array.isArray(garden[key]))continue;for(const row of garden[key]){if(!row.createdAt||!row.updatedAt)issues.push({severity:'medium',type:'missing-timestamp',collection:key,id:row.id});if(!row.createdBy||!row.updatedBy)issues.push({severity:'low',type:'missing-attribution',collection:key,id:row.id});const allowed=STATUS_MODELS[key];if(allowed&&!allowed.includes(row.status))issues.push({severity:'medium',type:'invalid-status',collection:key,id:row.id,status:row.status})}}return issues}
export function validateGardenData(input={}){const garden=migrateGardenDataset(input),issues=[...duplicateIdIssues(garden),...relationshipIssues(garden),...metadataIssues(garden)],high=issues.filter(row=>row.severity==='high').length,medium=issues.filter(row=>row.severity==='medium').length;return{ok:high===0,ready:high===0&&medium===0,schemaVersion:garden.schemaVersion,issues,counts:Object.fromEntries(Object.keys(COLLECTION_DEFINITIONS).filter(key=>Array.isArray(garden[key])).map(key=>[key,garden[key].length])),summary:{high,medium,low:issues.length-high-medium,total:issues.length},garden}}

export function createOperation({recordType,recordId,action,payload={},createdBy='System',deviceId='device-local',baseVersion=0,operationId}={}){const at=nowIso(),id=operationId||`op-${integrityHash(stableStringify({recordType,recordId,action,payload,createdBy,deviceId,at:at.slice(0,19)}))}`;return{operationId:id,id,recordType,recordId,action,payload,createdAt:at,createdBy,deviceId,baseVersion:Number(baseVersion)||0,retryCount:0,status:'pending',lastError:null}}
export function enqueueOperation(queue=[],operation){return array(queue).some(row=>row.operationId===operation.operationId)?array(queue):[...array(queue),operation]}
export function markOperation(queue=[],operationId,status,lastError=null){return array(queue).map(row=>row.operationId===operationId?{...row,status,lastError,retryCount:status==='failed'?Number(row.retryCount||0)+1:row.retryCount,updatedAt:nowIso()}:row)}

export const ROLE_POLICY={owner:{view:true,edit:true,completeTasks:true,manageInventory:true,manageVacation:true,manageSettings:true,delete:true,purge:true,manageMembers:true},householdMember:{view:true,edit:true,completeTasks:true,manageInventory:true,manageVacation:true,manageSettings:false,delete:true,purge:false,manageMembers:false},caretaker:{view:true,edit:false,completeTasks:'assigned-vacation-only',manageInventory:false,manageVacation:false,manageSettings:false,delete:false,purge:false,manageMembers:false,addCompletionNotes:true},readOnlyGuest:{view:true,edit:false,completeTasks:false,manageInventory:false,manageVacation:false,manageSettings:false,delete:false,purge:false,manageMembers:false}};

export const CONFLICT_POLICIES={taskCompletion:'Completed wins over an older active copy. Deduplicate the same operation ID and preserve who completed it and when.',notes:'Newest confirmed revision wins; preserve prior revision in activity or revision history where the workflow supports it.',photos:'Preserve different content hashes. Deduplicate an exact repeated upload. A delete marker applies only to that photo ID.',seedQuantity:'Reconcile append-only seed transactions. Never replace quantity from a stale snapshot; flag negative or impossible results.',shoppingItems:'Merge exact duplicate keys. Purchased and already-owned states cannot be silently reverted by an older edit. Preserve quantity changes and source links.',vacationPlan:'One stable plan ID. Date changes trigger recalculation; manually edited instructions and completed/canceled actions survive regeneration.',vacationAction:'Completed or canceled wins over stale active state. Preserve manual assignment and instruction changes.',plantName:'Newest valid name wins while all relationships remain attached to the stable plant ID.',deletionVsEdit:'A deletion marker wins over an older edit. A newer edit against a deleted record becomes a recovery conflict; never silently resurrect.',harvests:'Distinct events remain. Retry with the same operation ID or duplicate key is ignored.',watering:'Distinct events remain. Retry with the same operation ID is ignored; stale plant projections cannot erase newer events.',plantJourney:'Union lifecycle events by stable event ID or operation ID, sort chronologically, and keep the newest valid plant projection.',rainfall:'Observed and corrected rainfall remain events. Forecast rain never becomes a completion event.'};

const newer=(a,b)=>String(a?.updatedAt||a?.createdAt||'').localeCompare(String(b?.updatedAt||b?.createdAt||''))>=0?a:b;
function mergeById(a=[],b=[],policy,keyFor=row=>row.id){const map=new Map();for(const row of [...array(a),...array(b)]){const key=keyFor(row)||row.id,current=map.get(key);if(!current){map.set(key,clone(row));continue}map.set(key,policy?policy(current,row):newer(current,row))}return[...map.values()]}
function mergeTaskCompletion(a,b){if(a.deletedAt||b.deletedAt)return newer(a,b);const completed=row=>['completed','done'].includes(row.status)||Boolean(row.completedAt);if(completed(a)&&!completed(b))return a;if(completed(b)&&!completed(a))return b;return newer(a,b)}
function mergeShopping(a,b){if(a.deletedAt||b.deletedAt)return newer(a,b);const row=newer(a,b);return{...row,quantity:Math.max(number(a.quantity),number(b.quantity)),purchased:Boolean(a.purchased||b.purchased),alreadyOwned:Boolean(a.alreadyOwned||b.alreadyOwned),status:a.purchased||b.purchased?'purchased':a.alreadyOwned||b.alreadyOwned?'owned':row.status}}
function mergeVacationPlan(a,b){if(a.deletedAt||b.deletedAt)return newer(a,b);const row=newer(a,b),tasks=mergeById(a.tasks,b.tasks,(left,right)=>{if(left.status==='completed'||right.status==='completed')return{...newer(left,right),status:'completed',completedAt:left.completedAt||right.completedAt,completedBy:left.completedBy||right.completedBy};if(left.manualEdited&&!right.manualEdited)return left;if(right.manualEdited&&!left.manualEdited)return right;return newer(left,right)});return{...row,tasks}}
function mergePlant(a,b){if(a.deletedAt||b.deletedAt)return newer(a,b);const row=newer(a,b),history=mergeById(a.stageHistory,b.stageHistory,mergeTaskCompletion).sort((x,y)=>String(x.enteredAt||x.createdAt).localeCompare(String(y.enteredAt||y.createdAt)));return{...row,stageHistory:history}}
function mergePhoto(a,b){if(a.deletedAt||b.deletedAt)return newer(a,b);return newer(a,b)}
export function mergeSharedGardenStates(leftInput,rightInput){const left=migrateGardenDataset(leftInput),right=migrateGardenDataset(rightInput),merged={...left,...right,profile:{...left.profile,...right.profile}};const keys=new Set([...Object.keys(COLLECTION_DEFINITIONS).filter(key=>Array.isArray(left[key])||Array.isArray(right[key]))]);for(const key of keys){let policy,keyFor=row=>row.id;if(key==='taskHistory'||key==='wateringEvents'||key==='soilCheckEvents'){policy=mergeTaskCompletion;keyFor=row=>row.operationId||row.id}else if(key==='shoppingItems')policy=mergeShopping;else if(key==='vacationPlans')policy=mergeVacationPlan;else if(key==='plants')policy=mergePlant;else if(key==='photos'){policy=mergePhoto;keyFor=row=>row.contentHash?`${row.parentType}|${row.parentId}|${row.contentHash}`:row.id}else if(key==='seedTransactions'||key==='offlineOperations')keyFor=row=>row.operationId||row.id;merged[key]=mergeById(left[key],right[key],policy,keyFor)}return migrateGardenDataset(merged)}

export function reconcileSeedQuantity(packet,transactions=[]){const starting=number(packet.originalQuantity??packet.quantity),relevant=array(transactions).filter(row=>row.packetId===packet.id&&!row.deletedAt&&row.status!=='canceled'&&!['reserved','reservation-released'].includes(row.type)),seen=new Set(),accepted=[],duplicates=[];let delta=0;for(const tx of relevant){const key=tx.operationId||tx.id;if(seen.has(key)){duplicates.push(tx);continue}seen.add(key);delta+=number(tx.quantity);accepted.push(tx)}const available=starting+delta;return{packetId:packet.id,starting,delta,available,valid:available>=0,accepted,duplicates,warning:available<0?'Seed transactions exceed the packet quantity. Review the conflicting operations.':''}}
export function applySeedTransaction(gardenInput,transaction){const garden=migrateGardenDataset(gardenInput),operation=transaction.operationId?transaction:{...transaction,operationId:`seed:${integrityHash(stableStringify(transaction))}`};if(garden.seedTransactions.some(row=>row.operationId===operation.operationId))return{garden,applied:false,reason:'duplicate-operation'};const row=normalizeRecord('seedTransactions',{...operation,status:'completed',occurredAt:operation.occurredAt||nowIso()},garden.seedTransactions.length,operation.actor||garden.profile?.gardenerName||'System',new Set(garden.seedTransactions.map(item=>item.id)),nowIso()),transactions=[row,...garden.seedTransactions],packet=garden.seedPackets.find(item=>item.id===row.packetId);if(!packet)return{garden,applied:false,reason:'missing-packet'};if(row.type==='reserved'||row.type==='reservation-released'){const requested=Math.abs(number(row.quantity)),currentReserved=Math.max(0,number(packet.reservedQuantity)),reserved=row.type==='reserved'?Math.min(number(packet.quantity),currentReserved+requested):Math.max(0,currentReserved-requested),available=Math.max(0,number(packet.quantity)-reserved),seedPackets=garden.seedPackets.map(item=>item.id===row.packetId?{...item,reservedQuantity:reserved,updatedAt:row.occurredAt,updatedBy:row.actor||row.createdBy,revision:Number(item.revision||1)+1}:item);return{garden:{...garden,seedTransactions:transactions,seedPackets},applied:true,reconciliation:{packetId:packet.id,available,reserved,valid:true}}}const reconciliation=reconcileSeedQuantity(packet,transactions);if(!reconciliation.valid)return{garden,applied:false,reason:'invalid-quantity',reconciliation};const seedPackets=garden.seedPackets.map(item=>item.id===row.packetId?{...item,quantity:reconciliation.available,status:reconciliation.available===0?'empty':item.status==='empty'?'active':item.status,updatedAt:row.occurredAt,updatedBy:row.actor||row.createdBy,revision:Number(item.revision||1)+1}:item);return{garden:{...garden,seedTransactions:transactions,seedPackets},applied:true,reconciliation}}

export function buildGardenBackup(input){const garden=migrateGardenDataset(input),health=validateGardenData(garden),exportedAt=nowIso(),manifest={app:'The Runyan Garden',exportVersion:BACKUP_EXPORT_VERSION,schemaVersion:DATASET_SCHEMA_VERSION,dataReadinessVersion:DATA_READINESS_VERSION,exportedAt,timezone:GARDEN_TIMEZONE,photoHandling:{mode:'embedded-and-manifested',description:'Original embedded local images are included inside their parent records. The photos collection stores stable metadata and parent references.',count:garden.photos.length},recordCounts:health.counts};const checksum=integrityHash({manifest,garden});return{manifest,checksum,garden}}
export function validateGardenBackup(payload){try{if(!payload||typeof payload!=='object')throw new Error('Backup is not an object.');if(!payload.manifest||!payload.garden||!payload.checksum)throw new Error('Backup is missing its manifest, garden data, or integrity value.');if(Number(payload.manifest.exportVersion)>BACKUP_EXPORT_VERSION)throw new Error('This backup was created by a newer unsupported export format.');const expected=integrityHash({manifest:payload.manifest,garden:payload.garden});if(expected!==payload.checksum)throw new Error('Backup integrity check failed. The file may be incomplete or changed.');const health=validateGardenData(payload.garden),counts=payload.manifest.recordCounts||{};for(const[key,value]of Object.entries(counts))if(Number(value)!==Number(health.counts[key]||0))throw new Error(`Backup record count mismatch for ${key}.`);return{ok:health.ok,health,garden:health.garden,photoHandling:payload.manifest.photoHandling}}catch(error){return{ok:false,error,message:error.message||'Backup validation failed.'}}}
export function restoreGardenBackupToIsolated(payload){const validation=validateGardenBackup(payload);if(!validation.ok)return{ok:false,...validation};const restored=migrateGardenDataset(clone(validation.garden)),restoredHealth=validateGardenData(restored);return{ok:restoredHealth.ok,garden:restored,health:restoredHealth,equivalent:integrityHash(restored)===integrityHash(validation.garden),sourceUntouched:true}}
export function downloadGardenBackup(garden){const payload=buildGardenBackup(garden),validation=validateGardenBackup(payload);if(!validation.ok)return validation;const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`runyan-garden-backup-v${BACKUP_EXPORT_VERSION}-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);return{ok:true,payload,validation}}

const TABLE_MAP={spaces:'growing_spaces',plants:'plants',seedPackets:'seed_packets',seedTransactions:'seed_transactions',trays:'indoor_projects',growLights:'grow_lights',hardeningPlans:'hardening_plans',hydroPods:'hydro_pods',greenhouseReadings:'greenhouse_readings',reminders:'tasks',taskHistory:'task_completions',wateringEvents:'watering_events',soilCheckEvents:'soil_check_events',shoppingItems:'shopping_items',vacationPlans:'vacation_plans',harvests:'harvests',problems:'garden_records',photos:'photos',attachments:'attachments',activity:'activity_log',calculatorResults:'calculator_results',plantingDecisions:'planting_decisions',environmentalCorrections:'rainfall_corrections'};
function upsertRows(target,key,rows){const table=target[key]||[],map=new Map(table.map(row=>[row.id,row]));for(const row of rows)map.set(row.id,clone(row));target[key]=[...map.values()]}
export function migrateToMockCloud(input,target={}){const garden=migrateGardenDataset(input),cloud=clone(target);cloud.households=cloud.households||[{id:'household-runyan',name:garden.profile?.gardenName||'The Runyan Garden',createdAt:garden.createdAt||garden.updatedAt}];cloud.household_members=cloud.household_members||[{id:'member-archie',householdId:'household-runyan',displayName:'Archie',role:'owner'},{id:'member-brooke',householdId:'household-runyan',displayName:'Brooke',role:'owner'}];cloud.gardens=cloud.gardens||[{id:'garden-runyan',householdId:'household-runyan',name:garden.profile?.gardenName||'The Runyan Garden',timezone:GARDEN_TIMEZONE,schemaVersion:garden.schemaVersion}];for(const[source,table]of Object.entries(TABLE_MAP)){let rows=array(garden[source]);if(source==='vacationPlans'){upsertRows(cloud,table,rows.map(({tasks,...plan})=>plan));upsertRows(cloud,'vacation_actions',rows.flatMap(plan=>array(plan.tasks).map(task=>({...task,vacationPlanId:plan.id}))));continue}if(source==='plants'){upsertRows(cloud,table,rows.map(({stageHistory,...plant})=>plant));upsertRows(cloud,'lifecycle_events',rows.flatMap(plant=>array(plant.stageHistory).map(event=>({...event,plantId:plant.id}))));continue}upsertRows(cloud,table,rows)}cloud.migration_metadata={operationId:'phase-4-6x-mock-migration',sourceSchemaVersion:garden.schemaVersion,completedAt:garden.migrationMetadata?.lastMigrationAt||garden.updatedAt,status:'completed'};return cloud}
export function validateMockMigration(input,cloud){const garden=migrateGardenDataset(input),results=[];for(const[source,table]of Object.entries(TABLE_MAP)){const expected=source==='vacationPlans'?garden.vacationPlans.length:source==='plants'?garden.plants.length:array(garden[source]).length,actual=array(cloud[table]).length;results.push({recordType:source,table,expected,actual,status:expected===actual?'ready':'blocked'})}const actionExpected=garden.vacationPlans.flatMap(plan=>array(plan.tasks)).length,lifecycleExpected=garden.plants.flatMap(plant=>array(plant.stageHistory)).length;results.push({recordType:'vacationActions',table:'vacation_actions',expected:actionExpected,actual:array(cloud.vacation_actions).length,status:actionExpected===array(cloud.vacation_actions).length?'ready':'blocked'},{recordType:'lifecycleEvents',table:'lifecycle_events',expected:lifecycleExpected,actual:array(cloud.lifecycle_events).length,status:lifecycleExpected===array(cloud.lifecycle_events).length?'ready':'blocked'});return{ok:results.every(row=>row.status!=='blocked'),results}}
export function rehearseMigration(input){const source=migrateGardenDataset(input),backup=buildGardenBackup(source),backupValidation=validateGardenBackup(backup);if(!backupValidation.ok)return{ok:false,stage:'backup',backupValidation};const isolated=restoreGardenBackupToIsolated(backup);if(!isolated.ok)return{ok:false,stage:'restore',isolated};const first=migrateToMockCloud(isolated.garden),firstValidation=validateMockMigration(isolated.garden,first),second=migrateToMockCloud(isolated.garden,first),secondValidation=validateMockMigration(isolated.garden,second),idempotent=integrityHash(first)===integrityHash(second),partial=clone(first);if(array(partial.growing_spaces).length)partial.growing_spaces=partial.growing_spaces.slice(1);else if(array(partial.plants).length)partial.plants=partial.plants.slice(1);const retry=migrateToMockCloud(isolated.garden,partial),retryValidation=validateMockMigration(isolated.garden,retry),rollback=restoreGardenBackupToIsolated(backup);return{ok:backupValidation.ok&&isolated.ok&&firstValidation.ok&&secondValidation.ok&&idempotent&&retryValidation.ok&&rollback.ok,backupValidation,restore:isolated,firstValidation,secondValidation,idempotent,interrupted:{detected:!validateMockMigration(isolated.garden,partial).ok,retryOk:retryValidation.ok},rollback:{ok:rollback.ok,sourcePreserved:true,targetDiscardable:true},cloud:first}}

export function runSharedWorkflowSimulation(input){
 const base=migrateGardenDataset(input),archie=clone(base),brooke=clone(base),actorA='Archie',actorB='Brooke',at=nowIso();
 const task=archie.reminders[0]||normalizeRecord('reminders',{id:'simulation-task',taskId:'simulation-task',title:'Check soil',taskType:'Check Moisture',dueDate:at.slice(0,10),enabled:true},0,actorA,new Set(),at);if(!archie.reminders.some(row=>row.id===task.id))archie.reminders.push(task);if(!brooke.reminders.some(row=>row.id===task.id))brooke.reminders.push(clone(task));
 const completion={id:'simulation-completion',operationId:`task:${task.id}:${task.dueDate}:completed`,taskId:task.id,title:task.title,status:'completed',completedAt:at,createdAt:at,updatedAt:at,createdBy:actorA,updatedBy:actorA,revision:1};archie.taskHistory.push(completion);brooke.taskHistory.push({...completion,id:'simulation-completion-retry',createdBy:actorB,updatedBy:actorB});
 const packet=base.seedPackets[0];if(packet){const reserve={id:'sim-reserve',operationId:'sim-seed-reserve',packetId:packet.id,type:'reserved',quantity:-1,actor:actorB,status:'completed',createdAt:at,updatedAt:at};archie.seedTransactions.push(reserve);brooke.seedTransactions.push(clone(reserve))}
 const merged=mergeSharedGardenStates(archie,brooke),completionCount=merged.taskHistory.filter(row=>row.operationId===completion.operationId).length,seedRetryCount=packet?merged.seedTransactions.filter(row=>row.operationId==='sim-seed-reserve').length:0,health=validateGardenData(merged);return{ok:completionCount===1&&seedRetryCount<2&&health.ok,completionCount,seedRetryCount,health,merged,policies:CONFLICT_POLICIES,roles:ROLE_POLICY}}

export function readinessDecision(input){const garden=migrateGardenDataset(input),health=validateGardenData(garden),simulation=runSharedWorkflowSimulation(garden),rehearsal=rehearseMigration(garden),blockers=[];if(!health.ok)blockers.push('High-severity local data integrity issues remain.');if(!simulation.ok)blockers.push('Shared workflow simulation did not preserve one authoritative result.');if(!rehearsal.ok)blockers.push('Backup, restore, migration retry, or rollback rehearsal failed.');return{decision:blockers.length?'NOT READY FOR PHASE 5.0':'READY FOR PHASE 5.0',blockers,health,simulation,rehearsal}}
