import React,{useMemo,useState}from'react';
import{AlertTriangle,Archive,Camera,CheckCircle2,Clock3,History,Leaf,Sprout,Trash2,X}from'lucide-react';
import{buildPlantJourneyEvents,createStageHistoryEntry,normalizeLifecycleStage,normalizeStageHistory,PLANT_LIFECYCLE_STAGES}from'./gardenIntelligence.js';
import{formatDateTime}from'./data.js';

const fileToDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});

export default function GardenControls({modal,garden,close,savePlant,archivePlant,deletePlant,saveHarvest,saveProblem}){
 const plant=garden.plants.find(item=>item.id===modal.plant?.id)||modal.plant;if(!plant)return null;
 const[view,setView]=useState(modal.view||'plant');
 const[draft,setDraft]=useState({...plant,stage:normalizeLifecycleStage(plant.stage),stageHistory:normalizeStageHistory(plant,garden.profile?.gardenerName)});
 const[stageNote,setStageNote]=useState(''),[stagePhoto,setStagePhoto]=useState('');
 const[harvest,setHarvest]=useState({amount:1,unit:'count',quality:'Good',note:'',growAgain:'yes'});
 const[problem,setProblem]=useState({type:'Pest spotted',severity:'Keep watching',note:''});
 const journey=useMemo(()=>buildPlantJourneyEvents({plant:draft,activity:garden.activity||[],harvests:garden.harvests||[],problems:garden.problems||[]}),[draft,garden.activity,garden.harvests,garden.problems]);
 const save=event=>{event.preventDefault();const previous=normalizeLifecycleStage(plant.stage),next=normalizeLifecycleStage(draft.stage);let stageHistory=normalizeStageHistory(draft,garden.profile?.gardenerName);if(next!==previous){stageHistory=[...stageHistory,createStageHistoryEntry({stage:next,notes:stageNote,photos:stagePhoto?[stagePhoto]:[],actor:garden.profile?.gardenerName})]}savePlant(plant.id,{...draft,stage:next,stageHistory,stageUpdatedAt:next!==previous?new Date().toISOString():draft.stageUpdatedAt});close()};
 const addStagePhoto=async file=>{if(!file)return;if(file.size>1800000)return window.alert('Choose a photo smaller than about 1.8 MB.');setStagePhoto(await fileToDataUrl(file))};
 const submitHarvest=event=>{event.preventDefault();saveHarvest(plant.id,harvest);close()};
 const submitProblem=event=>{event.preventDefault();saveProblem(plant.id,problem);close()};
 return <div className="overlay modal-overlay" onMouseDown={close}><section className="detail-modal control-modal plant-journey-modal" onMouseDown={event=>event.stopPropagation()}>
  <button className="modal-close" onClick={close} aria-label="Close"><X/></button><span className="modal-kicker">PLANT CONTROL CENTER</span><h2>{plant.name}</h2>
  <div className="control-tabs"><button className={view==='plant'?'active':''} onClick={()=>setView('plant')}>Details</button><button className={view==='journey'?'active':''} onClick={()=>setView('journey')}>Journey</button><button className={view==='harvest'?'active':''} onClick={()=>setView('harvest')}>Harvest</button><button className={view==='problem'?'active':''} onClick={()=>setView('problem')}>Problem</button></div>
  {view==='plant'&&<form className="modal-form" onSubmit={save}><label>Plant name or identifier<input value={draft.name||''} onChange={event=>setDraft({...draft,name:event.target.value})} required/></label><label>Variety<input value={draft.variety||''} onChange={event=>setDraft({...draft,variety:event.target.value})}/></label><div className="two-field-row"><label>Quantity<input type="number" min="1" value={draft.quantity||1} onChange={event=>setDraft({...draft,quantity:Number(event.target.value)})}/></label><label>Started<input type="date" value={draft.plantedAt||''} onChange={event=>setDraft({...draft,plantedAt:event.target.value})}/></label></div><label>Plant location<select value={draft.spaceId||''} onChange={event=>setDraft({...draft,spaceId:event.target.value})}>{garden.spaces.filter(space=>!space.deletedAt).map(space=><option key={space.id} value={space.id}>{space.name}{space.hidden?' (hidden)':''}</option>)}</select><small className="field-help">Every plant remains linked to one exact growing space.</small></label><label>Current lifecycle stage<select value={draft.stage||'Established'} onChange={event=>setDraft({...draft,stage:event.target.value})}>{PLANT_LIFECYCLE_STAGES.map(stage=><option key={stage}>{stage}</option>)}</select></label>{normalizeLifecycleStage(draft.stage)!==normalizeLifecycleStage(plant.stage)&&<section className="stage-change-fields"><label>Stage note<textarea value={stageNote} onChange={event=>setStageNote(event.target.value)} placeholder="What changed when this plant entered the new stage?"/></label><label className="photo-upload-button"><Camera/>{stagePhoto?'Replace stage photo':'Add optional stage photo'}<input type="file" accept="image/*" capture="environment" onChange={event=>addStagePhoto(event.target.files?.[0])}/></label>{stagePhoto&&<img className="stage-photo-preview" src={stagePhoto} alt="New lifecycle stage"/>}</section>}<label>Private notes<textarea value={draft.notes||''} onChange={event=>setDraft({...draft,notes:event.target.value})} placeholder="Growth, flavor, pests, things to remember next year…"/></label><button className="primary-button" type="submit">Save plant changes</button><div className="record-danger-zone"><button type="button" onClick={()=>archivePlant(plant.id)}><Archive/>Archive / finish</button><button type="button" className="danger-control" onClick={()=>deletePlant(plant.id)}><Trash2/>Delete plant</button></div></form>}
  {view==='journey'&&<div className="plant-journey"><section className="journey-current"><Sprout/><span><small>CURRENT STAGE</small><strong>{normalizeLifecycleStage(draft.stage)}</strong><em>{garden.spaces.find(space=>space.id===draft.spaceId)?.name||'Location unavailable'}</em></span></section><div className="journey-timeline">{journey.length?journey.map(event=><article key={`${event.type}-${event.id}`}><span className={`journey-dot type-${event.type}`}>{event.completed?<CheckCircle2/>:<Clock3/>}</span><div><small>{formatDateTime(event.at)}</small><strong>{event.title}</strong>{event.detail&&<p>{event.detail}</p>}{event.photos?.length>0&&<div className="journey-photos">{event.photos.map((photo,index)=><img key={index} src={photo} alt={`${event.title} record`}/>)}</div>}</div></article>):<div className="journey-empty"><History/><strong>No journey events yet.</strong><p>Stage changes, completed care, harvests, and problems will appear here.</p></div>}</div></div>}
  {view==='harvest'&&<form className="modal-form" onSubmit={submitHarvest}><div className="control-callout"><Leaf/><span><strong>Record what was actually picked.</strong><small>Repeat-producing plants stay active.</small></span></div><div className="two-field-row"><label>Amount<input type="number" min="0" step="0.1" value={harvest.amount} onChange={event=>setHarvest({...harvest,amount:Number(event.target.value)})}/></label><label>Unit<select value={harvest.unit} onChange={event=>setHarvest({...harvest,unit:event.target.value})}><option>count</option><option>ounces</option><option>pounds</option><option>handful</option><option>bunch</option><option>basket</option></select></label></div><label>Quality<select value={harvest.quality} onChange={event=>setHarvest({...harvest,quality:event.target.value})}><option>Excellent</option><option>Good</option><option>Okay</option><option>Poor</option></select></label><label>Grow this again?<select value={harvest.growAgain} onChange={event=>setHarvest({...harvest,growAgain:event.target.value})}><option value="yes">Yes</option><option value="maybe">Maybe</option><option value="no">No</option></select></label><label>Harvest note<textarea value={harvest.note} onChange={event=>setHarvest({...harvest,note:event.target.value})}/></label><button className="primary-button" type="submit">Save harvest</button></form>}
  {view==='problem'&&<form className="modal-form" onSubmit={submitProblem}><div className="control-callout warning"><AlertTriangle/><span><strong>Log what you see, not a guess.</strong><small>This creates useful history without pretending to diagnose it.</small></span></div><label>Problem type<select value={problem.type} onChange={event=>setProblem({...problem,type:event.target.value})}><option>Pest spotted</option><option>Disease concern</option><option>Frost damage</option><option>Heat damage</option><option>Animal damage</option><option>Plant died</option><option>General issue</option></select></label><label>What should happen next?<select value={problem.severity} onChange={event=>setProblem({...problem,severity:event.target.value})}><option>Keep watching</option><option>Needs attention soon</option><option>Needs attention today</option></select></label><label>What was observed?<textarea value={problem.note} onChange={event=>setProblem({...problem,note:event.target.value})} required/></label><button className="primary-button" type="submit">Save problem record</button></form>}
 </section></div>
}
