import React,{useMemo,useState}from'react';
import{Camera,CheckCircle2,Leaf,Sprout,TriangleAlert}from'lucide-react';
import{formatDateTime}from'./data.js';
import{photoCapabilityLabel}from'./connectedIntelligence.js';
import{SecondaryHero}from'./SecondaryUI.jsx';

export default function GardenMemory({garden,navigate,resolveProblem}){
 const[tab,setTab]=useState('overview'),harvests=(garden.harvests||[]).filter(row=>!row.deletedAt),problems=(garden.problems||[]).filter(row=>!row.deletedAt),active=problems.filter(row=>row.status!=='resolved'),resolved=problems.filter(row=>row.status==='resolved');
 const totals=useMemo(()=>{const map=new Map();harvests.forEach(harvest=>{const key=harvest.plantId||`${harvest.name}|${harvest.variety||''}`,row=map.get(key)||{key,name:harvest.name||harvest.cropName||'Harvest',variety:harvest.variety||'',spaceName:harvest.spaceName||'',count:0,amounts:{},growAgain:harvest.growAgain};row.count+=1;row.amounts[harvest.unit]=(row.amounts[harvest.unit]||0)+(Number(harvest.amount)||0);if(harvest.growAgain)row.growAgain=harvest.growAgain;map.set(key,row)});return[...map.values()].sort((a,b)=>b.count-a.count)},[harvests]);
 return <main className="screen secondary-screen memory-screen"><SecondaryHero icon={Sprout} eyebrow="GARDEN RECORDS" title="Garden History" description="Harvests, issues, completed actions, and season decisions." onBack={()=>navigate('garden')} backLabel="Back to Garden" className="memory-header"/><section className="memory-body secondary-screen-content screen-pad"><div className="memory-tabs">{['overview','harvests','problems','review'].map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div>
  {tab==='overview'&&<div className="memory-summary-grid"><article><strong>{harvests.length}</strong><span>Harvest records</span></article><article><strong>{totals.length}</strong><span>Plantings harvested</span></article><article><strong>{active.length}</strong><span>Active issues</span></article><article><strong>{resolved.length}</strong><span>Resolved issues</span></article></div>}
  {tab==='harvests'&&<section className="memory-list connected-memory-list">{totals.length&&<div className="memory-totals">{totals.map(row=><article key={row.key}><Leaf/><span><strong>{row.name}{row.variety?` — ${row.variety}`:''}</strong><small>{row.count} harvest{row.count===1?'':'s'} · {Object.entries(row.amounts).map(([unit,amount])=>`${amount} ${unit}`).join(', ')}</small><small>{[row.spaceName,row.growAgain&&`Grow again: ${row.growAgain}`].filter(Boolean).join(' · ')}</small></span></article>)}</div>}<h2>Individual harvest records</h2>{harvests.length?harvests.map(harvest=><article key={harvest.id} className="memory-record-card">{harvest.photo?<img src={harvest.photo} alt={`${harvest.name||'Garden'} harvest`}/>:<Camera/>}<span><strong>{harvest.name}{harvest.variety?` — ${harvest.variety}`:''}</strong><small>{harvest.amount} {harvest.unit} · {harvest.quality||'Quality not recorded'} · {harvest.spaceName||'Growing Space not recorded'}</small><small>{formatDateTime(harvest.harvestedAt||harvest.at)}{harvest.useDestination?` · ${harvest.useDestination}`:''}</small>{harvest.photo&&<em>{photoCapabilityLabel(harvest)}</em>}{harvest.note&&<p>{harvest.note}</p>}</span></article>):<div className="empty-memory"><Leaf/><span><strong>No harvests yet.</strong><small>Harvest records appear here automatically from the Plant Journey.</small></span></div>}</section>}
  {tab==='problems'&&<section className="memory-list connected-memory-list">{active.map(problem=><article key={problem.id} className="memory-record-card">{problem.photo?<img src={problem.photo} alt={`${problem.plantName||'Plant'} issue record`}/>:<TriangleAlert/>}<span><strong>{problem.type} · {problem.plantName||'Plant not recorded'}</strong><small>{problem.severity} · {problem.spaceName||'Growing Space not recorded'} · {formatDateTime(problem.observedAt||problem.at)}</small>{problem.note&&<p>{problem.note}</p>}{problem.actionTaken&&<small><b>Action taken:</b> {problem.actionTaken}</small>}{problem.photo&&<em>{photoCapabilityLabel(problem)}</em>}</span><button onClick={()=>resolveProblem(problem.id)}><CheckCircle2/> Resolve</button></article>)}{!active.length&&<div className="empty-memory"><CheckCircle2/><span><strong>No active problems.</strong><small>Resolved issues remain part of the season and Plant Journey history.</small></span></div>}{resolved.length>0&&<details className="resolved-problem-history"><summary>{resolved.length} resolved issue{resolved.length===1?'':'s'}</summary>{resolved.map(problem=><p key={problem.id}><strong>{problem.type}</strong> · {problem.plantName||'Plant'} · resolved {formatDateTime(problem.resolvedAt||problem.updatedAt||problem.at)}</p>)}</details>}</section>}
  {tab==='review'&&<section className="season-review"><span className="section-kicker">2026 SEASON REVIEW</span><h2>What the connected records say so far</h2><p>{totals[0]?`${totals[0].name}${totals[0].variety?` — ${totals[0].variety}`:''} has been harvested most often.`:'Harvest some crops to begin the production review.'}</p><p>{active.length?`${active.length} issue${active.length===1?'':'s'} still need attention.`:'No unresolved garden problems are currently recorded.'}</p><p>{harvests.filter(row=>String(row.growAgain).toLowerCase()==='no').length?'At least one harvested planting is marked not to grow again.':'No harvested planting is currently marked to skip next season.'}</p></section>}
 </section></main>;
}
