import React,{useMemo,useState}from'react';
import{Check,Edit3,Leaf,PackageCheck,Plus,ShoppingBasket,Sprout,Trash2,Undo2,X}from'lucide-react';
import{SecondaryHero,SecondarySectionHeader}from'./SecondaryUI.jsx';
import{gardenShoppingItems,SHOPPING_CATEGORIES}from'./gardenShopping.js';

const emptyItem=()=>({name:'',category:'Seeds',cropId:'',variety:'',brand:'',quantity:1,note:'',reason:'Added manually.',intendedSpaceId:'',desiredWindow:''});

function ItemEditor({item,garden,onSave,onCancel}){
 const[d,setD]=useState({...item});
 const submit=event=>{event.preventDefault();if(!d.name.trim())return;onSave(d)};
 return <form className="shopping-item-editor" onSubmit={submit}><div className="shopping-editor-heading"><strong>{item.id?'Edit garden item':'Add garden item'}</strong><button type="button" onClick={onCancel} aria-label="Close item editor"><X/></button></div><label>Item name<input value={d.name} onChange={event=>setD({...d,name:event.target.value})} required placeholder="Bell Pepper Seeds"/></label><div className="shopping-two-fields"><label>Category<select value={d.category} onChange={event=>setD({...d,category:event.target.value})}>{SHOPPING_CATEGORIES.map(category=><option key={category}>{category}</option>)}</select></label><label>Quantity<input type="number" min="1" value={d.quantity} onChange={event=>setD({...d,quantity:Number(event.target.value)||1})}/></label></div><div className="shopping-two-fields"><label>Variety<input value={d.variety||''} onChange={event=>setD({...d,variety:event.target.value})} placeholder="Optional"/></label><label>Brand<input value={d.brand||''} onChange={event=>setD({...d,brand:event.target.value})} placeholder="Optional"/></label></div><label>Intended Growing Space<select value={d.intendedSpaceId||''} onChange={event=>setD({...d,intendedSpaceId:event.target.value})}><option value="">Decide later</option>{(garden.spaces||[]).filter(space=>!space.deletedAt&&!space.hidden).map(space=><option key={space.id} value={space.id}>{space.name}</option>)}</select></label><label>Desired planting date or window<input value={d.desiredWindow||''} onChange={event=>setD({...d,desiredWindow:event.target.value})} placeholder="Optional"/></label><label>Note<textarea value={d.note||''} onChange={event=>setD({...d,note:event.target.value})} placeholder="Optional details"/></label><button className="primary-button" type="submit"><Check/>Save item</button></form>;
}

function ShoppingItemCard({item,garden,onUpdate,onRemove,onEdit,onSeedInventory,onAddPlant,onOpenSource}){
 const space=garden.spaces?.find(row=>row.id===item.intendedSpaceId),isSeed=item.category==='Seeds',isPlant=item.category==='Starter Plant';
 return <article className={`garden-shopping-item ${item.purchased?'is-purchased':''}`}><div className="shopping-item-icon" aria-hidden="true">{item.purchased?<PackageCheck/>:<ShoppingBasket/>}</div><div className="shopping-item-copy"><span><small>{item.category}</small>{item.purchased&&<em>PURCHASED</em>}</span><h2>{item.name}</h2><p>{[item.variety,item.brand].filter(Boolean).join(' · ')||item.reason||'Garden purchase'}</p><div className="shopping-item-meta"><span>Qty {item.quantity||1}</span>{space&&<span>{space.name}</span>}{item.desiredWindow&&<span>{item.desiredWindow}</span>}</div>{item.note&&<small>{item.note}</small>}</div><div className="shopping-item-actions">{item.purchased?<button onClick={()=>onUpdate(item,{purchased:false,purchasedAt:''})}><Undo2/>Undo purchased</button>:<button className="shopping-purchase-button" onClick={()=>onUpdate(item,{purchased:true,purchasedAt:new Date().toISOString()})}><Check/>Mark purchased</button>}<button onClick={()=>onEdit(item)}><Edit3/>Edit</button>{item.sourceRecommendation&&<button onClick={()=>onOpenSource(item)}>View recommendation</button>}{item.purchased&&isSeed&&!item.linkedSeedInventoryId&&<button className="shopping-handoff-button" onClick={()=>onSeedInventory(item)}><Sprout/>Add to Seed Inventory</button>}{item.purchased&&isPlant&&!item.linkedPlantId&&<button className="shopping-handoff-button" onClick={()=>onAddPlant(item)}><Leaf/>Add Plant</button>}<button className="shopping-remove-button" onClick={()=>onRemove(item)}><Trash2/>Remove</button></div></article>;
}

export default function GardenShoppingList({garden,navigate,onAddItem,onUpdateItem,onRemoveItem,onClearPurchased,onBeginSeedInventory,onBeginPlant}){
 const[filter,setFilter]=useState('Needed'),[editing,setEditing]=useState(null),[adding,setAdding]=useState(false),items=useMemo(()=>gardenShoppingItems(garden),[garden]),needed=items.filter(item=>!item.purchased),purchased=items.filter(item=>item.purchased),visible=filter==='Purchased'?purchased:needed;
 const saveNew=data=>{const result=onAddItem(data);if(result?.status==='added')setAdding(false)};
 const saveEdit=data=>{onUpdateItem(editing,data);setEditing(null)};
 const openSource=item=>{sessionStorage.setItem('planting-desk-destination',item.desiredWindow&&item.desiredWindow>new Date().toISOString().slice(0,10)?'ahead':'grow');navigate('plan-plant')};
 return <main className="screen secondary-screen garden-shopping-screen"><SecondaryHero icon={ShoppingBasket} eyebrow="RUNYAN GARDEN CENTER" title="Garden Shopping List" description="Seeds, plants, and supplies to pick up for the garden." onBack={()=>navigate('center')} backLabel="Back to Garden Center" className="center-department-hero"/><section className="screen-pad secondary-screen-content garden-shopping-content"><div className="shopping-list-toolbar"><div className="secondary-segmented-control" role="tablist"><button className={filter==='Needed'?'active':''} onClick={()=>setFilter('Needed')}>Needed <b>{needed.length}</b></button><button className={filter==='Purchased'?'active':''} onClick={()=>setFilter('Purchased')}>Purchased <b>{purchased.length}</b></button></div><button className="shopping-add-button" onClick={()=>setAdding(true)}><Plus/>Add item</button></div>{adding&&<ItemEditor item={emptyItem()} garden={garden} onSave={saveNew} onCancel={()=>setAdding(false)}/>} {editing&&<ItemEditor item={editing} garden={garden} onSave={saveEdit} onCancel={()=>setEditing(null)}/>} {visible.length?<><SecondarySectionHeader eyebrow={filter==='Purchased'?'PURCHASED':'STILL NEEDED'} title={filter==='Purchased'?'Picked up':'Garden shopping'} count={visible.length}/><div className="garden-shopping-list">{visible.map(item=><ShoppingItemCard key={item.id} item={item} garden={garden} onUpdate={onUpdateItem} onRemove={onRemoveItem} onEdit={setEditing} onSeedInventory={onBeginSeedInventory} onAddPlant={onBeginPlant} onOpenSource={openSource}/>)}</div>{filter==='Purchased'&&purchased.length>0&&<button className="clear-purchased-button" onClick={onClearPurchased}><Trash2/>Clear purchased items</button>}</>:<div className="secondary-empty-state"><ShoppingBasket/><h2>{filter==='Purchased'?'No purchased items saved.':'Nothing to pick up right now.'}</h2><p>{filter==='Purchased'?'Items appear here after they are marked purchased.':'Planting Desk recommendations can add seeds, plants, and supplies here when something is needed.'}</p>{filter==='Needed'&&<div><button onClick={()=>{sessionStorage.setItem('planting-desk-destination','grow');navigate('plan-plant')}}>View Grow Now</button><button onClick={()=>{sessionStorage.setItem('planting-desk-destination','ahead');navigate('plan-plant')}}>View Plan Ahead</button><button onClick={()=>setAdding(true)}>Add Item Manually</button></div>}</div>}</section></main>;
}
