import React,{useMemo,useState}from'react';
import{ArrowLeft,Check,ChevronRight,Copy,Download,ExternalLink,QrCode,ScanLine,Share2,Tags}from'lucide-react';
import{QRCodeSVG}from'qrcode.react';
import{downloadBedSigns,downloadPlantTags,publicBedLink}from'./qrExport.js';

const STATUS_KEY='runyan-garden-label-status-v2';
const loadStatus=()=>{try{return JSON.parse(localStorage.getItem(STATUS_KEY)||'{}')}catch{return{}}};

export default function LabelCounter({garden,navigate}){
 const spaces=useMemo(()=>(garden.spaces||[]).filter(s=>!s.hidden&&!s.deletedAt),[garden.spaces]);
 const plants=useMemo(()=>(garden.plants||[]).filter(p=>!p.archived&&!p.deletedAt),[garden.plants]);
 const[status,setStatus]=useState(loadStatus),[selected,setSelected]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('beds');
 const save=next=>{setStatus(next);localStorage.setItem(STATUS_KEY,JSON.stringify(next))};
 const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const chosen=spaces.filter(s=>selected.includes(s.id));
 const run=async(fn,success)=>{try{setBusy(true);await fn();setMessage(success)}catch(e){setMessage(e?.message||'That file could not be created.')}finally{setBusy(false)}};
 const copy=async space=>{const link=publicBedLink(space.id);try{await navigator.clipboard.writeText(link);setMessage(`${space.name} exact bed link copied.`)}catch{window.prompt('Copy this exact bed link:',link)}};
 const share=async space=>{const link=publicBedLink(space.id);if(navigator.share){try{await navigator.share({title:`${space.name} · The Runyan Garden`,text:`See what is growing in ${space.name}.`,url:link});return}catch(e){if(e?.name==='AbortError')return}}copy(space)};
 const markInstalled=space=>{const next={...status,[space.id]:{state:'installed',at:new Date().toISOString()}};save(next);setMessage(`${space.name} marked as installed.`)};
 const bedPlants=id=>plants.filter(p=>p.spaceId===id);
 return <main className="screen label-counter-screen"><section className="dark-header label-counter-header"><button className="back-button" onClick={()=>navigate('back')}><ArrowLeft/></button><QrCode/><span>GARDEN CENTER DEPARTMENT</span><h1>QR & Label Studio</h1><p>Permanent bed signs and cut-apart plant tags.</p></section><section className="screen-pad label-counter-content">
  <div className="label-studio-tabs"><button className={tab==='beds'?'active':''} onClick={()=>setTab('beds')}><QrCode/>Bed signs</button><button className={tab==='plants'?'active':''} onClick={()=>setTab('plants')}><Tags/>Plant tags</button></div>
  {message&&<div className="label-counter-message" role="status">{message}</div>}
  {tab==='beds'&&<><section className="label-studio-intro"><strong>One permanent sign per garden bed</strong><p>Each PDF includes the exact bed name, a large QR code, the current plant list, and a stable bed code. Download it to Files, print it later, and laminate it for the bed.</p></section><div className="label-counter-toolbar"><div><span className="section-kicker">BED SIGNS</span><strong>{spaces.length} available · {Object.values(status).filter(x=>x?.state==='installed').length} installed</strong></div>{chosen.length>0&&<button disabled={busy} onClick={()=>run(()=>downloadBedSigns(chosen,plants),`${chosen.length} bed sign PDF${chosen.length===1?'':'s'} created.`)}><Download/>Download selected ({chosen.length})</button>}</div>{spaces.length?<div className="label-library">{spaces.map(space=>{const installed=status[space.id]?.state==='installed',count=bedPlants(space.id).length;return <article key={space.id} className="label-library-card"><button className={`label-select ${selected.includes(space.id)?'selected':''}`} onClick={()=>toggle(space.id)} aria-label={`Select ${space.name}`}><Check/></button><div className="label-qr-preview"><QRCodeSVG value={publicBedLink(space.id)} size={84} includeMargin level="M"/></div><div className="label-library-copy"><span>{installed?'INSTALLED':'READY TO DOWNLOAD'}</span><h2>{space.name}</h2><small>{count} plant record{count===1?'':'s'} · exact bed QR</small><div><button disabled={busy} onClick={()=>run(()=>downloadBedSigns([space],plants),`${space.name} PDF created.`)}><Download/>Bed sign PDF</button><button onClick={()=>window.open(publicBedLink(space.id),'_blank','noopener,noreferrer')}><ScanLine/>Test exact view</button><button onClick={()=>share(space)}><Share2/>Share</button><button onClick={()=>copy(space)}><Copy/>Copy link</button>{!installed&&<button onClick={()=>markInstalled(space)}><Check/>Mark installed</button>}<button onClick={()=>{sessionStorage.setItem('garden-open-bed',space.id);navigate('garden')}}><ExternalLink/>Edit bed</button></div></div><ChevronRight/></article>})}</div>:<div className="label-empty"><QrCode/><h2>No bed signs yet</h2><p>Add a named garden bed or growing area first.</p><button onClick={()=>navigate('garden')}>Go to the garden</button></div>}</>}
  {tab==='plants'&&<><section className="label-studio-intro"><strong>Individual tags for the plants inside each bed</strong><p>The PDF creates cut-apart tags for Pepper #1, Pepper #2, varieties, quantities, stages, and their exact garden location. Each tag’s QR opens the parent bed so visitors can see everything growing there.</p></section><div className="plant-tag-summary"><Tags/><span><strong>{plants.length} active plant tag{plants.length===1?'':'s'} ready</strong><small>Eight cut-apart tags per letter-size PDF page.</small></span><button disabled={busy||!plants.length} onClick={()=>run(()=>downloadPlantTags(spaces,plants),'Plant tag PDF created.') }><Download/>Download all plant tags</button></div><div className="plant-tag-preview-list">{spaces.map(space=>{const items=bedPlants(space.id);if(!items.length)return null;return <section key={space.id}><h2>{space.name}</h2>{items.map(p=><article key={p.id}><Tags/><span><strong>{p.name}</strong><small>{[p.cropName,p.variety].filter(Boolean).join(' · ')||'Variety not recorded'} · {p.quantity||1} plant{Number(p.quantity||1)===1?'':'s'}</small></span></article>)}</section>})}</div></>}
 </section></main>;
}
