import React,{useMemo,useState}from'react';
import{Check,Copy,Download,ExternalLink,Printer,QrCode,ScanLine,Share2,Tags}from'lucide-react';
import{QRCodeSVG}from'qrcode.react';
import{SecondaryHero}from'./SecondaryUI.jsx';
import{downloadBedSigns,downloadCustomQrLabel,downloadPlantTags,publicBedLink,publicRecordLink}from'./qrExport.js';

const STATUS_KEY='runyan-garden-label-status-v2';
const TYPES=[['space','Growing Space'],['plant','Plant or batch'],['tray','Seedling tray'],['pod','Hydroponic pod']];
const loadStatus=()=>{try{return JSON.parse(localStorage.getItem(STATUS_KEY)||'{}')}catch{return{}}};
function targetRows(garden,type){if(type==='space')return(garden.spaces||[]).filter(row=>!row.deletedAt).map(row=>({id:row.id,label:row.name,detail:row.type}));if(type==='plant')return(garden.plants||[]).filter(row=>!row.archived&&!row.deletedAt).map(row=>({id:row.id,label:row.name,detail:row.variety||row.stage}));if(type==='tray')return(garden.trays||[]).filter(row=>!row.deletedAt).map(row=>({id:row.id,label:row.name,detail:row.crop}));return(garden.hydroPods||[]).filter(row=>!row.deletedAt).map(row=>({id:row.id,label:`Pod ${row.position}`,detail:row.crop||row.status}))}

export default function LabelCounter({garden,navigate,initialTab='beds'}){
 const spaces=useMemo(()=>(garden.spaces||[]).filter(s=>!s.hidden&&!s.deletedAt),[garden.spaces]),plants=useMemo(()=>(garden.plants||[]).filter(p=>!p.archived&&!p.deletedAt),[garden.plants]);
 const[status,setStatus]=useState(loadStatus),[selected,setSelected]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState(initialTab),[labelType,setLabelType]=useState('space'),[targetId,setTargetId]=useState(''),[labelNote,setLabelNote]=useState('');
 const customRows=useMemo(()=>targetRows(garden,labelType),[garden,labelType]),customRecord=customRows.find(row=>row.id===targetId)||customRows[0],customLink=customRecord?publicRecordLink(labelType,customRecord.id):'';
 const save=next=>{setStatus(next);localStorage.setItem(STATUS_KEY,JSON.stringify(next))};
 const toggle=id=>setSelected(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id]),chosen=spaces.filter(space=>selected.includes(space.id));
 const run=async(fn,success)=>{try{setBusy(true);await fn();setMessage(success)}catch(error){setMessage(error?.message||'That file could not be created.')}finally{setBusy(false)}};
 const copyLink=async(link,success)=>{try{await navigator.clipboard.writeText(link);setMessage(success)}catch{window.prompt('Copy this exact garden link:',link)}};
 const shareLink=async({title,text,link})=>{if(navigator.share){try{await navigator.share({title,text,url:link});return}catch(error){if(error?.name==='AbortError')return}}copyLink(link,'Exact garden link copied.')};
 const copy=space=>copyLink(publicBedLink(space.id),`${space.name} exact bed link copied.`),share=space=>shareLink({title:`${space.name} · The Runyan Garden`,text:`See what is growing in ${space.name}.`,link:publicBedLink(space.id)});
 const markInstalled=space=>{const next={...status,[space.id]:{state:'installed',at:new Date().toISOString()}};save(next);setMessage(`${space.name} marked as installed.`)},bedPlants=id=>plants.filter(plant=>plant.spaceId===id);
 const printCustom=()=>{if(!customRecord)return;const printable=document.getElementById('custom-qr-label-preview')?.outerHTML;if(!printable)return;const popup=window.open('','_blank','width=480,height=640');if(!popup)return setMessage('The browser blocked the print window.');popup.document.write(`<html><head><title>${customRecord.label}</title><style>body{font-family:Arial;padding:24px}.custom-qr-preview{width:300px;border:2px solid #063c27;border-radius:18px;padding:20px;text-align:center}.custom-qr-preview h2{margin:10px 0 2px}.custom-qr-preview p{margin:4px 0;color:#555}</style></head><body>${printable}<script>window.onload=()=>window.print()</script></body></html>`);popup.document.close()};
 return <main className="screen secondary-screen label-counter-screen"><SecondaryHero icon={QrCode} eyebrow="TOOL SHED UTILITY" title="Plant Labels" description="Create permanent bed signs, individual plant tags, or one custom QR label for a saved garden record." onBack={()=>navigate('tools')} backLabel="Back to Tool Shed" className="tool-shed-hero label-counter-hero"/><section className="screen-pad secondary-screen-content label-counter-content"><div className="label-studio-tabs secondary-mode-selector" role="tablist"><button className={tab==='beds'?'active':''} onClick={()=>setTab('beds')}><QrCode/><span><strong>Bed Signs</strong></span></button><button className={tab==='plants'?'active':''} onClick={()=>setTab('plants')}><Tags/><span><strong>Plant Tags</strong></span></button><button className={tab==='custom'?'active':''} onClick={()=>setTab('custom')}><QrCode/><span><strong>Custom QR Label</strong></span></button></div>{message&&<div className="label-counter-message" role="status">{message}</div>}
 {tab==='beds'&&<><section className="label-studio-intro"><strong>One permanent sign per Growing Space</strong><p>Each PDF includes the exact space name, QR code, current plant list, and stable record link.</p></section><div className="label-counter-toolbar"><div><span className="section-kicker">BED SIGNS</span><strong>{spaces.length} available · {Object.values(status).filter(item=>item?.state==='installed').length} installed</strong></div>{chosen.length>0&&<button disabled={busy} onClick={()=>run(()=>downloadBedSigns(chosen,plants),`${chosen.length} bed sign PDF${chosen.length===1?'':'s'} created.`)}><Download/>Download selected ({chosen.length})</button>}</div>{spaces.length?<div className="label-library">{spaces.map(space=>{const installed=status[space.id]?.state==='installed',count=bedPlants(space.id).length;return <article key={space.id} className="label-library-card"><button className={`label-select ${selected.includes(space.id)?'selected':''}`} onClick={()=>toggle(space.id)} aria-label={`Select ${space.name}`}><Check/></button><div className="label-qr-preview"><QRCodeSVG value={publicBedLink(space.id)} size={84} includeMargin level="M"/></div><div className="label-library-copy"><span>{installed?'INSTALLED':'READY TO DOWNLOAD'}</span><h2>{space.name}</h2><small>{count} plant record{count===1?'':'s'} · exact Growing Space QR</small><div><button disabled={busy} onClick={()=>run(()=>downloadBedSigns([space],plants),`${space.name} PDF created.`)}><Download/>Bed sign PDF</button><button onClick={()=>window.open(publicBedLink(space.id),'_blank','noopener,noreferrer')}><ScanLine/>Test Exact View</button><button onClick={()=>share(space)}><Share2/>Share</button><button onClick={()=>copy(space)}><Copy/>Copy Link</button>{!installed&&<button onClick={()=>markInstalled(space)}><Check/>Mark Installed</button>}<button onClick={()=>{sessionStorage.setItem('garden-open-bed',space.id);navigate('garden')}}><ExternalLink/>Edit Growing Space</button></div></div></article>})}</div>:<div className="secondary-empty-state"><QrCode/><h2>No Growing Space signs yet</h2><p>Add a named bed, container, or growing area first.</p><button onClick={()=>navigate('garden')}>Go to Garden</button></div>}</>}
 {tab==='plants'&&<><section className="label-studio-intro"><strong>Individual labels for active plants</strong><p>The PDF creates cut-apart labels with an exact plant QR, plant name, variety, quantity, stage, and garden location.</p></section><div className="plant-tag-summary"><Tags/><span><strong>{plants.length} active plant label{plants.length===1?'':'s'} ready</strong><small>Eight cut-apart labels per letter-size PDF page.</small></span><button disabled={busy||!plants.length} onClick={()=>run(()=>downloadPlantTags(spaces,plants),'Plant label PDF created.')}><Download/>Download all plant labels</button></div><div className="plant-tag-preview-list">{spaces.map(space=>{const items=bedPlants(space.id);if(!items.length)return null;return <section key={space.id}><h2>{space.name}</h2>{items.map(plant=><article key={plant.id}><Tags/><span><strong>{plant.name}</strong><small>{[plant.cropName,plant.variety].filter(Boolean).join(' · ')||'Variety not recorded'} · {plant.quantity||1} plant{Number(plant.quantity||1)===1?'':'s'}</small></span></article>)}</section>})}</div></>}
 {tab==='custom'&&<><section className="label-studio-intro"><strong>One selected saved garden record</strong><p>Choose the record type, exact record, and optional note. Existing <code>gardenLabel</code> links remain valid.</p></section><section className="custom-label-builder"><label>Record Type<select value={labelType} onChange={event=>{setLabelType(event.target.value);setTargetId('')}}>{TYPES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Garden Record<select value={targetId||customRecord?.id||''} onChange={event=>setTargetId(event.target.value)}>{customRows.map(row=><option key={row.id} value={row.id}>{row.label} — {row.detail}</option>)}</select></label><label>Optional Label Note<input value={labelNote} onChange={event=>setLabelNote(event.target.value)}/></label></section>{customRecord?<><section id="custom-qr-label-preview" className="custom-qr-preview"><div>THE RUNYAN GARDEN</div><QRCodeSVG value={customLink} size={180} fgColor="#063c27" bgColor="#fbf7ec" level="M" includeMargin/><h2>{customRecord.label}</h2><p>{labelNote||customRecord.detail}</p><small>Scan to open this garden record</small></section><div className="custom-label-actions"><button className="primary-button" disabled={busy} onClick={()=>run(()=>downloadCustomQrLabel({title:customRecord.label,subtitle:customRecord.detail,note:labelNote,link:customLink,type:labelType}),'Custom QR label PDF created.')}><Download/>Download PDF</button><button onClick={printCustom}><Printer/>Print</button><button onClick={()=>shareLink({title:`${customRecord.label} · The Runyan Garden`,text:labelNote||customRecord.detail,link:customLink})}><Share2/>Share</button><button onClick={()=>copyLink(customLink,'Custom QR label link copied.')}><Copy/>Copy Link</button></div></>:<div className="secondary-empty-state"><QrCode/><h2>No records are available for this label type.</h2><p>Add the record first, then return here.</p></div>}</>}
 </section></main>;
}
