import React,{useMemo,useState}from'react';
import{ArrowLeft,Check,ChevronRight,Copy,ExternalLink,Printer,QrCode,ScanLine}from'lucide-react';
import{QRCodeSVG}from'qrcode.react';
const STATUS_KEY='runyan-garden-label-status-v2';
const loadStatus=()=>{try{return JSON.parse(localStorage.getItem(STATUS_KEY)||'{}')}catch{return{}}};
const bedLink=id=>`${window.location.origin}${window.location.pathname}?bed=${encodeURIComponent(id)}&view=public`;
const waitForPaint=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>setTimeout(resolve,500))));
export default function LabelCounter({garden,navigate}){
 const spaces=useMemo(()=>(garden.spaces||[]).filter(s=>!s.hidden&&!s.deletedAt),[garden.spaces]);
 const[status,setStatus]=useState(loadStatus),[selected,setSelected]=useState([]),[printing,setPrinting]=useState([]),[message,setMessage]=useState('');
 const save=next=>{setStatus(next);localStorage.setItem(STATUS_KEY,JSON.stringify(next))};
 const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const print=async items=>{setPrinting(items);document.body.classList.add('printing-garden-labels');await waitForPaint();let cleaned=false,armed=false;const cleanup=()=>{if(cleaned)return;cleaned=true;document.body.classList.remove('printing-garden-labels');setPrinting([]);window.removeEventListener('afterprint',cleanup);window.removeEventListener('focus',returnFromPrint);document.removeEventListener('visibilitychange',visibilityReturn)};const returnFromPrint=()=>{if(armed)setTimeout(cleanup,900)};const visibilityReturn=()=>{if(armed&&document.visibilityState==='visible')setTimeout(cleanup,900)};window.addEventListener('afterprint',cleanup);window.addEventListener('focus',returnFromPrint);document.addEventListener('visibilitychange',visibilityReturn);setTimeout(()=>{armed=true},1200);window.print();setMessage('Print preview opened. The QR sheet will stay loaded until you close the preview.')};
 const copy=async space=>{const link=bedLink(space.id);try{await navigator.clipboard.writeText(link);setMessage(`${space.name} public bed link copied.`)}catch{window.prompt('Copy this exact bed link:',link)}};
 const markInstalled=space=>{const next={...status,[space.id]:{state:'installed',at:new Date().toISOString()}};save(next);setMessage(`${space.name} marked as installed.`)};
 const test=space=>window.open(bedLink(space.id),'_blank','noopener,noreferrer');
 const chosen=spaces.filter(s=>selected.includes(s.id));
 return <main className="screen label-counter-screen"><section className="dark-header label-counter-header"><button className="back-button" onClick={()=>navigate('back')}><ArrowLeft/></button><QrCode/><span>GARDEN CENTER DEPARTMENT</span><h1>Label Counter</h1><p>Permanent links to exact garden beds.</p></section><section className="screen-pad label-counter-content"><div className="label-counter-toolbar"><div><span className="section-kicker">BED & SPACE LABELS</span><strong>{spaces.length} available · {Object.values(status).filter(x=>x?.state==='installed').length} installed</strong></div>{chosen.length>0&&<button onClick={()=>print(chosen)}><Printer/>Print selected ({chosen.length})</button>}</div>{message&&<div className="label-counter-message" role="status">{message}</div>}{spaces.length?<div className="label-library">{spaces.map(space=>{const installed=status[space.id]?.state==='installed';return <article key={space.id} className="label-library-card"><button className={`label-select ${selected.includes(space.id)?'selected':''}`} onClick={()=>toggle(space.id)} aria-label={`Select ${space.name}`}><Check/></button><div className="label-qr-preview"><QRCodeSVG value={bedLink(space.id)} size={84} includeMargin={true} level="M"/></div><div className="label-library-copy"><span>{installed?'INSTALLED':'READY TO PRINT'}</span><h2>{space.name}</h2><small>{space.type?.replaceAll('-',' ')||'Garden space'} · exact public bed link</small><div><button onClick={()=>print([space])}><Printer/>{installed?'Reprint':'Print'}</button><button onClick={()=>test(space)}><ScanLine/>Test QR</button><button onClick={()=>copy(space)}><Copy/>Copy exact link</button>{!installed&&<button onClick={()=>markInstalled(space)}><Check/>Mark installed</button>}<button onClick={()=>{sessionStorage.setItem('garden-open-bed',space.id);navigate('garden')}}><ExternalLink/>Edit bed</button></div></div><ChevronRight/></article>})}</div>:<div className="label-empty"><QrCode/><h2>No labels yet</h2><p>Add a garden bed or growing space and its exact QR label will appear here automatically.</p><button onClick={()=>navigate('garden')}>Go to the garden</button></div>}</section><div className="qr-print-sheet" aria-hidden={printing.length===0}>{printing.map(s=><article className="qr-print-label" key={s.id}><div className="qr-print-brand">THE RUNYAN GARDEN</div><QRCodeSVG value={bedLink(s.id)} size={240} includeMargin={true} level="M"/><h2>{s.name}</h2><p>Scan to see what is growing here.</p><small>Bed code: {s.id}</small></article>)}</div></main>;
}