import React from'react';
import{Bell,ChevronDown,ChevronRight,CircleHelp,DatabaseBackup,Info,MapPin,Newspaper,Settings,Sprout,Users}from'lucide-react';
import{SecondaryCard,SecondaryHero}from'./SecondaryUI.jsx';

function SettingsRow({icon:Icon,title,detail,onClick}){return <button type="button" onClick={onClick}><Icon/><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight/></button>}

export default function MoreHub({garden,navigate}){
 const active=garden.profile?.gardenerName||'Brooke',location=(garden.profile?.location||'Green Bay').replace(/\s+54302$/,''),zone=garden.profile?.zone||'5b',notifications=garden.profile?.notifications||{},alertCount=[notifications.weather!==false,notifications.tasks!==false,notifications.shopping!==false].filter(Boolean).length;
 return <main className="screen secondary-screen more-screen"><SecondaryHero icon={Sprout} eyebrow="GARDEN COMPASS" title="More" description="Garden settings, backup, help, updates, and app information." className="more-hero"/><section className="screen-pad secondary-screen-content more-content"><details className="more-settings-hub"><summary><span className="more-settings-icon"><Settings/></span><span><small>GARDEN & ACCOUNT SETTINGS</small><strong>{active} · {location}</strong><em>Gardeners, location, frost dates, and notifications</em></span><ChevronDown className="more-settings-chevron"/></summary><div><SettingsRow icon={Users} title="Garden and gardeners" detail="Garden name and active gardener" onClick={()=>navigate('admin-profile')}/><SettingsRow icon={MapPin} title="Location and frost dates" detail={`${location} · Zone ${zone}`} onClick={()=>navigate('admin-location')}/><SettingsRow icon={Bell} title="Notifications" detail={`${alertCount} alert type${alertCount===1?'':'s'} enabled`} onClick={()=>navigate('admin-notifications')}/></div></details><div className="secondary-card-list more-compact-list"><SecondaryCard kind="admin" icon={DatabaseBackup} title="Backup & Data" description="Back up, restore, and review garden data." onClick={()=>navigate('admin-backup')}/><SecondaryCard kind="admin" icon={CircleHelp} title="How Garden Compass Works" description="Learn where to find your garden, plans, tools, and settings." onClick={()=>navigate('admin-help')}/><SecondaryCard kind="admin" icon={Newspaper} title="What's New" description="Recent user-facing improvements" onClick={()=>navigate('admin-whatsnew')}/><SecondaryCard kind="admin" icon={Info} title="About Garden Compass" description="Version, storage, and app information" onClick={()=>navigate('admin-about')}/></div></section></main>;
}
