import{cropCatalog,newId}from'./data.js';
import{normalizeLifecycleStage,normalizeStageHistory}from'./gardenIntelligence.js';
import{nextLifecycleStage}from'./seedToHarvest.js';
const DAY=86400000,cropMap=Object.fromEntries(cropCatalog.map(crop=>[crop.id,crop])),harvestDays={lettuce:45,onions:55,garlic:270,spinach:42,peppers:80,basil:45,marigold:55},earlyStages=new Set(['Planned','Seed Purchased','Seed Started','Germinating','Seedling','Potted Up','Hardening Off']);
function dateOnly(value){const raw=String(value||'').slice(0,10),date=raw?new Date(`${raw}T12:00:00`):new Date();return Number.isNaN(date.getTime())?new Date():date}
export function addDays(value,days){const date=dateOnly(value);date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)}
export function daysFromNow(value){return Math.ceil((dateOnly(value).getTime()-dateOnly(new Date().toISOString().slice(0,10)).getTime())/DAY)}
export function prettyDate(value){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(dateOnly(value))}
export function nextStage(current,plant={}){return nextLifecycleStage({...plant,stage:normalizeLifecycleStage(current)})||normalizeLifecycleStage(current)}
export function normalizePlanning(garden){const actor=garden.profile?.gardenerName||'System';return{...garden,seeds:[],seedPackets:Array.isArray(garden.seedPackets)?garden.seedPackets:Array.isArray(garden.seeds)?garden.seeds:[],succession:Array.isArray(garden.succession)?garden.succession:[],harvests:Array.isArray(garden.harvests)?garden.harvests:[],plants:(garden.plants||[]).map(plant=>({batchName:plant.batchName||'Batch 1',quantity:Number(plant.quantity)||1,successionEnabled:Boolean(plant.successionEnabled),successionDays:Number(plant.successionDays)||14,...plant,stage:normalizeLifecycleStage(plant.stage),stageHistory:normalizeStageHistory(plant,actor)}))}}
export function buildTimeline(garden,now=new Date()){const today=now.toISOString().slice(0,10),items=[];(garden.plants||[]).forEach(plant=>{const crop=cropMap[plant.cropId],stage=normalizeLifecycleStage(plant.stage),planted=plant.plantedAt||today,stageEntered=plant.stageUpdatedAt||planted,estimate=plant.estimates?.harvest?.current||plant.estimates?.maturity?.current||'',estimatedStart=String(estimate).slice(0,10),harvestDate=plant.expectedHarvest||estimatedStart||addDays(planted,harvestDays[plant.cropId]||60),harvestDelta=daysFromNow(harvestDate);normalizeStageHistory(plant,garden.profile?.gardenerName).forEach(entry=>items.push({id:`history-${plant.id}-${entry.id}`,type:'lifecycle',plantId:plant.id,date:String(entry.enteredAt).slice(0,10),title:`${plant.name}: ${entry.stage}`,detail:entry.notes||'Lifecycle stage entered',priority:4,historical:true,classification:entry.classification||'Confirmed',photos:entry.photos||[]}));if(stage==='Harvesting'||(!['Finished','Failed','Removed'].includes(stage)&&harvestDelta>=-7&&harvestDelta<=30))items.push({id:`harvest-${plant.id}`,type:'harvest',plantId:plant.id,date:harvestDate,title:stage==='Harvesting'?`Harvest ${plant.name}`:`Check ${plant.name} for harvest`,detail:`${plant.batchName||'Current batch'} • ${crop?.harvest||'Check maturity'}`,priority:stage==='Harvesting'?1:3,estimated:stage!=='Harvesting'});if(earlyStages.has(stage)){const checkDate=addDays(stageEntered,['Planned','Seed Purchased'].includes(stage)?7:stage==='Seed Started'?5:3);items.push({id:`stage-${plant.id}`,type:'stage',plantId:plant.id,date:checkDate,title:`Check ${plant.name} progress`,detail:`Current stage: ${stage}`,priority:2})}if(plant.successionEnabled){const existing=(garden.succession||[]).find(item=>item.plantId===plant.id&&item.status!=='done'),due=existing?.dueDate||addDays(planted,plant.successionDays||14);items.push({id:existing?.id||`succession-${plant.id}`,type:'succession',plantId:plant.id,date:due,title:`Start the next ${plant.name} batch`,detail:`${plant.quantity||1} now • repeats every ${plant.successionDays||14} days`,priority:2})}});(garden.succession||[]).filter(item=>!item.plantId&&item.status!=='done').forEach(item=>items.push({...item,type:'succession',priority:2}));return items.filter(item=>item.historical||(daysFromNow(item.date)>=-7&&daysFromNow(item.date)<=60)).sort((a,b)=>b.historical-a.historical||a.date.localeCompare(b.date)||a.priority-b.priority)}
export function splitTimeline(items){return{week:items.filter(item=>!item.historical&&daysFromNow(item.date)<=7),month:items.filter(item=>!item.historical&&daysFromNow(item.date)>7&&daysFromNow(item.date)<=30),later:items.filter(item=>!item.historical&&daysFromNow(item.date)>30),history:items.filter(item=>item.historical).sort((a,b)=>b.date.localeCompare(a.date))}}
export function seedStatusForCrop(garden,cropId){const seed=(garden.seedPackets||[]).find(item=>item.cropId===cropId||item.name?.toLowerCase()===cropMap[cropId]?.name.toLowerCase());if(!seed)return{label:'Not in seed box',tone:'red',seed:null};if(Number(seed.quantity)<=0)return{label:'Out of seeds',tone:'red',seed};const age=new Date().getFullYear()-Number(seed.packetYear||new Date().getFullYear());if(age>=4)return{label:'Test germination',tone:'gold',seed};if(Number(seed.quantity)-(Number(seed.reservedQuantity)||0)<=5)return{label:'Running low',tone:'gold',seed};return{label:'Already owned',tone:'green',seed}}
export function createSuccession(plant,interval=14,quantity=6){return{id:newId('succession'),plantId:plant.id,cropId:plant.cropId,title:`Start the next ${plant.name} batch`,detail:`${quantity} plants or seeds`,dueDate:addDays(new Date().toISOString().slice(0,10),interval),date:addDays(new Date().toISOString().slice(0,10),interval),interval,quantity,status:'scheduled'}}
