import { cropCatalog, newId } from './data.js';
import { formatGardenDateRange, localDateInputValue } from './dateFormat.js';
import { timingDefaults } from './gardenTools.js';
import { assessPlantingWeatherReadiness } from './weatherDecisionEngine.js';

const DAY=86400000;
const PLANTING_TASK_TYPES=new Set(['Start Seeds','Direct Sow','Transplant','Pot Up','Harden Off','Prepare Space','Install Support','Plan Succession','Thin Seedlings','Reserve Space']);
const INDOOR_TYPES=new Set(['indoor','basement','seed-tray','greenhouse','hydro']);
const OUTDOOR_TYPES=new Set(['bed','black-square-bed','white-oval-bed','in-ground','container','potato-grow-bag','raised-bed']);
const LONG_SEASON=new Set(['bell-pepper','hot-pepper','tomato','eggplant','onion','leek','winter-squash','pumpkin','melon']);
const DIRECT_SOW=new Set(['lettuce','spinach','kale','radish','peas','carrot','corn','green-bean','cucumber','zucchini','winter-squash','pumpkin','green-onion','cilantro','dill','parsley','chard','arugula','beet','turnip','bok-choy','nasturtium','calendula','sweet-alyssum','potato']);
const COOL_FALL=new Set(['lettuce','spinach','kale','radish','carrot','peas','cabbage','broccoli','cauliflower','chard','arugula','beet','turnip','bok-choy','cilantro','dill']);
const TRANSPLANT_ONLY_NOW=new Set(['tomato','bell-pepper','hot-pepper','eggplant']);
const LARGE_CROPS=new Set(['corn','cucumber','zucchini','winter-squash','pumpkin','melon']);
const PERENNIALS=new Set(['strawberry','chives','thyme','oregano','sage','raspberry','asparagus']);
const POLLINATORS=new Set(['marigold','nasturtium','calendula','sweet-alyssum','anise-hyssop','coneflower','bee-balm']);

const GUIDANCE={
 lettuce:{type:'heat-tolerant loose-leaf or summer-crisp lettuce',traits:['slow bolting','heat tolerant','baby-leaf suitable'],examples:['Amish Deer Tongue'],use:'Tender leaves for salads and sandwiches.',harvest:'30–55 days, sooner for baby leaves'},
 spinach:{type:'slow-bolting spinach',traits:['slow bolting','cool tolerant','baby-leaf suitable'],examples:['Indian Summer','Olympia'],use:'Tender leaves for salads or cooking.',harvest:'35–50 days'},
 kale:{type:'cold-tolerant leaf kale',traits:['cold tolerant','short season','repeat harvest'],examples:[],use:'Leaves for sautéing, soups, or salads.',harvest:'30–60 days for baby or mature leaves'},
 radish:{type:'fast spring or fall radish',traits:['short season','direct sow','compact'],examples:[],use:'Crisp roots and edible greens.',harvest:'22–40 days'},
 carrot:{type:'short-season or baby carrot',traits:['short season','smooth-rooted','suitable for loose soil'],examples:[],use:'Fresh eating, roasting, or storage depending on type.',harvest:'50–75 days'},
 peas:{type:'short-season snap or snow pea',traits:['cool tolerant','short season','trellis suitable'],examples:[],use:'Sweet edible pods or shelling peas.',harvest:'55–70 days'},
 cabbage:{type:'early-maturing fall cabbage',traits:['short season','cold tolerant','compact head'],examples:[],use:'Slaw, sautéing, roasting, or storage.',harvest:'60–90 days from transplant'},
 broccoli:{type:'early-maturing broccoli',traits:['short season','cold tolerant','side-shoot production'],examples:[],use:'Main heads and later side shoots.',harvest:'55–80 days from transplant'},
 cauliflower:{type:'short-season cauliflower',traits:['short season','cold tolerant','uniform maturity'],examples:[],use:'Fresh eating, roasting, or freezing.',harvest:'55–80 days from transplant'},
 tomato:{type:'early-maturing tomato transplant',traits:['early maturing','disease resistant','appropriate growth habit'],examples:[],use:'Choose cherry, slicing, or paste fruit for the intended kitchen use.',harvest:'50–75 days from transplant'},
 'bell-pepper':{type:'early-maturing sweet pepper transplant',traits:['early maturing','compact when space is limited','thick-walled fruit'],examples:[],use:'Fresh eating, stuffing, roasting, or freezing.',harvest:'55–80 days from transplant'},
 'hot-pepper':{type:'early-maturing hot pepper transplant',traits:['early maturing','compact','heat level suited to the household'],examples:[],use:'Fresh salsa, pickling, drying, or hot sauce.',harvest:'60–90 days from transplant'},
 eggplant:{type:'short-season eggplant transplant',traits:['short season','early maturing','compact'],examples:[],use:'Grilling, roasting, curries, or casseroles.',harvest:'55–80 days from transplant'},
 'green-bean':{type:'bush bean for speed or pole bean for vertical harvest',traits:['short season','disease resistant','growth habit matched to support'],examples:[],use:'Fresh snap beans, freezing, or pickling.',harvest:'50–65 days'},
 cucumber:{type:'pickling or slicing cucumber',traits:['early maturing','disease resistant','trellis suitable when needed'],examples:[],use:'Choose pickling types for jars or slicing types for fresh eating.',harvest:'50–65 days'},
 zucchini:{type:'compact zucchini or summer squash',traits:['early maturing','compact when space is limited','powdery-mildew resistance'],examples:[],use:'Fresh cooking, grilling, baking, or freezing.',harvest:'45–60 days'},
 'winter-squash':{type:'short-season winter squash',traits:['short season','compact vine when needed','storage quality'],examples:[],use:'Roasting, soups, baking, and winter storage.',harvest:'80–100 days'},
 pumpkin:{type:'small-fruited short-season pumpkin',traits:['short season','smaller vine when space is limited','intended for cooking or carving'],examples:[],use:'Cooking, decorating, or carving depending on type.',harvest:'85–105 days'},
 basil:{type:'culinary basil transplant or indoor planting',traits:['slow bolting','compact when container grown','disease resistant'],examples:['Genovese'],use:'Fresh leaves for pesto, sauces, and garnishing.',harvest:'30–50 days'},
 cilantro:{type:'slow-bolting cilantro',traits:['slow bolting','cool tolerant','succession suitable'],examples:[],use:'Leaves for fresh cooking and mature seed for coriander.',harvest:'30–50 days'},
 dill:{type:'leaf dill or pickling dill',traits:['slow bolting for leaf harvest','large seed heads for pickling when desired'],examples:['Hercules','Long Island Mammoth'],use:'Leaves, flowers, or seed for cooking and pickling.',harvest:'40–70 days'},
 parsley:{type:'flat-leaf culinary parsley',traits:['cold tolerant','container suitable','repeat harvest'],examples:[],use:'Fresh herb for sauces, salads, and cooking.',harvest:'70–90 days'},
 arugula:{type:'cool-season arugula',traits:['short season','baby-leaf suitable','slow bolting'],examples:[],use:'Peppery leaves for salads, pizza, or cooking.',harvest:'25–40 days'},
 beet:{type:'baby or short-season beet',traits:['short season','dual-purpose roots and greens','compact'],examples:[],use:'Roots for roasting or pickling; young leaves are edible.',harvest:'45–65 days'},
 turnip:{type:'salad or baby turnip',traits:['short season','cool tolerant','edible greens'],examples:[],use:'Tender roots and greens for fresh eating or cooking.',harvest:'35–55 days'},
 'bok-choy':{type:'baby or compact bok choy',traits:['short season','cold tolerant','compact'],examples:[],use:'Crisp stems and leaves for stir-fries or soups.',harvest:'30–50 days'},
 chard:{type:'compact Swiss chard',traits:['heat tolerant','repeat harvest','container suitable'],examples:[],use:'Tender leaves and stems for cooking.',harvest:'30–60 days'},
 leek:{type:'baby leek or early leek',traits:['early maturing','cold tolerant','baby harvest suitable'],examples:['Albinstar Baby Leek'],use:'Mild onion flavor for soups, roasting, and sautés.',harvest:'90–110 days'},
 strawberry:{type:'hardy strawberry plant',traits:['Wisconsin hardy','disease resistant','June-bearing or day-neutral by preference'],examples:[],use:'Perennial fruit for fresh eating or preserving.',harvest:'Usually the following season after establishment'},
 nasturtium:{type:'bush or trailing nasturtium',traits:['edible flowers','container suitable','growth habit matched to space'],examples:[],use:'Peppery edible leaves and flowers; also useful garden color.',harvest:'Blooms in roughly 50–70 days'},
 calendula:{type:'single or semi-double calendula',traits:['cool tolerant','pollinator accessible','edible petals'],examples:[],use:'Bright flowers with edible petals; not a proven pest-control treatment.',harvest:'Blooms in roughly 45–60 days'},
 'sweet-alyssum':{type:'sweet alyssum',traits:['small flowers','container edge suitable','beneficial-insect forage'],examples:['Pastel Carpet Mix'],use:'Low flower border that provides pollen and nectar.',harvest:'Blooms in roughly 45–60 days'},
 chives:{type:'hardy culinary chive plant',traits:['Wisconsin hardy','compact','pollinator flowers'],examples:[],use:'Perennial onion-flavored leaves and edible flowers.',harvest:'Light harvest after establishment'}
};

const DISCOVERY=[
 {id:'arugula',name:'Arugula',family:'vegetables',sun:'4–6 hours',harvest:'25–40 days',summary:'Fast peppery salad green for cool weather.'},
 {id:'beet',name:'Beets',family:'vegetables',sun:'6+ hours',harvest:'45–65 days',summary:'Roots and greens from one compact crop.'},
 {id:'turnip',name:'Baby Turnips',family:'vegetables',sun:'5–6 hours',harvest:'35–55 days',summary:'Fast cool-season roots with edible greens.'},
 {id:'bok-choy',name:'Baby Bok Choy',family:'vegetables',sun:'4–6 hours',harvest:'30–50 days',summary:'Compact Asian green for stir-fries and soups.'},
 {id:'nasturtium',name:'Nasturtiums',family:'flowers',sun:'6+ hours',harvest:'Blooms in 50–70 days',summary:'Edible flowers and leaves in bush or trailing forms.'},
 {id:'calendula',name:'Calendula',family:'flowers',sun:'6+ hours',harvest:'Blooms in 45–60 days',summary:'Cool-tolerant edible flower with open blooms for insects.'},
 {id:'sweet-alyssum',name:'Sweet Alyssum',family:'flowers',sun:'4–6 hours',harvest:'Blooms in 45–60 days',summary:'Low flowering edge plant that provides pollen and nectar.'},
 {id:'chives',name:'Chives',family:'herbs',sun:'6+ hours',harvest:'Perennial harvest after establishment',summary:'Hardy culinary perennial with edible flowers.'},
 {id:'eggplant',name:'Eggplant',family:'vegetables',sun:'8+ hours',harvest:'55–80 days from transplant',summary:'Heat-loving crop that must be treated as a transplant opportunity this late.'},
 {id:'leek',name:'Leeks',family:'vegetables',sun:'6+ hours',harvest:'90–120 days',summary:'Long-season onion relative; baby-leek types are the practical shorter option.'}
];

const todayKey=()=>new Date().toISOString().slice(0,10);
export const plantingDateKey=value=>value instanceof Date?localDateInputValue(value):String(value||todayKey()).slice(0,10);
const dateKey=plantingDateKey;
const addDays=(value,days)=>{const date=new Date(`${dateKey(value)}T12:00:00`);date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)};
const addWeeksKey=(value,weeks)=>addDays(dateKey(value),Number(weeks||0)*7);
const normalize=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const packetKey=packet=>`${packet.exactPacket?'packet':'seed'}-${packet.id}`;
const decisionMap=garden=>new Map((garden.plantingDecisions||[]).filter(item=>!item.deletedAt).map(item=>[item.subjectKey,item]));
const firstNumber=value=>{const values=String(value||'').match(/\d+/g)?.map(Number)||[];return values.length?Math.max(...values):null};
const frostDate=year=>new Date(`${year}-10-10T12:00:00`);
const daysRemaining=(date=new Date())=>Math.max(0,Math.floor((frostDate(date.getFullYear())-new Date(`${dateKey(date)}T12:00:00`))/DAY));

function inferCropId(record={}){if(record.cropId)return record.cropId;const text=normalize(`${record.name||''} ${record.variety||''}`);if(/eggplant/.test(text))return'eggplant';if(/california wonder|bell pepper|sweet pepper/.test(text))return'bell-pepper';if(/jalapeno|serrano|cayenne|hot pepper|chili|chile/.test(text))return'hot-pepper';const match=[...cropCatalog,...DISCOVERY].find(crop=>{const name=normalize(crop.name);return text===name||text.includes(name)||name.includes(text)});return match?.id||''}
function stockFor(record={}){const status=normalize(`${record.status||''} ${record.availability||''}`),blocked=Boolean(record.deletedAt||record.discarded||record.available===false||/discarded|unavailable|used up|empty/.test(status)),raw=record.quantity??record.seedsRemaining??record.amount,quantity=raw===''||raw===null||raw===undefined?null:Number(raw),reserved=Number(record.reservedQuantity??record.reserved??0)||0;return{blocked,available:quantity===null?null:Math.max(0,quantity-reserved)}}
export function seedInventory(garden={}){const rows=(garden.seedPackets||[]).map(packet=>({...packet,exactPacket:true})).map(record=>{const stock=stockFor(record);return{...record,cropId:inferCropId(record),quantityAvailable:stock.available,blocked:stock.blocked||stock.available===0}}).filter(record=>!record.blocked);return rows}

function activeCount(space,garden){return(garden.plants||[]).filter(plant=>!plant.deletedAt&&!plant.archived&&plant.spaceId===space.id).reduce((sum,plant)=>sum+(Number(plant.quantity)||1),0)}
function suitableSpaces(garden,crop,method){return(garden.spaces||[]).filter(space=>!space.hidden&&!space.deletedAt).map(space=>{const count=activeCount(space,garden),capacity=Number(space.capacity)||0;if(capacity&&count>=capacity)return null;const indoor=['Start Indoors','Indoor Growing'].includes(method);if(indoor&&!INDOOR_TYPES.has(space.type))return null;if(!indoor&&method!=='Save for Later'&&method!=='Not This Season'&&!OUTDOOR_TYPES.has(space.type)&&space.type!=='greenhouse')return null;let score=100-count*4;const warnings=[],sun=normalize(space.sunExposure);if(String(crop?.sun||'').includes('8+')&&/shade|part shade/.test(sun)){score-=35;warnings.push('Recorded sunlight may be too low.')}if(space.type==='container'&&LARGE_CROPS.has(crop?.id)){score-=30;warnings.push('This crop may outgrow a typical container.')}if(space.type==='container'&&!space.size)warnings.push('Container size is not recorded.');if(/poor/.test(normalize(space.drainageQuality)))warnings.push('Drainage is recorded as poor.');if(space.expectedAvailableDate&&space.expectedAvailableDate>todayKey()){score-=20;warnings.push(`Expected available ${space.expectedAvailableDate}.`)}return{...space,score,warnings,activeCount:count}}).filter(Boolean).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name))}
function cropAlreadyPlanned(garden,cropId){return(garden.plants||[]).some(plant=>!plant.deletedAt&&!plant.archived&&plant.cropId===cropId)||(garden.yearPlan?.crops||[]).some(item=>item.cropId===cropId&&['definitely','maybe'].includes(item.status))}
function packetAlreadyStarted(garden,packet){return(garden.plants||[]).some(plant=>!plant.deletedAt&&!plant.archived&&(plant.seedId===packet.id||plant.sourcePacketId===packet.id||(packet.cropId&&plant.cropId===packet.cropId&&normalize(plant.variety)===normalize(packet.variety))))}

function seasonWindow(cropId,date=new Date()){
 const year=date.getFullYear(),make=(sm,sd,em,ed,label)=>({start:`${year}-${String(sm).padStart(2,'0')}-${String(sd).padStart(2,'0')}`,end:`${year}-${String(em).padStart(2,'0')}-${String(ed).padStart(2,'0')}`,label});
 if(COOL_FALL.has(cropId))return make(8,1,9,15,'Green Bay fall planting window');
 if(cropId==='garlic')return make(9,20,10,25,'Green Bay fall garlic window');
 if(PERENNIALS.has(cropId))return make(4,15,9,15,'Spring through early-fall establishment window');
 if(['marigold','nasturtium','calendula','sweet-alyssum'].includes(cropId))return make(5,15,7,31,'Warm-season flower window');
 if(LONG_SEASON.has(cropId))return make(2,15,4,1,'Indoor-start window');
 return make(5,15,7,15,'Green Bay outdoor planting window');
}

const MONTHS={january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12};
function profileDateKey(value,fallback,year){const text=String(value||fallback).trim(),match=text.match(/([a-z]+)\s+(\d{1,2})/i),month=MONTHS[String(match?.[1]||'').toLowerCase()]||MONTHS[String(fallback).split(/\s+/)[0].toLowerCase()],day=Number(match?.[2]||String(fallback).match(/\d+/)?.[0]||1);return`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
function packetTitle(packet={},crop={}){return[packet.brand,packet.variety||packet.name||crop.name].filter(Boolean).join(' ')||crop.name||'Saved seed packet'}
function spaceSummary(garden,crop,method){const spaces=suitableSpaces(garden,crop,method);return spaces[0]?{id:spaces[0].id,name:spaces[0].name,warnings:spaces[0].warnings||[]}:null}
function harvestWindow(startKey,packet,crop){const days=firstNumber(packet?.daysToMaturity)||firstNumber(crop?.harvest);if(!days)return'';return formatGardenDateRange(addDays(startKey,days),addDays(startKey,days+14))}
function readinessStatus(today,start,end,fallStart=''){if(today>=start&&today<=end)return'ready-now';if(today<start)return dayDeltaFor(today,start)<=30?'outdoor-approaching':'wait-schedule';if(fallStart&&today<fallStart)return'wait-schedule';return'missed-window'}
function dayDeltaFor(from,to){return Math.round((new Date(`${dateKey(to)}T12:00:00`)-new Date(`${dateKey(from)}T12:00:00`))/DAY)}

export function plantingReadinessForPacket({packet={},garden={},weather=null,date=new Date()}={}){
 const cropId=inferCropId(packet),crop=catalogRows().find(row=>row.id===cropId)||{id:cropId,name:packet.name||'Saved packet',harvest:packet.daysToMaturity?`${packet.daysToMaturity} days`:''},year=date.getFullYear(),today=dateKey(date),lastFrost=profileDateKey(garden.profile?.lastFrost,'May 15',year),firstFrost=profileDateKey(garden.profile?.firstFrost,'October 10',year),defaults=timingDefaults(cropId,packet),indoorStart=addWeeksKey(lastFrost,-defaults.indoorBefore),transplantDate=addWeeksKey(lastFrost,defaults.transplantAfter),directSowDate=addWeeksKey(lastFrost,defaults.directAfter),fallPlantingDate=defaults.fallBefore>0?addWeeksKey(firstFrost,-defaults.fallBefore):'',isLong=LONG_SEASON.has(cropId),isDirect=DIRECT_SOW.has(cropId),method=cropId==='potato'?'Plant Seed Potatoes':isLong?'Start Indoors':isDirect?'Direct Sow':'Buy Transplants';
 let start=isLong?indoorStart:directSowDate,end=isLong?addDays(indoorStart,21):addDays(directSowDate,cropId==='potato'?42:45),label='WAIT AND SCHEDULE',action=`Schedule ${method.toLowerCase()} for ${formatGardenDateRange(start,start)}.`,reason='This uses the saved packet, Green Bay frost timing, and crop-level defaults.';
 if(fallPlantingDate&&COOL_FALL.has(cropId)&&today>addDays(directSowDate,45)){start=fallPlantingDate;end=addDays(fallPlantingDate,30);reason='The spring window has passed, so the next realistic saved-packet opportunity is the fall planting window.'}
 const statusKey=readinessStatus(today,start,end,fallPlantingDate),weatherReadiness=assessPlantingWeatherReadiness({method,cropId,seasonallySuitable:statusKey!=='missed-window',weather}),suggestedSpace=spaceSummary(garden,crop,method);
 if(statusKey==='ready-now'){label='READY NOW';action=weatherReadiness?.status&&/wait|delay|risk/i.test(`${weatherReadiness.status} ${weatherReadiness.explanation}`)?`Use the next calm window, then ${method.toLowerCase()} from this packet.`:`${method} from this saved packet now.`}
 else if(statusKey==='outdoor-approaching'){label='COMING UP';action=`Get supplies and space ready for ${formatGardenDateRange(start,start)}.`}
 else if(statusKey==='missed-window'){label='MISSED WINDOW';action=isLong?'Do not start this packet from seed for the current outdoor season; save it for next spring or use a healthy transplant.':'Save this packet for the next realistic planting window.';reason='The normal packet-starting window has passed for a reliable Green Bay result.'}
 return{packetId:packet.id||'',cropId,statusKey,label,method,action,recommendedDate:start,windowStart:start,windowEnd:end,indoorStart,transplantDate,directSowDate,fallPlantingDate,expectedHarvestWindow:harvestWindow(isLong?transplantDate:start,packet,crop),reason,weatherNote:weatherReadiness?.explanation||'',suggestedSpace,title:packetTitle(packet,crop),packetFacts:[packet.daysToMaturity&&`${packet.daysToMaturity} days to maturity`,packet.germinationEstimate&&`germinates ${packet.germinationEstimate}`,packet.depth&&`plant ${packet.depth} deep`,packet.spacing&&`${packet.spacing} spacing`].filter(Boolean)};
}

function currentAction(crop,packet,weather,date=new Date(),garden={}){
 const id=crop.id,window=seasonWindow(id,date),today=dateKey(date),maturity=firstNumber(packet?.daysToMaturity)||firstNumber(crop.harvest)||60,remaining=daysRemaining(date),weatherPoor=Boolean(weather?.signals?.poorPlantingWindow?.status),existingSeedling=(garden.plants||[]).find(plant=>!plant.deletedAt&&!plant.archived&&plant.cropId===id&&['Seedling','Potted Up','Hardening Off'].includes(plant.stage));
 if(existingSeedling)return{method:'Transplant Existing Seedlings',status:weatherPoor?'Plant during the next suitable window':'Transplant an existing seedling',action:weatherPoor?'Wait for the next calm, moderate planting window, then transplant the saved seedling.':'Transplant the existing seedling when its hardening and space are ready.',group:'Transplant Existing Seedlings',window,priority:98,realistic:true};
 if(TRANSPLANT_ONLY_NOW.has(id)){
  const transplantDays=Math.max(45,maturity);
  if(remaining<transplantDays+7)return{method:'Not This Season',status:'Too late this season',action:'Do not start from seed or buy a late transplant now. Save this crop for spring planning.',group:'Not This Season',window,priority:15,realistic:false,risk:`Only about ${remaining} frost-free days remain.`};
  return{method:'Buy Transplants',status:weatherPoor?'Plant during the next suitable window':'Buy a transplant now',action:weatherPoor?'Choose a healthy nursery transplant, but wait for a calmer planting window.':'Buy a healthy, compact transplant and plant it promptly.',group:'Buy Transplants',window,priority:86,realistic:true};
 }
 if(PERENNIALS.has(id)){if(today<=window.end)return{method:'Perennials and Plants',status:weatherPoor?'Plant during the next suitable window':'Plant now',action:weatherPoor?'Choose a healthy plant and wait for a moderate establishment window.':'Buy or divide a healthy plant and establish it now.',group:'Perennials and Plants',window,priority:70,realistic:true};return{method:'Save for Later',status:'Save for spring',action:'Plan this perennial for spring establishment.',group:'Save for Later',window:{...window,start:`${date.getFullYear()+1}-04-15`,end:`${date.getFullYear()+1}-06-15`},priority:30,realistic:true}}
 if(POLLINATORS.has(id)&&!DIRECT_SOW.has(id))return{method:'Buy Transplants',status:'Buy a transplant now',action:'Choose a healthy flowering plant with accessible single or semi-double blooms.',group:'Buy Transplants',window,priority:62,realistic:true};
 if(today<window.start)return{method:LONG_SEASON.has(id)?'Start Indoors':DIRECT_SOW.has(id)?'Direct Sow':'Buy Transplants',status:`Wait until ${formatGardenDateRange(window.start,window.end)}`,action:LONG_SEASON.has(id)?'Save for the indoor-start window.':`Wait for the recommended window, then ${DIRECT_SOW.has(id)?'direct sow':'use a transplant'}.`,group:'Save for Later',window,priority:40,realistic:true};
 if(today>window.end){
  if(COOL_FALL.has(id)){const next={...window,start:`${date.getFullYear()+1}-08-01`,end:`${date.getFullYear()+1}-09-15`};return{method:'Save for Later',status:'Save for fall',action:'This fall window has passed. Save it for the next cool-season window.',group:'Save for Later',window:next,priority:35,realistic:true}}
  if(DIRECT_SOW.has(id)&&maturity<=remaining-14)return{method:'Direct Sow',status:weatherPoor?'Plant during the next suitable window':'Plant now',action:weatherPoor?'Wait for the next suitable weather window, then direct sow.':'Direct sow now and keep the seed zone evenly moist.',group:POLLINATORS.has(id)?'Pollinator and Companion Plants':'Direct Sow',window,priority:78,realistic:true};
  return{method:'Not This Season',status:'Too late this season',action:'The remaining season is unlikely to support a reliable harvest. Save this crop for next year.',group:'Not This Season',window,priority:10,realistic:false,risk:`About ${maturity} days are needed and only about ${remaining} frost-free days remain.`};
 }
 if(LONG_SEASON.has(id))return{method:'Start Indoors',status:'Start indoors now',action:'Start indoors under strong light, then transplant after hardening when the outdoor window arrives.',group:'Start Indoors',window,priority:84,realistic:true};
 if(DIRECT_SOW.has(id)){if(maturity>remaining-14)return{method:'Not This Season',status:'Too late this season',action:'Do not direct sow now; maturity before frost is unlikely.',group:'Not This Season',window,priority:12,realistic:false,risk:`About ${maturity} days are needed and only about ${remaining} frost-free days remain.`};return{method:'Direct Sow',status:weatherPoor?'Plant during the next suitable window':'Plant now',action:weatherPoor?'Wait for the next moderate, lower-risk weather window, then direct sow.':'Direct sow now in the selected Growing Space.',group:POLLINATORS.has(id)?'Pollinator and Companion Plants':'Direct Sow',window,priority:90,realistic:true}}
 return{method:'Buy Transplants',status:weatherPoor?'Plant during the next suitable window':'Buy a transplant now',action:weatherPoor?'Choose a healthy transplant and wait for a better planting window.':'Buy a healthy transplant and plant it now.',group:'Buy Transplants',window,priority:75,realistic:true};
}

function traitsFor(crop,packet){const guide=GUIDANCE[crop.id]||{};return packet?.variety?[`Saved variety: ${packet.variety}`,...(guide.traits||[])]:guide.traits||['short season','locally appropriate','matched to the selected Growing Space']}
function recommendationCard({crop,packet=null,garden,weather,source='discovery'}){
 const guide=GUIDANCE[crop.id]||{},action=currentAction(crop,packet,weather,new Date(),garden),spaces=suitableSpaces(garden,crop,action.method),subjectKey=packet?packetKey(packet):`catalog-${crop.id}`,decision=decisionMap(garden).get(subjectKey),owned=Boolean(packet),windowText=formatGardenDateRange(action.window.start,action.window.end),title=packet?[packet.brand,packet.variety||packet.name].filter(Boolean).join(' ')||packet.name:guide.type||crop.name,subtitle=guide.type&&title!==guide.type?guide.type:guide.use||crop.summary||'',weatherReadiness=assessPlantingWeatherReadiness({method:action.method,cropId:crop.id,seasonallySuitable:action.realistic,weather}),weatherReason=weatherReadiness.explanation,risks=[action.risk,...(spaces[0]?.warnings||[])].filter(Boolean);
 return{id:subjectKey,subjectKey,source,owned,packet,crop,cropId:crop.id,cropName:crop.name,variety:packet?.variety||'',brand:packet?.brand||'',title,subtitle,statusLabel:owned?'Owned Seed':action.method==='Buy Transplants'?'Transplant Needed':action.method==='Perennials and Plants'?'Plant Available':'Seeds Needed',status:action.status,actionNow:action.action,method:action.method,group:decision?.decision==='later'?'Save for Later':decision?.decision==='not-this-season'?'Not This Season':action.group,date:decision?.decision==='later'&&decision.dueDate?decision.dueDate:action.window.start,windowEnd:action.window.end,timing:decision?.decision==='later'?`Review ${formatGardenDateRange(decision.dueDate,decision.dueDate)}`:windowText,recommendedWindow:windowText,reason:guide.use||crop.summary||'A locally appropriate garden option.',whyGreenBay:action.realistic?`${action.status}. The method and maturity are matched to Green Bay’s remaining season.`:'The remaining Green Bay season does not support a reliable result.',uncertainty:owned?'Use the exact packet directions when they are more specific than general guidance.':'Choose a packet or plant with the listed traits; no matching owned packet is currently saved.',traits:traitsFor(crop,packet),examples:guide.examples||[],harvestTime:packet?.daysToMaturity?`${packet.daysToMaturity} days to maturity`:guide.harvest||crop.harvest||'Variety dependent',commonUse:guide.use||crop.summary||'',spaces,weatherReadiness,weatherNote:weatherReason,needs:owned?'Owned seed packet':action.method==='Buy Transplants'||action.method==='Perennials and Plants'?'Plant or transplant needed':'Seeds needed',confidence:owned&&action.realistic?'High':action.realistic?'Medium':'High',risks,priority:action.priority+(owned?10:0),decision,strongNow:action.realistic&&['Plant now','Buy a transplant now','Start indoors now','Transplant an existing seedling','Plant during the next suitable window'].includes(action.status)};
}

function catalogRows(recommendations=[]){const map=new Map([...cropCatalog,...DISCOVERY].map(crop=>[crop.id,crop]));for(const row of recommendations)map.set(row.id,{...map.get(row.id),...row});return[...map.values()]}
function filterDecision(card){const decision=card.decision;if(decision?.decision==='not-this-season')return{...card,group:'Not This Season',status:'Not this season',actionNow:'This opportunity was removed from the current season.'};if(decision?.decision==='later'&&decision.dueDate>todayKey())return{...card,group:'Save for Later',status:'Saved for later',actionNow:`Review this opportunity on ${formatGardenDateRange(decision.dueDate,decision.dueDate)}.`};return card}

export function groupPlantingRecommendations(cards=[]){const order=['Direct Sow','Start Indoors','Buy Transplants','Transplant Existing Seedlings','Perennials and Plants','Pollinator and Companion Plants','Indoor Growing','Save for Later','Not This Season'],descriptions={'Direct Sow':'Seeds planted directly in a bed or container','Start Indoors':'Seeds that need protected indoor growth first','Buy Transplants':'Healthy nursery plants are the realistic present option','Transplant Existing Seedlings':'Saved seedlings ready for their next move','Perennials and Plants':'Established plants, divisions, and long-term crops','Pollinator and Companion Plants':'Useful flowers and garden-supporting plants','Indoor Growing':'Crops that can continue under suitable lights','Save for Later':'Worth keeping for the next realistic window','Not This Season':'Opportunities rejected to avoid false optimism'};return order.map(name=>({name,description:descriptions[name],items:cards.filter(card=>card.group===name).sort((a,b)=>b.priority-a.priority||a.title.localeCompare(b.title))})).filter(group=>group.items.length)}

export function buildGrowNowRecommendations({garden,recommendations=[],weather=null}){
 const inventory=seedInventory(garden),byCrop=new Map(inventory.map(packet=>[packet.cropId,[...(byCropPlaceholder(inventory,packet.cropId))]])),cards=[];
 for(const packet of inventory){if(!packet.cropId||packetAlreadyStarted(garden,packet))continue;const crop=catalogRows(recommendations).find(row=>row.id===packet.cropId);if(crop)cards.push(filterDecision(recommendationCard({crop,packet,garden,weather,source:packet.exactPacket?'owned-packet':'owned-seed-record'})))}
 const ownedIds=new Set(inventory.map(packet=>packet.cropId));
 for(const crop of catalogRows(recommendations)){if(ownedIds.has(crop.id)||cropAlreadyPlanned(garden,crop.id))continue;cards.push(filterDecision(recommendationCard({crop,garden,weather,source:DISCOVERY.some(row=>row.id===crop.id)?'discovery':'catalog'})))}
 const unique=new Map();for(const card of cards){const current=unique.get(card.subjectKey);if(!current||card.priority>current.priority)unique.set(card.subjectKey,card)}
 const all=[...unique.values()].sort((a,b)=>b.priority-a.priority||a.title.localeCompare(b.title)),actionable=all.filter(card=>!['Save for Later','Not This Season'].includes(card.group)).slice(0,16),later=all.filter(card=>card.group==='Save for Later').slice(0,4),rejected=all.filter(card=>card.group==='Not This Season').slice(0,4),ordered=[...actionable,...later,...rejected];
 return{cards:ordered,groups:groupPlantingRecommendations(ordered),owned:ordered.filter(card=>card.owned),purchases:ordered.filter(card=>!card.owned),next:ordered.find(card=>card.group==='Save for Later')||null};
}
function byCropPlaceholder(inventory,cropId){return inventory.filter(packet=>packet.cropId===cropId)}

export function buildPlanAheadRecommendations({garden,recommendations=[],weather=null}){const result=buildGrowNowRecommendations({garden,recommendations,weather});return result.cards.filter(card=>['Save for Later','Not This Season'].includes(card.group)||!card.strongNow).sort((a,b)=>String(a.date).localeCompare(String(b.date))||b.priority-a.priority)}

export function plantingActionLabel(item,plant){const stage=String(plant?.stage||'');if(item.task?.taskType==='Harden Off'||/hardening/i.test(`${item.type||''} ${item.title||''}`))return'Complete Today’s Step';if(item.type==='succession')return'Start Next Batch';if(item.type==='transplant')return'Mark as Transplanted';if(item.type==='pot-up')return'Mark as Potted Up';if(item.type==='space-prep')return'Prepare Space';if(item.type==='support')return'Install Support';if(item.type==='stage'){if(stage==='Planned')return'Mark Seed Purchased';if(stage==='Seed Purchased')return'Start Seeds';if(stage==='Seed Started')return'Mark Germinating';if(stage==='Germinating')return'Mark Seedling';if(stage==='Seedling')return'Mark as Potted Up';if(stage==='Potted Up')return'Begin Hardening Off';if(stage==='Hardening Off')return'Complete Today’s Step'}return'Open Plant'}
export function plantingItems(timeline=[],{tasks=[],garden={},completions=[]}={}){const decisions=decisionMap(garden),completedIds=new Set((completions||[]).map(item=>typeof item==='string'?item:item.id)),items=[];timeline.filter(item=>!item.historical&&!item.informational&&['stage','succession','planting','transplant','hardening','pot-up','space-prep','support'].includes(item.type)).forEach(item=>{const decision=decisions.get(item.id);if(decision?.decision==='not-this-season')return;items.push({...item,date:decision?.decision==='later'&&decision.dueDate?decision.dueDate:item.date,decision,confirmed:Boolean(decision?.decision==='later')})});tasks.filter(task=>!completedIds.has(task.id)&&!task.weatherDriven&&(PLANTING_TASK_TYPES.has(task.taskType)||task.kind==='seasonalGuide'||task.kind==='setupPlant')).forEach(task=>{const subjectKey=`task-${task.id}`,decision=decisions.get(subjectKey);if(decision?.decision==='not-this-season')return;items.push({id:subjectKey,subjectKey,type:'task',task,plantId:task.plant?.id||'',date:decision?.decision==='later'&&decision.dueDate?decision.dueDate:task.dueDate,title:task.title,detail:task.subtitle||task.reason||'',reason:task.reason||'',priority:task.priority||50,confirmed:Boolean(task.manual||decision?.decision==='later'),estimated:!task.manual,decision})});const unique=new Map();items.forEach(item=>{const plant=(garden.plants||[]).find(entry=>entry.id===item.plantId),kind=item.type==='task'?item.task?.taskType:item.type==='stage'&&plant?.stage==='Hardening Off'?'Harden Off':item.type,key=`${item.plantId||item.id}|${normalize(kind)}|${dateKey(item.date)}`,current=unique.get(key);if(!current||item.type==='task'||Number(item.priority)>Number(current.priority))unique.set(key,item)});return[...unique.values()].sort((a,b)=>dateKey(a.date).localeCompare(dateKey(b.date))||Number(b.priority||0)-Number(a.priority||0))}
export function recentPlantUpdates(timeline=[]){return timeline.filter(item=>item.type==='lifecycle'||item.historical||item.informational).sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
export function createPlantingDecision({subjectKey,decision,dueDate='',note=''},actor='System'){const now=new Date().toISOString();return{id:newId('planting-decision'),subjectKey,decision,dueDate:dueDate||todayKey(),note,actor,at:now,createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor,revision:1,deletedAt:null}}
