import React,{useMemo,useState}from'react';
import{CalendarClock,CalendarDays,Leaf,PackageSearch,Sprout}from'lucide-react';
import PlantRecommendations from'./PlantRecommendations.jsx';
import YearPlanner from'./YearPlanner.jsx';
import{daysFromNow,prettyDate,seedStatusForCrop}from'./planning.js';

function PlanList({items,garden,completePlanItem,updatePlantStage,recordHarvest,scheduleSuccession}){return <div className="desk-plan-list">{items.map(item=>{const plant=garden.plants.find(p=>p.id===item.plantId),seed=item.type==='succession'?seedStatusForCrop(garden,item.cropId||plant?.cropId):null;return <article key={item.id} className={`desk-plan-card plan-type-${item.type}`}><div className="desk-plan-date"><strong>{prettyDate(item.date)}</strong><small>{daysFromNow(item.date)===0?'Today':daysFromNow(item.date)===1?'Tomorrow':`In ${daysFromNow(item.date)} days`}</small></div><div className="desk-plan-copy"><h3>{item.title}</h3><p>{item.detail}</p>{item.type==='succession'&&<div className={`succession-seed-status tone-${seed?.tone||'red'}`}>{seed?.seed?<><Sprout/><span><strong>{seed.seed.variety||seed.seed.name}</strong><small>{seed.label} · packet {seed.seed.packetYear||'year unknown'}</small></span></>:<><PackageSearch/><span><strong>No matching seed recorded</strong><small>Add a packet at the Seed Counter before this batch is due.</small></span></>}</div>}</div><div className="desk-plan-actions">{item.type==='stage'&&plant&&<button onClick={()=>updatePlantStage(plant.id)}>Update stage</button>}{item.type==='harvest'&&plant&&<button onClick={()=>recordHarvest(plant.id)}>Log harvest</button>}{item.type==='succession'&&plant&&<button onClick={()=>scheduleSuccession(plant.id,true)}>{seed?.seed?'Start next batch':'Review seed need'}</button>}<button className="plan-done" onClick={()=>completePlanItem(item)}>Done</button></div></article>})}{!items.length&&<div className="all-clear desk-empty"><Leaf/><span><strong>Nothing scheduled in this window.</strong><small>The desk will fill from plants, seed starts, succession plans, and seasonal work.</small></span></div>}</div>}

export default function PlanPlantHub(props){const[view,setView]=useState('week'),timeline=props.timeline||[];const week=useMemo(()=>timeline.filter(i=>{const d=daysFromNow(i.date);return d>=0&&d<=7}),[timeline]);const soon=useMemo(()=>timeline.filter(i=>{const d=daysFromNow(i.date);return d>=8&&d<=45}),[timeline]);const tabs=[['week','This week','Next 7 days',CalendarDays],['grow','Grow now','Seasonal ideas',Leaf],['soon','Coming soon','Days 8–45',CalendarClock],['next','Next year','Future garden',Sprout]];return <main className="screen planting-desk-page"><section className="dark-header planting-desk-header"><span>THE RUNYAN GARDEN THINKS AHEAD</span><h1>Planting Desk</h1><p>One place for this week, seasonal opportunities, future work, and next year’s garden.</p></section><section className="screen-pad planting-desk-body"><div className="planting-desk-tabs" role="tablist">{tabs.map(([id,label,sub,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'auto'}))}}><Icon/><span><strong>{label}</strong><small>{sub}</small></span></button>)}</div>{view==='week'&&<section className="desk-panel"><div className="desk-section-intro"><span className="section-kicker">TODAY THROUGH DAY 7</span><h2>This week’s planting work</h2><p>Only work inside the next seven days appears here.</p></div><PlanList items={week} {...props}/></section>}{view==='soon'&&<section className="desk-panel"><div className="desk-section-intro"><span className="section-kicker">DAY 8 THROUGH DAY 45</span><h2>Prepare before it becomes urgent</h2><p>Seed starts, transplant preparation, succession batches, and seasonal windows after this week.</p></div><PlanList items={soon} {...props}/></section>}{view==='grow'&&<section className="desk-panel"><PlantRecommendations embedded recommendations={props.recommendations} setModal={props.setModal}/></section>}{view==='next'&&<section className="desk-panel"><YearPlanner garden={props.garden} saveYearPlan={props.saveYearPlan}/></section>}</section></main>}
