import{fieldSourceLabel}from'./connectedIntelligence.js';

const normalize=value=>String(value??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const exact=value=>normalize(value);
const now=()=>new Date().toISOString();

export const OFFICIAL_SEED_PRODUCTS=[
 {id:'burpee-prod000747',officialProductId:'prod000747',brand:'Burpee',crop:'Lettuce',cropId:'lettuce',variety:'Iceberg A',productName:'Iceberg A Lettuce Seeds',category:'vegetable',sourceName:'Burpee official product page',sourceUrl:'https://www.burpee.com/lettuce-iceberg-a-prod000747.html',guideSourceName:'Burpee official lettuce growing guide',guideUrl:'https://support.burpee.com/support/solutions/articles/60000961783-learn-about-lettuce',identityAliases:['lettuce iceberg a','iceberg a lettuce','burpee iceberg a'],productFields:{daysToMaturity:85,plantHeight:'9–15 inches',plantSpread:'6 inches',sunlight:'Full sun',notableClaims:'Crisphead lettuce · thrives in cooler weather'},guideFields:{depth:'1/4 inch',rowSpacing:'12 inches',thinningSpacing:'8 inches',germinationEstimate:'7–10 days',sowingMethod:'Direct sow',directSowGuidance:'Sow in average soil in full sun in early spring and again in late summer for a fall crop.',seasonalWindow:'Early spring and late summer for fall harvest',waterGuidance:'Keep evenly moist. Water deeply during dry periods unless regular rainfall has supplied enough moisture.',soilGuidance:'Average, well-drained soil enriched with organic matter',successionGuidance:'Sow every two weeks to extend the harvest',harvestGuidance:'Harvest when the head is firm and full-sized; cooler weather supports better quality.',containerSuitability:'Suitable when the container provides enough space for a crisphead lettuce plant.'}},
 {id:'burpee-green-ice',officialProductId:'prod000738',brand:'Burpee',crop:'Lettuce',cropId:'lettuce',variety:'Green Ice',productName:'Green Ice Lettuce Seeds',category:'vegetable',sourceName:'Burpee official product catalog',sourceUrl:'https://www.burpee.com/vegetables/lettuce/',identityAliases:['lettuce green ice','green ice lettuce'],productFields:{sunlight:'Full sun'}},
 {id:'burpee-bibb',officialProductId:'burpee-bibb',brand:'Burpee',crop:'Lettuce',cropId:'lettuce',variety:'Burpee Bibb',productName:'Burpee Bibb Lettuce Seeds',category:'vegetable',sourceName:'Burpee official product catalog',sourceUrl:'https://www.burpee.com/vegetables/lettuce/',identityAliases:['burpee bibb lettuce','lettuce burpee bibb'],productFields:{designations:['Heirloom']}}
];

export function seedLookupIdentity(draft={}){return{brand:draft.brand||'',crop:draft.name||draft.cropName||'',cropId:draft.cropId||'',variety:draft.variety||'',productName:draft.productName||'',barcode:draft.barcode||'',sku:draft.sku||draft.officialProductId||'',packetYear:draft.packetYear||'',rawText:[draft.packetIntelligence?.front?.rawText,draft.packetIntelligence?.back?.rawText].filter(Boolean).join('\n')}}
const textScore=(actual,expected,weight)=>{const a=exact(actual),b=exact(expected);if(!a||!b)return 0;if(a===b)return weight;if(a.includes(b)||b.includes(a))return weight*.72;const tokens=new Set(a.split(' ')),other=b.split(' '),overlap=other.filter(token=>tokens.has(token)).length/Math.max(1,other.length);return overlap>=.75?weight*.55:0};
export function scoreSeedProduct(identity={},product={}){let score=0,reasons=[];if(identity.barcode&&product.barcode&&normalize(identity.barcode)===normalize(product.barcode)){score+=100;reasons.push('exact barcode')}if(identity.sku&&product.officialProductId&&normalize(identity.sku)===normalize(product.officialProductId)){score+=90;reasons.push('exact product ID')}const brand=textScore(identity.brand,product.brand,20);if(brand){score+=brand;reasons.push('brand')}const crop=textScore(identity.crop||identity.cropId,product.crop||product.cropId,22);if(crop){score+=crop;reasons.push('crop')}const variety=textScore(identity.variety,product.variety,38);if(variety){score+=variety;reasons.push('variety')}const productName=textScore(identity.productName,product.productName,24);if(productName){score+=productName;reasons.push('product name')}const raw=normalize(identity.rawText);if(raw&&product.identityAliases?.some(alias=>raw.includes(normalize(alias)))){score+=36;reasons.push('packet text')}return{score:Math.round(score),reasons,exact:score>=70&&Boolean(brand&&crop&&(variety||productName||raw))}}

const cacheKey=identity=>`runyan-seed-product-lookup:${[identity.brand,identity.crop,identity.variety,identity.barcode,identity.sku].map(normalize).join('|')}`;
const readCache=key=>{try{const row=JSON.parse(sessionStorage.getItem(key)||'null');if(row&&Date.now()-new Date(row.cachedAt).getTime()<86400000)return row}catch{}return null};
const writeCache=(key,value)=>{try{sessionStorage.setItem(key,JSON.stringify({...value,cachedAt:now()}))}catch{}};
async function verifyOfficialSource(product,fetcher=globalThis.fetch){if(!fetcher||!product.sourceUrl)return{reachable:false};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),6000);try{const response=await fetcher(product.sourceUrl,{method:'GET',signal:controller.signal,mode:'cors'});return{reachable:Boolean(response?.ok),status:response?.status||0}}catch{return{reachable:false}}finally{clearTimeout(timer)}}
export async function lookupSeedProducts(identity={},options={}){const key=cacheKey(identity),cached=typeof sessionStorage!=='undefined'&&!options.ignoreCache?readCache(key):null;if(cached)return cached;const ranked=OFFICIAL_SEED_PRODUCTS.map(product=>({...product,match:scoreSeedProduct(identity,product)})).filter(product=>product.match.score>=20).sort((a,b)=>b.match.score-a.match.score),candidates=ranked.slice(0,4);let liveVerification={reachable:false};if(candidates[0]?.match.exact&&options.verifyOnline!==false)liveVerification=await verifyOfficialSource(candidates[0],options.fetcher);const result={identity,candidates,exactCandidate:candidates.find(candidate=>candidate.match.exact)||null,liveVerification,lookedUpAt:now(),source:'official-product-index'};if(typeof sessionStorage!=='undefined')writeCache(key,result);return result}

const onlineMeta=(product,field,value,detail='official-product')=>({source:'online',sourceDetail:detail,sourceLabel:detail==='official-product'?'Found online · official product page':'Found online · official growing guide',confidence:'High',sourceUrl:detail==='official-product'?product.sourceUrl:product.guideUrl||product.sourceUrl,sourceName:detail==='official-product'?product.sourceName:product.guideSourceName||product.sourceName,exactProductId:product.officialProductId,originalText:String(value),extractedAt:now(),manuallyCorrected:false,correctedAt:null});
const same=(a,b)=>normalize(Array.isArray(a)?a.join(' '):a)===normalize(Array.isArray(b)?b.join(' '):b);
export function applySeedProductCandidate(draft={},product={}){let next={...draft,fieldMeta:{...(draft.fieldMeta||{})},packetIntelligence:{...(draft.packetIntelligence||{}),onlineLookup:{exactProductId:product.officialProductId,productId:product.id,sourceName:product.sourceName,sourceUrl:product.sourceUrl,guideSourceName:product.guideSourceName,guideUrl:product.guideUrl,matchedAt:now(),match:product.match||null},conflicts:[...(draft.packetIntelligence?.conflicts||[])]},exactProductId:product.officialProductId,onlineSourceUrl:product.sourceUrl};const fields={brand:product.brand,name:product.crop,cropId:product.cropId,variety:product.variety,productName:product.productName,category:product.category,...(product.productFields||{})},guide=product.guideFields||{};for(const [key,value] of Object.entries({...fields,...guide})){if(value===undefined||value===null||value==='')continue;const current=next[key],meta=next.fieldMeta[key]||{},detail=Object.prototype.hasOwnProperty.call(guide,key)?'official-guide':'official-product',incoming=onlineMeta(product,key,value,detail);if(meta.source==='manual'||meta.manuallyCorrected){continue}if(current!==''&&current!==null&&current!==undefined&&!same(current,value)){const conflict={field:key,activeValue:current,activeSource:fieldSourceLabel(meta),onlineValue:value,onlineSource:incoming.sourceLabel,sourceUrl:incoming.sourceUrl,detectedAt:now(),status:'needs-review'};next.packetIntelligence.conflicts=[...next.packetIntelligence.conflicts.filter(row=>row.field!==key||row.status==='resolved'),conflict];if(meta.source==='packet'&&meta.confidence!=='Low')continue}next={...next,[key]:value,fieldMeta:{...next.fieldMeta,[key]:incoming}}}return next}
export function resolveSeedConflict(draft={},fieldName,choice='active'){const conflicts=draft.packetIntelligence?.conflicts||[],conflict=conflicts.find(row=>row.field===fieldName&&row.status!=='resolved');if(!conflict)return draft;let next=draft;if(choice==='online')next={...draft,[fieldName]:conflict.onlineValue,fieldMeta:{...(draft.fieldMeta||{}),[fieldName]:{...(draft.fieldMeta?.[fieldName]||{}),source:'online',sourceLabel:conflict.onlineSource,sourceUrl:conflict.sourceUrl,confidence:'High',manuallyCorrected:false,correctedAt:null}}};else next={...draft,fieldMeta:{...(draft.fieldMeta||{}),[fieldName]:{...(draft.fieldMeta?.[fieldName]||{}),source:'corrected',confidence:'High',manuallyCorrected:true,correctedAt:now()}}};return{...next,packetIntelligence:{...(next.packetIntelligence||{}),conflicts:conflicts.map(row=>row===conflict?{...row,status:'resolved',resolution:choice,resolvedAt:now()}:row)}}}
