const API_TIMEOUT=Number(import.meta.env?.VITE_SEED_PACKET_ANALYSIS_TIMEOUT_MS)||120000;
const CACHE_PREFIX='runyan-seed-vision-result:v1:';
const DEVICE_KEY='runyan-garden-device-id';
const imageType=new Set(['image/jpeg','image/png','image/webp']);

const readDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('The selected photo could not be read.'));reader.readAsDataURL(file)});
const imageFrom=value=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('The selected photo could not be opened.'));image.src=value});
async function resize(dataUrl,{maxDimension,quality}){const image=await imageFrom(dataUrl),scale=Math.min(1,maxDimension/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d',{alpha:false});context.fillStyle='#fff';context.fillRect(0,0,width,height);context.drawImage(image,0,0,width,height);const output=canvas.toDataURL('image/jpeg',quality);return{dataUrl:output,width,height,bytes:Math.ceil(output.length*.75),mimeType:'image/jpeg'}}
async function hashText(value){const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
export async function preparePacketPhoto(file){if(!file||!imageType.has(file.type))throw new Error('Use a JPEG, PNG, or WebP packet photo.');if(file.size>25*1024*1024)throw new Error('This packet photo is too large. Choose a smaller photo.');const original=await readDataUrl(file),[display,analysis]=await Promise.all([resize(original,{maxDimension:1600,quality:.8}),resize(original,{maxDimension:3200,quality:.92})]),hash=await hashText(analysis.dataUrl);return{displayPhoto:display.dataUrl,analysisPhoto:analysis.dataUrl,hash,meta:{originalBytes:file.size,displayBytes:display.bytes,analysisBytes:analysis.bytes,width:analysis.width,height:analysis.height,mimeType:file.type}}}
export function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_KEY,id)}return id}
export async function packetVisionHealth(){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch('/api/health',{signal:controller.signal,headers:{accept:'application/json'}});if(!response.ok)return{ok:false,configured:false};const json=await response.json();return{ok:Boolean(json.apiService),configured:Boolean(json.packetVisionConfigured),version:json.version||'',buildId:json.buildId||''}}catch{return{ok:false,configured:false}}finally{clearTimeout(timer)}}
function cacheKey(frontHash,backHash,draftId=''){return`${CACHE_PREFIX}${frontHash}|${backHash}|${draftId}`}
export function loadCachedPacketAnalysis(frontHash,backHash,draftId=''){try{const key=cacheKey(frontHash,backHash,draftId),row=JSON.parse(sessionStorage.getItem(key)||'null');if(row&&Date.now()-row.savedAt<6*60*60*1000)return row.result}catch{}return null}
export function storeCachedPacketAnalysis(frontHash,backHash,draftId,result){try{sessionStorage.setItem(cacheKey(frontHash,backHash,draftId),JSON.stringify({savedAt:Date.now(),result}))}catch{}}
export async function analyzePacketPhotos({frontImage,backImage,frontHash='',backHash='',draftContext={},force=false}){if(!frontImage||!backImage)throw new Error('Add both packet photos before analyzing.');if(!force){const cached=loadCachedPacketAnalysis(frontHash,backHash,draftContext.draftId);if(cached)return{...cached,cacheHit:true}}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),API_TIMEOUT);try{const response=await fetch('/api/seed-packets/analyze',{method:'POST',signal:controller.signal,headers:{'content-type':'application/json','x-device-id':deviceId()},body:JSON.stringify({frontImage,backImage,draftContext,photoHashes:{front:frontHash,back:backHash}})}),json=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(json?.error?.message||'Packet analysis could not finish.');error.code=json?.error?.code||'analysis_failed';error.requestId=json?.error?.requestId||'';throw error}storeCachedPacketAnalysis(frontHash,backHash,draftContext.draftId,json);return json}catch(error){if(error.name==='AbortError'){const timeout=new Error('Packet analysis could not finish. Try again when the connection is stable.');timeout.code='network_timeout';throw timeout}throw error}finally{clearTimeout(timer)}}
