import{fieldSourceLabel}from'./connectedIntelligence.js';
import{isTrustedPacketValue}from'./seedPacketIntelligence.js';

const normalize=value=>String(value??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const now=()=>new Date().toISOString();
const CACHE_PREFIX='runyan-seed-product-cache:v2:';
const CACHE_TTL=7*24*60*60*1000;

export const OFFICIAL_SEED_PRODUCTS=[
 {id:'burpee-prod000747',officialProductId:'prod000747',brand:'Burpee',crop:'Lettuce',cropId:'lettuce',variety:'Iceberg A',productName:'Iceberg A Lettuce Seeds',category:'vegetable',sourceName:'Burpee official product page',sourceUrl:'https://www.burpee.com/lettuce-iceberg-a-prod000747.html',guideSourceName:'Burpee official lettuce growing guide',guideUrl:'https://support.burpee.com/support/solutions/articles/60000961783-learn-about-lettuce',identityAliases:['lettuce iceberg a','iceberg a lettuce','burpee iceberg a'],productFields:{designations:['Heirloom'],daysToMaturity:65,plantHeight:'9–15 inches',plantSpread:'6 inches',sunlight:'Full sun',notableClaims:'Crisphead lettuce · thrives in cooler weather'},guideFields:{depth:'1/4 inch',spacing:'12 inches',rowSpacing:'12 inches',thinningSpacing:'6 inches',germinationEstimate:'7–10 days',sowingMethod:'Direct sow',directSowGuidance:'Sow in average soil in full sun in early spring and again in late summer for a fall crop.',seasonalWindow:'Early spring and late summer for a fall crop',waterGuidance:'Keep evenly moist throughout growth.',soilGuidance:'Average, well-drained soil enriched with organic matter.',successionGuidance:'Sow every two weeks to extend the harvest.',harvestGuidance:'Harvest when the head is firm and full-sized.',containerSuitability:'Container friendly when plants have about 12 inches of space.'}},
 {id:'burpee-green-ice',officialProductId:'prod000738',brand:'Burpee',crop:'Lettuce',cropId:'lettuce',variety:'Green Ice',productName:'Green Ice Lettuce Seeds',category:'vegetable',sourceName:'Burpee official product catalog',sourceUrl:'https://www.burpee.com/vegetables/lettuce/',identityAliases:['lettuce green ice','green ice lettuce'],productFields:{sunlight:'Full sun'}},
 {id:'burpee-bibb',officialProductId:'burpee-bibb',brand:'Burpee',crop:'Lettuce',cropId:'lettuce',variety:'Burpee Bibb',productName:'Burpee Bibb Lettuce Seeds',category:'vegetable',sourceName:'Burpee official product catalog',sourceUrl:'https://www.burpee.com/vegetables/lettuce/',identityAliases:['burpee bibb lettuce','lettuce burpee bibb'],productFields:{designations:['Heirloom']}}
];

export function seedLookupIdentity(draft={}){return{brand:draft.brand||'',crop:draft.name||draft.cropName||'',cropId:draft.cropId||'',variety:draft.variety||'',productName:draft.productName||'',barcode:draft.barcode||'',sku:draft.sku||draft.officialProductId||'',packetYear:draft.packetYear||'',rawText:[draft.packetIntelligence?.front?.rawText,draft.packetIntelligence?.back?.rawText].filter(Boolean).join('\n')}}
const textScore=(actual,expected,weight)=>{const a=normalize(actual),b=normalize(expected);if(!a||!b)return 0;if(a===b)return weight;if(a.includes(b)||b.includes(a))return weight*.72;const tokens=new Set(a.split(' ')),other=b.split(' '),overlap=other.filter(token=>tokens.has(token)).length/Math.max(1,other.length);return overlap>=.75?weight*.55:0};
export function scoreSeedProduct(identity={},product={}){let score=0,reasons=[];if(identity.barcode&&product.barcode&&normalize(identity.barcode)===normalize(product.barcode)){score+=120;reasons.push('exact barcode')}if(identity.sku&&product.officialProductId&&normalize(identity.sku)===normalize(product.officialProductId)){score+=100;reasons.push('exact product ID')}const brand=textScore(identity.brand,product.brand,20);if(brand){score+=brand;reasons.push('brand')}const crop=textScore(identity.crop||identity.cropId,product.crop||product.cropId,22);if(crop){score+=crop;reasons.push('crop')}const variety=textScore(identity.variety,product.variety,42);if(variety){score+=variety;reasons.push('variety')}const productName=textScore(identity.productName,product.productName,26);if(productName){score+=productName;reasons.push('product name')}const raw=normalize(identity.rawText);if(raw&&product.identityAliases?.some(alias=>raw.includes(normalize(alias)))){score+=40;reasons.push('packet text')}const exact=Boolean((score>=78&&brand&&crop&&(variety||productName||raw))||reasons.includes('exact barcode')||reasons.includes('exact product ID'));const tier=exact?'exact':score>=55?'medium':'low';return{score:Math.round(score),reasons,exact,tier}}

const cacheKey=identity=>`${CACHE_PREFIX}${[identity.brand,identity.crop,identity.variety,identity.barcode,identity.sku].map(normalize).join('|')}`;
const storage=()=>typeof localStorage!=='undefined'?localStorage:typeof sessionStorage!=='undefined'?sessionStorage:null;
const readCache=key=>{try{const row=JSON.parse(storage()?.getItem(key)||'null');if(row&&Date.now()-new Date(row.cachedAt).getTime()<CACHE_TTL)return{...row,cacheHit:true}}catch{}return null};
const writeCache=(key,value)=>{try{storage()?.setItem(key,JSON.stringify({...value,cachedAt:now()}))}catch{}};
async function verifyOfficialSource(product,fetcher=globalThis.fetch){if(!fetcher||!product.sourceUrl)return{reachable:false};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4500);try{const response=await fetcher(product.sourceUrl,{method:'GET',signal:controller.signal,mode:'cors'});return{reachable:Boolean(response?.ok),status:response?.status||0}}catch{return{reachable:false}}finally{clearTimeout(timer)}}
export async function lookupSeedProducts(identity={},options={}){const key=cacheKey(identity),cached=!options.ignoreCache?readCache(key):null;if(cached)return cached;const ranked=OFFICIAL_SEED_PRODUCTS.map(product=>({...product,match:scoreSeedProduct(identity,product)})).filter(product=>product.match.score>=20).sort((a,b)=>b.match.score-a.match.score),rankedPrimary=ranked[0]||null,primary=rankedPrimary?.match.tier==='low'?null:rankedPrimary,clearWinner=Boolean(primary&&(primary.match.exact||(primary.match.score-(ranked[1]?.match.score||0)>=28))),candidates=clearWinner?[primary]:ranked.filter(product=>product.match.tier!=='low').slice(0,3);let liveVerification={reachable:false};if(primary?.match.exact&&options.verifyOnline===true)liveVerification=await verifyOfficialSource(primary,options.fetcher);const result={identity,candidates,primaryCandidate:primary,otherCandidates:clearWinner?ranked.slice(1,3):[],exactCandidate:primary?.match.exact?primary:null,clearWinner,liveVerification,lookedUpAt:now(),source:'official-product-index',cacheHit:false};writeCache(key,result);return result}

const onlineMeta=(product,field,value,detail='official-product')=>({source:'online',sourceDetail:detail,sourceLabel:detail==='official-product'?'Found on official product page':'Found in official growing guide',confidence:'High',sourceUrl:detail==='official-product'?product.sourceUrl:product.guideUrl||product.sourceUrl,sourceName:detail==='official-product'?product.sourceName:product.guideSourceName||product.sourceName,exactProductId:product.officialProductId,originalText:String(value),extractedAt:now(),manuallyCorrected:false,correctedAt:null});
const same=(a,b)=>normalize(Array.isArray(a)?a.join(' '):a)===normalize(Array.isArray(b)?b.join(' '):b);
export function applySeedProductCandidate(draft={},product={}){let completed=0,replacedInvalid=0,next={...draft,fieldMeta:{...(draft.fieldMeta||{})},packetIntelligence:{...(draft.packetIntelligence||{}),onlineLookup:{exactProductId:product.officialProductId,productId:product.id,sourceName:product.sourceName,sourceUrl:product.sourceUrl,guideSourceName:product.guideSourceName,guideUrl:product.guideUrl,matchedAt:now(),match:product.match||null,selected:true},conflicts:[...(draft.packetIntelligence?.conflicts||[])]},exactProductId:product.officialProductId,onlineSourceUrl:product.sourceUrl};const fields={brand:product.brand,name:product.crop,cropId:product.cropId,variety:product.variety,productName:product.productName,category:product.category,...(product.productFields||{})},guide=product.guideFields||{};for(const [key,value] of Object.entries({...fields,...guide})){if(value===undefined||value===null||value==='')continue;const current=next[key],meta=next.fieldMeta[key]||{},detail=Object.prototype.hasOwnProperty.call(guide,key)?'official-guide':'official-product',incoming=onlineMeta(product,key,value,detail),hasCurrent=current!==''&&current!==null&&current!==undefined&&!(Array.isArray(current)&&!current.length),trustedCurrent=hasCurrent&&isTrustedPacketValue(key,current,meta);if(meta.source==='manual'||meta.manuallyCorrected)continue;if(hasCurrent&&trustedCurrent&&!same(current,value)){const conflict={field:key,activeValue:current,activeSource:fieldSourceLabel(meta),onlineValue:value,onlineSource:incoming.sourceLabel,sourceUrl:incoming.sourceUrl,detectedAt:now(),status:'needs-review'};next.packetIntelligence.conflicts=[...next.packetIntelligence.conflicts.filter(row=>row.field!==key||row.status==='resolved'),conflict];if(meta.source==='packet'&&meta.confidence!=='Low')continue}if(hasCurrent&&!trustedCurrent)replacedInvalid++;if(!hasCurrent)completed++;next={...next,[key]:value,fieldMeta:{...next.fieldMeta,[key]:incoming}}}return{...next,draftStatus:'Ready to save',packetIntelligence:{...next.packetIntelligence,applicationSummary:{completed,replacedInvalid,appliedAt:now()}}}}
export function clearSeedProductMatch(draft={}){const onlineFields=Object.entries(draft.fieldMeta||{}).filter(([,meta])=>meta?.source==='online').map(([key])=>key),fieldMeta={...(draft.fieldMeta||{})},next={...draft},packetSources=[draft.packetIntelligence?.front?.fields||{},draft.packetIntelligence?.back?.fields||{}];for(const key of onlineFields){const original=packetSources.map(source=>source[key]).find(meta=>meta&&isTrustedPacketValue(key,meta.value,meta));if(original){next[key]=original.value;fieldMeta[key]=original}else{delete fieldMeta[key];next[key]=''}}return{...next,fieldMeta,exactProductId:'',onlineSourceUrl:'',draftStatus:'Ready to review',packetIntelligence:{...(next.packetIntelligence||{}),onlineLookup:null,applicationSummary:null,conflicts:(next.packetIntelligence?.conflicts||[]).filter(row=>row.status==='resolved')}}}
export function resolveSeedConflict(draft={},fieldName,choice='active'){const conflicts=draft.packetIntelligence?.conflicts||[],conflict=conflicts.find(row=>row.field===fieldName&&row.status!=='resolved');if(!conflict)return draft;let next=draft;if(choice==='online')next={...draft,[fieldName]:conflict.onlineValue,fieldMeta:{...(draft.fieldMeta||{}),[fieldName]:{...(draft.fieldMeta?.[fieldName]||{}),source:'online',sourceLabel:conflict.onlineSource,sourceUrl:conflict.sourceUrl,confidence:'High',manuallyCorrected:false,correctedAt:null}}};else next={...draft,fieldMeta:{...(draft.fieldMeta||{}),[fieldName]:{...(draft.fieldMeta?.[fieldName]||{}),source:'corrected',confidence:'High',manuallyCorrected:true,correctedAt:now()}}};return{...next,packetIntelligence:{...(next.packetIntelligence||{}),conflicts:conflicts.map(row=>row===conflict?{...row,status:'resolved',resolution:choice,resolvedAt:now()}:row)}}}
