import React,{useEffect,useMemo,useRef,useState}from'react';
import{AlertTriangle,ArrowLeft,Bell,ChevronRight,Download,Info,MapPin,Settings,Sprout,Upload,Users}from'lucide-react';
import{APP_VERSION,BUILD_ID,UPDATED_AT,WHATS_NEW}from'./version.js';
import{DEFAULT_PROFILES,ProfileAvatar,ProfileSwitcher}from'./RunyanProfiles.jsx';
import{exportGardenBackup}from'./syncModel.js';

const ACTIVE_PROFILE_KEY='runyan-garden-active-profile',GARDEN_KEY='brookes-garden-state-v2';
const slogans=['Two directors. One shared pile of dirt.','Extremely organized seeds. Questionably located tools.','Keeping plants alive through teamwork and mild panic.','Shared dirt. Shared responsibility. Separate opinions.'];

export default function SettingsCenter({garden,navigate}){
 const activeId=localStorage.getItem(ACTIVE_PROFILE_KEY)||'brooke',active=DEFAULT_PROFILES.find(p=>p.id===activeId)||DEFAULT_PROFILES[0],slogan=slogans[new Date().getDate()%slogans.length],[restoreMessage,setRestoreMessage]=useState(''),[notificationPermission,setNotificationPermission]=useState(()=>typeof Notification==='undefined'?'unsupported':Notification.permission),restoreRef=useRef(null);
 const switchProfile=id=>{const selected=DEFAULT_PROFILES.find(p=>p.id===id)||DEFAULT_PROFILES[0];localStorage.setItem(ACTIVE_PROFILE_KEY,selected.id);try{const g=JSON.parse(localStorage.getItem(GARDEN_KEY)||'{}');localStorage.setItem(GARDEN_KEY,JSON.stringify({...g,profile:{...(g.profile||{}),gardenerName:selected.name,activeProfileId:selected.id}}))}catch{}window.scrollTo(0,0);window.location.reload()};
 const qa=useMemo(()=>{const plants=(garden.plants||[]).filter(p=>!p.deletedAt&&!p.archived),spaces=(garden.spaces||[]).filter(s=>!s.deletedAt),seeds=[...(garden.seeds||[]),...(garden.seedPackets||[])].filter(s=>!s.deletedAt);const issues=[];const unassigned=plants.filter(p=>!p.spaceId||!spaces.some(s=>s.id===p.spaceId)).length;if(unassigned)issues.push(`${unassigned} plant${unassigned===1?' is':'s are'} not assigned to a Growing Space`);const unmatched=plants.filter(p=>!p.cropId).length;if(unmatched)issues.push(`${unmatched} plant${unmatched===1?' needs':'s need'} a crop match for tailored reminders`);const unnamed=spaces.filter(s=>/^raised bed|^garden space/i.test(s.name||'')).length;if(unnamed)issues.push(`${unnamed} Growing Space${unnamed===1?' has':'s have'} a generic name`);return{issues,plants:plants.length,spaces:spaces.length,seeds:seeds.length,photos:spaces.filter(s=>s.photo).length}},[garden]);
 useEffect(()=>{const target=sessionStorage.getItem('settings-destination');sessionStorage.removeItem('settings-destination');if(target)requestAnimationFrame(()=>document.getElementById(`settings-${target}`)?.scrollIntoView({block:'start'}))},[]);
 const restore=async file=>{if(!file)return;try{const text=await file.text(),payload=JSON.parse(text),restored=payload.garden||payload;if(!restored||!Array.isArray(restored.plants)||!Array.isArray(restored.spaces))throw new Error('This file does not contain a valid Runyan Garden backup.');if(!window.confirm(`Restore ${restored.plants.length} plant record${restored.plants.length===1?'':'s'} and ${restored.spaces.length} Growing Space${restored.spaces.length===1?'':'s'} from this backup? Current device data will be replaced.`))return;localStorage.setItem(GARDEN_KEY,JSON.stringify(restored));setRestoreMessage('Backup restored. Reloading the garden…');window.setTimeout(()=>window.location.reload(),500)}catch(error){setRestoreMessage(error?.message||'That backup could not be restored.')}};
 const requestNotifications=async()=>{if(typeof Notification==='undefined')return setNotificationPermission('unsupported');const permission=await Notification.requestPermission();setNotificationPermission(permission)};
 const permissionLabel=notificationPermission==='granted'?'Browser notifications allowed':notificationPermission==='denied'?'Browser notifications blocked':notificationPermission==='unsupported'?'Browser notifications unavailable':'Browser permission not requested';
 return <main className="screen simple-screen profile-screen settings-center"><section className="dark-header simple-header compact-simple-header"><button className="back-button settings-back" onClick={()=>navigate?.('back')} aria-label="Go back"><ArrowLeft/></button><div className="simple-icon"><Settings/></div><span>THE RUNYAN GARDEN</span><h1>Garden Settings</h1><p>Established 2024 • Green Bay, Wisconsin<br/>{slogan}</p></section><section className="profile-form-wrap">
  <section className="profile-group" id="settings-settings"><span className="section-kicker">GARDEN PROFILE</span><div className="profile-switch-grid director-display">{DEFAULT_PROFILES.map(profile=><div key={profile.id}><ProfileAvatar profile={profile} small/><span><strong>{profile.name}</strong><small>{profile.role}</small></span></div>)}</div></section>
  <section className="profile-group" id="settings-location"><span className="section-kicker">LOCATION AND FROST DATES</span><div className="runyan-establishment-card"><MapPin/><strong>Green Bay, Wisconsin 54302</strong><span>USDA Zone 5b. Weather, frost timing, and seasonal planting guidance use this saved location.</span></div></section>
  <section className="profile-group" id="settings-notifications"><span className="section-kicker">NOTIFICATION SETTINGS</span><div className="notification-settings-card"><Bell/><span><strong>{permissionLabel}</strong><small>Weather alerts, overdue work, and Chore Board counts remain visible inside the app regardless of browser permission.</small></span></div><button className="indoor-center-link backup-link" disabled={notificationPermission==='granted'||notificationPermission==='unsupported'} onClick={requestNotifications}><Bell/><span><strong>{notificationPermission==='granted'?'Notifications already allowed':'Allow browser notifications'}</strong><small>Your browser or iPhone may still require notification permission in system settings.</small></span><ChevronRight/></button></section>
  <section className="profile-group" id="settings-backup"><span className="section-kicker">BACKUP AND RESTORE</span><button className="indoor-center-link backup-link" onClick={()=>exportGardenBackup(garden)}><Download/><span><strong>Download garden backup</strong><small>Save a recovery copy containing the current garden records on this device.</small></span><ChevronRight/></button><button className="indoor-center-link backup-link" onClick={()=>restoreRef.current?.click()}><Upload/><span><strong>Restore from backup</strong><small>Choose a Runyan Garden backup file and review the record count before replacing this device’s data.</small></span><ChevronRight/></button><input ref={restoreRef} className="visually-hidden-input" type="file" accept="application/json,.json" onChange={event=>restore(event.target.files?.[0])}/>{restoreMessage&&<p className="restore-message" role="status">{restoreMessage}</p>}</section>
  <section className="profile-group"><span className="section-kicker">GARDEN DATA CHECK</span><div className="version-grid"><span><small>Plants</small><strong>{qa.plants}</strong></span><span><small>Spaces</small><strong>{qa.spaces}</strong></span><span><small>Seeds</small><strong>{qa.seeds}</strong></span><span><small>Bed photos</small><strong>{qa.photos}</strong></span></div><div className={`sync-qa-card ${qa.issues.length?'needs-review':'is-ready'}`}>{qa.issues.length?<><AlertTriangle/><span><strong>{qa.issues.length} garden record issue{qa.issues.length===1?'':'s'} worth reviewing</strong>{qa.issues.map(x=><small key={x}>• {x}</small>)}</span></>:<><Sprout/><span><strong>The saved garden records are connected.</strong><small>Known plants are linked to crop and Growing Space records.</small></span></>}</div></section>
  <section className="version-center" id="settings-about"><div className="version-title"><Info/><div><span className="section-kicker">ABOUT THIS APP</span><h2>The Runyan Garden</h2></div></div><div className="version-grid"><span><small>Version</small><strong>{APP_VERSION}</strong></span><span><small>Build</small><strong>{BUILD_ID}</strong></span><span><small>Updated</small><strong>{UPDATED_AT}</strong></span><span><small>Storage</small><strong>On this device</strong></span></div><div className="whats-new"><span className="section-kicker">WHAT’S NEW IN {APP_VERSION}</span>{WHATS_NEW.map(item=><div key={item}><Sprout/><span>{item}</span></div>)}</div></section>
  <details className="profile-group gardener-switch-details"><summary><Users/><span><small>WHO’S USING THE APP?</small><strong>{active.name} • {active.role}</strong></span><ChevronRight/></summary><ProfileSwitcher profiles={DEFAULT_PROFILES} activeId={active.id} onSwitch={switchProfile}/></details>
 </section></main>;
}
