import React,{useMemo}from'react';
import{AlertTriangle,ChevronRight,Download,Info,MapPin,Settings,Sprout,Users}from'lucide-react';
import{APP_VERSION,BUILD_ID,UPDATED_AT,WHATS_NEW}from'./version.js';
import{DEFAULT_PROFILES,ProfileAvatar,ProfileSwitcher}from'./RunyanProfiles.jsx';
import{exportGardenBackup}from'./syncModel.js';
const ACTIVE_PROFILE_KEY='runyan-garden-active-profile',GARDEN_KEY='brookes-garden-state-v2';
const slogans=['Two directors. One shared pile of dirt.','Extremely organized seeds. Questionably located tools.','Keeping plants alive through teamwork and mild panic.','Shared dirt. Shared responsibility. Separate opinions.'];
export default function SettingsCenter({garden}){
 const activeId=localStorage.getItem(ACTIVE_PROFILE_KEY)||'brooke',active=DEFAULT_PROFILES.find(p=>p.id===activeId)||DEFAULT_PROFILES[0],slogan=slogans[new Date().getDate()%slogans.length];
 const switchProfile=id=>{const selected=DEFAULT_PROFILES.find(p=>p.id===id)||DEFAULT_PROFILES[0];localStorage.setItem(ACTIVE_PROFILE_KEY,selected.id);try{const g=JSON.parse(localStorage.getItem(GARDEN_KEY)||'{}');localStorage.setItem(GARDEN_KEY,JSON.stringify({...g,profile:{...(g.profile||{}),gardenerName:selected.name,activeProfileId:selected.id}}))}catch{}window.scrollTo(0,0);window.location.reload()};
 const qa=useMemo(()=>{const plants=(garden.plants||[]).filter(p=>!p.deletedAt&&!p.archived),spaces=(garden.spaces||[]).filter(s=>!s.deletedAt),seeds=(garden.seeds||[]).filter(s=>!s.deletedAt);const issues=[];const unassigned=plants.filter(p=>!p.spaceId||!spaces.some(s=>s.id===p.spaceId)).length;if(unassigned)issues.push(`${unassigned} plant${unassigned===1?' is':'s are'} not assigned to a growing space`);const unmatched=plants.filter(p=>!p.cropId).length;if(unmatched)issues.push(`${unmatched} plant${unmatched===1?' needs':'s need'} a crop match for tailored reminders`);const unnamed=spaces.filter(s=>/^raised bed|^garden space/i.test(s.name||'')).length;if(unnamed)issues.push(`${unnamed} growing space${unnamed===1?' has':'s have'} a generic name`);const unknown=(garden.activity||[]).filter(a=>!a.actor||a.actor==='Unknown').length;if(unknown)issues.push(`${unknown} older activit${unknown===1?'y has':'ies have'} no gardener attached`);return{issues,plants:plants.length,spaces:spaces.length,seeds:seeds.length,photos:spaces.filter(s=>s.photo).length,activity:(garden.activity||[]).length}},[garden]);
 return <main className="screen simple-screen profile-screen settings-center"><section className="dark-header simple-header compact-simple-header"><div className="simple-icon"><Settings/></div><span>THE RUNYAN GARDEN</span><h1>Runyan Garden Settings</h1><p>Established 2024 • Green Bay, Wisconsin<br/>{slogan}</p></section><section className="profile-form-wrap">
  <section className="profile-group"><span className="section-kicker">THE DIRECTORS</span><div className="profile-switch-grid director-display">{DEFAULT_PROFILES.map(profile=><div key={profile.id}><ProfileAvatar profile={profile} small/><span><strong>{profile.name}</strong><small>{profile.role}</small></span></div>)}</div></section>
  <section className="profile-group"><span className="section-kicker">GARDEN & APP</span><div className="runyan-establishment-card"><MapPin/><strong>Green Bay, Wisconsin</strong><span>USDA Zone 5b • Weather and seasonal guidance use this location.</span></div><button className="indoor-center-link backup-link" onClick={()=>exportGardenBackup(garden)}><Download/><span><strong>Download garden backup</strong><small>Save a recovery copy before the shared-garden migration.</small></span><ChevronRight/></button></section>
  <section className="profile-group"><span className="section-kicker">READY FOR SHARED SYNC</span><div className="version-grid"><span><small>Plants</small><strong>{qa.plants}</strong></span><span><small>Spaces</small><strong>{qa.spaces}</strong></span><span><small>Seeds</small><strong>{qa.seeds}</strong></span><span><small>Bed photos</small><strong>{qa.photos}</strong></span></div><div className={`sync-qa-card ${qa.issues.length?'needs-review':'is-ready'}`}>{qa.issues.length?<><AlertTriangle/><span><strong>{qa.issues.length} thing{qa.issues.length===1?'':'s'} worth reviewing before sync</strong>{qa.issues.map(x=><small key={x}>• {x}</small>)}</span></>:<><Sprout/><span><strong>The garden data is ready for migration.</strong><small>Known plants are connected to crop and space records.</small></span></>}</div></section>
  <section className="version-center"><div className="version-title"><Info/><div><span className="section-kicker">ABOUT THIS APP</span><h2>The Runyan Garden</h2></div></div><div className="version-grid"><span><small>Version</small><strong>{APP_VERSION}</strong></span><span><small>Build</small><strong>{BUILD_ID}</strong></span><span><small>Updated</small><strong>{UPDATED_AT}</strong></span><span><small>Storage</small><strong>On this device</strong></span></div><div className="whats-new"><span className="section-kicker">WHAT’S NEW IN {APP_VERSION}</span>{WHATS_NEW.map(item=><div key={item}><Sprout/><span>{item}</span></div>)}</div></section>
  <details className="profile-group gardener-switch-details"><summary><Users/><span><small>WHO’S USING THE APP?</small><strong>{active.name} • {active.role}</strong></span><ChevronRight/></summary><ProfileSwitcher profiles={DEFAULT_PROFILES} activeId={active.id} onSwitch={switchProfile}/></details>
 </section></main>;
}