import React from'react';
import{Calculator,CalendarDays,FileText,PackageSearch,Ruler,Seedling,Tags,Wrench}from'lucide-react';
import{SecondaryCard,SecondaryHero,SecondarySectionHeader}from'./SecondaryUI.jsx';

export default function ToolShed({navigate}){
 return <main className="screen secondary-screen tool-shed-screen"><SecondaryHero icon={Wrench} eyebrow="OPTIONAL GARDEN UTILITIES" title="Tool Shed" description="Calculate, measure, estimate, print, label, and prepare." className="tool-shed-hero"/><section className="screen-pad secondary-screen-content tool-shed-content">
  <section className="tool-shed-group"><SecondarySectionHeader eyebrow="CREATE AND PRINT"/><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="gold" icon={Tags} title="Plant Labels" description="Create bed signs, plant tags, and custom QR labels." meta="Existing QR and PDF workflow" onClick={()=>navigate('labels')}/><SecondaryCard kind="utility" tone="green" icon={FileText} title="Printable Garden Pack" description="Print garden logs, maps, planning sheets, and checklists." onClick={()=>navigate('printable-pack')}/></div></section>
  <section className="tool-shed-group"><SecondarySectionHeader eyebrow="CALCULATE"/><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="cream" icon={Ruler} title="Spacing Calculator" description="Estimate how many plants fit in a Growing Space." onClick={()=>navigate('spacing-calculator')}/><SecondaryCard kind="utility" tone="green" icon={PackageSearch} title="Soil & Container Calculator" description="Estimate soil volume and common bag quantities." onClick={()=>navigate('soil-calculator')}/><SecondaryCard kind="utility" tone="gold" icon={CalendarDays} title="Frost & Planting Dates" description="Check planting dates using saved Green Bay frost timing." onClick={()=>navigate('frost-calculator')}/><SecondaryCard kind="utility" tone="cream" icon={Seedling} title="Seed Quantity Calculator" description="Estimate how many seeds to start for the plants wanted." onClick={()=>navigate('seed-quantity-calculator')}/></div></section>
  <section className="tool-shed-group"><SecondarySectionHeader eyebrow="MEASURE"/><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="green" icon={Calculator} title="Garden Measurements" description="Convert common garden dimensions, areas, volumes, and row lengths." onClick={()=>navigate('garden-measurements')}/></div></section>
 </section></main>;
}
