import React from'react';
import{Calculator,CalendarDays,ClipboardList,CloudSun,DatabaseBackup,FileText,History,NotebookPen,PackageSearch,Ruler,Settings,Sprout,Tags,Wrench}from'lucide-react';
import{SecondaryCard,SecondaryHero,SecondarySectionHeader}from'./SecondaryUI.jsx';

export default function ToolShed({navigate}){
 return <main className="screen secondary-screen tool-shed-screen"><SecondaryHero icon={Wrench} eyebrow="OPTIONAL UTILITIES" title="Tool Shed" description="Calculators, printables, labels, and record tools." className="tool-shed-hero"/><section className="screen-pad secondary-screen-content tool-shed-content">
  <details className="tool-shed-group tool-shed-drawer" open><summary><SecondarySectionHeader eyebrow="GARDEN TOOLS"/><span>4</span></summary><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="green" icon={PackageSearch} title="Seed Library" description="Open saved packets and packet capture." onClick={()=>navigate('seed-tools')}/><SecondaryCard kind="utility" tone="gold" icon={CalendarDays} title="Planting Calendar" description="Review planting windows and frost timing." onClick={()=>navigate('plan-plant')}/><SecondaryCard kind="utility" tone="cream" icon={ClipboardList} title="Chore Board" description="Open today's garden tasks." onClick={()=>navigate('chores')}/><SecondaryCard kind="utility" tone="green" icon={CloudSun} title="Weather Tools" description="Forecast, rain history, and garden impacts." onClick={()=>navigate('weather')}/></div></details>
  <details className="tool-shed-group tool-shed-drawer"><summary><SecondarySectionHeader eyebrow="RECORDS"/><span>3</span></summary><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="cream" icon={History} title="Garden History" description="Harvests, issues, and saved records." onClick={()=>navigate('memory')}/><SecondaryCard kind="utility" tone="gold" icon={NotebookPen} title="Harvest Tracking" description="Open records and log harvest notes." onClick={()=>navigate('memory')}/><SecondaryCard kind="utility" tone="green" icon={FileText} title="Notes and Printables" description="Garden logs, maps, and checklists." onClick={()=>navigate('printable-pack')}/></div></details>
  <details className="tool-shed-group tool-shed-drawer"><summary><SecondarySectionHeader eyebrow="UTILITIES"/><span>7</span></summary><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="gold" icon={Tags} title="Plant Labels" description="Create bed signs, plant tags, and QR labels." meta="Existing QR and PDF workflow" onClick={()=>navigate('labels')}/><SecondaryCard kind="utility" tone="cream" icon={Ruler} title="Spacing Calculator" description="Estimate how many plants fit in a Growing Space." onClick={()=>navigate('spacing-calculator')}/><SecondaryCard kind="utility" tone="green" icon={PackageSearch} title="Soil Calculator" description="Estimate soil volume and bag quantities." onClick={()=>navigate('soil-calculator')}/><SecondaryCard kind="utility" tone="gold" icon={Sprout} title="Seed Quantity" description="Estimate seeds to start from a plant target." onClick={()=>navigate('seed-quantity-calculator')}/><SecondaryCard kind="utility" tone="cream" icon={Calculator} title="Measurements" description="Convert garden dimensions, areas, and volumes." onClick={()=>navigate('garden-measurements')}/><SecondaryCard kind="utility" tone="green" icon={Settings} title="Settings" description="Garden preferences and location." onClick={()=>navigate('more')}/><SecondaryCard kind="utility" tone="cream" icon={DatabaseBackup} title="Data Management" description="Backup and restore local records." onClick={()=>navigate('admin-backup')}/></div></details>
 </section></main>;
}
