import React,{useEffect,useMemo,useState}from'react';
import{ArrowRight,Calculator,Copy,FileText,PackageSearch,Printer,Ruler,Snowflake,Sprout}from'lucide-react';
import{SecondaryHero,SecondarySectionHeader}from'./SecondaryUI.jsx';
import{cropCatalog}from'./data.js';
import{gardenShoppingItems}from'./gardenShopping.js';
import{seedInventory}from'./plantingDesk.js';
import{connectedDuplicateKey}from'./connectedIntelligence.js';
import{calculateMeasurement,calculatePlantingDates,calculateSeedQuantity,calculateSoilVolume,calculateSpacing,formatToolDate,parseSpaceDimensions,parseSpacingInches,timingDefaults}from'./gardenTools.js';

const toolInfo={
 spacing:{icon:Ruler,eyebrow:'CALCULATE',title:'Spacing Calculator',description:'Estimate how many plants fit without changing the Growing Space.'},
 soil:{icon:PackageSearch,eyebrow:'CALCULATE',title:'Soil & Container Calculator',description:'Estimate soil volume, gallons, and common bag quantities.'},
 frost:{icon:Snowflake,eyebrow:'CALCULATE',title:'Frost & Planting Dates',description:'Check a planting scenario against saved Green Bay frost timing.'},
 seeds:{icon:Sprout,eyebrow:'CALCULATE',title:'Seed Quantity Calculator',description:'Estimate how many seeds to start for the final number of plants needed.'},
 measurements:{icon:Ruler,eyebrow:'MEASURE',title:'Garden Measurements',description:'Use common garden dimensions and conversions without a generic calculator.'},
 print:{icon:Printer,eyebrow:'CREATE AND PRINT',title:'Printable Garden Pack',description:'Create blank or prefilled garden logs, maps, and planning sheets.'}
};
const activeSpaces=garden=>(garden.spaces||[]).filter(space=>!space.hidden&&!space.deletedAt);
const inventoryChoices=garden=>seedInventory(garden).filter(item=>item.cropId);
const selectionOptions=garden=>[...inventoryChoices(garden).map(item=>({value:`packet:${item.id}`,label:[item.brand,item.variety||item.name].filter(Boolean).join(' ')||item.name,item,cropId:item.cropId,exact:true})),...cropCatalog.map(crop=>({value:`crop:${crop.id}`,label:crop.name,cropId:crop.id,crop,exact:false}))];
const resolveChoice=(garden,value)=>selectionOptions(garden).find(item=>item.value===value)||selectionOptions(garden)[0];
const fmt=value=>Number.isFinite(value)?Number(value).toLocaleString('en-US',{maximumFractionDigits:2}):'—';
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

const resultRecord=(type,data={})=>{const targetId=data.spaceId||data.packetId||data.cropId||data.mode||'garden',basis=data.choiceValue||data.mode||data.shape||'';return{id:`calculator-${type}-${targetId}-${basis}`.replace(/[^a-z0-9-]+/gi,'-').toLowerCase(),type,duplicateKey:`calculator|${type}|${targetId}|${basis}`.toLowerCase(),source:'Tool Shed',confidence:'Estimated',...data}};
function ResultActions({children}){return <div className="tool-result-actions">{children}</div>}

function ChoiceSelect({garden,value,onChange,label='Crop or exact packet'}){const options=selectionOptions(garden);return <label>{label}<select value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option.value} value={option.value}>{option.exact?'Exact packet · ':''}{option.label}</option>)}</select></label>}
function SpaceSelect({garden,value,onChange,allowCustom=true}){return <label>Growing Space<select value={value} onChange={event=>onChange(event.target.value)}>{allowCustom&&<option value="custom">Custom dimensions</option>}{activeSpaces(garden).map(space=><option key={space.id} value={space.id}>{space.name}</option>)}</select></label>}
function EstimateNotice({children}){return <p className="tool-estimate-note"><Calculator/>{children}</p>}

function SpacingTool({garden,onSaveSpaceNote,onSaveResult,onApplyToSpace,onOpenPlanting}){
 const spaces=activeSpaces(garden),[spaceId,setSpaceId]=useState(spaces[0]?.id||'custom'),[choiceValue,setChoiceValue]=useState(selectionOptions(garden)[0]?.value||''),[layout,setLayout]=useState('square'),[length,setLength]=useState(4),[width,setWidth]=useState(8),[diameter,setDiameter]=useState(18),[rowSpacing,setRowSpacing]=useState('');
 const choice=resolveChoice(garden,choiceValue),space=spaces.find(item=>item.id===spaceId),spacingText=choice?.exact?(choice.item.spacing||cropCatalog.find(crop=>crop.id===choice?.cropId)?.spacing):(choice?.crop?.spacing||cropCatalog.find(crop=>crop.id===choice?.cropId)?.spacing),spacing=parseSpacingInches(spacingText,12),result=calculateSpacing({layout,lengthFeet:length,widthFeet:width,diameterInches:diameter,spacingInches:spacing,rowSpacingInches:rowSpacing}),record=resultRecord('spacing',{spaceId,choiceValue,cropId:choice?.cropId||'',packetId:choice?.exact?choice.item.id:'',layout,lengthFeet:Number(length)||0,widthFeet:Number(width)||0,diameterInches:Number(diameter)||0,spacingText,capacity:result.count,result,sourceLabel:choice?.exact&&choice.item.spacing?'Exact packet guidance':'General crop guidance'});
 useEffect(()=>{if(!space)return;const dims=parseSpaceDimensions(space);if(dims.lengthFeet)setLength(dims.lengthFeet);if(dims.widthFeet)setWidth(dims.widthFeet);if(dims.diameterInches)setDiameter(dims.diameterInches);if(['container','potato-grow-bag'].includes(space.type))setLayout('container')},[spaceId]);
 const save=()=>{onSaveResult?.(record);if(space)onSaveSpaceNote?.(space.id,`Spacing estimate — ${choice?.label||'Crop'}: approximately ${result.count} plants using ${result.spacingInches} in. ${layout} spacing. ${result.detail} Estimate only.`)};
 const apply=()=>{if(!space)return;onApplyToSpace?.(space.id,{planningLayout:{cropId:choice?.cropId||'',sourcePacketId:choice?.exact?choice.item.id:'',layout,capacity:result.count,spacingInches:result.spacingInches,rowSpacingInches:result.rowSpacingInches,source:record.sourceLabel,updatedAt:new Date().toISOString()}},record)};
 return <><SecondarySectionHeader eyebrow="SPACE AND CROP" description="Exact packet spacing is preferred when the selected packet records it."/><div className="tool-form-card"><SpaceSelect garden={garden} value={spaceId} onChange={setSpaceId}/><ChoiceSelect garden={garden} value={choiceValue} onChange={setChoiceValue}/><label>Layout<select value={layout} onChange={event=>setLayout(event.target.value)}><option value="rows">Rows</option><option value="grid">Grid</option><option value="square">Square spacing</option><option value="container">Round container</option></select></label>{layout==='container'?<label>Container diameter (inches)<input type="number" min="1" value={diameter} onChange={event=>setDiameter(event.target.value)}/></label>:<div className="tool-two-fields"><label>Length (feet)<input type="number" min="0" step="0.25" value={length} onChange={event=>setLength(event.target.value)}/></label><label>Width (feet)<input type="number" min="0" step="0.25" value={width} onChange={event=>setWidth(event.target.value)}/></label></div>}{layout==='rows'&&<label>Row spacing (inches)<input type="number" min="1" placeholder={`Suggested ${Math.round(spacing*1.5)}`} value={rowSpacing} onChange={event=>setRowSpacing(event.target.value)}/></label>}</div><section className="tool-result-card"><span className="tool-result-kicker">APPROXIMATE CAPACITY</span><strong>{result.count} plant{result.count===1?'':'s'}</strong><p>{result.detail}</p><dl><div><dt>Spacing used</dt><dd>{result.spacingInches} in.</dd></div><div><dt>Edge clearance</dt><dd>About {fmt(result.edgeClearanceInches)} in.</dd></div><div><dt>Guidance source</dt><dd>{record.sourceLabel}</dd></div></dl><small>{spacingText||'No spacing text was recorded; a 12-inch fallback was used.'}</small><ResultActions><button className="secondary-button" onClick={save}>Save reusable result</button>{space&&<button className="secondary-button" onClick={apply}>Apply to {space.name}</button>}<button className="primary-button" onClick={()=>onOpenPlanting?.({source:'spacing-calculator',spaceId,cropId:choice?.cropId||'',sourcePacketId:choice?.exact?choice.item.id:'',capacity:result.count,spacingInches:result.spacingInches})}>Create planting plan</button></ResultActions></section><EstimateNotice>Capacity is an estimate. Access paths, supports, plant habit, sun, and maintenance space may reduce the practical count.</EstimateNotice></>;
}

function SoilTool({garden,onSaveResult,onApplyToSpace,onAddShoppingItem}){
 const spaces=activeSpaces(garden),[spaceId,setSpaceId]=useState('custom'),[shape,setShape]=useState('raised'),[length,setLength]=useState(8),[width,setWidth]=useState(4),[depth,setDepth]=useState(10),[diameter,setDiameter]=useState(18),[height,setHeight]=useState(16),[gallons,setGallons]=useState(10),[buffer,setBuffer]=useState(10),space=spaces.find(item=>item.id===spaceId);
 useEffect(()=>{if(!space)return;const dims=parseSpaceDimensions(space);if(dims.lengthFeet)setLength(dims.lengthFeet);if(dims.widthFeet)setWidth(dims.widthFeet);if(dims.depthInches)setDepth(dims.depthInches);if(dims.diameterInches)setDiameter(dims.diameterInches);if(dims.gallons)setGallons(dims.gallons);if(space.type==='container')setShape(dims.diameterInches?'round':'rectangular');else if(space.type==='potato-grow-bag')setShape('grow-bag');else setShape('raised')},[spaceId]);
 const result=calculateSoilVolume({shape,length,width,depth,diameter,height,gallons,lengthUnit:'ft',widthUnit:'ft',depthUnit:'in',diameterUnit:'in',heightUnit:'in',bufferPercent:buffer}),record=resultRecord('soil',{spaceId,shape,length:Number(length)||0,width:Number(width)||0,depth:Number(depth)||0,diameter:Number(diameter)||0,height:Number(height)||0,gallons:Number(gallons)||0,buffer:Number(buffer)||0,result}),bagSize='1.5',bagCount=result.bags[bagSize]||0;
 const apply=()=>{if(!space)return;onApplyToSpace?.(space.id,{soilCalculation:{shape,cubicFeet:result.cubicFeet,bufferedCubicFeet:result.bufferedCubicFeet,estimatedGallons:result.estimatedGallons,bufferPercent:result.bufferPercent,updatedAt:new Date().toISOString()},lengthFeet:Number(length)||undefined,widthFeet:Number(width)||undefined,depthInches:Number(depth)||undefined,diameterInches:Number(diameter)||undefined},record)};
 const shop=()=>onAddShoppingItem?.({name:'Garden Soil',category:'Soil & Amendments',quantity:bagCount||1,note:`${bagSize} cu. ft. bags for ${space?.name||'calculated space'}`,reason:`Soil calculator estimated ${fmt(result.bufferedCubicFeet)} cu. ft. including buffer.`,intendedSpaceId:spaceId==='custom'?'':spaceId,sourceProjectId:record.id,priority:65});
 return <><SecondarySectionHeader eyebrow="SHAPE AND DIMENSIONS" description="Load a saved Growing Space or enter one-time dimensions."/><div className="tool-form-card"><SpaceSelect garden={garden} value={spaceId} onChange={setSpaceId}/><label>Shape<select value={shape} onChange={event=>setShape(event.target.value)}><option value="round">Round pot</option><option value="rectangular">Rectangular planter</option><option value="raised">Raised bed</option><option value="grow-bag">Grow bag</option><option value="custom">Custom rectangular dimensions</option></select></label>{shape==='round'?<div className="tool-two-fields"><label>Diameter (inches)<input type="number" min="0" value={diameter} onChange={event=>setDiameter(event.target.value)}/></label><label>Height (inches)<input type="number" min="0" value={height} onChange={event=>setHeight(event.target.value)}/></label></div>:shape==='grow-bag'?<label>Labeled capacity (gallons)<input type="number" min="0" value={gallons} onChange={event=>setGallons(event.target.value)}/></label>:<><div className="tool-two-fields"><label>Length (feet)<input type="number" min="0" step="0.25" value={length} onChange={event=>setLength(event.target.value)}/></label><label>Width (feet)<input type="number" min="0" step="0.25" value={width} onChange={event=>setWidth(event.target.value)}/></label></div><label>Fill depth (inches)<input type="number" min="0" step="0.5" value={depth} onChange={event=>setDepth(event.target.value)}/></label></>}<label>Extra buffer<select value={buffer} onChange={event=>setBuffer(event.target.value)}><option value="0">No buffer</option><option value="5">5%</option><option value="10">10%</option><option value="15">15%</option></select></label></div><section className="tool-result-card"><span className="tool-result-kicker">ESTIMATED SOIL</span><strong>{fmt(result.cubicFeet)} cubic feet</strong><p>{fmt(result.estimatedGallons)} gallons before the {result.bufferPercent}% buffer.</p><div className="soil-bag-grid">{Object.entries(result.bags).map(([size,count])=><span key={size}><b>{count}</b><small>{size} cu. ft. bags</small></span>)}</div><small>{result.assumption} Bag counts include the selected buffer and round up to whole bags.</small><ResultActions><button className="secondary-button" onClick={()=>onSaveResult?.(record)}>Save reusable result</button>{space&&<button className="secondary-button" onClick={apply}>Apply dimensions to {space.name}</button>}<button className="primary-button" onClick={shop}>Add {bagCount||1} soil bag{(bagCount||1)===1?'':'s'} to Shopping List</button></ResultActions></section><EstimateNotice>Settling, existing soil, tapered containers, and manufacturer bag fill can change the amount actually needed.</EstimateNotice></>;
}

function FrostTool({garden,onSaveResult,onOpenPlanting}){
 const options=selectionOptions(garden),[choiceValue,setChoiceValue]=useState(options[0]?.value||''),choice=resolveChoice(garden,choiceValue),defaults=timingDefaults(choice?.cropId,choice?.item||{}),[indoor,setIndoor]=useState(defaults.indoorBefore),[transplant,setTransplant]=useState(defaults.transplantAfter),[direct,setDirect]=useState(defaults.directAfter),[fall,setFall]=useState(defaults.fallBefore);
 useEffect(()=>{const next=timingDefaults(choice?.cropId,choice?.item||{});setIndoor(next.indoorBefore);setTransplant(next.transplantAfter);setDirect(next.directAfter);setFall(next.fallBefore)},[choiceValue]);
 const result=calculatePlantingDates({profile:garden.profile||{},cropId:choice?.cropId,packet:choice?.item||{},indoorBefore:indoor,transplantAfter:transplant,directAfter:direct,fallBefore:fall}),record=resultRecord('frost',{choiceValue,cropId:choice?.cropId||'',packetId:choice?.exact?choice.item.id:'',result:{lastFrost:result.lastFrost.toISOString(),firstFrost:result.firstFrost.toISOString(),indoorStart:result.indoorStart.toISOString(),transplantDate:result.transplantDate.toISOString(),directSowDate:result.directSowDate.toISOString(),fallPlantingDate:result.fallPlantingDate?.toISOString()||'',defaults:result.defaults},sourceLabel:choice?.exact?'Exact packet timing where recorded':'General crop guidance'});
 return <><SecondarySectionHeader eyebrow="DATE SCENARIO" description={`${garden.profile?.location||'Green Bay, Wisconsin'} · Zone ${garden.profile?.zone||'5b'}`}/><div className="tool-form-card"><ChoiceSelect garden={garden} value={choiceValue} onChange={setChoiceValue}/><div className="tool-two-fields"><label>Indoor start weeks before last frost<input type="number" min="0" max="20" value={indoor} onChange={event=>setIndoor(event.target.value)}/></label><label>Transplant weeks after last frost<input type="number" min="-10" max="12" value={transplant} onChange={event=>setTransplant(event.target.value)}/></label></div><div className="tool-two-fields"><label>Direct-sow weeks after last frost<input type="number" min="-10" max="12" value={direct} onChange={event=>setDirect(event.target.value)}/></label><label>Fall planting weeks before first frost<input type="number" min="0" max="20" value={fall} onChange={event=>setFall(event.target.value)}/></label></div></div><section className="tool-result-card frost-results"><span className="tool-result-kicker">CALCULATED DATES</span><dl><div><dt>Working last frost</dt><dd>{formatToolDate(result.lastFrost)}</dd></div><div><dt>Start indoors</dt><dd>{indoor>0?formatToolDate(result.indoorStart):'Not selected'}</dd></div><div><dt>Transplant</dt><dd>{formatToolDate(result.transplantDate)}</dd></div><div><dt>Direct sow</dt><dd>{formatToolDate(result.directSowDate)}</dd></div><div><dt>Working first frost</dt><dd>{formatToolDate(result.firstFrost)}</dd></div><div><dt>Fall planting</dt><dd>{result.fallPlantingDate?formatToolDate(result.fallPlantingDate):'Not selected'}</dd></div></dl><small>{record.sourceLabel}</small><ResultActions><button className="secondary-button" onClick={()=>onSaveResult?.(record)}>Save date scenario</button><button className="primary-button" onClick={()=>onOpenPlanting?.({source:'frost-calculator',cropId:choice?.cropId||'',sourcePacketId:choice?.exact?choice.item.id:'',calculatedDates:record.result})}>Use in Planting Desk</button></ResultActions></section><EstimateNotice>These are planning dates, not weather guarantees. Planting Desk will still check current conditions and available Growing Spaces.</EstimateNotice></>;
}

function SeedQuantityTool({garden,onSaveResult,onReserveSeeds,onAddShoppingItem,onOpenIndoor}){
 const packets=inventoryChoices(garden),[packetId,setPacketId]=useState(packets[0]?.id||''),[desired,setDesired]=useState(12),[germination,setGermination]=useState(85),[survival,setSurvival]=useState(90),[extras,setExtras]=useState(2),packet=packets.find(item=>item.id===packetId),result=calculateSeedQuantity({desiredPlants:desired,germinationRate:germination,survivalRate:survival,extras,available:packet?.quantityAvailable??null}),record=resultRecord('seed-quantity',{packetId,cropId:packet?.cropId||'',desired:Number(desired)||0,germination:Number(germination)||0,survival:Number(survival)||0,extras:Number(extras)||0,result});
 const addShortage=()=>{if(!result.shortfall)return;onAddShoppingItem?.({name:`${packet?.name||'Seed'} Seeds`,category:'Seeds',cropId:packet?.cropId||'',variety:packet?.variety||'',brand:packet?.brand||'',quantity:result.shortfall,reason:`Seed Quantity Calculator found a shortage of ${result.shortfall} seeds.`,sourceProjectId:record.id,priority:70})};
 return <><SecondarySectionHeader eyebrow="TARGET AND ASSUMPTIONS" description="Compare the desired planting against the exact packet. Reservations do not claim seeds were started."/><div className="tool-form-card"><label>Exact packet or saved seed<select value={packetId} onChange={event=>setPacketId(event.target.value)}><option value="">No packet selected</option>{packets.map(item=><option key={item.id} value={item.id}>{[item.brand,item.variety||item.name].filter(Boolean).join(' ')||item.name} · {item.quantityAvailable??'unknown'} available</option>)}</select></label><div className="tool-two-fields"><label>Final plants desired<input type="number" min="1" value={desired} onChange={event=>setDesired(event.target.value)}/></label><label>Extra plants desired<input type="number" min="0" value={extras} onChange={event=>setExtras(event.target.value)}/></label></div><div className="tool-two-fields"><label>Expected germination %<input type="number" min="1" max="100" value={germination} onChange={event=>setGermination(event.target.value)}/></label><label>Expected transplant survival %<input type="number" min="1" max="100" value={survival} onChange={event=>setSurvival(event.target.value)}/></label></div></div><section className="tool-result-card"><span className="tool-result-kicker">ESTIMATED STARTING QUANTITY</span><strong>{result.seedsToStart} seeds</strong><p>Targets {result.targetPlants} surviving plants: {result.desiredPlants} wanted plus {result.extras} extras.</p><dl><div><dt>Germination assumption</dt><dd>{result.germinationRate}%</dd></div><div><dt>Survival assumption</dt><dd>{result.survivalRate}%</dd></div>{packet&&<div><dt>Packet available</dt><dd>{result.available}</dd></div>}</dl>{result.shortfall>0&&<div className="tool-warning">Estimated need exceeds available seed by {result.shortfall}.</div>}<ResultActions><button className="secondary-button" onClick={()=>onSaveResult?.(record)}>Save reusable result</button>{packet&&result.shortfall===0&&<button className="secondary-button" onClick={()=>onReserveSeeds?.(packet.id,result.seedsToStart,record)}>Reserve {result.seedsToStart} seeds</button>}{result.shortfall>0&&<button className="secondary-button" onClick={addShortage}>Add shortage to Shopping List</button>}<button className="primary-button" onClick={()=>onOpenIndoor?.({source:'seed-quantity-calculator',sourcePacketId:packet?.id||'',cropId:packet?.cropId||'',crop:packet?.name||'',variety:packet?.variety||'',cells:result.seedsToStart,seedsUsed:result.seedsToStart})}>Start this tray indoors</button></ResultActions></section><EstimateNotice>A reservation protects planning quantity but does not reduce inventory. Inventory changes only when seeds are actually recorded as started.</EstimateNotice></>;
}

const measurementFields={
 'inches-feet':['Inches',null,null],'bed-area':['Length (feet)','Width (feet)',null],'square-feet':['Length (inches)','Width (inches)',null],'cubic-feet':['Length (inches)','Width (inches)','Depth (inches)'],'gallons-cubic':['Gallons',null,null],'row-length':['Row length (feet)','Plant spacing (inches)',null],'round-volume':['Diameter (inches)','Height (inches)',null]
};
function MeasurementsTool({garden,onSaveResult,onApplyToSpace}){
 const spaces=activeSpaces(garden),[spaceId,setSpaceId]=useState('custom'),[mode,setMode]=useState('bed-area'),[a,setA]=useState(8),[b,setB]=useState(4),[c,setC]=useState(10),[copied,setCopied]=useState(false),space=spaces.find(item=>item.id===spaceId),labels=measurementFields[mode],result=calculateMeasurement({mode,a,b,c}),record=resultRecord('measurement',{spaceId,mode,a:Number(a)||0,b:Number(b)||0,c:Number(c)||0,result});
 useEffect(()=>{if(!space)return;const dims=parseSpaceDimensions(space);if(dims.lengthFeet)setA(dims.lengthFeet);if(dims.widthFeet)setB(dims.widthFeet);if(dims.depthInches)setC(dims.depthInches);if(dims.gallons&&mode==='gallons-cubic')setA(dims.gallons);if(dims.diameterInches&&mode==='round-volume')setA(dims.diameterInches)},[spaceId,mode]);
 const copy=async()=>{const text=`${result.label}: ${fmt(result.value)} (${result.detail})`;try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{window.prompt('Copy this result:',text)}};
 const apply=()=>{if(!space)return;const patch=mode==='bed-area'?{lengthFeet:Number(a)||0,widthFeet:Number(b)||0,size:`${Number(a)||0} × ${Number(b)||0} ft`}:mode==='round-volume'?{diameterInches:Number(a)||0,depthInches:Number(b)||0,size:`${Number(a)||0} in diameter × ${Number(b)||0} in high`}:{savedMeasurement:{mode,a:Number(a)||0,b:Number(b)||0,c:Number(c)||0,result,updatedAt:new Date().toISOString()}};onApplyToSpace?.(space.id,patch,record)};
 return <><SecondarySectionHeader eyebrow="QUICK GARDEN CONVERSIONS" description="Load saved dimensions where available, save the result, or apply it to a Growing Space."/><div className="tool-form-card"><SpaceSelect garden={garden} value={spaceId} onChange={setSpaceId}/><label>Measurement<select value={mode} onChange={event=>setMode(event.target.value)}><option value="inches-feet">Inches to feet</option><option value="bed-area">Bed area in square feet</option><option value="square-feet">Square inches to square feet</option><option value="cubic-feet">Cubic inches to cubic feet</option><option value="gallons-cubic">Gallons to cubic feet</option><option value="row-length">Plants along a row</option><option value="round-volume">Round container volume</option></select></label><div className="tool-two-fields"><label>{labels[0]}<input type="number" step="0.01" value={a} onChange={event=>setA(event.target.value)}/></label>{labels[1]&&<label>{labels[1]}<input type="number" step="0.01" value={b} onChange={event=>setB(event.target.value)}/></label>}</div>{labels[2]&&<label>{labels[2]}<input type="number" step="0.01" value={c} onChange={event=>setC(event.target.value)}/></label>}</div><section className="tool-result-card"><span className="tool-result-kicker">RESULT</span><strong>{fmt(result.value)} {result.label.toLowerCase()}</strong><p>{result.detail}</p><ResultActions><button className="secondary-button" onClick={copy}><Copy/>{copied?'Copied':'Copy result'}</button><button className="secondary-button" onClick={()=>onSaveResult?.(record)}>Save reusable result</button>{space&&<button className="primary-button" onClick={apply}>Apply to {space.name}</button>}</ResultActions></section></>;
}

const printableOptions=[['notes','Blank Garden Notes'],['map','Growing Space Map'],['seed-log','Seed-Starting Log'],['harvest-log','Harvest Log'],['watering','Watering Observation Sheet'],['season','Seasonal Planning Sheet'],['shopping','Shopping Checklist'],['labels','Plant Labels']];
function printableBody(template,garden,spaceId){
 const spaces=activeSpaces(garden),selected=spaceId==='all'?spaces:spaces.filter(space=>space.id===spaceId),plants=(garden.plants||[]).filter(plant=>!plant.deletedAt&&!plant.archived),rows=count=>Array.from({length:count},()=>'<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td></tr>').join(''),table=(headers,body)=>`<table><thead><tr>${headers.map(header=>`<th>${header}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table>`;
 if(template==='map')return selected.map(space=>`<section><h2>${escapeHtml(space.name)}</h2><p>${escapeHtml(space.type)} · ${escapeHtml(space.size||'Dimensions not recorded')}</p><div class="map-box">${plants.filter(plant=>plant.spaceId===space.id).map(plant=>`<span>${escapeHtml(plant.name)}${plant.variety?` · ${escapeHtml(plant.variety)}`:''}</span>`).join('')||'<em>Sketch or place plants here</em>'}</div></section>`).join('');
 if(template==='seed-log')return table(['Date','Crop / Variety','Packet','Quantity','Tray / Space'],rows(14));
 if(template==='harvest-log')return table(['Date','Plant','Amount','Unit','Notes'],rows(14));
 if(template==='watering')return table(['Date','Plant / Space','Soil Check','Watered?','Notes'],rows(14));
 if(template==='season')return table(['Crop','Start / Sow','Transplant','Growing Space','Notes'],(garden.yearPlan?.crops||[]).map(item=>`<tr><td>${escapeHtml(cropCatalog.find(crop=>crop.id===item.cropId)?.name||item.cropId)}</td><td></td><td></td><td>${escapeHtml(spaces.find(space=>space.id===item.spaceId)?.name||'')}</td><td></td></tr>`).join('')||rows(12));
 if(template==='shopping'){const items=gardenShoppingItems(garden).filter(item=>!item.purchased);return `<ul class="checklist">${items.map(item=>`<li>☐ ${escapeHtml(item.quantity||1)} ${escapeHtml(item.name)}${item.note?` — ${escapeHtml(item.note)}`:''}</li>`).join('')||Array.from({length:16},()=>'<li>☐</li>').join('')}</ul>`}
 return `<div class="notes-lines">${Array.from({length:24},()=>'<div></div>').join('')}</div>`;
}
function PrintableTool({garden,navigate}){
 const[template,setTemplate]=useState('notes'),[spaceId,setSpaceId]=useState('all'),title=printableOptions.find(item=>item[0]===template)?.[1]||'Garden Printable';
 const print=()=>{if(template==='labels'){navigate('labels');return}const popup=window.open('','_blank','width=760,height=900');if(!popup)return window.alert('Allow pop-ups to print this garden sheet.');popup.document.write(`<!doctype html><html><head><title>${escapeHtml(title)}</title><style>@page{margin:.45in}body{font-family:Arial,sans-serif;color:#173d2b}header{border-bottom:3px solid #0b4d33;margin-bottom:18px;padding-bottom:10px}h1{margin:0;font-family:Georgia,serif}small{color:#59685d}table{width:100%;border-collapse:collapse}th,td{border:1px solid #9aa79e;padding:7px;height:28px;text-align:left;font-size:11px}.map-box{min-height:220px;border:2px solid #0b4d33;padding:14px;display:flex;flex-wrap:wrap;gap:8px}.map-box span{border:1px solid #aaa;padding:5px}.notes-lines div{height:30px;border-bottom:1px solid #9aa79e}.checklist{list-style:none;padding:0}.checklist li{min-height:28px;border-bottom:1px solid #bbb;padding:5px}section{page-break-inside:avoid;margin-bottom:22px}</style></head><body><header><h1>${escapeHtml(title)}</h1><small>The Runyan Garden · ${escapeHtml(garden.profile?.location||'Green Bay, Wisconsin')} · Printed ${escapeHtml(new Date().toLocaleDateString())}</small></header>${printableBody(template,garden,spaceId)}<script>window.onload=()=>window.print()</script></body></html>`);popup.document.close()};
 return <><SecondarySectionHeader eyebrow="CHOOSE A SHEET" description="Print blank pages or prefill them from saved garden records."/><div className="tool-form-card"><label>Printable<select value={template} onChange={event=>setTemplate(event.target.value)}>{printableOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{template==='map'&&<label>Growing Spaces<select value={spaceId} onChange={event=>setSpaceId(event.target.value)}><option value="all">All Growing Spaces</option>{activeSpaces(garden).map(space=><option key={space.id} value={space.id}>{space.name}</option>)}</select></label>}<button className="primary-button" onClick={print}>{template==='labels'?<><ArrowRight/>Open Plant Labels</>:<><Printer/>Print or Save as PDF</>}</button></div><section className="printable-preview-card"><FileText/><span><strong>{title}</strong><small>{template==='labels'?'Uses the existing Plant Labels workflow and preserves all QR destinations.':'A printer-friendly sheet using current garden records where appropriate.'}</small></span></section></>;
}

export default function ToolUtility({mode,garden,navigate,onSaveSpaceNote,onSaveResult,onApplyToSpace,onAddShoppingItem,onOpenPlanting,onReserveSeeds,onOpenIndoor}){
 const info=toolInfo[mode]||toolInfo.spacing,Icon=info.icon,shared={garden,onSaveResult,onApplyToSpace,onAddShoppingItem,onOpenPlanting,onReserveSeeds,onOpenIndoor};
 return <main className="screen secondary-screen tool-utility-screen"><SecondaryHero icon={Icon} eyebrow={info.eyebrow} title={info.title} description={info.description} onBack={()=>navigate('tools')} backLabel="Back to Tool Shed" className="tool-utility-hero"/><section className="screen-pad secondary-screen-content tool-utility-content">{mode==='spacing'&&<SpacingTool {...shared} onSaveSpaceNote={onSaveSpaceNote}/>} {mode==='soil'&&<SoilTool {...shared}/>} {mode==='frost'&&<FrostTool {...shared}/>} {mode==='seeds'&&<SeedQuantityTool {...shared}/>} {mode==='measurements'&&<MeasurementsTool {...shared}/>} {mode==='print'&&<PrintableTool garden={garden} navigate={navigate}/>}</section></main>;
}
