import React from'react';
import{Calculator,CalendarDays,CloudSun,Droplets,FileText,NotebookPen,PackageSearch,Ruler,Sprout,Tags,Wrench}from'lucide-react';
import{SecondaryCard,SecondaryHero,SecondarySectionHeader}from'./SecondaryUI.jsx';

export default function ToolShed({navigate}){
 return <main className="screen secondary-screen tool-shed-screen"><SecondaryHero icon={Wrench} eyebrow="OPTIONAL GARDEN UTILITIES" title="Tool Shed" description="Calculate, measure, estimate, print, label, and check weather tools." className="tool-shed-hero"/><section className="screen-pad secondary-screen-content tool-shed-content">
  <details className="tool-shed-group tool-shed-drawer"><summary><SecondarySectionHeader eyebrow="WEATHER TOOLS"/><span>3</span></summary><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="green" icon={CloudSun} title="Garden Weather" description="Open forecast, rain history, garden impacts, and weather actions." onClick={()=>navigate('weather')}/><SecondaryCard kind="utility" tone="gold" icon={Droplets} title="Rain and Watering Review" description="Check recent rain before deciding whether to water." onClick={()=>navigate('weather')}/><SecondaryCard kind="utility" tone="cream" icon={CalendarDays} title="Forecast and Frost Timing" description="Review weather timing before planting or protecting crops." onClick={()=>navigate('weather')}/></div></details>
  <details className="tool-shed-group tool-shed-drawer"><summary><SecondarySectionHeader eyebrow="NOTES & PRINTABLES"/><span>2</span></summary><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="gold" icon={Tags} title="Plant Labels" description="Create bed signs, plant tags, and custom QR labels." meta="Existing QR and PDF workflow" onClick={()=>navigate('labels')}/><SecondaryCard kind="utility" tone="green" icon={FileText} title="Printable Garden Pack" description="Print garden logs, maps, planning sheets, and checklists." onClick={()=>navigate('printable-pack')}/></div></details>
  <details className="tool-shed-group tool-shed-drawer"><summary><SecondarySectionHeader eyebrow="UTILITIES"/><span>5</span></summary><div className="secondary-card-list tool-shed-card-list"><SecondaryCard kind="utility" tone="cream" icon={Ruler} title="Spacing Calculator" description="Estimate how many plants fit in a Growing Space." onClick={()=>navigate('spacing-calculator')}/><SecondaryCard kind="utility" tone="green" icon={PackageSearch} title="Soil & Container Calculator" description="Estimate soil volume and common bag quantities." onClick={()=>navigate('soil-calculator')}/><SecondaryCard kind="utility" tone="gold" icon={CalendarDays} title="Frost & Planting Dates" description="Check planting dates using saved Green Bay frost timing." onClick={()=>navigate('frost-calculator')}/><SecondaryCard kind="utility" tone="cream" icon={Sprout} title="Seed Quantity Calculator" description="Estimate how many seeds to start for the plants wanted." onClick={()=>navigate('seed-quantity-calculator')}/><SecondaryCard kind="utility" tone="green" icon={Calculator} title="Garden Measurements" description="Convert common garden dimensions, areas, volumes, and row lengths." onClick={()=>navigate('garden-measurements')}/></div></details>
 </section></main>;
}
