import{connectedDuplicateKey,localDateKey,taskDuplicateKey}from'./connectedIntelligence.js';
const DAY=86400000;
const normalize=value=>String(value||'').toLowerCase();
const isoDate=value=>localDateKey(value)||localDateKey(new Date());
const addDays=(date,days)=>{const d=new Date(`${isoDate(date)}T12:00:00`);d.setDate(d.getDate()+days);return isoDate(d)};
const daysBetween=(start,end)=>Math.max(1,Math.round((new Date(`${isoDate(end)}T12:00:00`)-new Date(`${isoDate(start)}T12:00:00`))/DAY)+1);
const activeSpaces=garden=>(garden.spaces||[]).filter(space=>!space.deletedAt&&!space.hidden);
const activePlants=garden=>(garden.plants||[]).filter(plant=>!plant.deletedAt&&!plant.archived&&!['finished','failed','removed'].includes(normalize(plant.stage)));
const recent=value=>{if(!value)return false;const date=new Date(value);return!Number.isNaN(date.getTime())&&Date.now()-date.getTime()<48*60*60*1000};
const taskId=(planId,section,action,targetId,dueDate)=>`vacation-${planId}-${section}-${normalize(action).replace(/[^a-z0-9]+/g,'-')}-${targetId||'garden'}-${dueDate}`;
const priority=urgency=>urgency==='Urgent'?92:urgency==='High'?78:urgency==='Normal'?60:45;
function makeTask(plan,{section,action,targetType='garden',targetId='',targetName='Whole garden',dueDate,instruction,whatToCheck='',whatNotToDo='',weatherException='',urgency='Normal',source='Vacation Mode',taskType='Vacation Care'}){const duplicateKey=taskDuplicateKey({taskType,action,targetId,plantId:targetType==='plant'?targetId:'',spaceId:targetType==='space'?targetId:'',dueDate,category:taskType});return{id:taskId(plan.id,section,action,targetId,dueDate),vacationPlanId:plan.id,section,action,targetType,targetId,targetName,dueDate,instruction,whatToCheck,whatNotToDo,weatherException,urgency,priority:priority(urgency),source,taskType,duplicateKey,status:'active',manualEdited:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
export function vacationWeatherFingerprint(weather={}){const forecasts=(weather.forecasts||[]).slice(0,10).map(row=>[isoDate(row.forecast_for||row.start_time),Math.round(Number(row.maximum_temperature??row.temperature??0)),Math.round(Number(row.minimum_temperature??0)),Math.round(Number(row.precipitation_probability??0)),Math.round(Number(row.wind_speed??0))].join(':')).join('|');return[weather.fetchedAt||weather.updatedAt||'',Math.round(Number(weather.recentRain24h||0)*100),Math.round(Number(weather.high||0)),Math.round(Number(weather.low||0)),Math.round(Number(weather.wind||0)),forecasts].join('|')}
function forecastSummary(weather={},start,end){const rows=(weather.forecasts||[]).filter(row=>{const date=isoDate(row.forecast_for||row.start_time);return date>=isoDate(start)&&date<=isoDate(end)}),high=Math.max(...rows.map(row=>Number(row.maximum_temperature??row.temperature)).filter(Number.isFinite),Number(weather.high)||-999),low=Math.min(...rows.map(row=>Number(row.minimum_temperature??row.temperature)).filter(Number.isFinite),Number(weather.low)||999),rainChance=Math.max(0,...rows.map(row=>Number(row.precipitation_probability||0)),Number(weather.rainChance||0)),wind=Math.max(0,...rows.map(row=>Number(row.wind_speed||0)),Number(weather.wind||0)),rainAmount=rows.reduce((sum,row)=>sum+Math.max(0,Number(row.precipitation_amount||0)),0);return{high:high===-999?null:high,low:low===999?null:low,rainChance,wind,rainAmount,recentRain:Number(weather.recentRain24h||0),heatRisk:high>=88,frostRisk:low<=36,stormRisk:wind>=25||Boolean(weather.signals?.stormRisk?.status||weather.signals?.windDamageRisk?.status),meaningfulRain:rainAmount>=.25||rainChance>=70}}
function exposure(space={}){const type=normalize(space.type);if(['indoor','basement','hydro','greenhouse','seed-tray'].includes(type))return'protected';if(space.weatherExposure==='covered'||/covered|porch|overhang/.test(normalize(`${space.weatherExposure} ${space.name}`)))return'covered';return'exposed'}
function plantSensitivity(plant={}){const stage=normalize(plant.stage);if(/seedling|germinating|seed started|transplant/.test(stage))return'high';if(/flowering|fruiting|harvesting/.test(stage))return'medium';return'normal'}
const spaceKind=space=>{const type=normalize(space?.type);if(['container','potato-grow-bag'].includes(type))return'container';if(type==='greenhouse')return'greenhouse';if(['indoor','basement','hydro','seed-tray'].includes(type))return'indoor';if(/bed|row|ground/.test(type))return'bed';return exposure(space)==='protected'?'indoor':'bed'};
const firstName=list=>(list[0]?.name)||'garden';
const priorityLabel=value=>value>=80?'HIGH PRIORITY':value>=55?'MEDIUM PRIORITY':'LOW PRIORITY';
const makeReviewItem=(id,priority,subject,action,reason,extra={})=>({id,priority,priorityLabel:priorityLabel(priority),subject,action,reason,dateRange:extra.dateRange||'',sourcePacket:extra.sourcePacket||'',crop:extra.crop||'',variety:extra.variety||'',indoorOutdoor:extra.indoorOutdoor||'',growingSpaceRecommendation:extra.growingSpaceRecommendation||'',nextAvailableAction:extra.nextAvailableAction||'',plantId:extra.plantId||'',spaceId:extra.spaceId||'',weatherFactors:extra.weatherFactors||[]});
function plantCropLabel(plant={}){return plant.cropName||plant.crop||plant.name||plant.cropId||'Saved plant'}
function plantVarietyLabel(plant={}){return plant.variety||plant.cultivar||plant.seedVariety||''}
function packetSourceLabel(plant={}){return plant.packetBrand||plant.seedPacketBrand||plant.packetSource||plant.seedSource||plant.sourcePacket||'Saved plant record'}
function dateRangeText(start,end){return start===end?formatSimpleDate(start):`${formatSimpleDate(start)} - ${formatSimpleDate(end)}`}
function formatSimpleDate(value){const date=new Date(`${isoDate(value)}T12:00:00`);return `${date.getMonth()+1}/${date.getDate()}/${String(date.getFullYear()).slice(2)}`}
export function buildVacationIntelligence({garden={},weather={},plan={},now=new Date()}={}){
 const start=isoDate(plan.departureDate),end=isoDate(plan.returnDate),todayKey=isoDate(now),summary=forecastSummary(weather,start,end),spaces=activeSpaces(garden),plants=activePlants(garden),spaceById=new Map(spaces.map(space=>[space.id,space])),beforeRange=dateRangeText(addDays(start,-2),addDays(start,-1)),tripRange=dateRangeText(start,end),items=[],riskReasons=[],riskWarnings=[];
 const groups={container:[],bed:[],greenhouse:[],indoor:[]};
 for(const plant of plants){const space=spaceById.get(plant.spaceId)||{};groups[spaceKind(space)].push({...plant,space})}
 const containerSpaces=spaces.filter(space=>spaceKind(space)==='container'),bedSpaces=spaces.filter(space=>spaceKind(space)==='bed'),greenhouseSpaces=spaces.filter(space=>spaceKind(space)==='greenhouse'),indoorSpaces=spaces.filter(space=>spaceKind(space)==='indoor');
 const rainExpected=summary.rainAmount>=.75||summary.rainChance>=75,lightRain=summary.rainAmount>=.25||summary.rainChance>=55,hot=summary.heatRisk||Number(summary.high)>=88,frost=summary.frostRisk,noRain=!lightRain,containersNeedCare=containerSpaces.length>0||groups.container.length>0,seedlings=[...groups.indoor,...groups.greenhouse,...groups.container,...groups.bed].filter(plant=>plantSensitivity(plant)==='high'),harvestPlants=plants.filter(plant=>/harvesting|fruiting/.test(normalize(plant.stage)));
 let riskScore=0;
 if(containersNeedCare){riskScore+=hot?3:2;riskWarnings.push(`${containerSpaces.length||groups.container.length} container growing area${(containerSpaces.length||groups.container.length)===1?'':'s'}`)}
 if(seedlings.length){riskScore+=seedlings.length>2?3:2;riskWarnings.push(`${seedlings.length} high-risk seedling or recent planting record${seedlings.length===1?'':'s'}`)}
 if(greenhouseSpaces.length){riskScore+=hot?3:1;riskWarnings.push('Greenhouse conditions are separate from outdoor rain')}
 if(hot&&noRain){riskScore+=3;riskWarnings.push('Heat with little dependable rain')}
 else if(hot){riskScore+=1;riskWarnings.push('Hot weather is possible')}
 if(frost){riskScore+=3;riskWarnings.push('Frost risk appears in the trip forecast')}
 if(rainExpected&&!hot&&!frost)riskScore=Math.max(0,riskScore-2);
 if(rainExpected)riskReasons.push('Meaningful rain is expected during the trip');
 if(!rainExpected&&lightRain)riskReasons.push('Some rain is possible, but it may not be enough for containers');
 if(!lightRain)riskWarnings.push('Less than dependable rain is expected');
 if(plants.length&&!seedlings.length)riskReasons.push('No high-risk seedlings were found');
 if(bedSpaces.length&&rainExpected)riskReasons.push('Garden beds should receive outdoor rain');
 if(!plants.length)riskReasons.push('No active plant records are saved yet');
 const riskLevel=riskScore>=6?'HIGH':riskScore>=3?'MEDIUM':'LOW';
 const beforePlants=[...new Set(plants.map(plant=>plant.spaceId).filter(Boolean))];
 for(const space of containerSpaces){const linked=plants.filter(plant=>plant.spaceId===space.id),crop=plantCropLabel(linked[0]||{});items.push(makeReviewItem(`container-${space.id}`,hot&&noRain?95:78,space.name,hot&&noRain?'Deep water before leaving.':'Check container soil before leaving.',hot&&noRain?'Containers dry faster and hot weather with limited rain is expected.':'Containers can dry unevenly, so soil should be checked even when rain is possible.',{dateRange:beforeRange,crop, variety:plantVarietyLabel(linked[0]||{}),sourcePacket:packetSourceLabel(linked[0]||{}),indoorOutdoor:'Outdoor container',growingSpaceRecommendation:`Keep in ${space.name}; group containers where watering is easy.`,nextAvailableAction:`Recheck soil during ${tripRange} if leaves wilt or soil dries.`,spaceId:space.id,plantId:linked[0]?.id||'',weatherFactors:[hot?'Heat expected':'No heat alert',rainExpected?'Rain expected':summary.rainAmount<.25?'Less than 0.25 inches rain expected':'Limited rain expected']}))}
 for(const space of greenhouseSpaces){const linked=plants.filter(plant=>plant.spaceId===space.id);items.push(makeReviewItem(`greenhouse-${space.id}`,hot?96:82,space.name,hot?'Vent and water greenhouse plants before leaving.':'Confirm greenhouse water and airflow before leaving.','Greenhouse plants do not receive outdoor rainfall and heat can build quickly.',{dateRange:beforeRange,crop:plantCropLabel(linked[0]||{}),variety:plantVarietyLabel(linked[0]||{}),sourcePacket:packetSourceLabel(linked[0]||{}),indoorOutdoor:'Protected greenhouse',growingSpaceRecommendation:`Keep airflow open in ${space.name}.`,nextAvailableAction:'Check for wilt and excessive heat during the trip.',spaceId:space.id,plantId:linked[0]?.id||'',weatherFactors:[hot?'Heat expected':'Normal temperature forecast','Outdoor rain does not water greenhouse plants']}))}
 for(const space of indoorSpaces){const linked=plants.filter(plant=>plant.spaceId===space.id);items.push(makeReviewItem(`indoor-${space.id}`,88,space.name,'Water trays and verify lights before leaving.','Indoor seedlings and protected starts cannot use rain, and small cells dry quickly.',{dateRange:beforeRange,crop:plantCropLabel(linked[0]||{}),variety:plantVarietyLabel(linked[0]||{}),sourcePacket:packetSourceLabel(linked[0]||{}),indoorOutdoor:'Indoor/protected',growingSpaceRecommendation:`Keep in ${space.name} with stable light and moisture.`,nextAvailableAction:'Check trays when you return or sooner if someone is already visiting.',spaceId:space.id,plantId:linked[0]?.id||'',weatherFactors:['Outdoor weather does not water indoor starts']}))}
 for(const plant of harvestPlants){const space=spaceById.get(plant.spaceId)||{};items.push(makeReviewItem(`harvest-${plant.id}`,86,plant.name,'Harvest ripe or nearly ripe produce before leaving.',hot?'Hot weather can reduce quality or push produce past peak while you are away.':'Produce may become overripe during the vacation window.',{dateRange:beforeRange,crop:plantCropLabel(plant),variety:plantVarietyLabel(plant),sourcePacket:packetSourceLabel(plant),indoorOutdoor:spaceKind(space)==='indoor'||spaceKind(space)==='greenhouse'?'Protected':'Outdoor',growingSpaceRecommendation:space.name||'Current growing space',nextAvailableAction:'Inspect harvest-ready plants when you return.',plantId:plant.id,spaceId:plant.spaceId,weatherFactors:[hot?'Heat expected':'Normal temperature forecast']}))}
 for(const plant of seedlings){const space=spaceById.get(plant.spaceId)||{};items.push(makeReviewItem(`seedling-${plant.id}`,90,plant.name,'Stabilize seedling moisture and protection before leaving.','Seedlings and recent starts have smaller root systems and less buffer while unattended.',{dateRange:beforeRange,crop:plantCropLabel(plant),variety:plantVarietyLabel(plant),sourcePacket:packetSourceLabel(plant),indoorOutdoor:spaceKind(space)==='indoor'||spaceKind(space)==='greenhouse'?'Protected':'Outdoor',growingSpaceRecommendation:space.name||'Move to the most stable protected area if practical.',nextAvailableAction:'Check for wilt, damping-off, or dry cells after the trip.',plantId:plant.id,spaceId:plant.spaceId,weatherFactors:[hot?'Heat expected':'Normal temperature forecast',frost?'Frost risk':'No frost risk']}))}
 if(bedSpaces.length){const bedNames=bedSpaces.map(space=>space.name).join(', ');items.push(makeReviewItem('garden-beds',rainExpected?35:hot?70:55,'Garden beds',rainExpected?'No extra watering needed unless soil is dry.':'Check bed moisture and water only dry root zones before leaving.',rainExpected?'Rain is expected and garden beds retain moisture better than containers.':hot?'Beds have more moisture reserve than containers, but heat and limited rain can dry active roots.':'Normal weather is expected, but a quick soil check prevents surprises.',{dateRange:beforeRange,sourcePacket:'Saved garden spaces',crop:'Mixed garden beds',indoorOutdoor:'Outdoor bed',growingSpaceRecommendation:bedNames,nextAvailableAction:'Walk beds after returning and record only actions actually needed.',spaceId:bedSpaces[0].id,weatherFactors:[rainExpected?'Rain expected':noRain?'Little dependable rain':'Some rain possible',hot?'Heat expected':'No heat alert']}))}
 if(!items.length)items.push(makeReviewItem('whole-garden-review',45,'Whole garden','Do one quick garden walk before leaving.','No high-risk saved plants were found, but Vacation Mode needs current records to be more specific.',{dateRange:beforeRange,sourcePacket:'Saved garden records',crop:'All active records',indoorOutdoor:'Mixed',growingSpaceRecommendation:'Update plant spaces for better guidance.',nextAvailableAction:'Add or update plant records when you return.'}));
 const sorted=items.sort((a,b)=>b.priority-a.priority||a.subject.localeCompare(b.subject));
 const dailyChecks=sorted.filter(item=>item.priority>=70).slice(0,8).map(item=>({id:`check-${item.id}`,label:item.subject,instruction:item.nextAvailableAction||item.action,reason:item.reason,plantId:item.plantId,spaceId:item.spaceId}));
 if(dailyChecks.length===0)dailyChecks.push({id:'check-general',label:'Garden walk',instruction:'Check containers, greenhouse, and harvest-ready plants only if conditions look dry or stressed.',reason:'Vacation risk is low, but a quick visual check catches surprises.'});
 const doNot=[];
 if(rainExpected&&bedSpaces.length)doNot.push('Do not water garden beds during the rain period unless soil is actually dry.');
 if(seedlings.length)doNot.push('Do not overwater seedlings or leave trays sitting in water.');
 if(greenhouseSpaces.length)doNot.push('Do not count outdoor rain as greenhouse watering.');
 if(!doNot.length)doNot.push('Do not duplicate chores that were already completed or logged.');
 const completed=[];
 if(rainExpected&&bedSpaces.length)completed.push('Rain likely covered outdoor garden beds.');
 if(!hot&&!frost)completed.push('No major temperature emergency was expected.');
 if(!completed.length)completed.push('Vacation Mode preserved the trip plan and records for review.');
 const needsAttention=['Inspect containers and protected spaces first.'];
 if(harvestPlants.length)needsAttention.push('Check harvest-ready plants.');
 if(seedlings.length)needsAttention.push('Review seedlings or recent plantings.');
 if(hot)needsAttention.push('Look for heat stress and dry root zones.');
 if(frost)needsAttention.push('Inspect tender plants for cold damage.');
 return{schemaVersion:1,generatedAt:new Date().toISOString(),dateRange:{departureDate:start,returnDate:end,label:tripRange},weather:{high:summary.high,low:summary.low,rainChance:summary.rainChance,rainAmount:summary.rainAmount,heatRisk:hot,frostRisk:frost,meaningfulRain:summary.meaningfulRain,summary:rainExpected?'Meaningful rain is expected.':hot&&noRain?'Hot, dry conditions need attention.':'Normal vacation weather checks apply.'},risk:{level:riskLevel,label:`${riskLevel} RISK`,score:riskScore,summary:riskLevel==='LOW'?'Your garden should be okay with normal checks.':riskLevel==='MEDIUM'?'Some areas need attention before you leave.':'Attention is recommended before leaving.',reasons:riskReasons,warnings:riskWarnings},beforeYouLeave:sorted,helperGuide:{title:'Garden Buddy Guide',dates:tripRange,dailyChecks,doNot,localOnly:true},returnHome:{title:end<todayKey?'Welcome Back':'Welcome Back Review',completed,needsAttention},futureAccessModel:{ownerScope:'Garden Owner',helperInstructionScope:'Local printable Garden Buddy guide only',temporaryAccessPrepared:false,phase:'Phase 5-ready metadata only'},recordLinks:{plantIds:[...new Set(sorted.map(item=>item.plantId).filter(Boolean))],spaceIds:[...new Set(sorted.map(item=>item.spaceId).filter(Boolean))],coveredSpaceIds:beforePlants}};
}
export function buildVacationPlan({garden={},weather={},departureDate,returnDate,caretakerAvailable=false,caretakerName='',caretakerNotes='',id=null,actor='System'}={}){const start=isoDate(departureDate),end=isoDate(returnDate),duration=daysBetween(start,end),createdAt=new Date().toISOString(),plan={id:id||`trip-${start}-${end}`,status:'active',departureDate:start,returnDate:end,duration,caretakerAvailable:Boolean(caretakerAvailable),caretakerName:caretakerName||'',caretakerNotes:caretakerNotes||'',weatherFingerprint:vacationWeatherFingerprint(weather),weatherEvaluatedAt:weather.fetchedAt||weather.updatedAt||createdAt,createdAt,updatedAt:createdAt,createdBy:actor,updatedBy:actor,revision:1,deletedAt:null,tasks:[],changes:[]},summary=forecastSummary(weather,start,end),spaces=activeSpaces(garden),plants=activePlants(garden),before=addDays(start,-1),after=addDays(end,1),tasks=[];
 const containers=spaces.filter(space=>['container','potato-grow-bag'].includes(normalize(space.type))),greenhouses=spaces.filter(space=>normalize(space.type)==='greenhouse'),protectedSpaces=spaces.filter(space=>exposure(space)==='protected'&&normalize(space.type)!=='greenhouse'),exposedBeds=spaces.filter(space=>exposure(space)==='exposed'&&!containers.includes(space));
 for(const space of containers){const spacePlants=plants.filter(plant=>plant.spaceId===space.id),sensitive=spacePlants.some(plant=>plantSensitivity(plant)==='high'),recentlyWatered=spacePlants.length&&spacePlants.every(plant=>recent(plant.lastWatered));tasks.push(makeTask(plan,{section:'before',action:'Check container soil',targetType:'space',targetId:space.id,targetName:space.name,dueDate:before,instruction:recentlyWatered?'Confirm the soil is still evenly moist before leaving. Water only if the top inch is dry.':'Check the top inch of soil and water thoroughly only if it is dry.',whatToCheck:'Feel the soil one inch down and confirm drainage is working.',whatNotToDo:'Do not water automatically when the soil is still moist.',weatherException:'Forecast rain counts only if this container is fully exposed and meaningful rain actually reaches it.',urgency:sensitive||summary.heatRisk?'High':'Normal',taskType:'Check Moisture'}));if(caretakerAvailable&&duration>=3){for(let offset=2;offset<duration;offset+=summary.heatRisk?1:2){const due=addDays(start,offset);tasks.push(makeTask(plan,{section:'during',action:'Garden Buddy container soil check',targetType:'space',targetId:space.id,targetName:space.name,dueDate:due,instruction:`Check ${space.name} in the evening. Water only if the top inch is dry.`,whatToCheck:'Soil moisture, wilt that persists after sunset, and drainage.',whatNotToDo:'Do not water from the calendar alone and do not leave standing water.',weatherException:'Skip watering if meaningful observed rain reached this exposed container and the soil is still moist.',urgency:summary.heatRisk?'High':'Normal',taskType:'Check Moisture'}))}}}
 for(const space of exposedBeds){tasks.push(makeTask(plan,{section:'before',action:'Review exposed bed moisture',targetType:'space',targetId:space.id,targetName:space.name,dueDate:before,instruction:summary.recentRain>=.25?'Recent observed rain may have covered this bed. Check soil before adding more water.':'Check the root zone before leaving and water only where it is drying.',whatToCheck:'Moisture below the surface near active roots.',whatNotToDo:'Do not treat forecast rain as rain that already happened.',weatherException:summary.meaningfulRain?'Meaningful rain is forecast; verify that it actually occurs before skipping later checks.':'No dependable rain is currently shown for the trip.',urgency:summary.heatRisk?'High':'Normal',taskType:'Check Moisture'}));if(caretakerAvailable&&duration>=6)tasks.push(makeTask(plan,{section:'during',action:'Garden Buddy bed soil check',targetType:'space',targetId:space.id,targetName:space.name,dueDate:addDays(start,Math.min(duration-1,4)),instruction:`Check soil in ${space.name} below the surface. Water the root zone only if it is drying.`,whatToCheck:'Moisture two inches down and plant stress late in the day.',whatNotToDo:'Do not water because the surface looks pale if the root zone is moist.',weatherException:'Observed rain may replace this watering, but forecast probability alone does not.',urgency:'Normal',taskType:'Check Moisture'}))}
 for(const space of greenhouses){tasks.push(makeTask(plan,{section:'before',action:'Prepare greenhouse',targetType:'space',targetId:space.id,targetName:space.name,dueDate:before,instruction:'Confirm ventilation, watering access, shade, and safe airflow before departure.',whatToCheck:'Temperature controls, vents, irrigation, and anything that could fail while unattended.',whatNotToDo:'Do not count outdoor rainfall as greenhouse watering.',weatherException:summary.heatRisk?'High heat is possible; prioritize ventilation and shade.':'Continue to treat greenhouse conditions separately from outdoor weather.',urgency:summary.heatRisk?'Urgent':'High',taskType:'Greenhouse Ventilation'}));if(caretakerAvailable){for(let offset=1;offset<duration;offset+=summary.heatRisk?1:2)tasks.push(makeTask(plan,{section:'during',action:'Garden Buddy greenhouse check',targetType:'space',targetId:space.id,targetName:space.name,dueDate:addDays(start,offset),instruction:'Check temperature, airflow, and soil moisture. Ventilate before watering if heat is building.',whatToCheck:'Temperature, humidity, airflow, and dry containers.',whatNotToDo:'Do not leave the greenhouse closed during dangerous heat and do not assume outdoor rain reached plants.',weatherException:'Increase ventilation checks during hot or sunny weather.',urgency:summary.heatRisk?'Urgent':'High',taskType:'Greenhouse Ventilation'}))}}
 for(const space of protectedSpaces){if(caretakerAvailable&&duration>=5)tasks.push(makeTask(plan,{section:'during',action:'Check protected growing area',targetType:'space',targetId:space.id,targetName:space.name,dueDate:addDays(start,3),instruction:`Check ${space.name}; outdoor rain does not automatically cover this space.`,whatToCheck:'Actual moisture and equipment status.',whatNotToDo:'Do not apply outdoor rain credit to a protected space.',weatherException:'Use the real condition inside this space.',urgency:'Normal',taskType:'Check Moisture'}))}
 for(const plant of plants){const space=spaces.find(row=>row.id===plant.spaceId),stage=normalize(plant.stage),sensitive=plantSensitivity(plant);if(/harvesting|fruiting/.test(stage))tasks.push(makeTask(plan,{section:'before',action:'Harvest ripe produce',targetType:'plant',targetId:plant.id,targetName:plant.name,dueDate:before,instruction:`Pick ripe or nearly ripe produce from ${plant.name} before leaving.`,whatToCheck:'Fruit or leaves that will become overripe during the trip.',whatNotToDo:'Do not strip immature produce that should remain on the plant.',weatherException:summary.heatRisk?'Harvest heat-sensitive produce early in the day.':'Use normal harvest readiness.',urgency:'High',taskType:'Harvest'}));if(sensitive==='high')tasks.push(makeTask(plan,{section:'before',action:'Protect recent or young planting',targetType:'plant',targetId:plant.id,targetName:plant.name,dueDate:before,instruction:`Confirm ${plant.name} has stable moisture, shade or protection appropriate to its stage, and a clear Garden Buddy note if needed.`,whatToCheck:'Wilt, loose roots, unprotected trays, and drying containers.',whatNotToDo:'Do not leave a recent transplant in an unstable location.',weatherException:summary.heatRisk?'Add temporary afternoon protection if appropriate.':summary.frostRisk?'Prepare frost protection.':'Recheck the latest forecast before departure.',urgency:'High',taskType:'Vacation Care'}))}
 if(summary.stormRisk)tasks.push(makeTask(plan,{section:'before',action:'Secure garden before wind',dueDate:before,instruction:'Secure trellises, loose covers, lightweight pots, and tools before leaving.',whatToCheck:'Supports, hanging items, row covers, and containers that can tip.',whatNotToDo:'Do not leave loose plastic or fabric where it can damage plants.',weatherException:'Storm or strong-wind risk is present in the trip forecast.',urgency:'Urgent',taskType:'Storm Preparation'}));if(summary.frostRisk)tasks.push(makeTask(plan,{section:'before',action:'Prepare frost protection',dueDate:before,instruction:'Place frost cloth and weights where a Garden Buddy can deploy them quickly.',whatToCheck:'Tender outdoor plants and recently transplanted seedlings.',whatNotToDo:'Do not cover indoor or already protected records unnecessarily.',weatherException:'A low-temperature risk appears during the trip.',urgency:'Urgent',taskType:'Frost Protection'}));
 tasks.push(makeTask(plan,{section:'after',action:'Post-trip garden inspection',dueDate:after,instruction:'Walk every active Growing Space, check moisture and damage, and record only work that was actually completed.',whatToCheck:'Heat stress, storm damage, dry containers, greenhouse issues, ripe produce, and missed time-sensitive tasks.',whatNotToDo:'Do not automatically repeat every missed reminder; decide from current conditions.',weatherException:'Use observed weather and Garden Buddy notes rather than the old forecast.',urgency:'High',taskType:'Vacation Return'}));tasks.push(makeTask(plan,{section:'after',action:'Record Garden Buddy actions',dueDate:after,instruction:'Record watering, harvests, greenhouse checks, and problems completed during the trip so the normal garden history stays accurate.',whatToCheck:'Garden Buddy checkboxes and notes.',whatNotToDo:'Do not create duplicate records for actions already logged.',weatherException:'None.',urgency:'Normal',taskType:'Vacation Return'}));
 plan.tasks=linkExistingGardenTasks(garden,dedupeVacationTasks(tasks));plan.weatherSummary=summary;plan.intelligence=buildVacationIntelligence({garden,weather,plan});return plan}

export function linkExistingGardenTasks(garden={},tasks=[]){
 const existing=[...(garden.reminders||[]),...(garden.taskHistory||[])].filter(row=>!row.deletedAt&&row.status!=='skipped');
 return tasks.map(task=>{
  const key=taskDuplicateKey(task),match=existing.find(row=>taskDuplicateKey(row)===key);
  if(!match)return{...task,duplicateKey:key};
  const completed=match.status==='done'||match.status==='completed'||Boolean(match.completedAt);
  return{...task,duplicateKey:key,linkedTaskId:match.taskId||match.id,reusedExistingTask:true,status:completed?'completed':task.status,completedAt:completed?(match.completedAt||match.at||task.completedAt):task.completedAt};
 });
}
export function dedupeVacationTasks(tasks=[]){const map=new Map();for(const row of tasks){const key=row.duplicateKey||connectedDuplicateKey('vacation-task',row),current=map.get(key);if(!current||row.priority>current.priority)map.set(key,{...row,duplicateKey:key})}return[...map.values()].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||b.priority-a.priority)}
export function vacationTasksForBoard(garden={}){
 return (garden.vacationPlans||[])
  .filter(plan=>!plan.deletedAt&&plan.status==='active')
  .flatMap(plan=>(plan.tasks||[])
   .filter(row=>!row.deletedAt&&row.status!=='completed'&&!row.reusedExistingTask)
   .map(row=>({
    id:row.id,duplicateKey:row.duplicateKey,kind:'vacation',taskType:row.taskType||'Vacation Care',vacationPlanId:plan.id,
    priority:row.priority||60,title:row.action,subtitle:`${row.targetName}: ${row.instruction}`,
    reason:[row.whatToCheck,row.weatherException].filter(Boolean).join(' '),dueDate:row.dueDate,
    spaceId:row.targetType==='space'?row.targetId:'',plantId:row.targetType==='plant'?row.targetId:'',
    manual:true,source:'Vacation Mode',action:'Open Vacation Plan'
   })));
}
export function vacationPlanNeedsReview(plan={},weather={}){const current=vacationWeatherFingerprint(weather);return Boolean(plan.status==='active'&&plan.weatherFingerprint&&current&&current!==plan.weatherFingerprint)}
export function refreshVacationPlan(plan,garden,weather,actor='System'){const regenerated=buildVacationPlan({garden,weather,departureDate:plan.departureDate,returnDate:plan.returnDate,caretakerAvailable:plan.caretakerAvailable,caretakerName:plan.caretakerName,caretakerNotes:plan.caretakerNotes,id:plan.id,actor}),previous=new Map((plan.tasks||[]).map(row=>[row.duplicateKey,row])),changes=[];regenerated.tasks=regenerated.tasks.map(row=>{const old=previous.get(row.duplicateKey);if(!old)return row;if(old.manualEdited)return{...row,instruction:old.instruction,whatToCheck:old.whatToCheck,whatNotToDo:old.whatNotToDo,weatherException:old.weatherException,manualEdited:true,status:old.status,completedAt:old.completedAt};if(old.status==='completed')return{...row,status:'completed',completedAt:old.completedAt};if(old.instruction!==row.instruction||old.urgency!==row.urgency)changes.push({taskId:row.id,title:row.action,from:old.instruction,to:row.instruction,reason:'Forecast or trip details changed',requiresConfirmation:false});return row});for(const old of plan.tasks||[]){if(old.manualEdited&&!regenerated.tasks.some(row=>row.duplicateKey===old.duplicateKey))regenerated.tasks.push({...old,weatherReview:'No longer automatically required; kept because it was manually edited.'})}return{...regenerated,createdAt:plan.createdAt,createdBy:plan.createdBy,revision:Number(plan.revision||1)+1,updatedAt:new Date().toISOString(),updatedBy:actor,changes}}
