import React,{useMemo,useState}from'react';
import{AlertTriangle,ChevronDown,CloudRain,Droplets,Edit3,Gauge,MapPin,RefreshCw,Trash2,Wind,X}from'lucide-react';
import{formatGardenDate,formatGardenDateTime,formatGardenTime,localDateTimeInputValue}from'./dateFormat.js';

const amount=value=>Number.isFinite(Number(value))?`${Number(value).toFixed(2)} in`:'Not available';
const reading=value=>value===null||value===undefined?'—':value;

function CorrectionForm({initial=null,onSave,onCancel}){
 const[data,setData]=useState(()=>({rainfall_amount:initial?.precipitation_amount??'',temperature:initial?.temperature??'',note:initial?.entry_note||'',observed_at:localDateTimeInputValue(initial?.observed_at||new Date()),source:initial?.source_name||'Home weather monitor'}));
 const submit=event=>{event.preventDefault();const rain=Number(data.rainfall_amount);if(!Number.isFinite(rain)||rain<0||rain>10)return;onSave({...data,rainfall_amount:rain,temperature:data.temperature===''?null:Number(data.temperature),observed_at:new Date(data.observed_at).toISOString()})};
 return <form className="home-weather-form" onSubmit={submit}><div className="home-weather-form-heading"><span><small>LOCAL CORRECTION</small><strong>{initial?'Edit home reading':'Record rain at home'}</strong></span>{onCancel&&<button type="button" onClick={onCancel} aria-label="Close weather form"><X/></button>}</div><div className="weather-form-grid"><label>Rainfall amount (inches)<input type="number" min="0" max="10" step="0.01" inputMode="decimal" value={data.rainfall_amount} onChange={event=>setData({...data,rainfall_amount:event.target.value})} placeholder="0.56" required/></label><label>Outdoor temperature (optional)<input type="number" min="-60" max="140" step="0.1" inputMode="decimal" value={data.temperature} onChange={event=>setData({...data,temperature:event.target.value})} placeholder="72"/></label></div><label>Measurement time<input type="datetime-local" value={data.observed_at} onChange={event=>setData({...data,observed_at:event.target.value})} required/></label><label>Source<input value={data.source} onChange={event=>setData({...data,source:event.target.value})}/></label><label>Optional note<textarea rows="2" value={data.note} onChange={event=>setData({...data,note:event.target.value})} placeholder="Backyard gauge after the storm"/></label><div className="weather-form-actions"><button className="primary-button" type="submit"><Droplets/>{initial?'Save correction':'Record reading'}</button>{onCancel&&<button type="button" onClick={onCancel}>Cancel</button>}</div></form>
}

export function WeatherDetails({weather,source,stale,savedAt,error,loading,refresh,recordRain,updateCorrection,removeCorrection,corrections=[]}){
 const[adding,setAdding]=useState(false),[editing,setEditing]=useState(null),[notice,setNotice]=useState('');
 const current=weather?.currentObservation,forecast=weather?.forecasts||[],nextRain=forecast.find(row=>Number(row.precipitation_probability||0)>=50||Number(row.precipitation_amount||0)>=0.1),daily=forecast.filter(row=>row.minimum_temperature!==null||row.maximum_temperature!==null).slice(0,4),importantSignals=useMemo(()=>Object.entries(weather?.signals||{}).filter(([,value])=>value?.status).slice(0,6),[weather]);
 const saveNew=data=>{const saved=recordRain?.(data);if(saved){setNotice(`${Number(data.rainfall_amount).toFixed(2)} in recorded`);setAdding(false)}};
 const saveEdit=data=>{updateCorrection?.(editing.record_id,data);setNotice('Home reading updated');setEditing(null)};
 return <details className="weather-details-drawer"><summary><span><Gauge/><span><strong>Garden weather details</strong><small>Sources, rain history, forecast, and local corrections</small></span></span><ChevronDown/></summary><div className="weather-details-body">
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>CURRENT CONDITIONS</small><strong>{weather?.condition||'Conditions unavailable'}</strong></span><button onClick={refresh} disabled={loading} aria-label="Refresh garden weather"><RefreshCw/>{loading?'Updating':'Refresh'}</button></div><div className="weather-reading-grid"><article><small>Temperature</small><strong>{reading(weather?.temperature)}°</strong></article><article><small>Humidity</small><strong>{reading(weather?.humidity)}{weather?.humidity!==null&&weather?.humidity!==undefined?'%':''}</strong></article><article><small>Wind</small><strong>{reading(weather?.wind)} mph</strong></article><article><small>Recent rain</small><strong>{amount(weather?.recentRain24h)}</strong></article></div><p className="weather-source-line"><MapPin/> {current?.source_name||weather?.provider||'Source unavailable'} · {current?.observed_at?formatGardenDateTime(current.observed_at,{prefix:'Last observed '}):'Observation time unavailable'}</p>{(stale||error)&&<p className="weather-data-warning"><AlertTriangle/>{error||'Conditions are stale. Check soil before watering.'}</p>}</section>
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>RECENT CONDITIONS</small><strong>What matters to the garden</strong></span></div>{importantSignals.length?<div className="weather-signal-list">{importantSignals.map(([key,value])=><article key={key}><span className="weather-signal-icon">{key.toLowerCase().includes('rain')?<CloudRain/>:key.toLowerCase().includes('wind')?<Wind/>:<AlertTriangle/>}</span><span><strong>{key.replace(/([A-Z])/g,' $1').replace(/^./,letter=>letter.toUpperCase())}</strong><small>{value.reason}</small></span></article>)}</div>:<p>No major garden-weather adjustment is active.</p>}</section>
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>FORECAST</small><strong>Next useful window</strong></span></div>{nextRain?<p><strong>Next meaningful rain:</strong> {formatGardenDateTime(nextRain.forecast_for)} · {Math.round(nextRain.precipitation_probability||0)}% chance</p>:<p>No strong rain window is present in the available forecast.</p>}<div className="weather-forecast-strip">{daily.map(row=><article key={row.record_id}><small>{formatGardenDate(row.forecast_for)}</small><strong>{reading(row.maximum_temperature)}° / {reading(row.minimum_temperature)}°</strong><em>{Math.round(row.precipitation_probability||0)}% rain</em></article>)}</div></section>
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>LOCAL CORRECTIONS</small><strong>Home weather monitor</strong></span><button onClick={()=>setAdding(value=>!value)}><Droplets/>{adding?'Close':'Add reading'}</button></div>{notice&&<p className="weather-save-notice" role="status">{notice}</p>}{adding&&<CorrectionForm onSave={saveNew} onCancel={()=>setAdding(false)}/>} {editing&&<CorrectionForm initial={editing} onSave={saveEdit} onCancel={()=>setEditing(null)}/>} {!editing&&<div className="weather-correction-list">{corrections.length?corrections.map(row=><article key={row.record_id}><Droplets/><span><strong>{amount(row.precipitation_amount)} recorded</strong><small>{row.source_name||'Home weather monitor'} · {formatGardenDate(row.observed_at)} at {formatGardenTime(row.observed_at)}</small>{row.entry_note&&<em>{row.entry_note}</em>}</span><button onClick={()=>setEditing(row)} aria-label="Edit home weather reading"><Edit3/></button><button onClick={()=>removeCorrection?.(row.record_id)} aria-label="Remove home weather reading"><Trash2/></button></article>):<p>No home weather corrections are saved.</p>}</div>}</section>
  <section className="weather-detail-section weather-data-status"><div className="weather-detail-heading"><span><small>DATA STATUS</small><strong>{weather?.freshness||'Unavailable'} · {weather?.confidence||'Low'} confidence</strong></span></div><p>Last refresh: {savedAt?formatGardenDateTime(savedAt):'Not available'} · Connection: {source==='live'?'Official observation and forecast':source==='fallback'?'Regional fallback':source==='cached'?'Saved reading':'Unavailable'}</p><small>Garden weather station connection is available in a future update. No personal station is connected yet.</small></section>
 </div></details>
}
