import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,ChevronDown,CloudRain,Droplets,Edit3,Gauge,MapPin,RefreshCw,Trash2,X}from'lucide-react';
import{formatGardenDate,formatGardenDateTime,formatGardenTime,localDateTimeInputValue}from'./dateFormat.js';
import{bestWeatherTimestamp,formatRainAmount,groupWeatherImpacts,normalizeForecastDays,roundWeatherValue}from'./weatherPresentation.js';

const DETAILS_KEY='runyan-weather-details-open-v1';
const amount=value=>formatRainAmount(value)||'Not available';
const dayLabel=dateKey=>{const date=new Date(`${dateKey}T12:00:00`),today=new Date(),tomorrow=new Date();tomorrow.setDate(today.getDate()+1);const key=date.toISOString().slice(0,10);if(key===today.toISOString().slice(0,10))return'TODAY';if(key===tomorrow.toISOString().slice(0,10))return'TOMORROW';return date.toLocaleDateString('en-US',{weekday:'long'}).toUpperCase()};

function CorrectionForm({initial=null,onSave,onCancel}){
 const[data,setData]=useState(()=>({rainfall_amount:initial?.precipitation_amount??'',temperature:initial?.temperature??'',note:initial?.entry_note||'',observed_at:localDateTimeInputValue(initial?.observed_at||new Date()),source:initial?.source_name||'Home weather monitor'})),[error,setError]=useState('');
 const submit=event=>{event.preventDefault();const rain=Number(data.rainfall_amount);if(!Number.isFinite(rain)||rain<0||rain>10){setError('Enter a rainfall amount from 0 to 10 inches.');return}setError('');onSave({...data,rainfall_amount:rain,temperature:data.temperature===''?null:Number(data.temperature),observed_at:new Date(data.observed_at).toISOString()})};
 return <form className="home-weather-form compact-weather-form" onSubmit={submit}><div className="home-weather-form-heading"><span><small>LOCAL CORRECTION</small><strong>{initial?'Edit home reading':'Record rain at home'}</strong></span>{onCancel&&<button type="button" onClick={onCancel} aria-label="Close weather form"><X/></button>}</div><div className="weather-form-grid"><label>Rainfall amount (inches)<input type="number" min="0" max="10" step="0.01" inputMode="decimal" value={data.rainfall_amount} onChange={event=>setData({...data,rainfall_amount:event.target.value})} placeholder="0.56" required/></label><label>Outdoor temperature (optional)<input type="number" min="-60" max="140" step="0.1" inputMode="decimal" value={data.temperature} onChange={event=>setData({...data,temperature:event.target.value})} placeholder="72"/></label></div><label>Measurement time<input type="datetime-local" value={data.observed_at} onChange={event=>setData({...data,observed_at:event.target.value})} required/></label><label>Source<input value={data.source} onChange={event=>setData({...data,source:event.target.value})}/></label><label>Optional note<textarea rows="2" value={data.note} onChange={event=>setData({...data,note:event.target.value})} placeholder="Backyard gauge after the storm"/></label>{error&&<p role="alert" className="weather-form-error">{error}</p>}<div className="weather-form-actions"><button className="primary-button" type="submit"><Droplets/>{initial?'Save correction':'Record reading'}</button>{onCancel&&<button type="button" onClick={onCancel}>Cancel</button>}</div></form>;
}

export function WeatherDetails({weather,source,stale,savedAt,error,loading,refresh,recordRain,updateCorrection,removeCorrection,corrections=[],guidance}){
 const[adding,setAdding]=useState(false),[editing,setEditing]=useState(null),[notice,setNotice]=useState(''),[open,setOpen]=useState(()=>{try{return sessionStorage.getItem(DETAILS_KEY)==='open'}catch{return false}});
 const current=weather?.currentObservation,forecast=weather?.forecasts||[],days=useMemo(()=>normalizeForecastDays(forecast,4),[forecast]),impacts=useMemo(()=>groupWeatherImpacts(guidance?.recommendations||[],12),[guidance]),timestamp=bestWeatherTimestamp({weather,savedAt}),nextRain=days.find(day=>(day.rainProbability||0)>=50||day.rainAmount>=.1),recentRain=Number(weather?.recentRain24h||0);
 useEffect(()=>{const handler=()=>setOpen(true);window.addEventListener('runyan-open-weather-details',handler);return()=>window.removeEventListener('runyan-open-weather-details',handler)},[]);
 useEffect(()=>{try{sessionStorage.setItem(DETAILS_KEY,open?'open':'closed')}catch{}},[open]);
 const saveNew=data=>{const saved=recordRain?.(data);if(saved){setNotice(`${amount(data.rainfall_amount)} recorded`);setAdding(false)}};
 const saveEdit=data=>{updateCorrection?.(editing.record_id,data);setNotice('Home reading updated');setEditing(null)};
 const updatedText=timestamp.value?`${timestamp.label}: ${formatGardenDateTime(timestamp.value)}`:`${timestamp.label}: unavailable`;
 return <details id="garden-weather-details" className="weather-details-drawer phase-45-weather-details" open={open} onToggle={event=>setOpen(event.currentTarget.open)}><summary><span><Gauge/><span><strong>Garden weather details</strong><small>Forecast, rain history, all impacts, local corrections, and data source</small></span></span><ChevronDown/></summary><div className="weather-details-body compact-weather-details-body">
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>CURRENT CONDITIONS</small><strong>{weather?.condition||'Conditions unavailable'}</strong></span><button onClick={refresh} disabled={loading} aria-label="Refresh garden weather"><RefreshCw/>{loading?'Updating':'Refresh'}</button></div><div className="compact-weather-rows"><span><small>Temperature</small><strong>{roundWeatherValue(weather?.temperature,{suffix:'°'})||'Unavailable'}</strong></span><span><small>Humidity</small><strong>{roundWeatherValue(weather?.humidity,{suffix:'%'})||'Unavailable'}</strong></span><span><small>Wind</small><strong>{roundWeatherValue(weather?.wind,{suffix:' mph'})||'Unavailable'}</strong></span><span><small>Condition</small><strong>{weather?.condition||'Unavailable'}</strong></span></div><p className="weather-source-line"><MapPin/> {current?.source_name||weather?.provider||'Source unavailable'} · {current?.observed_at?formatGardenDateTime(current.observed_at,{prefix:'Observed '}):updatedText}</p>{(stale||error)&&<p className="weather-data-warning"><AlertTriangle/>{error||'Conditions are stale. Check soil before watering.'}</p>}</section>
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>RECENT RAIN</small><strong>{recentRain>0?`${amount(recentRain)} recorded recently`:'No meaningful recent rain recorded'}</strong></span></div><p>{recentRain>0?'Exposed spaces receive rainfall credit according to their saved exposure. Covered, indoor, and greenhouse spaces still require their own soil check.':'No recent observed or corrected rainfall is currently changing routine care.'}</p>{corrections.length>0&&<small>{corrections.length} home reading{corrections.length===1?'':'s'} included in the correction history.</small>}</section>
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>FORECAST</small><strong>{nextRain?`Next useful rain window: ${dayLabel(nextRain.date)}`:'Near-term garden forecast'}</strong></span></div>{nextRain&&<p>{nextRain.rainProbability!==null?`${nextRain.rainProbability}% rain chance`:''}{nextRain.rainAmount>0?`${nextRain.rainProbability!==null?' · ':''}${amount(nextRain.rainAmount)} forecast`:''}. Forecast rain has not been counted as completed watering.</p>}<div className="weather-forecast-strip normalized-forecast-strip">{days.length?days.map(day=><article key={day.date}><small>{dayLabel(day.date)} · {formatGardenDate(`${day.date}T12:00:00`)}</small><strong>{day.temperatureLabel}</strong><em>{day.rainProbability!==null?`${day.rainProbability}% rain`:day.rainAmount>0?`${amount(day.rainAmount)} forecast`:'Rain chance unavailable'}</em></article>):<p>Forecast details are temporarily unavailable.</p>}</div></section>
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>GARDEN IMPACTS</small><strong>All grouped weather guidance</strong></span></div>{impacts.length?<div className="weather-impact-detail-list">{impacts.map(impact=><article key={impact.key}><span><strong>{impact.title}</strong><small>{impact.summary}</small></span><em>{impact.confidence} confidence</em></article>)}</div>:<p>No major garden-weather adjustment is active.</p>}</section>
  <section className="weather-detail-section"><div className="weather-detail-heading"><span><small>LOCAL CORRECTIONS</small><strong>Home weather monitor</strong></span><button onClick={()=>setAdding(value=>!value)}><Droplets/>{adding?'Close':'Add reading'}</button></div>{notice&&<p className="weather-save-notice" role="status">{notice}</p>}{adding&&<CorrectionForm onSave={saveNew} onCancel={()=>setAdding(false)}/>} {editing&&<CorrectionForm initial={editing} onSave={saveEdit} onCancel={()=>setEditing(null)}/>} {!editing&&<div className="weather-correction-list">{corrections.length?corrections.map(row=><article key={row.record_id}><Droplets/><span><strong>{amount(row.precipitation_amount)} recorded</strong><small>{row.source_name||'Home weather monitor'} · {formatGardenDate(row.observed_at)} at {formatGardenTime(row.observed_at)}</small>{row.entry_note&&<em>{row.entry_note}</em>}</span><button onClick={()=>setEditing(row)} aria-label="Edit home weather reading"><Edit3/></button><button onClick={()=>removeCorrection?.(row.record_id)} aria-label="Remove home weather reading"><Trash2/></button></article>):<p>No home weather corrections are saved.</p>}</div>}</section>
  <section className="weather-detail-section weather-data-status"><div className="weather-detail-heading"><span><small>DATA STATUS</small><strong>{weather?.freshness||'Unavailable'} · {weather?.confidence||guidance?.confidence||'Low'} confidence</strong></span></div><p>{source==='live'?'Official observation and forecast':source==='fallback'?'Regional fallback weather':source==='cached'?'Saved weather reading':'Weather connection unavailable'} · {updatedText}</p><small>Personal garden-station connection is not enabled. The app continues using the approved public weather sources and saved local corrections.</small></section>
 </div></details>;
}
