import{classifySpaceExposure,rainCreditForSpace}from'./environmentalIntelligence.js';

export const WEATHER_DECISION_THRESHOLDS=Object.freeze({
 frostWatchF:38,frostF:36,freezeF:32,heatF:88,extremeHeatF:95,windCautionMph:18,windGustMph:25,strongWindGustMph:35,meaningfulRainIn:.25,heavyRainIn:.75,forecastRainProbability:70,forecastRainAmountIn:.2,forecastHeavyRainIn:.5,highHumidityPct:80,recentWateringHours:24,forecastHorizonHours:120
});

const TENDER=new Set(['tomato','bell-pepper','hot-pepper','eggplant','basil','cucumber','zucchini','winter-squash','pumpkin','melon','green-bean','marigold','nasturtium','sweet-alyssum']);
const COLD_TOLERANT=new Set(['kale','spinach','lettuce','radish','peas','cabbage','broccoli','cauliflower','chard','arugula','beet','turnip','bok-choy','carrot','parsley','cilantro','dill','chives']);
const HEAT_SENSITIVE=new Set(['lettuce','spinach','peas','radish','cilantro','broccoli','cauliflower','cabbage','bok-choy']);
const DISEASE_SUSCEPTIBLE=new Set(['tomato','bell-pepper','hot-pepper','cucumber','zucchini','winter-squash','pumpkin','potato','green-bean']);
const TALL_OR_TRELLISED=new Set(['tomato','corn','cucumber','green-bean','peas','sunflower','raspberry']);
const ACTIVE_STAGES=new Set(['Transplanted','Established','Flowering','Fruiting','Harvesting','Seedling','Potted Up','Hardening Off']);
const hash=value=>{let h=2166136261;for(const char of String(value)){h^=char.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
const asDate=value=>{const date=value instanceof Date?value:new Date(value);return Number.isNaN(date.getTime())?null:date};
const iso=value=>asDate(value)?.toISOString()||null;
const dateKey=value=>(iso(value)||new Date().toISOString()).slice(0,10);
const hoursSince=(value,now)=>{const date=asDate(value);return date?Math.max(0,(now-date.getTime())/3600000):Infinity};
const number=value=>Number.isFinite(Number(value))?Number(value):null;
const lower=value=>String(value||'').toLowerCase();
const unique=values=>[...new Set(values.filter(Boolean))];
const confidenceRank={Low:1,Medium:2,High:3};
const minConfidence=(...values)=>Object.entries(confidenceRank).find(([,rank])=>rank===Math.min(...values.filter(Boolean).map(value=>confidenceRank[value]||1)))?.[0]||'Low';
const activePlants=garden=>(garden?.plants||[]).filter(plant=>!plant.deletedAt&&!plant.archived&&ACTIVE_STAGES.has(plant.stage));
const activeSpaces=garden=>(garden?.spaces||[]).filter(space=>!space.deletedAt&&!space.hidden);
const spaceMap=garden=>new Map(activeSpaces(garden).map(space=>[space.id,space]));
const exposureFor=space=>classifySpaceExposure(space||{});
const isIndoor=space=>['indoor','basement','hydro','seed-tray'].includes(lower(space?.type))||exposureFor(space)==='indoor';
const isContainer=space=>['container','potato-grow-bag'].includes(lower(space?.type))||exposureFor(space)==='container-outdoors';
const isGreenhouse=space=>lower(space?.type)==='greenhouse';
const isExplicitlyProtected=space=>Boolean(space?.weatherProtected||space?.frostProtected||space?.heated||/protected|heated|enclosed/.test(lower(space?.protectionStatus||space?.weatherExposure)));
const isNewPlant=plant=>['Seedling','Potted Up','Hardening Off','Transplanted'].includes(plant?.stage)||Boolean(plant?.transplantedAt&&hoursSince(plant.transplantedAt,Date.now())<=168);
const cropId=plant=>plant?.cropId||'';
const rainCredit=(weather,space)=>weather?.rainCreditBySpace?.[space?.id]||rainCreditForSpace(space,weather?.recentRain24h||weather?.recentRain?.amount||0);
const forecastRows=weather=>(weather?.forecasts||[]).filter(row=>{const at=asDate(row.forecast_for);return at&&at.getTime()>=Date.now()-3600000&&at.getTime()<=Date.now()+WEATHER_DECISION_THRESHOLDS.forecastHorizonHours*3600000});
const forecastTemperature=row=>number(row.temperature??row.maximum_temperature??row.minimum_temperature);
const forecastAmount=row=>number(row.precipitation_amount)||0;
const forecastProbability=row=>number(row.precipitation_probability)||0;
const observedSource=weather=>weather?.currentObservation?.source_name||weather?.currentObservation?.source_provider||weather?.provider||'Weather source unavailable';
const observedAt=weather=>weather?.currentObservation?.observed_at||weather?.observedAt||weather?.fetchedAt||null;
const freshness=weather=>weather?.isStale?'Stale':weather?.freshness||(weather&&(weather.currentObservation||weather.forecasts?.length||weather.temperature!==null&&weather.temperature!==undefined||weather.high!==null&&weather.high!==undefined||weather.low!==null&&weather.low!==undefined||Object.keys(weather.signals||{}).length)?'Current':'Unavailable');
const weatherBaseConfidence=weather=>weather?.isStale?'Low':weather?.confidence||'Medium';

function sourceConflict(weather){
 const observations=(weather?.observations||[]).filter(row=>row?.observed_at).slice(0,8),recent=observations.filter(row=>hoursSince(row.observed_at,Date.now())<=2),sources=new Map();
 for(const row of recent){const key=row.source_provider||row.source_name||'unknown';if(!sources.has(key))sources.set(key,row)}
 const rows=[...sources.values()];if(rows.length<2)return false;
 for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=number(rows[i].temperature),b=number(rows[j].temperature),ar=number(rows[i].precipitation_amount)||0,br=number(rows[j].precipitation_amount)||0;if(a!==null&&b!==null&&Math.abs(a-b)>=8)return true;if(Math.abs(ar-br)>=.3)return true}
 return false;
}

function evidence(weather,items=[]){return items.filter(item=>item?.value!==null&&item?.value!==undefined).map(item=>({label:item.label,value:item.value,kind:item.kind||'observed'})).concat([{label:'Source',value:observedSource(weather),kind:weather?.currentObservation?'observed':'forecast'},{label:'Updated',value:observedAt(weather),kind:'metadata'}])}
function affectedNames(ids,rows){const set=new Set(ids);return rows.filter(row=>set.has(row.id)).map(row=>row.name).filter(Boolean)}
function fingerprint(input){return hash(JSON.stringify(input))}
function stableId(actionKey,day,plantIds=[],spaceIds=[]){return`weather-decision-${actionKey}-${day}-${hash(`${plantIds.slice().sort().join(',')}|${spaceIds.slice().sort().join(',')}`)}`}
function makeRecommendation({weather,now,category,actionKey,priority,title,explanation,recommendedAction,plants=[],spaces=[],timing='Today',evidenceItems=[],confidence=null,sourceType='forecast',destination='chores',validUntil=null,metadata={}}){
 const plantIds=unique(plants.map(row=>typeof row==='string'?row:row?.id)),spaceIds=unique(spaces.map(row=>typeof row==='string'?row:row?.id)),day=dateKey(now),baseConfidence=confidence||weatherBaseConfidence(weather),conflict=sourceConflict(weather),effectiveConfidence=conflict||freshness(weather)==='Stale'?minConfidence(baseConfidence,'Low'):baseConfidence,conditionFingerprint=fingerprint({category,actionKey,plantIds,spaceIds,title,weather:{temperature:weather?.temperature,high:weather?.high,low:weather?.low,wind:weather?.wind,windGust:weather?.windGust,recentRain24h:weather?.recentRain24h,rainChance:weather?.rainChance,freshness:freshness(weather)},metadata});
 return{recommendationId:stableId(actionKey,day,plantIds,spaceIds),category,actionKey,priority,title,plainLanguageExplanation:explanation,recommendedAction,affectedPlants:plantIds,affectedGrowingSpaces:spaceIds,timing,weatherEvidence:evidence(weather,evidenceItems),confidence:effectiveConfidence,source:observedSource(weather),sourceType,dataFreshness:freshness(weather),lastUpdated:observedAt(weather),conditionFingerprint,validUntil:validUntil||new Date(now+18*3600000).toISOString(),destination,metadata:{...metadata,sourceConflict:conflict}};
}
function isSuppressed(recommendation,history=[],now=Date.now()){
 return history.some(row=>row?.recommendationId===recommendation.recommendationId&&row?.conditionFingerprint===recommendation.conditionFingerprint&&['dismissed','completed','not-useful','watered'].includes(row.status)&&(!row.validUntil||new Date(row.validUntil).getTime()>now));
}
function dedupe(recommendations){const map=new Map();for(const row of recommendations){const current=map.get(row.recommendationId);if(!current||row.priority>current.priority)map.set(row.recommendationId,row)}return[...map.values()].sort((a,b)=>b.priority-a.priority||a.title.localeCompare(b.title))}

export function wateringDecisionForPlant({plant,space,weather,now=Date.now()}={}){
 const thresholds=WEATHER_DECISION_THRESHOLDS,credit=rainCredit(weather,space),observedRain=credit.amount||0,rows=forecastRows(weather).filter(row=>{const at=asDate(row.forecast_for);return at&&at.getTime()<=now+24*3600000}),maxProbability=Math.max(0,...rows.map(forecastProbability)),expectedAmount=rows.reduce((sum,row)=>sum+forecastAmount(row),0),fresh=freshness(weather),recentlyWatered=hoursSince(plant?.lastWatered,now)<=thresholds.recentWateringHours,dry=lower(plant?.moisture)==='dry',container=isContainer(space),protectedFromRain=credit.factor===0,hot=number(weather?.high)>=thresholds.heatF,windy=Math.max(number(weather?.wind)||0,number(weather?.windGust)||0)>=thresholds.windCautionMph;
 if(recentlyWatered)return{actionKey:'no-watering',status:'No watering currently needed',priority:25,explanation:`${plant?.name||'This plant'} was watered recently.`,confidence:fresh==='Stale'?'Low':'High',observedRain,expectedAmount,maxProbability};
 if(fresh==='Stale'||fresh==='Unavailable')return{actionKey:'check-soil',status:'Check soil before watering',priority:66,explanation:'Weather data is stale or unavailable, so a manual root-zone check is safer than a definite watering instruction.',confidence:'Low',observedRain,expectedAmount,maxProbability};
 if(dry&&observedRain<thresholds.meaningfulRainIn&&!(maxProbability>=thresholds.forecastRainProbability&&expectedAmount>=thresholds.forecastRainAmountIn))return{actionKey:'water-now',status:'Water now',priority:92,explanation:'The saved moisture status is dry and no meaningful observed rain reached this space.',confidence:'High',observedRain,expectedAmount,maxProbability};
 if(protectedFromRain&&number(weather?.recentRain24h)>=thresholds.meaningfulRainIn)return{actionKey:'check-soil',status:'Protected space may still need water',priority:78,explanation:'Outdoor rain was recorded, but this protected space received no automatic rain credit.',confidence:'High',observedRain,expectedAmount,maxProbability};
 if(observedRain>=thresholds.meaningfulRainIn&&!container)return{actionKey:'no-watering',status:'Recent rainfall likely covered this space',priority:30,explanation:`About ${observedRain.toFixed(2)} in of effective observed rain was credited to this space.`,confidence:weatherBaseConfidence(weather),observedRain,expectedAmount,maxProbability};
 if(observedRain>=thresholds.meaningfulRainIn&&container)return{actionKey:'check-soil',status:'Check container soil',priority:68,explanation:'The container received rain credit, but containers can shed rain unevenly and dry faster than beds.',confidence:'Medium',observedRain,expectedAmount,maxProbability};
 if(maxProbability>=thresholds.forecastRainProbability&&expectedAmount>=thresholds.forecastRainAmountIn)return{actionKey:'delay-watering',status:'Delay watering and reassess',priority:64,explanation:`Forecast rain is reasonably likely and totals about ${expectedAmount.toFixed(2)} in, but it has not happened yet.`,confidence:'Medium',observedRain,expectedAmount,maxProbability};
 if(maxProbability>=thresholds.forecastRainProbability&&expectedAmount<thresholds.forecastRainAmountIn)return{actionKey:'check-soil',status:'Check soil and recheck the forecast',priority:62,explanation:'Rain probability is elevated, but the forecast amount is small or uncertain, so it should not cancel watering by itself.',confidence:'Low',observedRain,expectedAmount,maxProbability};
 if(container&&(hot||windy))return{actionKey:'check-soil',status:'Prioritize container moisture checks',priority:82,explanation:'Heat or wind can dry containers faster than in-ground beds.',confidence:weatherBaseConfidence(weather),observedRain,expectedAmount,maxProbability};
 return{actionKey:'check-soil',status:'Check soil before watering',priority:52,explanation:'No weather evidence supports a definite water-or-skip decision. Check the root zone first.',confidence:'Medium',observedRain,expectedAmount,maxProbability};
}

function wateringRecommendations({weather,garden,now}){
 const spaces=spaceMap(garden),plants=activePlants(garden),groups=new Map();
 for(const plant of plants){const space=spaces.get(plant.spaceId)||null,decision=wateringDecisionForPlant({plant,space,weather,now}),key=`${decision.actionKey}|${space?.id||'unassigned'}`;if(!groups.has(key))groups.set(key,{decision,plants:[],spaces:[]});const group=groups.get(key);group.plants.push(plant);if(space)group.spaces.push(space)}
 const recommendations=[];
 for(const {decision,plants:rows,spaces:spaceRows} of groups.values()){
  if(decision.actionKey==='no-watering'&&decision.priority<35)continue;
  recommendations.push(makeRecommendation({weather,now,category:'watering',actionKey:decision.actionKey,priority:decision.priority,title:decision.status,explanation:decision.explanation,recommendedAction:decision.actionKey==='water-now'?'Water the affected plants during the next cooler practical window.':decision.actionKey==='delay-watering'?'Wait for the forecast period, then reassess soil moisture.':'Check the root zone before deciding whether to water.',plants:rows,spaces:spaceRows,timing:decision.actionKey==='delay-watering'?'After the forecast rain window':'Today',confidence:decision.confidence,sourceType:decision.observedRain>0?'observed':'forecast',evidenceItems:[{label:'Effective rain',value:`${decision.observedRain.toFixed(2)} in`,kind:'observed'},{label:'Forecast rain',value:`${decision.expectedAmount.toFixed(2)} in at ${Math.round(decision.maxProbability)}%`,kind:'forecast'}],destination:'chores'}));
 }
 return recommendations;
}

function frostRecommendations({weather,garden,now}){
 const spaces=spaceMap(garden),plants=activePlants(garden),current=number(weather?.temperature),rows=forecastRows(weather),forecastLow=Math.min(number(weather?.low)??Infinity,...rows.map(row=>number(row.minimum_temperature??row.temperature)).filter(value=>value!==null)),observedFreeze=current!==null&&current<=WEATHER_DECISION_THRESHOLDS.freezeF,riskLow=Math.min(current??Infinity,forecastLow),forecastOnly=!observedFreeze,atRisk=[],monitor=[],safe=[];
 for(const plant of plants){const space=spaces.get(plant.spaceId);if(isIndoor(space))continue;const tender=TENDER.has(cropId(plant))||isNewPlant(plant),cold=COLD_TOLERANT.has(cropId(plant))&&!isNewPlant(plant),protectedSpace=isExplicitlyProtected(space);if(cold)safe.push(plant);else if(tender&&!protectedSpace)atRisk.push(plant);else if(tender||isGreenhouse(space))monitor.push(plant)}
 if(!Number.isFinite(riskLow)||riskLow>WEATHER_DECISION_THRESHOLDS.frostWatchF)return[];
 const recommendations=[];
 if(atRisk.length){const freeze=riskLow<=WEATHER_DECISION_THRESHOLDS.freezeF,near=riskLow>WEATHER_DECISION_THRESHOLDS.frostF;recommendations.push(makeRecommendation({weather,now,category:'frost',actionKey:freeze?'protect-freeze':near?'recheck-frost':'protect-frost',priority:freeze?98:near?76:92,title:freeze?'Protect tender plants from a freeze':near?'Frost threshold is close':'Cover tender plants tonight',explanation:near?`The low is near ${Math.round(riskLow)}°. The forecast is close enough to watch, but not certain enough for an alarm.`:`Tender or newly established plants are exposed to a low near ${Math.round(riskLow)}°.`,recommendedAction:near?'Check the forecast again this evening.':'Cover exposed tender plants or move portable containers into protection.',plants:atRisk,spaces:unique(atRisk.map(plant=>spaces.get(plant.spaceId))),timing:observedFreeze?'Now, if it is safe':near?'Recheck this evening':'Before sunset',confidence:forecastOnly?minConfidence(weatherBaseConfidence(weather),'Medium'):weatherBaseConfidence(weather),sourceType:forecastOnly?'forecast':'observed',evidenceItems:[{label:forecastOnly?'Forecast low':'Observed temperature',value:`${Math.round(riskLow)}°F`,kind:forecastOnly?'forecast':'observed'}],destination:'chores'}))}
 if(!atRisk.length&&safe.length)recommendations.push(makeRecommendation({weather,now,category:'frost',actionKey:'no-frost-action',priority:24,title:'No exposed frost-sensitive plants need action',explanation:'The recorded outdoor plants are cold-tolerant, established, protected, or indoors.',recommendedAction:'Routine care can continue. Recheck only if the forecast worsens.',plants:safe,spaces:unique(safe.map(plant=>spaces.get(plant.spaceId))),timing:'Tonight',confidence:'Medium',sourceType:'forecast',evidenceItems:[{label:'Forecast low',value:`${Math.round(riskLow)}°F`,kind:'forecast'}],destination:'garden'}))
 if(monitor.length&&riskLow<=WEATHER_DECISION_THRESHOLDS.freezeF)recommendations.push(makeRecommendation({weather,now,category:'frost',actionKey:'monitor-protected-frost',priority:70,title:'Check protected spaces before the coldest period',explanation:'A greenhouse or recorded protected space may reduce exposure, but protection is not the same as confirmed heat.',recommendedAction:'Confirm covers, doors, and any recorded heat source before the low arrives.',plants:monitor,spaces:unique(monitor.map(plant=>spaces.get(plant.spaceId))),timing:'Before the overnight low',confidence:'Medium',sourceType:'forecast',evidenceItems:[{label:'Forecast low',value:`${Math.round(riskLow)}°F`,kind:'forecast'}],destination:'garden'}))
 return recommendations;
}

function heatRecommendations({weather,garden,now}){
 const high=Math.max(number(weather?.high)??-Infinity,...forecastRows(weather).map(row=>number(row.maximum_temperature??row.temperature)).filter(value=>value!==null));if(!Number.isFinite(high)||high<WEATHER_DECISION_THRESHOLDS.heatF)return[];const spaces=spaceMap(garden),plants=activePlants(garden),vulnerable=plants.filter(plant=>{const space=spaces.get(plant.spaceId);return!isIndoor(space)&&(isContainer(space)||isNewPlant(plant)||HEAT_SENSITIVE.has(cropId(plant))||high>=WEATHER_DECISION_THRESHOLDS.extremeHeatF)}),greenhouses=activeSpaces(garden).filter(isGreenhouse);if(!vulnerable.length&&!greenhouses.length)return[];const extreme=high>=WEATHER_DECISION_THRESHOLDS.extremeHeatF,recommendations=[];
 if(vulnerable.length)recommendations.push(makeRecommendation({weather,now,category:'heat',actionKey:extreme?'protect-extreme-heat':'check-heat-stress',priority:extreme?94:80,title:extreme?'Protect vulnerable plants from extreme heat':'Check containers and young plants early',explanation:`A high near ${Math.round(high)}° can dry containers quickly and stress seedlings, recent transplants, and cool-season crops.`,recommendedAction:'Check moisture during a cooler part of the day, provide temporary shade where appropriate, and avoid unnecessary midday handling.',plants:vulnerable,spaces:unique(vulnerable.map(plant=>spaces.get(plant.spaceId))),timing:'Early today and again before peak heat',confidence:'Medium',sourceType:'forecast',evidenceItems:[{label:'Forecast high',value:`${Math.round(high)}°F`,kind:'forecast'}],destination:'chores'}));
 if(greenhouses.length)recommendations.push(makeRecommendation({weather,now,category:'heat',actionKey:'ventilate-greenhouse',priority:high>=90?92:78,title:'Check greenhouse ventilation',explanation:'Outdoor warmth can make enclosed growing spaces much hotter than the outdoor reading.',recommendedAction:'Check the recorded greenhouse temperature and ventilation; do not assume the outdoor temperature equals the inside temperature.',spaces:greenhouses,timing:'Before midday heat',confidence:'Medium',sourceType:'forecast',evidenceItems:[{label:'Outdoor forecast high',value:`${Math.round(high)}°F`,kind:'forecast'}],destination:'indoor'}));return recommendations;
}

function windRecommendations({weather,garden,now}){
 const gust=Math.max(number(weather?.windGust)||0,...forecastRows(weather).map(row=>number(row.wind_gust??row.wind_speed)||0)),sustained=Math.max(number(weather?.wind)||0,...forecastRows(weather).map(row=>number(row.wind_speed)||0));if(gust<WEATHER_DECISION_THRESHOLDS.windGustMph&&sustained<WEATHER_DECISION_THRESHOLDS.windCautionMph)return[];const spaces=spaceMap(garden),plants=activePlants(garden),affected=plants.filter(plant=>{const space=spaces.get(plant.spaceId);return!isIndoor(space)&&!isExplicitlyProtected(space)&&(isNewPlant(plant)||isContainer(space)||TALL_OR_TRELLISED.has(cropId(plant)))});if(!affected.length)return[];const strong=gust>=WEATHER_DECISION_THRESHOLDS.strongWindGustMph;return[makeRecommendation({weather,now,category:'wind',actionKey:strong?'secure-strong-wind':'secure-wind',priority:strong?93:79,title:strong?'Secure vulnerable plants before strong gusts':'Check supports and exposed seedlings',explanation:`Gusts near ${Math.round(gust)} mph may shift containers, damage seedlings, or strain tall and trellised crops.`,recommendedAction:'Secure lightweight containers, inspect stakes and trellises, and delay transplanting until winds ease.',plants:affected,spaces:unique(affected.map(plant=>spaces.get(plant.spaceId))),timing:'Before the windiest period',confidence:'Medium',sourceType:'forecast',evidenceItems:[{label:'Peak gust',value:`${Math.round(gust)} mph`,kind:'forecast'},{label:'Sustained wind',value:`${Math.round(sustained)} mph`,kind:'forecast'}],destination:'chores'})]
}

function rainAndStormRecommendations({weather,garden,now}){
 const rows=forecastRows(weather),forecastTotal=rows.slice(0,48).reduce((sum,row)=>sum+forecastAmount(row),0),probability=Math.max(0,...rows.slice(0,48).map(forecastProbability)),observed=number(weather?.recentRain24h)||0,official=(weather?.activeAlerts||[]).some(alert=>/severe|thunderstorm|tornado|storm/i.test(`${alert.event||''} ${alert.headline||''}`)),storming=Boolean(weather?.isStormingNow),spaces=activeSpaces(garden).filter(space=>!isIndoor(space)),plants=activePlants(garden).filter(plant=>spaces.some(space=>space.id===plant.spaceId)),recommendations=[];
 if(storming||official)recommendations.push(makeRecommendation({weather,now,category:'storm',actionKey:'prepare-storm',priority:storming?99:92,title:storming?'Storm conditions are affecting the garden':'Prepare the garden for the expected storm',explanation:'Garden guidance supplements official alerts; it does not replace emergency weather information.',recommendedAction:'Secure loose materials and greenhouse components, delay watering or spraying, and inspect plants after conditions are safe.',plants,spaces,timing:storming?'Now, only if it is safe':'Before the storm period',confidence:storming?'High':'Medium',sourceType:storming?'observed':'forecast',evidenceItems:[{label:'Official alert',value:official?'Active':'None recorded',kind:'observed'}],destination:'chores'}));
 const heavyObserved=observed>=WEATHER_DECISION_THRESHOLDS.heavyRainIn,heavyForecast=probability>=WEATHER_DECISION_THRESHOLDS.forecastRainProbability&&forecastTotal>=WEATHER_DECISION_THRESHOLDS.forecastHeavyRainIn;if(heavyObserved||heavyForecast)recommendations.push(makeRecommendation({weather,now,category:'heavy-rain',actionKey:heavyObserved?'inspect-after-heavy-rain':'prepare-heavy-rain',priority:heavyObserved?87:82,title:heavyObserved?'Inspect drainage after heavy rain':'Heavy rain may affect garden work',explanation:heavyObserved?`${observed.toFixed(2)} in of observed rain may leave saturated soil or waterlogged containers.`:`About ${forecastAmount.toFixed(2)} in of rain is forecast at up to ${Math.round(probability)}% probability. It has not happened yet.`,recommendedAction:heavyObserved?'Check drainage and erosion, avoid compacting saturated soil, and monitor containers for waterlogging.':'Delay planting or digging during the wettest period and check drainage preparations.',plants,spaces,timing:heavyObserved?'After rain stops and conditions are safe':'Before the forecast rain period',confidence:heavyObserved?weatherBaseConfidence(weather):'Medium',sourceType:heavyObserved?'observed':'forecast',evidenceItems:[{label:heavyObserved?'Observed rain':'Forecast rain',value:`${(heavyObserved?observed:forecastTotal).toFixed(2)} in`,kind:heavyObserved?'observed':'forecast'},{label:'Probability',value:`${Math.round(probability)}%`,kind:'forecast'}],destination:'chores'}));return recommendations;
}

function diseaseRecommendations({weather,garden,now}){
 const humidity=number(weather?.humidity),recentRain=number(weather?.recentRain24h)||0,wetForecasts=forecastRows(weather).filter(row=>forecastProbability(row)>=60&&forecastAmount(row)>0).length,warm=number(weather?.temperature)>=60||number(weather?.high)>=70,humid=humidity!==null&&humidity>=WEATHER_DECISION_THRESHOLDS.highHumidityPct,repeatedWet=recentRain>=WEATHER_DECISION_THRESHOLDS.meaningfulRainIn||wetForecasts>=2;if(!(humid&&warm&&repeatedWet))return[];const spaces=spaceMap(garden),plants=activePlants(garden),susceptible=plants.filter(plant=>DISEASE_SUSCEPTIBLE.has(cropId(plant))||isGreenhouse(spaces.get(plant.spaceId)));if(!susceptible.length)return[];return[makeRecommendation({weather,now,category:'disease-risk',actionKey:'inspect-damp-risk',priority:68,title:'Conditions may favor fungal problems',explanation:'Warm humidity plus repeated wet conditions can increase risk. This is a risk signal, not a diagnosis.',recommendedAction:'Check susceptible leaves for early signs, avoid unnecessary overhead watering, and increase ventilation where practical.',plants:susceptible,spaces:unique(susceptible.map(plant=>spaces.get(plant.spaceId))),timing:'During routine inspection today',confidence:'Medium',sourceType:recentRain>0?'observed':'forecast',evidenceItems:[{label:'Humidity',value:humidity===null?'Unavailable':`${Math.round(humidity)}%`,kind:'observed'},{label:'Recent observed rain',value:`${recentRain.toFixed(2)} in`,kind:'observed'},{label:'Wet forecast periods',value:wetForecasts,kind:'forecast'}],destination:'memory'})]
}

function upcomingEvents(weather,now){
 const rows=forecastRows(weather).filter(row=>{const at=asDate(row.forecast_for);return at&&at.getTime()>now+6*3600000}),events=[];
 for(const row of rows){const at=asDate(row.forecast_for),low=number(row.minimum_temperature??row.temperature),high=number(row.maximum_temperature??row.temperature),gust=number(row.wind_gust??row.wind_speed)||0,amount=forecastAmount(row),probability=forecastProbability(row);let category='',title='',priority=0;if(low!==null&&low<=WEATHER_DECISION_THRESHOLDS.frostF){category='frost';title=`Frost preparation may be needed ${dateKey(at)}`;priority=90}else if(high!==null&&high>=WEATHER_DECISION_THRESHOLDS.extremeHeatF){category='heat';title=`A hot stretch may begin ${dateKey(at)}`;priority=80}else if(gust>=WEATHER_DECISION_THRESHOLDS.strongWindGustMph){category='wind';title=`Strong winds are expected ${dateKey(at)}`;priority=78}else if(probability>=WEATHER_DECISION_THRESHOLDS.forecastRainProbability&&amount>=WEATHER_DECISION_THRESHOLDS.forecastHeavyRainIn){category='heavy-rain';title=`Heavy rain may affect plans ${dateKey(at)}`;priority=76}if(!category)continue;const existing=events.find(event=>event.category===category&&Math.abs(new Date(event.startsAt)-at)<24*3600000);if(existing){existing.endsAt=iso(at);existing.priority=Math.max(existing.priority,priority)}else events.push({eventId:`weather-event-${category}-${dateKey(at)}`,category,title,priority,startsAt:iso(at),endsAt:iso(at),source:row.source_name||row.source_provider||observedSource(weather),confidence:freshness(weather)==='Stale'?'Low':'Medium'})}
 return events.sort((a,b)=>b.priority-a.priority||new Date(a.startsAt)-new Date(b.startsAt)).slice(0,4);
}

export function assessPlantingWeatherReadiness({method='Direct Sow',cropId='',seasonallySuitable=true,weather,now=Date.now()}={}){
 if(!seasonallySuitable)return{status:'Seasonally unsuitable',level:'not-seasonal',explanation:'Short-term weather does not override the seasonal recommendation.',confidence:'High'};
 if(!weather||freshness(weather)==='Unavailable')return{status:'Recheck forecast soon',level:'recheck',explanation:'Weather data is unavailable, so short-term readiness cannot be confirmed.',confidence:'Low'};
 if(freshness(weather)==='Stale')return{status:'Recheck forecast soon',level:'recheck',explanation:'The seasonal window may still be open, but weather data is stale.',confidence:'Low'};
 const rows=forecastRows(weather),low=Math.min(number(weather?.low)??Infinity,...rows.map(row=>number(row.minimum_temperature??row.temperature)).filter(value=>value!==null)),high=Math.max(number(weather?.high)??-Infinity,...rows.map(row=>number(row.maximum_temperature??row.temperature)).filter(value=>value!==null)),gust=Math.max(number(weather?.windGust)||0,...rows.map(row=>number(row.wind_gust??row.wind_speed)||0)),amount=rows.slice(0,24).reduce((sum,row)=>sum+forecastAmount(row),0),probability=Math.max(0,...rows.slice(0,24).map(forecastProbability)),tender=TENDER.has(cropId),transplant=/transplant|plant/i.test(method)&&! /direct sow/i.test(method);
 if((tender&&low<=WEATHER_DECISION_THRESHOLDS.frostF)||low<=WEATHER_DECISION_THRESHOLDS.freezeF)return{status:'Delay',level:'delay',explanation:'The seasonal window may be open, but frost or freeze risk makes this a poor short-term planting window.',confidence:'Medium'};
 if(gust>=WEATHER_DECISION_THRESHOLDS.windGustMph&&transplant)return{status:'Delay',level:'delay',explanation:'The seasonal window is open, but strong wind makes transplanting unnecessarily stressful.',confidence:'Medium'};
 if(high>=WEATHER_DECISION_THRESHOLDS.extremeHeatF&&transplant)return{status:'Delay',level:'delay',explanation:'The crop may be seasonally appropriate, but extreme heat makes transplanting risky today.',confidence:'Medium'};
 if(probability>=WEATHER_DECISION_THRESHOLDS.forecastRainProbability&&amount>=WEATHER_DECISION_THRESHOLDS.forecastHeavyRainIn)return{status:/direct sow/i.test(method)?'Delay':'Acceptable with caution',level:/direct sow/i.test(method)?'delay':'caution',explanation:/direct sow/i.test(method)?'Direct sowing is better after the heavy-rain period to reduce washout and compaction.':'Plant only if drainage is good and the heavy-rain period will not waterlog the root zone.',confidence:'Medium'};
 if(low<=WEATHER_DECISION_THRESHOLDS.frostWatchF&&tender)return{status:'Recheck forecast soon',level:'recheck',explanation:'The forecast is close to the frost threshold. Keep the seasonal recommendation, but recheck before planting.',confidence:'Low'};
 if(high>=WEATHER_DECISION_THRESHOLDS.heatF||gust>=WEATHER_DECISION_THRESHOLDS.windCautionMph)return{status:'Acceptable with caution',level:'caution',explanation:'The seasonal window is open, but use a cooler or calmer period and watch moisture closely.',confidence:'Medium'};
 return{status:'Good conditions',level:'good',explanation:'No short-term frost, extreme heat, strong wind, or heavy-rain conflict is present.',confidence:'Medium'};
}

export function buildWeatherDecisionEngine({weather=null,garden={},now=Date.now(),recommendationHistory=null}={}){
 const history=recommendationHistory||garden.weatherRecommendationHistory||[],hasWeather=Boolean(weather&&(weather.currentObservation||weather.forecasts?.length||weather.temperature!==null&&weather.temperature!==undefined||weather.high!==null&&weather.high!==undefined||weather.low!==null&&weather.low!==undefined||Object.keys(weather.signals||{}).length)),raw=[];
 if(!hasWeather){raw.push(makeRecommendation({weather:weather||{},now,category:'unavailable',actionKey:'manual-weather-check',priority:55,title:'Garden weather is temporarily unavailable',explanation:'Plants, records, and normal garden tools remain available. New high-confidence weather guidance is paused.',recommendedAction:'Use manual soil and plant checks, then retry the weather refresh.',timing:'Today',confidence:'Low',sourceType:'missing',destination:'today',validUntil:new Date(now+2*3600000).toISOString()}))}else{
  raw.push(...wateringRecommendations({weather,garden,now}),...frostRecommendations({weather,garden,now}),...heatRecommendations({weather,garden,now}),...windRecommendations({weather,garden,now}),...rainAndStormRecommendations({weather,garden,now}),...diseaseRecommendations({weather,garden,now}));
 }
 let recommendations=dedupe(raw).filter(row=>!isSuppressed(row,history,now));const actionable=recommendations.filter(row=>row.priority>=50&&row.actionKey!=='no-frost-action');if(!actionable.length&&hasWeather)recommendations=[makeRecommendation({weather,now,category:'calm',actionKey:'calm-weather',priority:20,title:'No weather-related garden action is needed today',explanation:'Conditions look steady enough for routine care to continue as planned.',recommendedAction:'Continue normal plant-specific care.',timing:'Today',confidence:weatherBaseConfidence(weather),sourceType:weather?.currentObservation?'observed':'forecast',destination:'today',validUntil:new Date(now+8*3600000).toISOString()})];
 const plants=activePlants(garden),spaces=activeSpaces(garden),brief=recommendations.filter(row=>row.priority>=50||row.category==='calm'||row.category==='unavailable').slice(0,3).map(row=>({...row,affectedPlantNames:affectedNames(row.affectedPlants,plants),affectedSpaceNames:affectedNames(row.affectedGrowingSpaces,spaces)}));
 return{schemaVersion:1,generatedAt:new Date(now).toISOString(),recommendations,brief,upcomingEvents:hasWeather?upcomingEvents(weather,now):[],byPlant:Object.fromEntries(plants.map(plant=>[plant.id,recommendations.filter(row=>row.affectedPlants.includes(plant.id))])),bySpace:Object.fromEntries(spaces.map(space=>[space.id,recommendations.filter(row=>row.affectedGrowingSpaces.includes(space.id))])),source:observedSource(weather||{}),freshness:freshness(weather||{}),confidence:sourceConflict(weather||{})?'Low':weatherBaseConfidence(weather||{})};
}

export function createWeatherRecommendationDecision(recommendation,status='dismissed',actor='System',now=new Date()){
 return{id:`weather-recommendation-history-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,recommendationId:recommendation.recommendationId,conditionFingerprint:recommendation.conditionFingerprint,status,category:recommendation.category,actionKey:recommendation.actionKey,affectedPlants:recommendation.affectedPlants||[],affectedGrowingSpaces:recommendation.affectedGrowingSpaces||[],weatherEvidence:recommendation.weatherEvidence||[],source:recommendation.source||'',dataFreshness:recommendation.dataFreshness||'',confidence:recommendation.confidence||'Low',actor,at:new Date(now).toISOString(),validUntil:recommendation.validUntil||new Date(new Date(now).getTime()+18*3600000).toISOString(),deletedAt:null};
}
