import React from'react';
import{AlertTriangle,ArrowLeft,Bell,Check,CheckCircle2,ChevronDown,ChevronRight,Cloud,CloudRain,Droplets,Leaf,Megaphone,Moon,RefreshCw,Snowflake,Sun}from'lucide-react';
import{formatDateTime}from'./data.js';
import{formatGardenTime}from'./dateFormat.js';
import{buildGardenIntelligenceEngine}from'./gardenIntelligenceEngine.js';
import{WisconsinLandscape}from'./art.jsx';
import{buildTaskBoard}from'./taskBoard.js';
import{WeatherDetails}from'./WeatherDetails.jsx';
import{formatRainAmount,groupWeatherImpacts,hasUsableWeather,roundWeatherValue}from'./weatherPresentation.js';

function WeatherIcon({weather,size=34}){const c=weather?.weatherCode??2;if([71,73,75,77,85,86].includes(c))return <Snowflake size={size}/>;if([51,53,55,61,63,65,66,67,80,81,82,95,96,99].includes(c))return <CloudRain size={size}/>;if([3,45,48].includes(c))return <Cloud size={size}/>;if(!weather?.isDay)return <Moon size={size}/>;if(c===0)return <Sun size={size}/>;return <CloudRain size={size}/>}
const weatherTime=value=>value?formatGardenTime(value):'time unavailable';

function ImpactIcon({impact}){if(impact.key==='watering')return <Droplets/>;if(impact.key==='frost-cold')return <Snowflake/>;if(impact.key==='heat-drying')return <Sun/>;if(impact.key==='storms-wind')return <Cloud/>;if(impact.key==='calm')return <CheckCircle2/>;return <AlertTriangle/>}

function WeatherLine({weather,loading,error,refresh,source,stale,savedAt,guidance,onOpenWeather}){
 const groups=groupWeatherImpacts(guidance?.recommendations||[],3),primary=groups[0],sourceLabel=weather?.provider||'Weather source unavailable',freshness=source==='live'&&!stale?`${sourceLabel} - updated ${weatherTime(savedAt||weather?.fetchedAt)}`:source==='fallback'?`${sourceLabel} - fallback - updated ${weatherTime(savedAt||weather?.fetchedAt)}`:`Saved weather - updated ${weatherTime(savedAt||weather?.fetchedAt)}`,temperature=roundWeatherValue(weather?.temperature,{suffix:' degrees'}),high=roundWeatherValue(weather?.high,{suffix:' degrees'}),low=roundWeatherValue(weather?.low,{suffix:' degrees'}),recentRain=Number(weather?.recentRain24h||0),usableWeather=hasUsableWeather(weather),calm=!primary||primary.key==='calm',headline=usableWeather?`${temperature||'Temperature unavailable'} ${weather.condition||'Condition unavailable'}`:loading?'Updating Green Bay weather':'Garden weather temporarily unavailable',subline=usableWeather?error||[high&&`High ${high}`,low&&`Low ${low}`].filter(Boolean).join(' - ')||'High and low unavailable':error||'Garden records and normal tools remain available.';
 return <section className={`compact-weather-line phase-45-current-weather ${stale&&usableWeather?'weather-is-stale':''}`}><div className="compact-weather-reading"><WeatherIcon weather={weather}/><span><strong>{headline}</strong><small>{subline}</small><em className="weather-freshness">{freshness}</em></span></div><button className="weather-refresh-button" onClick={refresh} aria-label="Refresh official weather"><RefreshCw/></button>{recentRain>0&&<div className="weather-rain-hold"><Droplets/><span><strong>{formatRainAmount(recentRain)} recorded recently</strong><small>Exposed spaces receive rain credit; protected spaces stay separate.</small></span></div>}{stale&&usableWeather&&!loading&&<div className="weather-stale-warning" role="status"><AlertTriangle/><span><strong>Weather may be outdated</strong><small>Use a soil check before making a definite watering decision.</small></span></div>}{usableWeather&&!loading&&<div className={`compact-weather-message ${calm?'is-calm':''}`}><Check/><span><strong>{calm?'Conditions look steady':primary.title}</strong><small>{calm?'No weather actions today.':primary.explanation||'Open Weather Impact for the garden action list.'}</small></span></div>}<button className="weather-rain-record" onClick={onOpenWeather}><Droplets/>View Weather Impact <ChevronRight/></button></section>;
}

function WhatMattersToday({board,activeTasks,seedIntelligence,navigate,onTask}){
 const announcement=activeTasks.find(task=>task.kind==='seasonalGuide')||activeTasks.find(task=>task.kind==='navigate')||null,seedAction=seedIntelligence.queues.today[0]||seedIntelligence.queues.week[0],visibleTasks=activeTasks.filter(task=>task!==announcement).slice(0,2),rows=visibleTasks.map(task=>({id:task.id,kicker:task.taskType||'CHORE',title:task.title,detail:task.subtitle||task.reason||'Due now',onClick:()=>onTask(task)}));
 if(seedAction&&!rows.some(row=>/seed|plant/i.test(`${row.title} ${row.detail}`)))rows.push({id:`seed-${seedAction.packetId}`,kicker:seedAction.status||'SEED WINDOW',title:seedAction.action,detail:seedAction.sourcePacket.name,onClick:()=>navigate('plan-plant')});
 const count=board.counts.needsAttention,hasRows=rows.length>0||announcement;
 return <section className="what-matters-today" aria-labelledby="what-matters-today-title"><div className="what-matters-heading"><span><small>WHAT MATTERS TODAY</small><strong id="what-matters-today-title">{count?`${count} item${count===1?'':'s'} need attention`:'All caught up for today'}</strong></span>{(board.counts.urgent>0||board.counts.overdue>0)&&<em>{[board.counts.urgent>0&&`${board.counts.urgent} urgent`,board.counts.overdue>0&&`${board.counts.overdue} overdue`].filter(Boolean).join(' - ')}</em>}</div>{hasRows?<div className="what-matters-list">{rows.slice(0,3).map(row=><button key={row.id} onClick={row.onClick}><span><small>{row.kicker}</small><strong>{row.title}</strong><em>{row.detail}</em></span><ChevronRight/></button>)}</div>:<p className="what-matters-empty">No urgent garden work is due right now.</p>}{announcement&&<button className="garden-announcement compact-announcement" onClick={()=>onTask(announcement)}><span className="announcement-icon"><Megaphone/></span><span><small>GARDEN ANNOUNCEMENT</small><strong>{announcement.title}</strong><em>{announcement.subtitle}</em></span><ChevronRight/></button>}<button className="home-primary-route" onClick={()=>navigate('chores')}>View all garden tasks <ChevronRight/></button></section>;
}

export function TodayWorkspace({profile,garden,tasks,dailyDone,noticeOpen,setNoticeOpen,weatherState,weatherAlert,weatherGuidance,activity,navigate,onTask,tomorrowTasks=[]}){
 const board=buildTaskBoard({tasks,completions:dailyDone}),active=board.needsAttention,last=(activity||[]).slice(0,1),seedIntelligence=buildGardenIntelligenceEngine({garden,weather:weatherState.weather,date:new Date()});
 return <main className="screen today-screen"><section className="today-hero compact-home-hero"><button className="round-control hero-bell" onClick={()=>setNoticeOpen(value=>!value)} aria-label="Open garden notifications"><Bell/>{active.length>0&&<span className="notification-count">{active.length}</span>}</button>{noticeOpen&&<div className="notification-popover actionable-briefing"><strong>Garden notifications</strong><span>{active.length?`${active.length} unfinished action${active.length===1?'':'s'} due now.`:'No unread garden actions right now.'}</span>{active.slice(0,3).map(task=><button key={task.id} onClick={()=>onTask(task)}>{task.title}<ChevronRight/></button>)}<button onClick={()=>navigate('chores')}>Open Chore Board <ChevronRight/></button></div>}<div className="hero-title-wrap compact-hero-title"><Leaf/><div><h1>{profile.gardenerName||'Brooke'}'s Garden</h1><p>The Runyan Garden - Green Bay</p></div></div><WisconsinLandscape/></section><section className="today-body compact-today-body screen-pad"><WeatherLine {...weatherState} alert={weatherAlert} guidance={weatherGuidance} onOpenWeather={()=>navigate('weather')}/><WhatMattersToday board={board} activeTasks={active} seedIntelligence={seedIntelligence} navigate={navigate} onTask={onTask}/>{last.length>0&&<details className="compact-handoff collapsible-handoff"><summary><span><small>LATEST HANDOFF</small><strong>What already happened</strong></span><ChevronDown/></summary>{last.map(entry=><article key={entry.id}><Check/><span><strong>{entry.actor?`${entry.actor}: `:''}{entry.title}</strong><small>{entry.detail}</small></span><em>{formatDateTime(entry.at)}</em></article>)}<button className="text-link" onClick={()=>navigate('chores')}>See completed work <ChevronRight/></button></details>}</section></main>;
}

export function WeatherWorkspace({weatherState,weatherGuidance,navigate}){
 const groups=groupWeatherImpacts(weatherGuidance?.recommendations||[],3),primary=groups[0];
 return <main className="screen secondary-screen weather-screen"><section className="screen-pad secondary-screen-content weather-page-content"><button className="secondary-back-arrow" onClick={()=>navigate('back')} aria-label="Go back"><ArrowLeft/></button><section className="weather-page-summary"><WeatherIcon weather={weatherState.weather}/><span><small>WEATHER TOOLS</small><h1>Garden Weather</h1><p>{primary&&primary.key!=='calm'?primary.summary:'Forecast, rain history, watering recommendations, local corrections, and data source.'}</p></span></section>{primary&&<section className={`garden-weather-brief phase-45-weather-brief ${primary.key==='calm'?'is-calm':''}`}><div className="garden-weather-brief-heading"><span><small>WHAT MATTERS NOW</small><strong>{primary.key==='calm'?'No weather actions today':primary.title}</strong></span><em>{weatherGuidance.confidence||primary.confidence||'Low'} confidence</em></div><article className={`garden-weather-insight priority-${primary.priority>=90?'urgent':primary.priority>=70?'high':'normal'}`}><div className="garden-weather-insight-copy"><span className="garden-weather-insight-icon"><ImpactIcon impact={primary}/></span><span><strong>{primary.title}</strong><p>{primary.summary}</p></span></div></article></section>}<WeatherDetails {...weatherState} guidance={weatherGuidance}/></section></main>;
}
