import{getCropProfile,newId}from'./data.js';
const DAY=86400000,SKIP_KEY='runyan-seasonal-skips-v1';
const daysSince=(v,n=new Date())=>!v?Infinity:Math.max(0,Math.floor((n-new Date(v))/DAY));
const dateKey=d=>new Date(d).toISOString().slice(0,10);
const addDays=(date,days)=>{const next=new Date(date);next.setDate(next.getDate()+days);return dateKey(next)};
const seasonalSkipped=(id,date)=>{try{const saved=JSON.parse(localStorage.getItem(SKIP_KEY)||'{}');return Number(saved[id])===date.getFullYear()}catch{return false}};
const location=(plant,spaces)=>spaces.find(space=>space.id===plant.spaceId)?.name||'Unassigned location';
const spaceFor=(plant,spaces)=>spaces.find(space=>space.id===plant.spaceId)||null;
const wetEnough=weather=>Number(weather?.rainHoldAmount||weather?.recentRain24h||0)>=.25;
const isOutdoor=space=>!['indoor','basement','hydro','greenhouse','seed-tray'].includes(space?.type);
const priorityLabel=value=>value>=90?'Urgent':value>=70?'High':value>=45?'Normal':'Low';
const task=(input,date=new Date())=>({dueDate:input.dueDate||dateKey(date),priority:input.priority||50,priorityLabel:priorityLabel(input.priority||50),weatherDriven:false,manual:false,...input});

export function getSeasonMode(d=new Date()){const m=d.getMonth()+1;if([12,1,2].includes(m))return{id:'winter',label:'Winter garden mode',headline:'Grow indoors. Plan outside.',focus:'Indoor crops, seed inventory, light capacity, and next-season starts.'};if([3,4].includes(m))return{id:'seed-starting',label:'Seed-starting mode',headline:'Start seeds and care for seedlings.',focus:'Germination, lights, potting up, and spring preparation.'};if([5,6].includes(m))return{id:'transition',label:'Outdoor transition mode',headline:'Move young plants outside safely.',focus:'Hardening off, transplanting, direct sowing, and frost checks.'};if([7,8].includes(m))return{id:'growth-harvest',label:'Growth and harvest mode',headline:'Keep it growing. Plan fall crops.',focus:'Care, harvest, succession sowing, and fall planting windows.'};return{id:'fall-shutdown',label:'Fall and winter-prep mode',headline:'Harvest, plant for fall, and prepare winter.',focus:'Garlic, cool crops, cleanup, overwintering, and next-season decisions.'}}

export function buildGardenWeatherAlerts(weather,date=new Date()){
 if(!weather)return[];
 const alerts=[];
 const tomorrow=addDays(date,1);
 const official=(weather.activeAlerts||[]).map((item,index)=>({id:`official-${index}-${item.event}`,type:/storm|tornado/i.test(item.event)?'Storm Warning':'Weather Alert',severity:item.severity||'Unknown',what:item.event,why:item.headline||'Official weather conditions may affect garden work.',when:'Now or during the alert period',source:'National Weather Service'}));
 alerts.push(...official);
 if(weather.low<=36)alerts.push({id:'frost-risk',type:'Frost Risk',severity:weather.low<=32?'Urgent':'High',what:`Low near ${weather.low}° expected tonight.`,why:'Tender seedlings, transplants, and warm-season plants can be damaged by cold.',when:'Before sunset today',source:weather.provider||'Weather service'});
 if(weather.high>=92)alerts.push({id:'heat-risk',type:'Heat Risk',severity:weather.high>=98?'Urgent':'High',what:`Temperatures near ${weather.high}° expected ${dateKey(date)===dateKey(new Date())?'today':'on '+dateKey(date)}.`,why:'New transplants, seedlings, containers, and greenhouse plants may need extra attention.',when:weather.high>=92?'Before the hottest part of the day':'Today',source:weather.provider||'Weather service'});
 const rain=Number(weather.rainHoldAmount||weather.recentRain24h||0);
 if(rain>=.5)alerts.push({id:'heavy-rain',type:'Heavy Rain',severity:rain>=1?'Urgent':'High',what:`About ${rain.toFixed(2)} in. of rain has been recorded recently.`,why:'Outdoor beds may not need watering and poorly drained spaces can stay saturated.',when:'Today and until the soil drains',source:weather.rainHoldSource||weather.provider||'Weather service'});
 if(weather.wind>=25)alerts.push({id:'high-wind',type:'High Wind',severity:weather.wind>=40?'Urgent':'High',what:`Wind around ${weather.wind} mph is affecting the garden.`,why:'Tall plants, stakes, covers, pots, and greenhouse vents may shift or break.',when:'While winds remain elevated',source:weather.provider||'Weather service'});
 if(weather.isStormingNow&&!alerts.some(alert=>alert.type==='Storm Warning'))alerts.push({id:'storm-now',type:'Storm Warning',severity:'Urgent',what:weather.condition||'A storm is happening now.',why:'Lightning, wind, and heavy rain make outdoor garden work unsafe.',when:'Now—wait until the storm has passed',source:weather.provider||'Weather service'});
 return alerts;
}

const interval=(crop,plant,weather,outdoor)=>{let days=3,moisture=String(crop?.moisture||'');if(/consistent|steady/.test(moisture))days=2;if(['lettuce','spinach','radish'].includes(crop?.id))days=1;if(['corn','tomato','cucumber','cabbage'].includes(crop?.id))days=2;if(!outdoor)days=Math.max(1,days-1);if(weather?.high>=85&&!wetEnough(weather))days=Math.max(1,days-1);if((weather?.dailyRainChance>=70||wetEnough(weather))&&outdoor)days+=2;if(/flower|fruit|harvest/.test(String(plant.stage).toLowerCase()))days=Math.max(1,days-1);return days};

function plantTasks(plant,spaces,now,weather){
 const out=[],stage=String(plant.stage||'').toLowerCase(),space=spaceFor(plant,spaces),outdoor=isOutdoor(space),crop=getCropProfile(plant.cropId),checkEvery=interval(crop,plant,weather,outdoor),soilAge=daysSince(plant.lastSoilCheck,now),waterAge=daysSince(plant.lastWatered,now),healthAge=daysSince(plant.lastHealthCheck,now),fertilizeAge=daysSince(plant.lastFertilized,now),rainPaused=outdoor&&wetEnough(weather),place=location(plant,spaces),today=dateKey(now);
 plant.spaceType=space?.type;
 if(!crop)out.push(task({id:`identify-${plant.id}`,kind:'plantDetail',taskType:'Inspect For Pests',plant,space,priority:94,title:`Match ${plant.name} to a crop`,subtitle:'Choose a crop profile so care and seasonal reminders can be tailored.',reason:'The plant record is not connected to a recognized crop.',action:'Fix Plant'},now));
 if(/planned|seed purchased/.test(stage))return out;
 if(/seed started|germinat|seedling|potted up/.test(stage)){out.push(task({id:`seedling-${plant.id}`,kind:'plantDetail',taskType:'Check Moisture',plant,space,priority:90,title:`Check ${plant.name} seedlings`,subtitle:`Check moisture ${crop?.checkDepth||'near the roots'}, light distance, airflow, crowding, and pot size.`,reason:`${plant.name} is in the ${plant.stage} stage in ${place}.`,action:'Open Plant'},now));return out}
 if(/hardening off/.test(stage))out.push(task({id:`harden-${plant.id}`,kind:'plantDetail',taskType:'Harden Off',plant,space,priority:91,title:`Continue hardening off ${plant.name}`,subtitle:`Increase outdoor exposure gradually and protect it from strong wind or midday heat.`,reason:`The plant is marked Hardening Off in ${place}.`,action:'Open Plant'},now));
 if(/harvesting/.test(stage))out.push(task({id:`harvest-${plant.id}`,kind:'plantDetail',taskType:'Harvest',plant,space,priority:96,title:`Check ${plant.name} for harvest`,subtitle:'Pick what is ready and record the result in the Plant Journey.',reason:'The plant is currently in the Harvesting stage.',action:'Review'},now));
 if(plant.moisture==='dry'&&!rainPaused)out.push(task({id:`water-${plant.id}`,kind:'soil',taskType:'Water',plant,space,priority:93,title:`Water ${plant.name}`,subtitle:`Water slowly at the root zone in ${place}.`,reason:'The most recent moisture check was recorded as dry.',action:'Open'},now));
 else if(!rainPaused&&(soilAge>=checkEvery||waterAge>=checkEvery+1))out.push(task({id:`soil-${plant.id}`,kind:'soil',taskType:'Check Moisture',plant,space,priority:82,title:`Check ${plant.name} moisture`,subtitle:`Check ${crop?.checkDepth||'about 1 inch'} down in ${place}. ${crop?.watering||'Water only when the root zone is becoming dry.'}`,reason:`This crop currently needs a moisture check about every ${checkEvery} day${checkEvery===1?'':'s'}.`,action:'Check Soil'},now));
 if(['established','flowering','fruiting','harvesting','transplanted'].some(value=>stage.includes(value))&&healthAge>=7)out.push(task({id:`pests-${plant.id}`,kind:'plantDetail',taskType:'Inspect For Pests',plant,space,priority:68,title:`Inspect ${plant.name} for pests`,subtitle:'Check leaves, stems, new growth, chewing, spots, webbing, and insects.',reason:'A weekly inspection catches problems before they spread.',action:'Inspect'},now));
 if(['established','flowering','fruiting'].some(value=>stage.includes(value))&&fertilizeAge>=21)out.push(task({id:`fertilize-${plant.id}`,kind:'plantDetail',taskType:'Fertilize',plant,space,priority:48,title:`Review fertilizer needs for ${plant.name}`,subtitle:'Use the crop record and actual growth before applying anything.',reason:'No fertilizer application has been recorded in at least 21 days.',action:'Open Plant'},now));
 if(['tomato','bell-pepper','hot-pepper'].includes(crop?.id)&&['established','flowering','fruiting'].some(value=>stage.includes(value))&&!plant.lastStaked)out.push(task({id:`stake-${plant.id}`,kind:'plantDetail',taskType:'Stake',plant,space,priority:72,title:`Check support for ${plant.name}`,subtitle:`Add or adjust support in ${place} before stems become overloaded.`,reason:'This crop commonly needs support as it grows and fruits.',action:'Open Plant'},now));
 if(crop?.id==='tomato'&&['established','flowering','fruiting'].some(value=>stage.includes(value))&&daysSince(plant.lastPruned,now)>=14)out.push(task({id:`prune-${plant.id}`,kind:'plantDetail',taskType:'Prune',plant,space,priority:52,title:`Review pruning for ${plant.name}`,subtitle:'Remove only damaged or clearly unnecessary growth; avoid aggressive pruning during stress.',reason:'No pruning review has been recorded in two weeks.',action:'Open Plant'},now));
 if(crop?.family==='flowers'&&stage.includes('flower')&&daysSince(plant.lastDeadheaded,now)>=7)out.push(task({id:`deadhead-${plant.id}`,kind:'plantDetail',taskType:'Deadhead',plant,space,priority:45,title:`Deadhead ${plant.name}`,subtitle:'Remove spent blooms if continued flowering is desired.',reason:'The plant is flowering and has not had a deadheading check this week.',action:'Open Plant'},now));
 if(space?.type==='potato-grow-bag'&&Number(space.seedPotatoesPlanted||0)>0&&space.hillingStage!=='Complete'&&daysSince(space.lastHilledDate,now)>=10)out.push(task({id:`hill-${space.id}`,kind:'plantDetail',taskType:'Hill Potatoes',plant,space,priority:78,title:`Hill potatoes in ${space.name}`,subtitle:'Add material gradually around active stems without burying all foliage.',reason:`This grow bag is at ${space.hillingStage||'an unrecorded'} hilling stage and was last hilled ${Number.isFinite(daysSince(space.lastHilledDate,now))?`${daysSince(space.lastHilledDate,now)} days ago`:'at an unknown date'}.`,action:'Open Plant'},now));
 return out;
}

function weatherTasks(weather,date){return buildGardenWeatherAlerts(weather,date).map(alert=>task({id:`weather-${alert.id}-${dateKey(date)}`,kind:'weather',taskType:alert.type,priority:alert.severity==='Urgent'?99:alert.severity==='High'?86:65,title:alert.type,subtitle:alert.what,reason:alert.why,when:alert.when,source:alert.source,weatherAlert:alert,weatherDriven:true,action:'Review'},date))}

function manualTasks(garden,date){return(garden.reminders||[]).filter(item=>!item.deletedAt&&item.enabled!==false).map(item=>task({id:item.taskId||`manual-${item.id}`,kind:'manual',taskType:item.taskType||'Check Moisture',plant:(garden.plants||[]).find(plant=>plant.id===item.plantId),space:(garden.spaces||[]).find(space=>space.id===item.spaceId),priority:Number(item.priority)||60,title:item.title||item.taskType||'Garden reminder',subtitle:item.note||'Manual garden reminder.',reason:item.reason||'This reminder was added manually.',dueDate:item.dueDate||dateKey(date),manual:true,action:'Open'},date))}

function seasonalTasks(garden,date){const m=date.getMonth()+1,d=date.getDate(),tasks=[],seeds=garden.seeds||[],has=id=>seeds.some(seed=>seed.cropId===id&&!seed.deletedAt);if((m===7||m===8)&&!seasonalSkipped('fall-planting-review',date))tasks.push(task({id:'fall-planting-review',kind:'seasonalGuide',taskType:'Harvest',season:'fall',priority:74,title:'Choose fall planting opportunities',subtitle:'Open a Green Bay-specific list of fast and cold-tolerant crops, including seeds already saved in the Garden Center.',reason:'Fall crops need enough time to mature before hard freezes and slower autumn growth.',action:'See Suggestions'},date));if((m===9||m===10)&&!seasonalSkipped('garlic-fall-window',date))tasks.push(task({id:'garlic-fall-window',kind:'seasonalGuide',taskType:'Check Moisture',season:'garlic',priority:78,title:'Plan fall garlic and winter preparation',subtitle:`${has('garlic')?'A garlic record is saved in the Seed Catalog.':'No garlic seed or cloves are recorded yet.'} Open guided options for planting, mulch, cleanup, and overwintering.`,reason:'Garlic and winter preparation happen before the ground freezes.',action:'Open Fall Guide'},date));if([11,12,1].includes(m)&&!seasonalSkipped('winter-plan-review',date))tasks.push(task({id:'winter-plan-review',kind:'navigate',taskType:'Check Moisture',target:'plan-plant',priority:65,title:'Review the next garden season',subtitle:'Confirm next-year crops, saved packets, indoor-start dates, lights, trays, and missing supplies.',reason:'Winter is planning season even when outdoor beds are resting.',action:'Open Next Season'},date));if(m===2&&d>=1&&!seasonalSkipped('early-seed-start-review',date))tasks.push(task({id:'early-seed-start-review',kind:'navigate',taskType:'Harden Off',target:'plan-plant',priority:88,title:'Check early indoor seed-starting dates',subtitle:'Peppers, onions, and other slow crops may need attention before spring feels close.',reason:'Green Bay’s outdoor season is short, so some crops need a long indoor head start.',action:'Open Planting Desk'},date));return tasks}

export function buildYearRoundTasks({garden,weather,date=new Date()}){const tasks=[],spaces=garden.spaces||[],plants=(garden.plants||[]).filter(plant=>!plant.deletedAt&&!plant.archived&&String(plant.stage).toLowerCase()!=='finished');if(!plants.length)tasks.push(task({id:'setup-first-plant',kind:'setupPlant',taskType:'Check Moisture',priority:99,title:'Add what is actually growing',subtitle:'Choose from the Seed Catalog or Crop Catalog for tailored reminders.',reason:'The app needs known plants to build useful work.',action:'Add Plant'},date));plants.forEach(plant=>tasks.push(...plantTasks({...plant},spaces,date,weather)));tasks.push(...weatherTasks(weather,date),...manualTasks(garden,date),...seasonalTasks(garden,date));if(spaces.some(space=>space.type==='greenhouse'&&!space.hidden&&!space.deletedAt))tasks.push(task({id:'greenhouse-check',kind:'greenhouse',taskType:'Check Moisture',priority:weather?.high>=80?90:55,title:weather?.high>=80?'Check the greenhouse before it overheats':'Record greenhouse conditions',subtitle:'Check temperature, humidity, airflow, and anything unusual.',reason:'A greenhouse is active and its conditions can differ sharply from outside weather.',action:'Check'},date));const unique=new Map();tasks.forEach(item=>{const current=unique.get(item.id);if(!current||item.priority>current.priority)unique.set(item.id,item)});return[...unique.values()].sort((a,b)=>{const due=String(a.dueDate).localeCompare(String(b.dueDate));return due||b.priority-a.priority}).slice(0,40)}

export function migrateGarden(input,starterGarden){const garden=input&&typeof input==='object'?input:starterGarden;return{...starterGarden,...garden,profile:{...starterGarden.profile,...(garden.profile||{})},spaces:garden.spaces||[],plants:garden.plants||[],activity:garden.activity||[],reminders:garden.reminders||[],taskHistory:garden.taskHistory||[],version:11}}

export function createManualReminder(data,actor='System'){const now=new Date().toISOString();return{id:newId('reminder'),taskId:newId('manual-task'),title:String(data.title||'').trim(),taskType:data.taskType||'Check Moisture',plantId:data.plantId||'',spaceId:data.spaceId||'',priority:Number(data.priority)||60,dueDate:data.dueDate||dateKey(now),reason:String(data.reason||'').trim(),note:String(data.note||'').trim(),enabled:true,createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor,revision:1,deletedAt:null}}
